/*
 * XREFs of ??1VIDMM_APERTURE_SEGMENT@@UEAA@XZ @ 0x1C00F7AE4
 * Callers:
 *     ??_GVIDMM_APERTURE_SEGMENT@@UEAAPEAXI@Z @ 0x1C0032380 (--_GVIDMM_APERTURE_SEGMENT@@UEAAPEAXI@Z.c)
 * Callees:
 *     ?FreeGuardPages@VIDMM_APERTURE_SEGMENT@@IEAAXXZ @ 0x1C00F7CCC (-FreeGuardPages@VIDMM_APERTURE_SEGMENT@@IEAAXXZ.c)
 *     ??1VIDMM_SEGMENT@@UEAA@XZ @ 0x1C00FBF80 (--1VIDMM_SEGMENT@@UEAA@XZ.c)
 */

void __fastcall VIDMM_APERTURE_SEGMENT::~VIDMM_APERTURE_SEGMENT(VIDMM_APERTURE_SEGMENT *this)
{
  *(_QWORD *)this = &VIDMM_APERTURE_SEGMENT::`vftable';
  if ( g_IsInternalReleaseOrDbg )
    *(_QWORD *)(WdLogNewEntry5_WdTrace(this) + 24) = this;
  VIDMM_APERTURE_SEGMENT::FreeGuardPages(this);
  VIDMM_SEGMENT::~VIDMM_SEGMENT(this);
}
