/*
 * XREFs of ??1DXGPROCESSSHAREDACCESS@@QEAA@XZ @ 0x1C013CF80
 * Callers:
 *     ??_GDXGPROCESSSHAREDACCESS@@QEAAPEAXI@Z @ 0x1C003BAFC (--_GDXGPROCESSSHAREDACCESS@@QEAAPEAXI@Z.c)
 *     ??1DXGSHAREDRESOURCEACCESS@@QEAA@XZ @ 0x1C013CF08 (--1DXGSHAREDRESOURCEACCESS@@QEAA@XZ.c)
 * Callees:
 *     <none>
 */

void __fastcall DXGPROCESSSHAREDACCESS::~DXGPROCESSSHAREDACCESS(DXGPROCESSSHAREDACCESS *this)
{
  void *v1; // rcx

  v1 = (void *)*((_QWORD *)this + 4);
  if ( v1 )
    ObfDereferenceObject(v1);
}
