/*
 * XREFs of ??_GDXGADAPTERSYNCOBJECTCA@@QEAAPEAXI@Z @ 0x1C0044BAC
 * Callers:
 *     ?Destroy@DXGSYNCOBJECTCA@@QEAAXXZ @ 0x1C0268E28 (-Destroy@DXGSYNCOBJECTCA@@QEAAXXZ.c)
 *     ?GetDxgAdapterSyncObject@DXGSYNCOBJECTCA@@QEAAJPEAVADAPTER_RENDER@@PEAPEAVDXGADAPTERSYNCOBJECT@@@Z @ 0x1C0269474 (-GetDxgAdapterSyncObject@DXGSYNCOBJECTCA@@QEAAJPEAVADAPTER_RENDER@@PEAPEAVDXGADAPTERSYNCOBJECT@@.c)
 * Callees:
 *     ??1DXGADAPTERSYNCOBJECT@@QEAA@XZ @ 0x1C00F5894 (--1DXGADAPTERSYNCOBJECT@@QEAA@XZ.c)
 */

DXGADAPTERSYNCOBJECT *__fastcall DXGADAPTERSYNCOBJECTCA::`scalar deleting destructor'(DXGADAPTERSYNCOBJECT *P)
{
  DXGADAPTERSYNCOBJECT::~DXGADAPTERSYNCOBJECT(P);
  if ( P )
    ExFreePoolWithTag(P, 0);
  return P;
}
