/*
 * XREFs of ??$CastToVmBusCommand@UDXGKVMB_COMMAND_CREATESYNCOBJECT@@@@YAPEAUDXGKVMB_COMMAND_CREATESYNCOBJECT@@PEAUDXGADAPTER_VMBUS_PACKET@@@Z @ 0x1C002D36C
 * Callers:
 *     ?VmBusCreateSyncObject@DXG_HOST_VIRTUALGPU_VMBUS@@SAEPEAUDXGADAPTER_VMBUS_PACKET@@@Z @ 0x1C017E2A0 (-VmBusCreateSyncObject@DXG_HOST_VIRTUALGPU_VMBUS@@SAEPEAUDXGADAPTER_VMBUS_PACKET@@@Z.c)
 *     ?VmBusUpdateGpuVirtualAddress@DXG_HOST_VIRTUALGPU_VMBUS@@SAEPEAUDXGADAPTER_VMBUS_PACKET@@@Z @ 0x1C0187000 (-VmBusUpdateGpuVirtualAddress@DXG_HOST_VIRTUALGPU_VMBUS@@SAEPEAUDXGADAPTER_VMBUS_PACKET@@@Z.c)
 * Callees:
 *     ?LogPacketLengthError@@YAXPEAUDXGADAPTER_VMBUS_PACKET@@_K@Z @ 0x1C017B1F8 (-LogPacketLengthError@@YAXPEAUDXGADAPTER_VMBUS_PACKET@@_K@Z.c)
 */

__int64 __fastcall CastToVmBusCommand<DXGKVMB_COMMAND_CREATESYNCOBJECT>(__int64 a1)
{
  if ( *(_DWORD *)(a1 + 80) >= 0x78u )
    return *(_QWORD *)(a1 + 72);
  LogPacketLengthError((struct DXGADAPTER_VMBUS_PACKET *)a1, 0x78uLL);
  return 0LL;
}
