/*
 * XREFs of ?Delete@DXG_GUEST_REMOTEOBJECTCHANNEL@@UEAAXXZ @ 0x1C01E6780
 * Callers:
 *     <none>
 * Callees:
 *     ??_GDXG_GUEST_REMOTEOBJECTCHANNEL@@IEAAPEAXI@Z @ 0x1C01E5B4C (--_GDXG_GUEST_REMOTEOBJECTCHANNEL@@IEAAPEAXI@Z.c)
 */

void __fastcall DXG_GUEST_REMOTEOBJECTCHANNEL::Delete(DXG_GUEST_REMOTEOBJECTCHANNEL *this)
{
  if ( this )
    DXG_GUEST_REMOTEOBJECTCHANNEL::`scalar deleting destructor'(this);
}
