/*
 * XREFs of ?SetWin32kInterface@DXGPROCESS@@QEAAXQEBU_DXGKWIN32KENG_INTERFACE@@@Z @ 0x1C01B7E40
 * Callers:
 *     ??0DXGPROCESSVM@@QEAA@PEAVDXGGLOBAL@@QEAU_EPROCESS@@PEAVDXGPROCESS@@2@Z @ 0x1C0034284 (--0DXGPROCESSVM@@QEAA@PEAVDXGGLOBAL@@QEAU_EPROCESS@@PEAVDXGPROCESS@@2@Z.c)
 * Callees:
 *     <none>
 */

void __fastcall DXGPROCESS::SetWin32kInterface(DXGPROCESS *this, const struct _DXGKWIN32KENG_INTERFACE *const a2)
{
  *((_QWORD *)this + 13) = a2;
}
