/*
 * XREFs of ??$_Get_size_of_n@$0BA@@std@@YA_K_K@Z @ 0x180010B48
 * Callers:
 *     ??$_Emplace_reallocate@V?$weak_ptr@VRendererResource@Engine@Spectre@@@std@@@?$vector@V?$weak_ptr@VRendererResource@Engine@Spectre@@@std@@V?$allocator@V?$weak_ptr@VRendererResource@Engine@Spectre@@@std@@@2@@std@@QEAAPEAV?$weak_ptr@VRendererResource@Engine@Spectre@@@1@QEAV21@$$QEAV21@@Z @ 0x1800109F0 (--$_Emplace_reallocate@V-$weak_ptr@VRendererResource@Engine@Spectre@@@std@@@-$vector@V-$weak_ptr.c)
 *     ??$_Emplace_reallocate@AEBV?$shared_ptr@VLightProbe@Engine@Spectre@@@std@@@?$vector@V?$shared_ptr@VLightProbe@Engine@Spectre@@@std@@V?$allocator@V?$shared_ptr@VLightProbe@Engine@Spectre@@@std@@@2@@std@@QEAAPEAV?$shared_ptr@VLightProbe@Engine@Spectre@@@1@QEAV21@AEBV21@@Z @ 0x18001207C (--$_Emplace_reallocate@AEBV-$shared_ptr@VLightProbe@Engine@Spectre@@@std@@@-$vector@V-$shared_pt.c)
 *     ?_Reallocate_exactly@?$vector@V?$shared_ptr@VLight@Engine@Spectre@@@std@@V?$allocator@V?$shared_ptr@VLight@Engine@Spectre@@@std@@@2@@std@@AEAAX_K@Z @ 0x180013280 (-_Reallocate_exactly@-$vector@V-$shared_ptr@VLight@Engine@Spectre@@@std@@V-$allocator@V-$shared_.c)
 *     ??$_Emplace_reallocate@V?$shared_ptr@VIRenderOutput@Engine@Spectre@@@std@@@?$vector@V?$shared_ptr@VIRenderOutput@Engine@Spectre@@@std@@V?$allocator@V?$shared_ptr@VIRenderOutput@Engine@Spectre@@@std@@@2@@std@@QEAAPEAV?$shared_ptr@VIRenderOutput@Engine@Spectre@@@1@QEAV21@$$QEAV21@@Z @ 0x180016F04 (--$_Emplace_reallocate@V-$shared_ptr@VIRenderOutput@Engine@Spectre@@@std@@@-$vector@V-$shared_pt.c)
 *     ??$_Emplace_reallocate@PEAVMutex@Engine@Spectre@@AEA_N@?$vector@U?$pair@PEBVMutex@Engine@Spectre@@_N@std@@V?$allocator@U?$pair@PEBVMutex@Engine@Spectre@@_N@std@@@2@@std@@QEAAPEAU?$pair@PEBVMutex@Engine@Spectre@@_N@1@QEAU21@$$QEAPEAVMutex@Engine@Spectre@@AEA_N@Z @ 0x180029958 (--$_Emplace_reallocate@PEAVMutex@Engine@Spectre@@AEA_N@-$vector@U-$pair@PEBVMutex@Engine@Spectre.c)
 *     ??$_Construct_n@AEBQEAV?$shared_ptr@VRenderDevice@Engine@Spectre@@@std@@AEBQEAV12@@?$vector@V?$shared_ptr@VRenderDevice@Engine@Spectre@@@std@@V?$allocator@V?$shared_ptr@VRenderDevice@Engine@Spectre@@@std@@@2@@std@@AEAAX_KAEBQEAV?$shared_ptr@VRenderDevice@Engine@Spectre@@@1@1@Z @ 0x18002E178 (--$_Construct_n@AEBQEAV-$shared_ptr@VRenderDevice@Engine@Spectre@@@std@@AEBQEAV12@@-$vector@V-$s.c)
 *     ??$_Emplace_reallocate@AEBV?$shared_ptr@VFrameBuffer@Engine@Spectre@@@std@@@?$vector@V?$shared_ptr@VFrameBuffer@Engine@Spectre@@@std@@V?$allocator@V?$shared_ptr@VFrameBuffer@Engine@Spectre@@@std@@@2@@std@@QEAAPEAV?$shared_ptr@VFrameBuffer@Engine@Spectre@@@1@QEAV21@AEBV21@@Z @ 0x18002E528 (--$_Emplace_reallocate@AEBV-$shared_ptr@VFrameBuffer@Engine@Spectre@@@std@@@-$vector@V-$shared_p.c)
 *     ??$_Emplace_reallocate@AEBV?$weak_ptr@VLoaderBase@Engine@Spectre@@@std@@@?$vector@V?$weak_ptr@VLoaderBase@Engine@Spectre@@@std@@V?$allocator@V?$weak_ptr@VLoaderBase@Engine@Spectre@@@std@@@2@@std@@QEAAPEAV?$weak_ptr@VLoaderBase@Engine@Spectre@@@1@QEAV21@AEBV21@@Z @ 0x18002E634 (--$_Emplace_reallocate@AEBV-$weak_ptr@VLoaderBase@Engine@Spectre@@@std@@@-$vector@V-$weak_ptr@VL.c)
 *     ??$_Emplace_reallocate@V?$shared_ptr@VCamera@Engine@Spectre@@@std@@@?$vector@V?$shared_ptr@VCamera@Engine@Spectre@@@std@@V?$allocator@V?$shared_ptr@VCamera@Engine@Spectre@@@std@@@2@@std@@QEAAPEAV?$shared_ptr@VCamera@Engine@Spectre@@@1@QEAV21@$$QEAV21@@Z @ 0x18002E72C (--$_Emplace_reallocate@V-$shared_ptr@VCamera@Engine@Spectre@@@std@@@-$vector@V-$shared_ptr@VCame.c)
 *     ??$_Insert_range@PEAV?$weak_ptr@VRendererResource@Engine@Spectre@@@std@@@?$vector@V?$weak_ptr@VRendererResource@Engine@Spectre@@@std@@V?$allocator@V?$weak_ptr@VRendererResource@Engine@Spectre@@@std@@@2@@std@@AEAAXV?$_Vector_const_iterator@V?$_Vector_val@U?$_Simple_types@V?$weak_ptr@VRendererResource@Engine@Spectre@@@std@@@std@@@std@@@1@PEAV?$weak_ptr@VRendererResource@Engine@Spectre@@@1@1Uforward_iterator_tag@1@@Z @ 0x18002F200 (--$_Insert_range@PEAV-$weak_ptr@VRendererResource@Engine@Spectre@@@std@@@-$vector@V-$weak_ptr@VR.c)
 *     ??$_Emplace_reallocate@AEBV?$shared_ptr@VComponent@Engine@Spectre@@@std@@@?$vector@V?$shared_ptr@VComponent@Engine@Spectre@@@std@@V?$allocator@V?$shared_ptr@VComponent@Engine@Spectre@@@std@@@2@@std@@QEAAPEAV?$shared_ptr@VComponent@Engine@Spectre@@@1@QEAV21@AEBV21@@Z @ 0x18003A324 (--$_Emplace_reallocate@AEBV-$shared_ptr@VComponent@Engine@Spectre@@@std@@@-$vector@V-$shared_ptr.c)
 *     ??$_Emplace_reallocate@AEBV?$shared_ptr@VCamera@Engine@Spectre@@@std@@@?$vector@V?$shared_ptr@VCamera@Engine@Spectre@@@std@@V?$allocator@V?$shared_ptr@VCamera@Engine@Spectre@@@std@@@2@@std@@QEAAPEAV?$shared_ptr@VCamera@Engine@Spectre@@@1@QEAV21@AEBV21@@Z @ 0x180056C54 (--$_Emplace_reallocate@AEBV-$shared_ptr@VCamera@Engine@Spectre@@@std@@@-$vector@V-$shared_ptr@VC.c)
 *     ??$_Emplace_reallocate@V?$weak_ptr@VIRenderOutput@Engine@Spectre@@@std@@@?$vector@V?$weak_ptr@VIRenderOutput@Engine@Spectre@@@std@@V?$allocator@V?$weak_ptr@VIRenderOutput@Engine@Spectre@@@std@@@2@@std@@QEAAPEAV?$weak_ptr@VIRenderOutput@Engine@Spectre@@@1@QEAV21@$$QEAV21@@Z @ 0x180056D3C (--$_Emplace_reallocate@V-$weak_ptr@VIRenderOutput@Engine@Spectre@@@std@@@-$vector@V-$weak_ptr@VI.c)
 *     ?_Buy_nonzero@?$vector@V?$shared_ptr@VCamera@Engine@Spectre@@@std@@V?$allocator@V?$shared_ptr@VCamera@Engine@Spectre@@@std@@@2@@std@@AEAAX_K@Z @ 0x180058440 (-_Buy_nonzero@-$vector@V-$shared_ptr@VCamera@Engine@Spectre@@@std@@V-$allocator@V-$shared_ptr@VC.c)
 *     ??$_Emplace_reallocate@V?$shared_ptr@VShaderPipeline@Engine@Spectre@@@std@@@?$vector@V?$shared_ptr@VShaderPipeline@Engine@Spectre@@@std@@V?$allocator@V?$shared_ptr@VShaderPipeline@Engine@Spectre@@@std@@@2@@std@@QEAAPEAV?$shared_ptr@VShaderPipeline@Engine@Spectre@@@1@QEAV21@$$QEAV21@@Z @ 0x18005F06C (--$_Emplace_reallocate@V-$shared_ptr@VShaderPipeline@Engine@Spectre@@@std@@@-$vector@V-$shared_p.c)
 *     ?_Reallocate_exactly@?$vector@V?$shared_ptr@VCamera@Engine@Spectre@@@std@@V?$allocator@V?$shared_ptr@VCamera@Engine@Spectre@@@std@@@2@@std@@AEAAX_K@Z @ 0x18006EA00 (-_Reallocate_exactly@-$vector@V-$shared_ptr@VCamera@Engine@Spectre@@@std@@V-$allocator@V-$shared.c)
 *     ??$_Emplace_reallocate@AEBV?$shared_ptr@VImageProcessingEffect@Engine@Spectre@@@std@@@?$vector@V?$shared_ptr@VImageProcessingEffect@Engine@Spectre@@@std@@V?$allocator@V?$shared_ptr@VImageProcessingEffect@Engine@Spectre@@@std@@@2@@std@@QEAAPEAV?$shared_ptr@VImageProcessingEffect@Engine@Spectre@@@1@QEAV21@AEBV21@@Z @ 0x1800711A8 (--$_Emplace_reallocate@AEBV-$shared_ptr@VImageProcessingEffect@Engine@Spectre@@@std@@@-$vector@V.c)
 *     ?_Buy_raw@?$vector@UVector4@Math@Utils@Spectre@@V?$allocator@UVector4@Math@Utils@Spectre@@@std@@@std@@AEAAX_K@Z @ 0x18007E584 (-_Buy_raw@-$vector@UVector4@Math@Utils@Spectre@@V-$allocator@UVector4@Math@Utils@Spectre@@@std@@.c)
 *     ??$_Emplace_reallocate@AEBVShaderOptionFilter@Engine@Spectre@@@?$vector@VShaderOptionFilter@Engine@Spectre@@V?$allocator@VShaderOptionFilter@Engine@Spectre@@@std@@@std@@QEAAPEAVShaderOptionFilter@Engine@Spectre@@QEAV234@AEBV234@@Z @ 0x180086164 (--$_Emplace_reallocate@AEBVShaderOptionFilter@Engine@Spectre@@@-$vector@VShaderOptionFilter@Engi.c)
 *     ??$_Construct_n@$$V@?$vector@UColor@Math@Utils@Spectre@@V?$allocator@UColor@Math@Utils@Spectre@@@std@@@std@@AEAAX_K@Z @ 0x18008EFD8 (--$_Construct_n@$$V@-$vector@UColor@Math@Utils@Spectre@@V-$allocator@UColor@Math@Utils@Spectre@@.c)
 *     ??$_Resize_reallocate@U_Value_init_tag@std@@@?$vector@UColor@Math@Utils@Spectre@@V?$allocator@UColor@Math@Utils@Spectre@@@std@@@std@@AEAAX_KAEBU_Value_init_tag@1@@Z @ 0x18008F2C0 (--$_Resize_reallocate@U_Value_init_tag@std@@@-$vector@UColor@Math@Utils@Spectre@@V-$allocator@UC.c)
 *     ??$_Emplace_reallocate@V?$shared_ptr@VImageProcessingEffect@Engine@Spectre@@@std@@@?$vector@V?$shared_ptr@VImageProcessingEffect@Engine@Spectre@@@std@@V?$allocator@V?$shared_ptr@VImageProcessingEffect@Engine@Spectre@@@std@@@2@@std@@QEAAPEAV?$shared_ptr@VImageProcessingEffect@Engine@Spectre@@@1@QEAV21@$$QEAV21@@Z @ 0x180093A7C (--$_Emplace_reallocate@V-$shared_ptr@VImageProcessingEffect@Engine@Spectre@@@std@@@-$vector@V-$s.c)
 *     ??$_Emplace_reallocate@AEAMAEAPEAVSceneNode@Engine@Spectre@@@?$vector@UNodeInfo@DistanceFromCameraSceneNodeTraversal@Engine@Spectre@@V?$allocator@UNodeInfo@DistanceFromCameraSceneNodeTraversal@Engine@Spectre@@@std@@@std@@QEAAPEAUNodeInfo@DistanceFromCameraSceneNodeTraversal@Engine@Spectre@@QEAU2345@AEAMAEAPEAVSceneNode@45@@Z @ 0x180094A84 (--$_Emplace_reallocate@AEAMAEAPEAVSceneNode@Engine@Spectre@@@-$vector@UNodeInfo@DistanceFromCame.c)
 *     ??$_Emplace_reallocate@AEBV?$shared_ptr@VResourceLoadedFnc@Engine@Spectre@@@std@@@?$vector@V?$shared_ptr@VResourceLoadedFnc@Engine@Spectre@@@std@@V?$allocator@V?$shared_ptr@VResourceLoadedFnc@Engine@Spectre@@@std@@@2@@std@@QEAAPEAV?$shared_ptr@VResourceLoadedFnc@Engine@Spectre@@@1@QEAV21@AEBV21@@Z @ 0x180097208 (--$_Emplace_reallocate@AEBV-$shared_ptr@VResourceLoadedFnc@Engine@Spectre@@@std@@@-$vector@V-$sh.c)
 *     ??$_Emplace_reallocate@AEBV?$shared_ptr@VShaderPipeline@Engine@Spectre@@@std@@@?$vector@V?$shared_ptr@VShaderPipeline@Engine@Spectre@@@std@@V?$allocator@V?$shared_ptr@VShaderPipeline@Engine@Spectre@@@std@@@2@@std@@QEAAPEAV?$shared_ptr@VShaderPipeline@Engine@Spectre@@@1@QEAV21@AEBV21@@Z @ 0x1800983CC (--$_Emplace_reallocate@AEBV-$shared_ptr@VShaderPipeline@Engine@Spectre@@@std@@@-$vector@V-$share.c)
 *     ??$_Construct_n@PEBV?$shared_ptr@VLightProbe@Engine@Spectre@@@std@@PEBV12@@?$vector@V?$shared_ptr@VLightProbe@Engine@Spectre@@@std@@V?$allocator@V?$shared_ptr@VLightProbe@Engine@Spectre@@@std@@@2@@std@@AEAAX_K$$QEAPEBV?$shared_ptr@VLightProbe@Engine@Spectre@@@1@1@Z @ 0x1800A402C (--$_Construct_n@PEBV-$shared_ptr@VLightProbe@Engine@Spectre@@@std@@PEBV12@@-$vector@V-$shared_pt.c)
 *     ??$_Emplace_reallocate@AEBUD3D11_SUBRESOURCE_DATA@@@?$vector@UD3D11_SUBRESOURCE_DATA@@V?$allocator@UD3D11_SUBRESOURCE_DATA@@@std@@@std@@QEAAPEAUD3D11_SUBRESOURCE_DATA@@QEAU2@AEBU2@@Z @ 0x1800CC544 (--$_Emplace_reallocate@AEBUD3D11_SUBRESOURCE_DATA@@@-$vector@UD3D11_SUBRESOURCE_DATA@@V-$allocat.c)
 *     ?_Reallocate_exactly@?$vector@UD3D11_SUBRESOURCE_DATA@@V?$allocator@UD3D11_SUBRESOURCE_DATA@@@std@@@std@@AEAAX_K@Z @ 0x1800CF46C (-_Reallocate_exactly@-$vector@UD3D11_SUBRESOURCE_DATA@@V-$allocator@UD3D11_SUBRESOURCE_DATA@@@st.c)
 *     ?_Reallocate_exactly@?$vector@V?$shared_ptr@UHolographicDisplayState@Holographic@D3D11@Engine@Spectre@@@std@@V?$allocator@V?$shared_ptr@UHolographicDisplayState@Holographic@D3D11@Engine@Spectre@@@std@@@2@@std@@AEAAX_K@Z @ 0x1800DA7C0 (-_Reallocate_exactly@-$vector@V-$shared_ptr@UHolographicDisplayState@Holographic@D3D11@Engine@Sp.c)
 *     ??$_Insert_range@PEAV?$shared_ptr@VTween@Tweening@Utils@Spectre@@@std@@@?$vector@V?$shared_ptr@VTween@Tweening@Utils@Spectre@@@std@@V?$allocator@V?$shared_ptr@VTween@Tweening@Utils@Spectre@@@std@@@2@@std@@AEAAXV?$_Vector_const_iterator@V?$_Vector_val@U?$_Simple_types@V?$shared_ptr@VTween@Tweening@Utils@Spectre@@@std@@@std@@@std@@@1@PEAV?$shared_ptr@VTween@Tweening@Utils@Spectre@@@1@1Uforward_iterator_tag@1@@Z @ 0x1800E0510 (--$_Insert_range@PEAV-$shared_ptr@VTween@Tweening@Utils@Spectre@@@std@@@-$vector@V-$shared_ptr@V.c)
 * Callees:
 *     ?_Throw_bad_array_new_length@std@@YAXXZ @ 0x180011AC4 (-_Throw_bad_array_new_length@std@@YAXXZ.c)
 */

__int64 __fastcall std::_Get_size_of_n<16>(unsigned __int64 a1)
{
  if ( a1 > 0xFFFFFFFFFFFFFFFLL )
    std::_Throw_bad_array_new_length();
  return 16 * a1;
}
