/*
 * XREFs of _std::_Hash_std::_Umap_traits_std::basic_string_wchar_t_std::char_traits_wchar_t__std::allocator_wchar_t____Spectre::Utils::ConfigurationValue_std::_Uhash_compare_std::basic_string_wchar_t_std::char_traits_wchar_t__std::allocator_wchar_t____std::hash_std::basic_string_wchar_t_std::char_traits_wchar_t__std::allocator_wchar_t______std::equal_to_std::basic_string_wchar_t_std::char_traits_wchar_t__std::allocator_wchar_t________std::allocator_std::pair_std::basic_string_wchar_t_std::char_traits_wchar_t__std::allocator_wchar_t____const__Spectre::Utils::ConfigurationValue____0___::_Hash_std::_Umap_traits_std::basic_string_wchar_t_std::char_traits_wchar_t__std::allocator_wchar_t____Spectre::Utils::ConfigurationValue_std::_Uhash_compare_std::basic_string_wchar_t_std::char_traits_wchar_t__std::allocator_wchar_t____std::hash_std::basic_string_wchar_t_std::char_traits_wchar_t__std::allocator_wchar_t______std::equal_to_std::basic_string_wchar_t_std::char_traits_wchar_t__std::allocator_wchar_t________std::allocator_std::pair_std::basic_string_wchar_t_std::char_traits_wchar_t__std::allocator_wchar_t____const__Spectre::Utils::ConfigurationValue____0____std::allocator_std::_List_node_std::pair_std::basic_string_wchar_t_std::char_traits_wchar_t__std::allocator_wchar_t____const__Spectre::Utils::ConfigurationValue__void________::_1_::dtor$0 @ 0x1800F1C7A
 * Callers:
 *     <none>
 * Callees:
 *     <none>
 */

void __fastcall std::_Hash_std::_Umap_traits_std::basic_string_wchar_t_std::char_traits_wchar_t__std::allocator_wchar_t____Spectre::Utils::ConfigurationValue_std::_Uhash_compare_std::basic_string_wchar_t_std::char_traits_wchar_t__std::allocator_wchar_t____std::hash_std::basic_string_wchar_t_std::char_traits_wchar_t__std::allocator_wchar_t______std::equal_to_std::basic_string_wchar_t_std::char_traits_wchar_t__std::allocator_wchar_t________std::allocator_std::pair_std::basic_string_wchar_t_std::char_traits_wchar_t__std::allocator_wchar_t____const__Spectre::Utils::ConfigurationValue____0___::_Hash_std::_Umap_traits_std::basic_string_wchar_t_std::char_traits_wchar_t__std::allocator_wchar_t____Spectre::Utils::ConfigurationValue_std::_Uhash_compare_std::basic_string_wchar_t_std::char_traits_wchar_t__std::allocator_wchar_t____std::hash_std::basic_string_wchar_t_std::char_traits_wchar_t__std::allocator_wchar_t______std::equal_to_std::basic_string_wchar_t_std::char_traits_wchar_t__std::allocator_wchar_t________std::allocator_std::pair_std::basic_string_wchar_t_std::char_traits_wchar_t__std::allocator_wchar_t____const__Spectre::Utils::ConfigurationValue____0____std::allocator_std::_List_node_std::pair_std::basic_string_wchar_t_std::char_traits_wchar_t__std::allocator_wchar_t____const__Spectre::Utils::ConfigurationValue__void________::_1_::dtor_0(
        __int64 a1,
        __int64 a2)
{
  std::list<std::pair<std::wstring const,Spectre::Utils::ConfigurationValue>>::~list<std::pair<std::wstring const,Spectre::Utils::ConfigurationValue>>((__int64 *)(*(_QWORD *)(a2 + 64) + 8LL));
}
