/*
 * XREFs of WPP_SF_qqq @ 0x1C003CB3C
 * Callers:
 *     ndisQuerySetMiniportEx @ 0x1C0009F70 (ndisQuerySetMiniportEx.c)
 *     ndisOidRequestComplete @ 0x1C000B560 (ndisOidRequestComplete.c)
 *     ndisSwapFilterHandlersForMediaDisconnect @ 0x1C0012428 (ndisSwapFilterHandlersForMediaDisconnect.c)
 *     ndisSetupNdis6OpenHandlers @ 0x1C001A4D4 (ndisSetupNdis6OpenHandlers.c)
 *     ndisSetupMiniportProtocolHandlers @ 0x1C001ACD4 (ndisSetupMiniportProtocolHandlers.c)
 *     ndisIfUpdateInterfaceOnInitialize @ 0x1C001D500 (ndisIfUpdateInterfaceOnInitialize.c)
 *     ndisIsValidMulticastFilter @ 0x1C001E744 (ndisIsValidMulticastFilter.c)
 *     ?ndisOidPostOpenSetEncapsulation@@YAXPEAU_NDIS_REQ_TRACKER@@@Z @ 0x1C0020CC0 (-ndisOidPostOpenSetEncapsulation@@YAXPEAU_NDIS_REQ_TRACKER@@@Z.c)
 *     ndisOidPostRSSParameters @ 0x1C00212E0 (ndisOidPostRSSParameters.c)
 *     ndisSetOpenRSSParameters @ 0x1C0021618 (ndisSetOpenRSSParameters.c)
 *     ndisRestoreFilterHandlersForMediaDisconnect @ 0x1C00222B0 (ndisRestoreFilterHandlersForMediaDisconnect.c)
 *     ndisOidPMAddRemove @ 0x1C00230F8 (ndisOidPMAddRemove.c)
 *     ndisPMAddWOLPattern @ 0x1C002319C (ndisPMAddWOLPattern.c)
 *     ndisOidPostTaskOffload @ 0x1C0048800 (ndisOidPostTaskOffload.c)
 *     ndisOidPreOffloadCaps @ 0x1C0048BD0 (ndisOidPreOffloadCaps.c)
 *     ndisProcessRequestAsync @ 0x1C0049840 (ndisProcessRequestAsync.c)
 *     ndisPMAddProtocolOffload @ 0x1C004C21C (ndisPMAddProtocolOffload.c)
 *     ndisPostSetRemoveWakeUpPattern @ 0x1C004CA60 (ndisPostSetRemoveWakeUpPattern.c)
 *     ndisQueryWakeUpPatternList @ 0x1C004CB98 (ndisQueryWakeUpPatternList.c)
 *     NdisCmRegisterAddressFamilyEx @ 0x1C0052B90 (NdisCmRegisterAddressFamilyEx.c)
 *     ndisDoLoopbackNetBufferList @ 0x1C005512C (ndisDoLoopbackNetBufferList.c)
 *     ndisMIsLoopbackNetBuffer @ 0x1C005656C (ndisMIsLoopbackNetBuffer.c)
 *     ndisFDoLoopbackNetBufferList @ 0x1C0059DF8 (ndisFDoLoopbackNetBufferList.c)
 *     ndisFIsLoopbackNetBuffer @ 0x1C005A34C (ndisFIsLoopbackNetBuffer.c)
 *     ndisOpenAdapterLegacyProtocol @ 0x1C005C920 (ndisOpenAdapterLegacyProtocol.c)
 *     ?ndisNsiGetInterfaceRodInformation@@YAJPEAU_NDIS_IF_BLOCK@@0PEAU_NM_REQUEST_GET_PARAMETER@@@Z @ 0x1C00A3830 (-ndisNsiGetInterfaceRodInformation@@YAJPEAU_NDIS_IF_BLOCK@@0PEAU_NM_REQUEST_GET_PARAMETER@@@Z.c)
 *     ?ndisNsiGetInterfaceRwInformation@@YAJPEAU_NDIS_IF_BLOCK@@0PEAU_NM_REQUEST_GET_PARAMETER@@@Z @ 0x1C00A4804 (-ndisNsiGetInterfaceRwInformation@@YAJPEAU_NDIS_IF_BLOCK@@0PEAU_NM_REQUEST_GET_PARAMETER@@@Z.c)
 *     ?ndisIfGetMiniportStatistics@@YAHPEAU_NDIS_MINIPORT_BLOCK@@PEAXPEAU_NDIS_FILTER_BLOCK@@@Z @ 0x1C00A4E40 (-ndisIfGetMiniportStatistics@@YAHPEAU_NDIS_MINIPORT_BLOCK@@PEAXPEAU_NDIS_FILTER_BLOCK@@@Z.c)
 *     ndisSetOpenEthAddDeleteMulticast @ 0x1C00A7EEC (ndisSetOpenEthAddDeleteMulticast.c)
 *     ndisAllocateConfigurationString @ 0x1C00AF2CC (ndisAllocateConfigurationString.c)
 *     ndisOidPrePacketFilter @ 0x1C00B6F50 (ndisOidPrePacketFilter.c)
 *     ndisSetOpenEthMulticastList @ 0x1C00BA148 (ndisSetOpenEthMulticastList.c)
 *     ndisOidPreOffloadEncapsulation @ 0x1C00BB9C0 (ndisOidPreOffloadEncapsulation.c)
 *     ndisOidPreRSSParameters @ 0x1C00BC5E0 (ndisOidPreRSSParameters.c)
 *     ndisOidPreRSSCaps @ 0x1C00BD870 (ndisOidPreRSSCaps.c)
 *     ndisMSetReceiveFilterAttributes @ 0x1C00BFD4C (ndisMSetReceiveFilterAttributes.c)
 *     ndisMUnloadEx @ 0x1C00C0560 (ndisMUnloadEx.c)
 *     ndisOidPreNicSwitchCaps @ 0x1C00CF980 (ndisOidPreNicSwitchCaps.c)
 *     ndisOidPreRcvFilterGlobalParameters @ 0x1C00CFC00 (ndisOidPreRcvFilterGlobalParameters.c)
 *     ndisOidPreReceiveFilterCaps @ 0x1C00CFE50 (ndisOidPreReceiveFilterCaps.c)
 *     ?ndisNsiGetIfRcvAddressRodInformation@@YAJPEAU_NDIS_IF_BLOCK@@PEAU_NDIS_IF_RCV_ADDRESS@@PEAU_NM_REQUEST_GET_PARAMETER@@@Z @ 0x1C00D0C20 (-ndisNsiGetIfRcvAddressRodInformation@@YAJPEAU_NDIS_IF_BLOCK@@PEAU_NDIS_IF_RCV_ADDRESS@@PEAU_NM_.c)
 *     ndisOidPreTaskOffload @ 0x1C00D2620 (ndisOidPreTaskOffload.c)
 *     ndisOidPrePMProtocolOffloadList @ 0x1C00D55F0 (ndisOidPrePMProtocolOffloadList.c)
 *     ndisOidPrePMWOLPatternList @ 0x1C00D5A00 (ndisOidPrePMWOLPatternList.c)
 *     ndisSetEnableWakeUp @ 0x1C00D72FC (ndisSetEnableWakeUp.c)
 *     NdisIMInitializeDeviceInstanceEx @ 0x1C00D9DE0 (NdisIMInitializeDeviceInstanceEx.c)
 *     ndisIMQueueDeviceInstance @ 0x1C00DA4D4 (ndisIMQueueDeviceInstance.c)
 *     ndisCreateFilterInstanceRegistry @ 0x1C00DB110 (ndisCreateFilterInstanceRegistry.c)
 *     ndisGetOrCreateFilterInstanceKey @ 0x1C00DB224 (ndisGetOrCreateFilterInstanceKey.c)
 *     ndisSetAllFilterDefaultParameters @ 0x1C00DB9CC (ndisSetAllFilterDefaultParameters.c)
 *     ndisSetFilterDefaultParameter @ 0x1C00DBC48 (ndisSetFilterDefaultParameter.c)
 *     ndisOidPreIovAllocateVF @ 0x1C00E65B0 (ndisOidPreIovAllocateVF.c)
 *     ndisOidPreIovCreateVPort @ 0x1C00E6AE0 (ndisOidPreIovCreateVPort.c)
 *     ?NdisPDStopEC@@YAXPEAUPD_EC_HANDLE__@@@Z @ 0x1C00ED900 (-NdisPDStopEC@@YAXPEAUPD_EC_HANDLE__@@@Z.c)
 *     NdisPDStartup @ 0x1C00EECB0 (NdisPDStartup.c)
 *     NdisOpenAdapterEx @ 0x1C00F7950 (NdisOpenAdapterEx.c)
 *     ndisMOpenAdapter @ 0x1C00F7CE4 (ndisMOpenAdapter.c)
 *     NdisCmActivateVc @ 0x1C0106650 (NdisCmActivateVc.c)
 *     NdisCoOidRequest @ 0x1C0107F10 (NdisCoOidRequest.c)
 *     NdisCoRequest @ 0x1C01083E0 (NdisCoRequest.c)
 * Callees:
 *     ?ndisWppFastTraceMessage@@YAXPEBU_GUID@@GZZ @ 0x1C004FBEC (-ndisWppFastTraceMessage@@YAXPEBU_GUID@@GZZ.c)
 */

void WPP_SF_qqq(unsigned __int16 a1, const struct _GUID *a2, ...)
{
  va_list va; // [rsp+70h] [rbp+18h] BYREF

  va_start(va, a2);
  ndisWppFastTraceMessage(a2, a1, va);
}
