/*
 * XREFs of WPP_SF_ @ 0x1C0028184
 * Callers:
 *     ?ndisDoPeriodicReceivesIndication@@YAKPEAU_NDIS_MINIPORT_BLOCK@@PEAU_NET_BUFFER_LIST@@@Z @ 0x1C0001008 (-ndisDoPeriodicReceivesIndication@@YAKPEAU_NDIS_MINIPORT_BLOCK@@PEAU_NET_BUFFER_LIST@@@Z.c)
 *     ndisMDispatchReceiveNetBufferLists @ 0x1C0001480 (ndisMDispatchReceiveNetBufferLists.c)
 *     NdisMIndicateReceiveNetBufferLists @ 0x1C0002030 (NdisMIndicateReceiveNetBufferLists.c)
 *     ndisMTopReceiveNetBufferLists @ 0x1C0002930 (ndisMTopReceiveNetBufferLists.c)
 *     NdisRetreatNetBufferListDataStart @ 0x1C0005E30 (NdisRetreatNetBufferListDataStart.c)
 *     ndisOidFreeInternalCloneRequest @ 0x1C000C1E4 (ndisOidFreeInternalCloneRequest.c)
 *     NdisFOidRequestComplete @ 0x1C000F660 (NdisFOidRequestComplete.c)
 *     NdisTryAcquireNicActive @ 0x1C0010980 (NdisTryAcquireNicActive.c)
 *     ?ndisInitializeNsiHelper@@YAJXZ @ 0x1C0012D10 (-ndisInitializeNsiHelper@@YAJXZ.c)
 *     ?ndisIfInitGetNetworkList@@YAJXZ @ 0x1C0012ED4 (-ndisIfInitGetNetworkList@@YAJXZ.c)
 *     ?ndisIfInitGetCompartmentList@@YAJXZ @ 0x1C0013120 (-ndisIfInitGetCompartmentList@@YAJXZ.c)
 *     ndisStartNsiClient @ 0x1C00136BC (ndisStartNsiClient.c)
 *     NdisAllocatePacketPoolEx @ 0x1C0013C50 (NdisAllocatePacketPoolEx.c)
 *     NdisFRegisterFilterDriver @ 0x1C00160A0 (NdisFRegisterFilterDriver.c)
 *     ndisIfReadNetworkGuidFromKey @ 0x1C0016938 (ndisIfReadNetworkGuidFromKey.c)
 *     ?ndisMRawIndicateStatusEx@@YAXPEAUNDIS_MINIPORT_ADAPTER_HANDLE__@@PEAU_NDIS_STATUS_INDICATION@@@Z @ 0x1C001741C (-ndisMRawIndicateStatusEx@@YAXPEAUNDIS_MINIPORT_ADAPTER_HANDLE__@@PEAU_NDIS_STATUS_INDICATION@@@.c)
 *     NdisAllocateNetBufferListPool @ 0x1C001A000 (NdisAllocateNetBufferListPool.c)
 *     ?ndisNsiQueuedIfBlockRodChangeNotification@@YAXPEAU_NDIS_WORK_ITEM@@PEAX@Z @ 0x1C001C570 (-ndisNsiQueuedIfBlockRodChangeNotification@@YAXPEAU_NDIS_WORK_ITEM@@PEAX@Z.c)
 *     ndisMDispatchReceiveNetBufferListsWithLock @ 0x1C001E2C0 (ndisMDispatchReceiveNetBufferListsWithLock.c)
 *     ndisThreadPoolTimerHandler @ 0x1C0022B20 (ndisThreadPoolTimerHandler.c)
 *     ndisCreatePMRejectWorkItem @ 0x1C00232DC (ndisCreatePMRejectWorkItem.c)
 *     NdisFreeSharedMemory @ 0x1C0025D90 (NdisFreeSharedMemory.c)
 *     ?ndisIfCreateCompartment@@YAJPEAU_NM_REQUEST_SET_ALL_PARAMETERS@@PEAPEAU_NDIS_IF_COMPARTMENT_BLOCK@@@Z @ 0x1C0040768 (-ndisIfCreateCompartment@@YAJPEAU_NM_REQUEST_SET_ALL_PARAMETERS@@PEAPEAU_NDIS_IF_COMPARTMENT_BLO.c)
 *     ndisStopNsiProvider @ 0x1C0045340 (ndisStopNsiProvider.c)
 *     ndisClonePMPatternList @ 0x1C004ACC4 (ndisClonePMPatternList.c)
 *     ndisCreatePMAddRemoveWorkItem @ 0x1C004ADD4 (ndisCreatePMAddRemoveWorkItem.c)
 *     ndisCreatePMPdcTaskClientWorkItem @ 0x1C004AE8C (ndisCreatePMPdcTaskClientWorkItem.c)
 *     ndisUpdateAndIndicatePMCapabilities @ 0x1C004CEFC (ndisUpdateAndIndicatePMCapabilities.c)
 *     ?ndisMEmitTraceRundown@@YAXPEAU_NDIS_MINIPORT_BLOCK@@@Z @ 0x1C004F9D8 (-ndisMEmitTraceRundown@@YAXPEAU_NDIS_MINIPORT_BLOCK@@@Z.c)
 *     ndisEnableWppTracingCallback @ 0x1C0050710 (ndisEnableWppTracingCallback.c)
 *     ndisMapOpenByName @ 0x1C00509FC (ndisMapOpenByName.c)
 *     ?ndisCoIndicatePromiscPacket@@YAXPEAXPEAU_NDIS_MINIPORT_BLOCK@@PEAU_NDIS_OPEN_BLOCK@@PEAU_NDIS_PACKET@@EE@Z @ 0x1C0053438 (-ndisCoIndicatePromiscPacket@@YAXPEAXPEAU_NDIS_MINIPORT_BLOCK@@PEAU_NDIS_OPEN_BLOCK@@PEAU_NDIS_P.c)
 *     ?ndisCoSendNetBufferListsToNdisPacket@@YAXPEAXPEAU_NET_BUFFER_LIST@@K@Z @ 0x1C0053630 (-ndisCoSendNetBufferListsToNdisPacket@@YAXPEAXPEAU_NET_BUFFER_LIST@@K@Z.c)
 *     ?ndisCoSendPacketsToNetBufferLists@@YAXPEAXPEAPEAU_NDIS_PACKET@@I@Z @ 0x1C00539A0 (-ndisCoSendPacketsToNetBufferLists@@YAXPEAXPEAPEAU_NDIS_PACKET@@I@Z.c)
 *     NdisWriteEventLogEntry @ 0x1C005C210 (NdisWriteEventLogEntry.c)
 *     ndisMIndicateQosParametersChange @ 0x1C005FA8C (ndisMIndicateQosParametersChange.c)
 *     ndisMResetMiniportInternal @ 0x1C0060C24 (ndisMResetMiniportInternal.c)
 *     ndisMIndicateSplitNblChain @ 0x1C0068A50 (ndisMIndicateSplitNblChain.c)
 *     ?NdisGetVersion640Shim@@YAIXZ @ 0x1C00765F0 (-NdisGetVersion640Shim@@YAIXZ.c)
 *     ndisSetOpenEthAddDeleteMulticast @ 0x1C00A7EEC (ndisSetOpenEthAddDeleteMulticast.c)
 *     ndisStartNsiProvider @ 0x1C00A8B1C (ndisStartNsiProvider.c)
 *     ndisDoesSystemSupportSriov @ 0x1C00A8BE4 (ndisDoesSystemSupportSriov.c)
 *     ndisPnPAddDevice @ 0x1C00A9500 (ndisPnPAddDevice.c)
 *     ?ndisPDReadKeywords@@YAJPEAU_NDIS_MINIPORT_BLOCK@@@Z @ 0x1C00AC27C (-ndisPDReadKeywords@@YAJPEAU_NDIS_MINIPORT_BLOCK@@@Z.c)
 *     ndisHandleLegacyTransport @ 0x1C00ACB98 (ndisHandleLegacyTransport.c)
 *     NdisReadConfiguration @ 0x1C00AE8B0 (NdisReadConfiguration.c)
 *     ndisCreateReceiveWorkerThreadPool @ 0x1C00AFB50 (ndisCreateReceiveWorkerThreadPool.c)
 *     NdisOpenProtocolConfiguration @ 0x1C00B06E0 (NdisOpenProtocolConfiguration.c)
 *     ndisQueryDeviceFlags @ 0x1C00B8680 (ndisQueryDeviceFlags.c)
 *     ndisCreateWoLPatternEntry @ 0x1C00BAAA0 (ndisCreateWoLPatternEntry.c)
 *     ndisMNotifyMachineName @ 0x1C00BD424 (ndisMNotifyMachineName.c)
 *     ndisEtwRegisterGuids @ 0x1C00BE134 (ndisEtwRegisterGuids.c)
 *     NdisRegisterTdiCallBack @ 0x1C00BE760 (NdisRegisterTdiCallBack.c)
 *     ?ndisIfInitGetInterfaceList@@YAJXZ @ 0x1C00D0208 (-ndisIfInitGetInterfaceList@@YAJXZ.c)
 *     ndisCreatePMProtocolOffloadEntry @ 0x1C00D4A60 (ndisCreatePMProtocolOffloadEntry.c)
 *     ndisCreateWakeUpPatternEntry @ 0x1C00D4AFC (ndisCreateWakeUpPatternEntry.c)
 *     ndisSetAddWakeUpPattern @ 0x1C00D6FD8 (ndisSetAddWakeUpPattern.c)
 *     ndisSetEnableWakeUp @ 0x1C00D72FC (ndisSetEnableWakeUp.c)
 *     ndisSetOpenAddWakeUpPattern @ 0x1C00D75D4 (ndisSetOpenAddWakeUpPattern.c)
 *     ndisXlateWakeUpPatternListToWolPatternList @ 0x1C00D8740 (ndisXlateWakeUpPatternListToWolPatternList.c)
 *     ndisXlateWolPatternListToWakeUpPatternList @ 0x1C00D89B0 (ndisXlateWolPatternListToWakeUpPatternList.c)
 *     ?ndisHandleLegacyBindIoctl@@YAXPEAU_UNICODE_STRING@@KPEBU1@@Z @ 0x1C00D8B84 (-ndisHandleLegacyBindIoctl@@YAXPEAU_UNICODE_STRING@@KPEBU1@@Z.c)
 *     ndisKillReceiveWorkerThreadPool @ 0x1C00D97BC (ndisKillReceiveWorkerThreadPool.c)
 *     NdisCloseFile @ 0x1C00DA620 (NdisCloseFile.c)
 *     NdisOpenFile @ 0x1C00DA7B0 (NdisOpenFile.c)
 *     NdisUnmapFile @ 0x1C00DAB10 (NdisUnmapFile.c)
 *     ndisGetMiniportInfo @ 0x1C00DDD7C (ndisGetMiniportInfo.c)
 *     NdisInitializeWrapper @ 0x1C00DEAF0 (NdisInitializeWrapper.c)
 *     NdisTerminateWrapper @ 0x1C00DEBD0 (NdisTerminateWrapper.c)
 *     ndisPnPCancelStopDevice @ 0x1C00E03B4 (ndisPnPCancelStopDevice.c)
 *     ndisPnPIrpStopDevice @ 0x1C00E16DC (ndisPnPIrpStopDevice.c)
 *     NdisSetAoAcOptions @ 0x1C00EAAB0 (NdisSetAoAcOptions.c)
 *     ?ndisBindReadFilterDriverSettingsFromV1Registry@@YA_NPEAUNDIS_BIND_FILTER_DRIVER@@AEAVKRegKey@@@Z @ 0x1C00F0CB8 (-ndisBindReadFilterDriverSettingsFromV1Registry@@YA_NPEAUNDIS_BIND_FILTER_DRIVER@@AEAVKRegKey@@@.c)
 *     ?DereferenceWdi@@YAXXZ @ 0x1C00F1DE0 (-DereferenceWdi@@YAXXZ.c)
 *     ?ReferenceWdi@@YA_NXZ @ 0x1C00F1EE8 (-ReferenceWdi@@YA_NXZ.c)
 *     NdisOpenAdapterEx @ 0x1C00F7950 (NdisOpenAdapterEx.c)
 *     ?ndisAttachFilterInner@@YAHPEAU_NDIS_MINIPORT_BLOCK@@PEAU_NDIS_FILTER_DRIVER_BLOCK@@KPEAUNDIS_BIND_FILTER_LINK@@@Z @ 0x1C00F821C (-ndisAttachFilterInner@@YAHPEAU_NDIS_MINIPORT_BLOCK@@PEAU_NDIS_FILTER_DRIVER_BLOCK@@KPEAUNDIS_BI.c)
 *     ndisPnPRemoveDevice @ 0x1C00FA8D0 (ndisPnPRemoveDevice.c)
 *     ?ndisDetachFilterInner@@YAXPEAU_NDIS_MINIPORT_BLOCK@@PEAU_NDIS_FILTER_BLOCK@@@Z @ 0x1C00FAB6C (-ndisDetachFilterInner@@YAXPEAU_NDIS_MINIPORT_BLOCK@@PEAU_NDIS_FILTER_BLOCK@@@Z.c)
 *     ?ndisUnbindProtocolOpen@@YAXPEAU_NDIS_MINIPORT_BLOCK@@PEAU_NDIS_OPEN_BLOCK@@@Z @ 0x1C00FADCC (-ndisUnbindProtocolOpen@@YAXPEAU_NDIS_MINIPORT_BLOCK@@PEAU_NDIS_OPEN_BLOCK@@@Z.c)
 *     NdisMapFile @ 0x1C0102A60 (NdisMapFile.c)
 *     ndisCreateNotifyQueue @ 0x1C0102EC8 (ndisCreateNotifyQueue.c)
 *     NdisMDeregisterDmaChannel @ 0x1C0103BD0 (NdisMDeregisterDmaChannel.c)
 *     NdisCmMakeCallComplete @ 0x1C0106D40 (NdisCmMakeCallComplete.c)
 *     NdisCoCreateVc @ 0x1C0107200 (NdisCoCreateVc.c)
 *     NdisMCmCreateVc @ 0x1C0108840 (NdisMCmCreateVc.c)
 *     NdisMCoIndicateStatus @ 0x1C0108F50 (NdisMCoIndicateStatus.c)
 *     NdisMCoIndicateStatusEx @ 0x1C0109020 (NdisMCoIndicateStatusEx.c)
 *     NdisMCoRequestComplete @ 0x1C0109090 (NdisMCoRequestComplete.c)
 *     ndisCoIndicateStatusInternal @ 0x1C01091F4 (ndisCoIndicateStatusInternal.c)
 *     ndisDereferenceVcPtr @ 0x1C0109638 (ndisDereferenceVcPtr.c)
 *     DriverEntry @ 0x1C01129E0 (DriverEntry.c)
 *     ndisIfInitialize @ 0x1C011412C (ndisIfInitialize.c)
 * Callees:
 *     <none>
 */

void __fastcall WPP_SF_(unsigned __int16 a1, const struct _GUID *a2)
{
  ndisWppFastTraceMessage(a2, a1, 0LL);
}
