/*
 * XREFs of WPP_SF_qdD @ 0x1C0045B1C
 * Callers:
 *     ndisOidRequestComplete @ 0x1C000B560 (ndisOidRequestComplete.c)
 *     ndisPreProcessOid @ 0x1C000BAF0 (ndisPreProcessOid.c)
 *     ndisSetDevicePower @ 0x1C0012104 (ndisSetDevicePower.c)
 *     ndisMFakeOidRequest @ 0x1C00123F0 (ndisMFakeOidRequest.c)
 *     ndisIndicateStatusInternal @ 0x1C00185E4 (ndisIndicateStatusInternal.c)
 *     ndisSetMiniportPacketFilter @ 0x1C001C100 (ndisSetMiniportPacketFilter.c)
 *     ndisUpdateFilterFakeStatus @ 0x1C001CF74 (ndisUpdateFilterFakeStatus.c)
 *     NdisAllocateGenericObject @ 0x1C00221A0 (NdisAllocateGenericObject.c)
 *     ndisUpdateMiniportFakeStatus @ 0x1C0022438 (ndisUpdateMiniportFakeStatus.c)
 *     ndisAllocateReceiveQueue @ 0x1C003CC6C (ndisAllocateReceiveQueue.c)
 *     ndisClearReceiveFilter @ 0x1C003D14C (ndisClearReceiveFilter.c)
 *     ndisFreeReceiveQueue @ 0x1C003D724 (ndisFreeReceiveQueue.c)
 *     ndisSetReceiveFilter @ 0x1C003EB5C (ndisSetReceiveFilter.c)
 *     NdisMAllocatePort @ 0x1C003F280 (NdisMAllocatePort.c)
 *     NdisMFreePort @ 0x1C003F5C0 (NdisMFreePort.c)
 *     ndisOidPreHDSplitCurrentConfig @ 0x1C0048A50 (ndisOidPreHDSplitCurrentConfig.c)
 *     ndisOidPreQosGetParameters @ 0x1C0049070 (ndisOidPreQosGetParameters.c)
 *     NdisWriteEventLogEntry @ 0x1C005C210 (NdisWriteEventLogEntry.c)
 *     ?ndisMRawInvokeDirectOidRequest@@YAHPEAU_NDIS_MINIPORT_BLOCK@@PEAU_NDIS_OID_REQUEST@@@Z @ 0x1C005DCF8 (-ndisMRawInvokeDirectOidRequest@@YAHPEAU_NDIS_MINIPORT_BLOCK@@PEAU_NDIS_OID_REQUEST@@@Z.c)
 *     ndisMFakeDirectOidRequest @ 0x1C005F680 (ndisMFakeDirectOidRequest.c)
 *     ndisMInvokeDirectOidRequest @ 0x1C005FCE8 (ndisMInvokeDirectOidRequest.c)
 *     ?ndisNicActiveAcquire@@YAJPEAU_NDIS_MINIPORT_BLOCK@@PEAU_NDIS_DEVICE_OBJECT_OPEN_CONTEXT@@PEAU_NDIS_PM_NIC_ACTIVE@@PEAU_IRP@@@Z @ 0x1C00719C4 (-ndisNicActiveAcquire@@YAJPEAU_NDIS_MINIPORT_BLOCK@@PEAU_NDIS_DEVICE_OBJECT_OPEN_CONTEXT@@PEAU_N.c)
 *     ndisMInvokeOidRequest @ 0x1C00A5080 (ndisMInvokeOidRequest.c)
 *     ndisSetSystemPower @ 0x1C00A79CC (ndisSetSystemPower.c)
 *     NdisMSetMiniportAttributes @ 0x1C00AA760 (NdisMSetMiniportAttributes.c)
 *     ndisPnPDispatch @ 0x1C00ACD70 (ndisPnPDispatch.c)
 *     ndisReadOffloadRegistry @ 0x1C00AE3F8 (ndisReadOffloadRegistry.c)
 *     ndisCheckNetworkInterfaceDataMismatch @ 0x1C00B8AB0 (ndisCheckNetworkInterfaceDataMismatch.c)
 *     ndisMiniportPreAddWoLPattern @ 0x1C00BA92C (ndisMiniportPreAddWoLPattern.c)
 *     ndisPreSetPMParameters @ 0x1C00BAE84 (ndisPreSetPMParameters.c)
 *     ndisMInitializeScatterGatherDma @ 0x1C00BB398 (ndisMInitializeScatterGatherDma.c)
 *     ndisOidPreLinkState @ 0x1C00BBB00 (ndisOidPreLinkState.c)
 *     ndisFInvokeNetPnPEvent @ 0x1C00BC170 (ndisFInvokeNetPnPEvent.c)
 *     ndisOidPreOffloadHwCaps @ 0x1C00BD360 (ndisOidPreOffloadHwCaps.c)
 *     ndisOidPreGetPciDeviceCustomProperties @ 0x1C00D1A70 (ndisOidPreGetPciDeviceCustomProperties.c)
 *     ndisOidPreMaxLinkSpeed @ 0x1C00D1E40 (ndisOidPreMaxLinkSpeed.c)
 *     ndisOidPreQosCapabilities @ 0x1C00D2210 (ndisOidPreQosCapabilities.c)
 *     ndisOidPreQosSetParameters @ 0x1C00D2310 (ndisOidPreQosSetParameters.c)
 *     ndisOidPreSetHDSplitParameters @ 0x1C00D2500 (ndisOidPreSetHDSplitParameters.c)
 *     ndisOidPreTcpConnectionOffload @ 0x1C00D2740 (ndisOidPreTcpConnectionOffload.c)
 *     ndisOidPreTcpConnectionOffloadHwCaps @ 0x1C00D2840 (ndisOidPreTcpConnectionOffloadHwCaps.c)
 *     ndisOidPreTcpConnectionOffloadParameters @ 0x1C00D2940 (ndisOidPreTcpConnectionOffloadParameters.c)
 *     ndisPreOffloadAdminSettings @ 0x1C00D2A30 (ndisPreOffloadAdminSettings.c)
 *     ndisPreTaskOffloadSet @ 0x1C00D2D20 (ndisPreTaskOffloadSet.c)
 *     ndisUpdateHDSplitKeyword @ 0x1C00D38B8 (ndisUpdateHDSplitKeyword.c)
 *     ndisMiniportPreAddProtocolOffload @ 0x1C00D4D0C (ndisMiniportPreAddProtocolOffload.c)
 *     ndisOidPMRemove @ 0x1C00D4F7C (ndisOidPMRemove.c)
 *     ndisOidPrePMCapabilities @ 0x1C00D5424 (ndisOidPrePMCapabilities.c)
 *     ndisPreQueryPMParameters @ 0x1C00D628C (ndisPreQueryPMParameters.c)
 *     ndisSetAddWakeUpPattern @ 0x1C00D6FD8 (ndisSetAddWakeUpPattern.c)
 *     ndisSetOpenAddWakeUpPattern @ 0x1C00D75D4 (ndisSetOpenAddWakeUpPattern.c)
 *     ndisSourcePreAddProtocolOffload @ 0x1C00D7A54 (ndisSourcePreAddProtocolOffload.c)
 *     ndisMDoProtocolRequest @ 0x1C00DC648 (ndisMDoProtocolRequest.c)
 *     ?ndisMRawInvokeOidRequest@@YAHPEAU_NDIS_MINIPORT_BLOCK@@PEAU_NDIS_OID_REQUEST@@@Z @ 0x1C00DD9EC (-ndisMRawInvokeOidRequest@@YAHPEAU_NDIS_MINIPORT_BLOCK@@PEAU_NDIS_OID_REQUEST@@@Z.c)
 *     NdisMRegisterInterrupt @ 0x1C00E07B0 (NdisMRegisterInterrupt.c)
 *     NdisMNetPnPEvent @ 0x1C00E1070 (NdisMNetPnPEvent.c)
 *     ndisOidPreIovBarResources @ 0x1C00E66B0 (ndisOidPreIovBarResources.c)
 *     ndisOidPreIovCaps @ 0x1C00E6800 (ndisOidPreIovCaps.c)
 *     ndisOidPreIovDeleteVPort @ 0x1C00E6D60 (ndisOidPreIovDeleteVPort.c)
 *     ndisOidPreIovFreeVF @ 0x1C00E6EA0 (ndisOidPreIovFreeVF.c)
 *     ndisOidPreIovGetVFVendorDeviceId @ 0x1C00E6FE0 (ndisOidPreIovGetVFVendorDeviceId.c)
 *     ndisOidPreIovOverlyingAdapterInfo @ 0x1C00E7420 (ndisOidPreIovOverlyingAdapterInfo.c)
 *     ndisOidPreIovPfLuid @ 0x1C00E74F0 (ndisOidPreIovPfLuid.c)
 *     ndisOidPreIovProbedBars @ 0x1C00E75F0 (ndisOidPreIovProbedBars.c)
 *     ndisOidPreIovReadVFConfigBlock @ 0x1C00E76E0 (ndisOidPreIovReadVFConfigBlock.c)
 *     ndisOidPreIovReadVFConfigSpace @ 0x1C00E7830 (ndisOidPreIovReadVFConfigSpace.c)
 *     ndisOidPreIovResetVF @ 0x1C00E7980 (ndisOidPreIovResetVF.c)
 *     ndisOidPreIovSetVFPowerState @ 0x1C00E7A90 (ndisOidPreIovSetVFPowerState.c)
 *     ndisOidPreIovVFParameters @ 0x1C00E7BA0 (ndisOidPreIovVFParameters.c)
 *     ndisOidPreIovVfSerialNumber @ 0x1C00E8100 (ndisOidPreIovVfSerialNumber.c)
 *     ndisOidPreIovWriteVFConfigBlock @ 0x1C00E8200 (ndisOidPreIovWriteVFConfigBlock.c)
 *     ndisOidPreIovWriteVFConfigSpace @ 0x1C00E8330 (ndisOidPreIovWriteVFConfigSpace.c)
 *     ?NdisPDAllocateMemory@@YAJPEAUPD_BUFFER_MANAGEMENT_GROUP_HANDLE__@@KPEAKPEAT_LARGE_INTEGER@@PEAPEAXPEAPEAUPD_MEMORY_HANDLE__@@@Z @ 0x1C00EB780 (-NdisPDAllocateMemory@@YAJPEAUPD_BUFFER_MANAGEMENT_GROUP_HANDLE__@@KPEAKPEAT_LARGE_INTEGER@@PEAP.c)
 *     ?NdisPDPIQueueControl@@YAJPEAU_NDIS_PD_QUEUE@@W4NDIS_PD_CONTROL_TYPE@@W4NDIS_PD_QUEUE_CONTROL_CODE@@PEAXK3KPEAK@Z @ 0x1C00ECEE0 (-NdisPDPIQueueControl@@YAJPEAU_NDIS_PD_QUEUE@@W4NDIS_PD_CONTROL_TYPE@@W4NDIS_PD_QUEUE_CONTROL_CO.c)
 *     ndisQueryPower @ 0x1C00F51BC (ndisQueryPower.c)
 *     ndisDevicePowerOn @ 0x1C00F5400 (ndisDevicePowerOn.c)
 *     ndisDevicePowerDown @ 0x1C00F58C0 (ndisDevicePowerDown.c)
 *     ndisMPowerPolicy @ 0x1C00F5B54 (ndisMPowerPolicy.c)
 *     ndisPnPNotifyBinding @ 0x1C00F77D4 (ndisPnPNotifyBinding.c)
 * Callees:
 *     ?ndisWppFastTraceMessage@@YAXPEBU_GUID@@GZZ @ 0x1C004FBEC (-ndisWppFastTraceMessage@@YAXPEBU_GUID@@GZZ.c)
 */

void WPP_SF_qdD(unsigned __int16 a1, const struct _GUID *a2, __int64 a3, int a4, ...)
{
  __int64 v4; // [rsp+70h] [rbp+18h] BYREF
  int v5; // [rsp+78h] [rbp+20h] BYREF
  va_list va; // [rsp+80h] [rbp+28h] BYREF

  va_start(va, a4);
  v5 = a4;
  v4 = a3;
  ndisWppFastTraceMessage(a2, a1, &v4, 8LL, &v5, 4LL, va, 4LL, 0LL);
}
