/*
 * XREFs of ??_EDMMVIDPNTOPOLOGY@@UEAAPEAXI@Z @ 0x1C002C5E0
 * Callers:
 *     ??_EDMMVIDPNTOPOLOGY@@WKA@EAAPEAXI@Z @ 0x1C0011150 (--_EDMMVIDPNTOPOLOGY@@WKA@EAAPEAXI@Z.c)
 *     ??_EDMMVIDPNTOPOLOGY@@WLA@EAAPEAXI@Z @ 0x1C0011160 (--_EDMMVIDPNTOPOLOGY@@WLA@EAAPEAXI@Z.c)
 * Callees:
 *     ??1DMMVIDPNTOPOLOGY@@UEAA@XZ @ 0x1C000426C (--1DMMVIDPNTOPOLOGY@@UEAA@XZ.c)
 *     ??3@YAXPEAX@Z @ 0x1C00689D8 (--3@YAXPEAX@Z.c)
 */

DMMVIDPNTOPOLOGY *__fastcall DMMVIDPNTOPOLOGY::`vector deleting destructor'(DMMVIDPNTOPOLOGY *this, char a2)
{
  DMMVIDPNTOPOLOGY::~DMMVIDPNTOPOLOGY(this);
  if ( (a2 & 1) != 0 )
    operator delete(this);
  return this;
}
