/*
 * XREFs of ?Release@DXGPRESENTMUTEX@@QEAAXXZ @ 0x1C000E574
 * Callers:
 *     ??1DXGPRESENTMUTEX@@QEAA@XZ @ 0x1C0001764 (--1DXGPRESENTMUTEX@@QEAA@XZ.c)
 *     ?Present@DXGCONTEXT@@QEAAJPEBUDXGK_PRESENT_PARAMS@@PEAVCOREDEVICEACCESS@@PEAVDXGADAPTERSTOPRESETLOCKSHARED@@PEAVCWin32kLocks@@PEAPEAV1@PEAUVIDSCH_SUBMIT_DATA_BASE@@@Z @ 0x1C006CD00 (-Present@DXGCONTEXT@@QEAAJPEBUDXGK_PRESENT_PARAMS@@PEAVCOREDEVICEACCESS@@PEAVDXGADAPTERSTOPRESET.c)
 *     ?PresentFromCdd@DXGCONTEXT@@QEAAJPEAU_D3DKMT_PRESENT@@IPEAVCOREDEVICEACCESS@@PEAVDXGADAPTERSTOPRESETLOCKSHARED@@PEAPEAV1@@Z @ 0x1C00D0E8C (-PresentFromCdd@DXGCONTEXT@@QEAAJPEAU_D3DKMT_PRESENT@@IPEAVCOREDEVICEACCESS@@PEAVDXGADAPTERSTOPR.c)
 * Callees:
 *     <none>
 */

void __fastcall DXGPRESENTMUTEX::Release(DXGPRESENTMUTEX *this)
{
  if ( *((_BYTE *)this + 16) )
  {
    *((_BYTE *)this + 16) = 0;
    DXGFASTMUTEX::Release((struct _KTHREAD **)(*((_QWORD *)this + 1) + 416LL));
  }
}
