/*
 * XREFs of _DXGDEVICE::OpenResourceObject_::_8_::ENSURE_LOCK_RELEASE::_ENSURE_LOCK_RELEASE @ 0x1C012C8D4
 * Callers:
 *     ?OpenResourceObject@DXGDEVICE@@QEAAJPEAU_D3DKMT_CREATEALLOCATION@@PEAU_D3DDDI_ALLOCATIONINFO2@@EPEAU_EPROCESS@@PEAU_DXGSHAREDALLOCOBJECT@@PEAVDXGRESOURCEREFERENCE@@PEAEPEAVDXGAUTOMUTEX@@PEAVDXGAUTOPUSHLOCK@@@Z @ 0x1C012D0CC (-OpenResourceObject@DXGDEVICE@@QEAAJPEAU_D3DKMT_CREATEALLOCATION@@PEAU_D3DDDI_ALLOCATIONINFO2@@E.c)
 * Callees:
 *     ?Release@DXGAUTOPUSHLOCK@@QEAAXXZ @ 0x1C0002B00 (-Release@DXGAUTOPUSHLOCK@@QEAAXXZ.c)
 *     ?ReleaseIfAcquired@DXGAUTOMUTEX@@QEAAXXZ @ 0x1C001C5D4 (-ReleaseIfAcquired@DXGAUTOMUTEX@@QEAAXXZ.c)
 */

void __fastcall DXGDEVICE::OpenResourceObject_::_8_::ENSURE_LOCK_RELEASE::_ENSURE_LOCK_RELEASE(DXGAUTOPUSHLOCK **a1)
{
  DXGAUTOMUTEX *v2; // rcx

  v2 = a1[1];
  if ( v2 )
    DXGAUTOMUTEX::ReleaseIfAcquired(v2);
  if ( *a1 )
    DXGAUTOPUSHLOCK::Release(*a1);
}
