/*
 * XREFs of ?GetKernelPtr@UMPDOBJ@@QAEPAXPAX@Z @ 0x1F3BE3
 * Callers:
 *     ?ThunkDDIOBJ@UMPDOBJ@@AAEHPAU_DDIOBJMAP@@PAPAXKPAX@Z @ 0x1F3EFC (-ThunkDDIOBJ@UMPDOBJ@@AAEHPAU_DDIOBJMAP@@PAPAXKPAX@Z.c)
 *     ?ThunkLINEATTRS@UMPDOBJ@@QAEHPAPAU_LINEATTRS@@@Z @ 0x1F3F8B (-ThunkLINEATTRS@UMPDOBJ@@QAEHPAPAU_LINEATTRS@@@Z.c)
 *     ?ThunkMemBlock@UMPDOBJ@@QAEHPAPAXK@Z @ 0x1F3FEA (-ThunkMemBlock@UMPDOBJ@@QAEHPAPAXK@Z.c)
 *     ?_AllocUserMem@UMPDOBJ@@AAEPAXKH@Z @ 0x1F40D8 (-_AllocUserMem@UMPDOBJ@@AAEPAXKH@Z.c)
 *     ?pstro@UMPDOBJ@@QAEHPAPAU_STROBJ@@@Z @ 0x1F45AC (-pstro@UMPDOBJ@@QAEHPAPAU_STROBJ@@@Z.c)
 *     ?pxlo@UMPDOBJ@@QAEHPAPAU_XLATEOBJ@@@Z @ 0x1F467B (-pxlo@UMPDOBJ@@QAEHPAPAU_XLATEOBJ@@@Z.c)
 *     ??1XUMPDOBJ@@QAE@XZ @ 0x20A147 (--1XUMPDOBJ@@QAE@XZ.c)
 *     ?Thunk@UMPDOBJ@@QAEKPAXK0K@Z @ 0x20A935 (-Thunk@UMPDOBJ@@QAEKPAXK0K@Z.c)
 *     ?UMPDDrvDitherColor@@YGKPAUDHPDEV__@@KKPAK@Z @ 0x20B5B6 (-UMPDDrvDitherColor@@YGKPAUDHPDEV__@@KKPAK@Z.c)
 *     ?UMPDDrvEnablePDEV@@YGPAUDHPDEV__@@PAU_devicemodeW@@PAGKPAPAUHSURF__@@KPAKKPAUtagDEVINFO@@PAUHDEV__@@1PAX@Z @ 0x20B9D7 (-UMPDDrvEnablePDEV@@YGPAUDHPDEV__@@PAU_devicemodeW@@PAGKPAPAUHSURF__@@KPAKKPAUtagDEVINFO@@PAUHDE.c)
 *     ?UMPDDrvEscape@@YGKPAU_SURFOBJ@@KKPAXK1@Z @ 0x20C1E1 (-UMPDDrvEscape@@YGKPAU_SURFOBJ@@KKPAXK1@Z.c)
 *     ?UMPDDrvFontManagement@@YGKPAU_SURFOBJ@@PAU_FONTOBJ@@KKPAXK2@Z @ 0x20C60A (-UMPDDrvFontManagement@@YGKPAU_SURFOBJ@@PAU_FONTOBJ@@KKPAXK2@Z.c)
 *     ?UMPDDrvNextBand@@YGHPAU_SURFOBJ@@PAU_POINTL@@@Z @ 0x20D15F (-UMPDDrvNextBand@@YGHPAU_SURFOBJ@@PAU_POINTL@@@Z.c)
 *     ?UMPDDrvQueryAdvanceWidths@@YGHPAUDHPDEV__@@PAU_FONTOBJ@@KPAKPAXK@Z @ 0x20D7AC (-UMPDDrvQueryAdvanceWidths@@YGHPAUDHPDEV__@@PAU_FONTOBJ@@KPAKPAXK@Z.c)
 *     ?UMPDDrvQueryDeviceSupport@@YGHPAU_SURFOBJ@@PAU_XLATEOBJ@@PAU_XFORMOBJ@@KKPAXK3@Z @ 0x20D90D (-UMPDDrvQueryDeviceSupport@@YGHPAU_SURFOBJ@@PAU_XLATEOBJ@@PAU_XFORMOBJ@@KKPAXK3@Z.c)
 *     ?UMPDDrvQueryFont@@YGPAU_IFIMETRICS@@PAUDHPDEV__@@KKPAK@Z @ 0x20DBEF (-UMPDDrvQueryFont@@YGPAU_IFIMETRICS@@PAUDHPDEV__@@KKPAK@Z.c)
 *     ?UMPDDrvQueryFontData@@YGJPAUDHPDEV__@@PAU_FONTOBJ@@KKPAU_GLYPHDATA@@PAXK@Z @ 0x20DD7A (-UMPDDrvQueryFontData@@YGJPAUDHPDEV__@@PAU_FONTOBJ@@KKPAU_GLYPHDATA@@PAXK@Z.c)
 *     ?UMPDDrvQueryFontTree@@YGPAXPAUDHPDEV__@@KKKPAK@Z @ 0x20DF1E (-UMPDDrvQueryFontTree@@YGPAXPAUDHPDEV__@@KKKPAK@Z.c)
 *     ?UMPDDrvQueryPerBandInfo@@YGKPAU_SURFOBJ@@PAU_PERBANDINFO@@@Z @ 0x20E10C (-UMPDDrvQueryPerBandInfo@@YGKPAU_SURFOBJ@@PAU_PERBANDINFO@@@Z.c)
 *     ?UMPDDrvStartBanding@@YGHPAU_SURFOBJ@@PAU_POINTL@@@Z @ 0x20E655 (-UMPDDrvStartBanding@@YGHPAU_SURFOBJ@@PAU_POINTL@@@Z.c)
 *     ?bSendLargeBitmap@UMPDOBJ@@QAEHPAU_SURFOBJ@@PAH@Z @ 0x20FDCC (-bSendLargeBitmap@UMPDOBJ@@QAEHPAU_SURFOBJ@@PAH@Z.c)
 * Callees:
 *     ?bSandboxedClient@UMPDOBJ@@QAEHXZ @ 0x1F4402 (-bSandboxedClient@UMPDOBJ@@QAEHXZ.c)
 */

char *__thiscall UMPDOBJ::GetKernelPtr(UMPDOBJ *this, char *a2)
{
  int v3; // ecx

  if ( !UMPDOBJ::bSandboxedClient(this) )
    return a2;
  v3 = *((_DWORD *)this + 52);
  if ( v3 && a2 )
    return &a2[-*(_DWORD *)(v3 + 24)];
  else
    return 0;
}
