/*
 * XREFs of _eftol_c@12 @ 0xEEF16
 * Callers:
 *     _GreCreateCompatibleBitmapInternal@24 @ 0x21480 (_GreCreateCompatibleBitmapInternal@24.c)
 *     ?bToPOINTL@EPOINTFL@@QAEHAAU_POINTL@@@Z @ 0x22DC0 (-bToPOINTL@EPOINTFL@@QAEHAAU_POINTL@@@Z.c)
 *     ?ExtTextOutRect@@YGHAAVXDCOBJ@@PAUtagRECT@@@Z @ 0x53A9C (-ExtTextOutRect@@YGHAAVXDCOBJ@@PAUtagRECT@@@Z.c)
 *     ?bGetNtoW_Win31@@YGHPAVMATRIX@@PAUtagLOGFONTW@@AAVIFIOBJ@@PAVDCOBJ@@KH@Z @ 0x6769C (-bGetNtoW_Win31@@YGHPAVMATRIX@@PAUtagLOGFONTW@@AAVIFIOBJ@@PAVDCOBJ@@KH@Z.c)
 *     ?bRealizeFont@RFONTOBJ@@QAEHPAVXDCOBJ@@PAVPDEVOBJ@@PAUtagENUMLOGFONTEXDVW@@PAVPFE@@PAU_FD_XFORM@@QAU_POINTL@@KKHHK@Z @ 0x84984 (-bRealizeFont@RFONTOBJ@@QAEHPAVXDCOBJ@@PAVPDEVOBJ@@PAUtagENUMLOGFONTEXDVW@@PAVPFE@@PAU_FD_XFORM@.c)
 *     ?lfOrientation@IFIOBJ@@QAEJXZ @ 0x8991C (-lfOrientation@IFIOBJ@@QAEJXZ.c)
 *     ?bSpDwmCreateLogicalSurface@@YGHPAUHDEV__@@PAVDWMSPRITE@@PAVSFMLOGICALSURFACE@@PAUtagSIZE@@PAPAV3@@Z @ 0xC6572 (-bSpDwmCreateLogicalSurface@@YGHPAUHDEV__@@PAVDWMSPRITE@@PAVSFMLOGICALSURFACE@@PAUtagSIZE@@PAPAV.c)
 *     ?vScale@ERECTL@@QAEXABVPOINTFL@@@Z @ 0x1CDA4B (-vScale@ERECTL@@QAEXABVPOINTFL@@@Z.c)
 *     ?vUpdateCachedDPIScaleValue@DC@@QAEXXZ @ 0x1D1265 (-vUpdateCachedDPIScaleValue@DC@@QAEXXZ.c)
 *     ?bSplitTriangle@@YGHPAU_TRIVERTEX@@PAKPAU_GRADIENT_TRIANGLE@@1PAE@Z @ 0x1EA00C (-bSplitTriangle@@YGHPAU_TRIVERTEX@@PAKPAU_GRADIENT_TRIANGLE@@1PAE@Z.c)
 *     _FLOATOBJ_GetLong@4 @ 0x1F313A (_FLOATOBJ_GetLong@4.c)
 *     ?GreScaleValuesInternal@@YGHAAVXDCOBJ@@PAJI@Z @ 0x1FCFB0 (-GreScaleValuesInternal@@YGHAAVXDCOBJ@@PAJI@Z.c)
 *     ?cjGetBrushOrPen@@YGJPAXH0@Z @ 0x1FD0B9 (-cjGetBrushOrPen@@YGJPAXH0@Z.c)
 *     _GreGetBitmapDpiScaleValue@4 @ 0x1FD33D (_GreGetBitmapDpiScaleValue@4.c)
 *     _GreAngleArc@24 @ 0x1FF67A (_GreAngleArc@24.c)
 *     ?ptlXform@EBOX@@QAE?AU_POINTL@@AAVEPOINTFL@@@Z @ 0x215265 (-ptlXform@EBOX@@QAE-AU_POINTL@@AAVEPOINTFL@@@Z.c)
 *     ?vArctan@@YGXVEFLOAT@@0AAV1@AAJ@Z @ 0x215329 (-vArctan@@YGXVEFLOAT@@0AAV1@AAJ@Z.c)
 *     ?vCosSin@@YGXVEFLOAT@@PAV1@1@Z @ 0x2154BB (-vCosSin@@YGXVEFLOAT@@PAV1@1@Z.c)
 *     ?vInitPageToDevice@EXFORMOBJ@@QAEXAAVXDCOBJ@@PAVMATRIX@@@Z @ 0x21D3B8 (-vInitPageToDevice@EXFORMOBJ@@QAEXAAVXDCOBJ@@PAVMATRIX@@@Z.c)
 *     ?vGenWidths@@YGXPAJ0AAVEFLOAT@@1JJJJ@Z @ 0x2252AD (-vGenWidths@@YGXPAJ0AAVEFLOAT@@1JJJJ@Z.c)
 *     ?vScale@EPOINTL@@QAEXABVPOINTFL@@@Z @ 0x226A07 (-vScale@EPOINTL@@QAEXABVPOINTFL@@@Z.c)
 *     ??0WIDENER@@QAE@AAVEPATHOBJ@@AAVEXFORMOBJ@@PAU_LINEATTRS@@@Z @ 0x234B5B (--0WIDENER@@QAE@AAVEPATHOBJ@@AAVEXFORMOBJ@@PAU_LINEATTRS@@@Z.c)
 *     ?bComputeIntersect@@YGHPAVEVECTORFX@@0000@Z @ 0x234D9E (-bComputeIntersect@@YGHPAVEVECTORFX@@0000@Z.c)
 *     ?bComputeWidenedBounds@EPATHOBJ@@QAEHAAV1@PAU_XFORMOBJ@@PAU_LINEATTRS@@@Z @ 0x234F52 (-bComputeWidenedBounds@EPATHOBJ@@QAEHAAV1@PAU_XFORMOBJ@@PAU_LINEATTRS@@@Z.c)
 *     ?ptfxFraction@@YG?AU_POINTFIX@@U1@PAVLINEDATA@@AAVEFLOAT@@2@Z @ 0x2360E3 (-ptfxFraction@@YG-AU_POINTFIX@@U1@PAVLINEDATA@@AAVEFLOAT@@2@Z.c)
 *     ?vVecSquareCompute@WIDENER@@AAEXAAVLINEDATA@@@Z @ 0x2377B1 (-vVecSquareCompute@WIDENER@@AAEXAAVLINEDATA@@@Z.c)
 * Callees:
 *     _eftol@0 @ 0xEEEF0 (_eftol@0.c)
 */

BOOL __stdcall eftol_c(int *a1, int *a2, int a3)
{
  char v3; // of

  *a2 = eftol(*a1, a3, a1[1]);
  return !v3;
}
