/*
 * XREFs of ?ADAPTER_RENDER_DdiGetRootPageTableSize@@YA_KPEAVADAPTER_RENDER@@PEAU_DXGKARG_GETROOTPAGETABLESIZE@@@Z @ 0x1C00198D0
 * Callers:
 *     <none>
 * Callees:
 *     ?DdiGetRootPageTableSize@ADAPTER_RENDER@@QEAA_KPEAU_DXGKARG_GETROOTPAGETABLESIZE@@@Z @ 0x1C0161B70 (-DdiGetRootPageTableSize@ADAPTER_RENDER@@QEAA_KPEAU_DXGKARG_GETROOTPAGETABLESIZE@@@Z.c)
 */

unsigned __int64 __fastcall ADAPTER_RENDER_DdiGetRootPageTableSize(
        struct ADAPTER_RENDER *a1,
        struct _DXGKARG_GETROOTPAGETABLESIZE *a2)
{
  return ADAPTER_RENDER::DdiGetRootPageTableSize(a1, a2);
}
