/*
 * XREFs of ?IsComputeOnlyAdapter@DXGADAPTER@@QEBAEXZ @ 0x1C00079D8
 * Callers:
 *     ?EnumAdaptersCallback@@YAJPEAVDXGADAPTER@@PEAX@Z @ 0x1C011C070 (-EnumAdaptersCallback@@YAJPEAVDXGADAPTER@@PEAX@Z.c)
 *     ?Initialize@DXGDEVICE@@QEAAJEE@Z @ 0x1C0129C34 (-Initialize@DXGDEVICE@@QEAAJEE@Z.c)
 *     ?FindFirstHWRenderAdapter@@YAJPEAVDXGADAPTER@@PEAX@Z @ 0x1C0173360 (-FindFirstHWRenderAdapter@@YAJPEAVDXGADAPTER@@PEAX@Z.c)
 *     ?CreateAdapter@DXGGLOBAL@@QEAAJPEAU_DEVICE_OBJECT@@PEAPEAVDXGADAPTER@@PEAXPEAU_DXGK_ADAPTER_CAPS@@PEAU_DXGK_DISPLAY_SCENARIO_CONTEXT@@@Z @ 0x1C017775C (-CreateAdapter@DXGGLOBAL@@QEAAJPEAU_DEVICE_OBJECT@@PEAPEAVDXGADAPTER@@PEAXPEAU_DXGK_ADAPTER_CAPS.c)
 *     ?Initialize@DXGADAPTER@@QEAAJPEAU_DEVICE_OBJECT@@PEAU_DXGK_ADAPTER_CAPS@@@Z @ 0x1C017A068 (-Initialize@DXGADAPTER@@QEAAJPEAU_DEVICE_OBJECT@@PEAU_DXGK_ADAPTER_CAPS@@@Z.c)
 *     ?DxgkpEscapeStopAdapters@@YAJPEAVDXGADAPTER@@PEAX@Z @ 0x1C020B920 (-DxgkpEscapeStopAdapters@@YAJPEAVDXGADAPTER@@PEAX@Z.c)
 *     DxgkSetIndirectDisplayRenderAdapter @ 0x1C0225468 (DxgkSetIndirectDisplayRenderAdapter.c)
 *     ?GetVendorAndDevice@DXGK_VIRTUAL_GPU_PARAV@@UEAAJPEAU_DXGKARG_GETVENDORANDDEVICE@@@Z @ 0x1C02348F0 (-GetVendorAndDevice@DXGK_VIRTUAL_GPU_PARAV@@UEAAJPEAU_DXGKARG_GETVENDORANDDEVICE@@@Z.c)
 * Callees:
 *     <none>
 */

bool __fastcall DXGADAPTER::IsComputeOnlyAdapter(DXGADAPTER *this)
{
  return *((int *)this + 649) >= 2600 && (*((_DWORD *)this + 642) & 8) != 0;
}
