/*
 * XREFs of ??1VIDMM_FENCE_STORAGE_PAGE@@QEAA@XZ @ 0x1C00A6FE0
 * Callers:
 *     ??_GVIDMM_FENCE_STORAGE_PAGE@@QEAAPEAXI@Z @ 0x1C0018C24 (--_GVIDMM_FENCE_STORAGE_PAGE@@QEAAPEAXI@Z.c)
 * Callees:
 *     ?FreeStorage@VIDMM_FENCE_STORAGE_PAGE@@AEAAXXZ @ 0x1C00A6FF8 (-FreeStorage@VIDMM_FENCE_STORAGE_PAGE@@AEAAXXZ.c)
 */

void __fastcall VIDMM_FENCE_STORAGE_PAGE::~VIDMM_FENCE_STORAGE_PAGE(VIDMM_FENCE_STORAGE_PAGE *this)
{
  VIDMM_FENCE_STORAGE_PAGE::FreeStorage(this);
}
