/*
 * XREFs of ??1SyncLockCriticalSection@Details@Wrappers@WRL@Microsoft@@QEAA@XZ @ 0x1800BBCA8
 * Callers:
 *     ?UpdateStreamResourcePriority@CBaseStreamGroupProxy@@UEAAJW4_ResourcePriorityAction@@KK@Z @ 0x180009E60 (-UpdateStreamResourcePriority@CBaseStreamGroupProxy@@UEAAJW4_ResourcePriorityAction@@KK@Z.c)
 *     ?UpdateStreamGroupResourcePriority@CSaDeviceProxy@@UEAAJW4_ResourcePriorityAction@@KK@Z @ 0x180009FD0 (-UpdateStreamGroupResourcePriority@CSaDeviceProxy@@UEAAJW4_ResourcePriorityAction@@KK@Z.c)
 *     ?GetDeviceVolumeStrip@CVolumeProvider@@UEAAJPEBGPEAPEAUIVolumeStrip@@@Z @ 0x18000F660 (-GetDeviceVolumeStrip@CVolumeProvider@@UEAAJPEBGPEAPEAUIVolumeStrip@@@Z.c)
 *     ?RegisterAppDeploymentNotifications@AtmosCheck@@AEAAJXZ @ 0x1800159D4 (-RegisterAppDeploymentNotifications@AtmosCheck@@AEAAJXZ.c)
 *     ?CreateStream@CAudioResourceManager@@UEAAJPEAUIAudioProcess@@PEAUIAudioStreamInfo@@KHHHHHH_JPEAVCEndpointCharacteristics@@KW4_AUDCLNT_SHAREMODE@@PEAUIAudioGraphCallback@@PEAUtWAVEFORMATEX@@22PEBU_GUID@@KPEBGKPEBUSPATIAL_STREAM_PROPERTIES@@PEAUIProcessSubmixProxy@@PEAUSYSTEM_AUDIO_STREAM@@@Z @ 0x180023730 (-CreateStream@CAudioResourceManager@@UEAAJPEAUIAudioProcess@@PEAUIAudioStreamInfo@@KHHHHHH_JPEAV.c)
 *     ?GetDefaultAudioEndpoint@DynamicAudioEndpointManager@@QEAAJKW4__MIDL___MIDL_itf_mmdeviceapi_0000_0000_0001@@W4__MIDL___MIDL_itf_mmdeviceapip_0000_0000_0001@@PEA_NPEAPEAUIMMDevice@@@Z @ 0x180031830 (-GetDefaultAudioEndpoint@DynamicAudioEndpointManager@@QEAAJKW4__MIDL___MIDL_itf_mmdeviceapi_0000.c)
 *     __lambda_3af8306e4cb261445d9be7b235e038d7_::operator()_::_1_::dtor$3 @ 0x18006596E (__lambda_3af8306e4cb261445d9be7b235e038d7_--operator()_--_1_--dtor$3.c)
 *     _AtmosCheck::RefreshSpatialAudioLicenseModelState_::_1_::dtor$0 @ 0x180068563 (_AtmosCheck--RefreshSpatialAudioLicenseModelState_--_1_--dtor$0.c)
 *     _CAudioSessionManager::Disconnect_::_1_::dtor$3 @ 0x18006A110 (_CAudioSessionManager--Disconnect_--_1_--dtor$3.c)
 *     _CProcessSubmixProxy::AddStream_::_1_::dtor$0 @ 0x18006A2F0 (_CProcessSubmixProxy--AddStream_--_1_--dtor$0.c)
 *     _CEndpointCharacteristics::GetStreamGroupFormat_::_1_::dtor$0 @ 0x18006A500 (_CEndpointCharacteristics--GetStreamGroupFormat_--_1_--dtor$0.c)
 *     _CProcessSubmixManager::OnNewProcessSubmix_::_1_::dtor$0 @ 0x18006A5C7 (_CProcessSubmixManager--OnNewProcessSubmix_--_1_--dtor$0.c)
 *     _CSpatialProperties::EnsureSpatialSettingsAreInitialized_::_1_::dtor$0 @ 0x18006A630 (_CSpatialProperties--EnsureSpatialSettingsAreInitialized_--_1_--dtor$0.c)
 *     _AtmosCheck::RegisterAppDeploymentNotifications_::_1_::dtor$2 @ 0x18006A6F0 (_AtmosCheck--RegisterAppDeploymentNotifications_--_1_--dtor$2.c)
 *     _AtmosCheck::AddArrayToLicenseMap_::_1_::dtor$1 @ 0x18006AF36 (_AtmosCheck--AddArrayToLicenseMap_--_1_--dtor$1.c)
 *     _CSpatialAudioTech::GetAtmosCheck_::_1_::dtor$0 @ 0x18006D750 (_CSpatialAudioTech--GetAtmosCheck_--_1_--dtor$0.c)
 *     _UseSupportedConnectorMode_::_1_::dtor$2 @ 0x18006DBF0 (_UseSupportedConnectorMode_--_1_--dtor$2.c)
 *     _CDeviceGraphObjectsStore::AddStreamGroup_::_1_::dtor$0 @ 0x18006ED80 (_CDeviceGraphObjectsStore--AddStreamGroup_--_1_--dtor$0.c)
 *     _CSpatialAudioTechnologies::CreateTopologyList_::_1_::dtor$0 @ 0x18006EF40 (_CSpatialAudioTechnologies--CreateTopologyList_--_1_--dtor$0.c)
 *     _CSpatialProperties::SetSpatialAudioSettingsInternal_::_1_::dtor$2 @ 0x18006F7EB (_CSpatialProperties--SetSpatialAudioSettingsInternal_--_1_--dtor$2.c)
 *     _AtmosCheck::QueryLicenseForSpatialSubtypeAndEndpoint_::_1_::dtor$0 @ 0x180070329 (_AtmosCheck--QueryLicenseForSpatialSubtypeAndEndpoint_--_1_--dtor$0.c)
 *     _CAudioSession::RegisterOwnerProcess_::_1_::dtor$0 @ 0x1800C2818 (_CAudioSession--RegisterOwnerProcess_--_1_--dtor$0.c)
 *     _CAudioSessionManager::RegisterDisconnectNotificationClient_::_1_::dtor$0 @ 0x1800C8FF1 (_CAudioSessionManager--RegisterDisconnectNotificationClient_--_1_--dtor$0.c)
 *     ?GetEndpointExtendedSpatialLicenseInfo@CPolicyConfig@@UEAAJPEBGKPEAUExtendedSpatialAudioEncoderInfo@@@Z @ 0x1800D29D0 (-GetEndpointExtendedSpatialLicenseInfo@CPolicyConfig@@UEAAJPEBGKPEAUExtendedSpatialAudioEncoderI.c)
 *     _CPolicyConfig::RefreshConnectorFormats_::_1_::dtor$3 @ 0x1800D373E (_CPolicyConfig--RefreshConnectorFormats_--_1_--dtor$3.c)
 *     _CPolicyConfig::RefreshConnectorFormats_::_1_::dtor$4 @ 0x1800D374A (_CPolicyConfig--RefreshConnectorFormats_--_1_--dtor$4.c)
 *     _CPolicyConfig::ReportSpatialLicenseChangedCallback_::_1_::dtor$0 @ 0x1800D3C0E (_CPolicyConfig--ReportSpatialLicenseChangedCallback_--_1_--dtor$0.c)
 *     _CPolicyConfig::SetDeviceFormatCommon_::_1_::dtor$1 @ 0x1800D46C6 (_CPolicyConfig--SetDeviceFormatCommon_--_1_--dtor$1.c)
 *     _CPolicyConfig::SetDeviceFormatInternal_::_1_::dtor$1 @ 0x1800D4B01 (_CPolicyConfig--SetDeviceFormatInternal_--_1_--dtor$1.c)
 *     _CPolicyConfig::ValidateSpatialAudioSettingsCallback_::_1_::dtor$0 @ 0x1800D662D (_CPolicyConfig--ValidateSpatialAudioSettingsCallback_--_1_--dtor$0.c)
 *     _CBaseStreamGroupProxy::AddStream_::_1_::dtor$0 @ 0x1800E2A31 (_CBaseStreamGroupProxy--AddStream_--_1_--dtor$0.c)
 *     _CBaseStreamGroupProxy::EnumerateProcessSubmixes_::_1_::dtor$0 @ 0x1800E3B2E (_CBaseStreamGroupProxy--EnumerateProcessSubmixes_--_1_--dtor$0.c)
 *     _CBaseStreamGroupProxy::RemoveStream_::_1_::dtor$1 @ 0x1800E54B3 (_CBaseStreamGroupProxy--RemoveStream_--_1_--dtor$1.c)
 *     _CBaseStreamGroupProxy::UpdateCountOfFormatSensitiveClients_::_1_::dtor$0 @ 0x1800E5AAE (_CBaseStreamGroupProxy--UpdateCountOfFormatSensitiveClients_--_1_--dtor$0.c)
 *     _CBaseStreamGroupProxy::UpdateCountOfLazyRequestClients_::_1_::dtor$0 @ 0x1800E5B92 (_CBaseStreamGroupProxy--UpdateCountOfLazyRequestClients_--_1_--dtor$0.c)
 *     _CBaseStreamGroupProxy::UpdateCountOfPeriodicitySensitiveClients_::_1_::dtor$0 @ 0x1800E5C73 (_CBaseStreamGroupProxy--UpdateCountOfPeriodicitySensitiveClients_--_1_--dtor$0.c)
 *     _CDeviceGraphObjectsStore::FindFirstMatchingSaDevice_::_1_::dtor$1 @ 0x1800E7770 (_CDeviceGraphObjectsStore--FindFirstMatchingSaDevice_--_1_--dtor$1.c)
 *     _CDeviceGraphObjectsStore::GetAllStreamGroups_::_1_::dtor$0 @ 0x1800E7AAB (_CDeviceGraphObjectsStore--GetAllStreamGroups_--_1_--dtor$0.c)
 *     _CDeviceGraphStore::GetAllStreamGroups_::_1_::dtor$1 @ 0x1800E7CE8 (_CDeviceGraphStore--GetAllStreamGroups_--_1_--dtor$1.c)
 *     _CDeviceGraphObjectsStore::GetConnectedStreamGroups_::_1_::dtor$0 @ 0x1800E7EFF (_CDeviceGraphObjectsStore--GetConnectedStreamGroups_--_1_--dtor$0.c)
 *     _CDeviceGraphStore::GetConnectedStreamGroups_::_1_::dtor$1 @ 0x1800E8148 (_CDeviceGraphStore--GetConnectedStreamGroups_--_1_--dtor$1.c)
 *     _CDeviceGraphObjectsStore::GetSaDevices_::_1_::dtor$0 @ 0x1800E8267 (_CDeviceGraphObjectsStore--GetSaDevices_--_1_--dtor$0.c)
 *     _CDeviceGraphObjectsStore::GetStreamGroupsConnectedToSaDevice_::_1_::dtor$0 @ 0x1800E837B (_CDeviceGraphObjectsStore--GetStreamGroupsConnectedToSaDevice_--_1_--dtor$0.c)
 *     _CDeviceGraphObjectsStore::GetStreamGroupsConnectedToSaDevice_::_1_::dtor$1 @ 0x1800E8387 (_CDeviceGraphObjectsStore--GetStreamGroupsConnectedToSaDevice_--_1_--dtor$1.c)
 *     _CDeviceGraphStore::GetSubmixHelper_::_1_::dtor$0 @ 0x1800E899A (_CDeviceGraphStore--GetSubmixHelper_--_1_--dtor$0.c)
 *     _CAudioResourceManager::CreateInternalLoopbackStream_::_1_::dtor$8 @ 0x1800EC1EA (_CAudioResourceManager--CreateInternalLoopbackStream_--_1_--dtor$8.c)
 *     _CAudioResourceManager::FreeResourcesAndLockForStreamGroupConnectionDisconnection_::_1_::dtor$0 @ 0x1800EC595 (_CAudioResourceManager--FreeResourcesAndLockForStreamGroupConnectionDisconnection_--_1_--dtor$0.c)
 *     _CAudioResourceManager::ReevaluateSaDeviceSettings_::_1_::dtor$2 @ 0x1800ED210 (_CAudioResourceManager--ReevaluateSaDeviceSettings_--_1_--dtor$2.c)
 *     _CAudioResourceManager::UpdateAuxiliaryInputForStreamGroup_::_1_::dtor$3 @ 0x1800EE25C (_CAudioResourceManager--UpdateAuxiliaryInputForStreamGroup_--_1_--dtor$3.c)
 *     _CProcessSubmixManager::GetAppSubmixClientContextHelper_::_1_::dtor$0 @ 0x1800F1B31 (_CProcessSubmixManager--GetAppSubmixClientContextHelper_--_1_--dtor$0.c)
 *     ?GetProcessSubmixById@CProcessSubmixManager@@UEAAJPEAVCAppSubmixClient@@_JPEAPEAUIProcessSubmixProxy@@@Z @ 0x1800F1BA0 (-GetProcessSubmixById@CProcessSubmixManager@@UEAAJPEAVCAppSubmixClient@@_JPEAPEAUIProcessSubmixP.c)
 *     asm_GetApplicationSubmixes$dtor$1 @ 0x1800F32EC (asm_GetApplicationSubmixes$dtor$1.c)
 *     _CEndpointCharacteristics::TryGetOverridingMixFormat_::_1_::dtor$0 @ 0x18010D5B5 (_CEndpointCharacteristics--TryGetOverridingMixFormat_--_1_--dtor$0.c)
 *     HasEndpointProtectionOverride @ 0x18010FBB4 (HasEndpointProtectionOverride.c)
 *     _HasEndpointProtectionOverride_::_1_::dtor$4 @ 0x18010FEF4 (_HasEndpointProtectionOverride_--_1_--dtor$4.c)
 *     _Sarm::CSpatialAudioResourceManager::HandleAppVolumePolicyChange_::_1_::dtor$0 @ 0x180114257 (_Sarm--CSpatialAudioResourceManager--HandleAppVolumePolicyChange_--_1_--dtor$0.c)
 *     _Sarm::CSpatialAudioResourceManager::HandleRedistributeObjects_::_1_::dtor$0 @ 0x1801142F9 (_Sarm--CSpatialAudioResourceManager--HandleRedistributeObjects_--_1_--dtor$0.c)
 *     _Sarm::CSpatialAudioResourceManager::HandleRequestForDynamicObjects_::_1_::dtor$0 @ 0x18011440E (_Sarm--CSpatialAudioResourceManager--HandleRequestForDynamicObjects_--_1_--dtor$0.c)
 *     _std::_Func_impl_no_alloc__lambda_afaf78576840e78fa8c7f1d1d7e112d3__void_::_Do_call_::_1_::dtor$0 @ 0x18011608E (_std--_Func_impl_no_alloc__lambda_afaf78576840e78fa8c7f1d1d7e112d3__void_--_Do_call_--_1_--dtor$.c)
 *     std::_Func_impl_no_alloc__lambda_c4f40eb4128b796d78dc595c2797cc70__void_::_Do_call @ 0x1801160C0 (std--_Func_impl_no_alloc__lambda_c4f40eb4128b796d78dc595c2797cc70__void_--_Do_call.c)
 *     _CExclusiveModeListener::OnExclusiveModeChange_::_1_::dtor$0 @ 0x1801198C4 (_CExclusiveModeListener--OnExclusiveModeChange_--_1_--dtor$0.c)
 *     _CExclusiveModeListener::OnHmdAdded_::_1_::dtor$0 @ 0x180119ADB (_CExclusiveModeListener--OnHmdAdded_--_1_--dtor$0.c)
 *     _CExclusiveModeListener::OnHmdRemoved_::_1_::dtor$0 @ 0x180119DCF (_CExclusiveModeListener--OnHmdRemoved_--_1_--dtor$0.c)
 *     _CExclusiveModeListener::OnHoloshellStateChange_::_1_::dtor$0 @ 0x180119FBD (_CExclusiveModeListener--OnHoloshellStateChange_--_1_--dtor$0.c)
 *     _DynamicAudioEndpointManager::AddRule_::_1_::dtor$0 @ 0x18011DCDB (_DynamicAudioEndpointManager--AddRule_--_1_--dtor$0.c)
 *     _DynamicAudioEndpointManager::GetRule_::_1_::dtor$3 @ 0x18011E588 (_DynamicAudioEndpointManager--GetRule_--_1_--dtor$3.c)
 *     _DynamicAudioEndpointManager::OnDeviceStateChanged_::_1_::dtor$0 @ 0x18011E9F7 (_DynamicAudioEndpointManager--OnDeviceStateChanged_--_1_--dtor$0.c)
 *     _DynamicAudioEndpointManager::RemoveRule_::_1_::dtor$0 @ 0x18011F1DE (_DynamicAudioEndpointManager--RemoveRule_--_1_--dtor$0.c)
 *     _DynamicAudioEndpointManager::RemoveRule_::_1_::dtor$1_0 @ 0x18011F31D (_DynamicAudioEndpointManager--RemoveRule_--_1_--dtor$1_0.c)
 *     _DynamicAudioEndpointManager::SetDefaultAudioEndpoint_::_1_::dtor$0 @ 0x18011F585 (_DynamicAudioEndpointManager--SetDefaultAudioEndpoint_--_1_--dtor$0.c)
 *     _DynamicAudioEndpointManager::UpdateRule_::_1_::dtor$0 @ 0x18011F8BA (_DynamicAudioEndpointManager--UpdateRule_--_1_--dtor$0.c)
 *     _CSpatialProperties::ClearSpatialAudioSettings_::_1_::dtor$0 @ 0x180121136 (_CSpatialProperties--ClearSpatialAudioSettings_--_1_--dtor$0.c)
 *     _CSpatialProperties::GetAudioFormatForSpatialFormat_::_1_::dtor$2 @ 0x180121CED (_CSpatialProperties--GetAudioFormatForSpatialFormat_--_1_--dtor$2.c)
 *     _CSpatialProperties::GetSpatialFormatForAudioFormat_::_1_::dtor$2 @ 0x180122EB7 (_CSpatialProperties--GetSpatialFormatForAudioFormat_--_1_--dtor$2.c)
 *     _CSpatialProperties::ProcessPropertyChange_::_1_::dtor$7 @ 0x180123C08 (_CSpatialProperties--ProcessPropertyChange_--_1_--dtor$7.c)
 *     _CSpatialProperties::SetSpatialAudioSettings_::_1_::dtor$2 @ 0x180124CC3 (_CSpatialProperties--SetSpatialAudioSettings_--_1_--dtor$2.c)
 *     _SpatialAudioDeviceStateWriter::ResetState_::_1_::dtor$0 @ 0x180128660 (_SpatialAudioDeviceStateWriter--ResetState_--_1_--dtor$0.c)
 *     _SpatialAudioDeviceStateWriter::SetActiveSpatialAudioEncoderId_::_1_::dtor$0 @ 0x180128707 (_SpatialAudioDeviceStateWriter--SetActiveSpatialAudioEncoderId_--_1_--dtor$0.c)
 *     _SpatialAudioDeviceStateWriter::SetSpatialRendererSelectionMode_::_1_::dtor$0 @ 0x1801287A7 (_SpatialAudioDeviceStateWriter--SetSpatialRendererSelectionMode_--_1_--dtor$0.c)
 *     _SpatialAudioDeviceStateWriter::SetSpatialVssSelectionMode_::_1_::dtor$0 @ 0x180128840 (_SpatialAudioDeviceStateWriter--SetSpatialVssSelectionMode_--_1_--dtor$0.c)
 *     _AtmosCheck::EnableAllAtmosCapabilities_::_1_::dtor$0 @ 0x180138649 (_AtmosCheck--EnableAllAtmosCapabilities_--_1_--dtor$0.c)
 *     _AtmosCheck::InitializeAppServiceMode_::_1_::dtor$0 @ 0x18013A0B9 (_AtmosCheck--InitializeAppServiceMode_--_1_--dtor$0.c)
 *     _AtmosCheck::IsLogLicenseResult_::_1_::dtor$0 @ 0x18013A5D8 (_AtmosCheck--IsLogLicenseResult_--_1_--dtor$0.c)
 *     _AtmosCheck::PerformLicenseCheckForAllEndpoints_::_1_::dtor$0 @ 0x18013A9C1 (_AtmosCheck--PerformLicenseCheckForAllEndpoints_--_1_--dtor$0.c)
 *     _AtmosCheck::RefreshLicenseStatus_::_1_::dtor$0 @ 0x18013B82C (_AtmosCheck--RefreshLicenseStatus_--_1_--dtor$0.c)
 *     _AtmosCheck::UninitializeAppServiceMode_::_1_::dtor$0 @ 0x18013C280 (_AtmosCheck--UninitializeAppServiceMode_--_1_--dtor$0.c)
 *     ?UnregisterAppDeploymentNotifications@AtmosCheck@@AEAAJXZ @ 0x18013C294 (-UnregisterAppDeploymentNotifications@AtmosCheck@@AEAAJXZ.c)
 *     _AtmosCheck::UnregisterAppDeploymentNotifications_::_1_::dtor$0 @ 0x18013C35E (_AtmosCheck--UnregisterAppDeploymentNotifications_--_1_--dtor$0.c)
 *     _AtmosCheck::UpdateLicenseMapForAllEndpoints_::_1_::dtor$0 @ 0x18013C706 (_AtmosCheck--UpdateLicenseMapForAllEndpoints_--_1_--dtor$0.c)
 * Callees:
 *     <none>
 */

void __fastcall Microsoft::WRL::Wrappers::Details::SyncLockCriticalSection::~SyncLockCriticalSection(
        struct _RTL_CRITICAL_SECTION **this)
{
  struct _RTL_CRITICAL_SECTION *v2; // rcx

  v2 = *this;
  if ( v2 )
  {
    LeaveCriticalSection(v2);
    *this = 0LL;
  }
}
