/*
 * XREFs of ??_GADAPTER_DISPLAY@@QEAAPEAXI@Z @ 0x1C002D5CC
 * Callers:
 *     ?CreateDisplayCore@ADAPTER_DISPLAY@@SAJPEAVDXGADAPTER@@PEAPEAV1@@Z @ 0x1C014F768 (-CreateDisplayCore@ADAPTER_DISPLAY@@SAJPEAVDXGADAPTER@@PEAPEAV1@@Z.c)
 *     ??1DXGADAPTER@@QEAA@XZ @ 0x1C01BC694 (--1DXGADAPTER@@QEAA@XZ.c)
 * Callees:
 *     ??1ADAPTER_DISPLAY@@QEAA@XZ @ 0x1C01C0614 (--1ADAPTER_DISPLAY@@QEAA@XZ.c)
 */

ADAPTER_DISPLAY *__fastcall ADAPTER_DISPLAY::`scalar deleting destructor'(ADAPTER_DISPLAY *P)
{
  ADAPTER_DISPLAY::~ADAPTER_DISPLAY(P);
  if ( P )
    ExFreePoolWithTag(P, 0);
  return P;
}
