/*
 * XREFs of ?UnPairAndRelease@DXGCOMPOSITIONSURFACEPROXY@@UEAAXXZ @ 0x1C0232F30
 * Callers:
 *     <none>
 * Callees:
 *     ?CloseSelfHandle@DXGCOMPOSITIONSURFACEPROXY@@IEAAJXZ @ 0x1C0230DB0 (-CloseSelfHandle@DXGCOMPOSITIONSURFACEPROXY@@IEAAJXZ.c)
 *     ?Release@DXGCOMPOSITIONSURFACEPROXY@@QEAAJXZ @ 0x1C0232518 (-Release@DXGCOMPOSITIONSURFACEPROXY@@QEAAJXZ.c)
 *     ?SendUnPairAndRelease@DXGCOMPOSITIONSURFACEPROXY@@IEAAJXZ @ 0x1C0232C4C (-SendUnPairAndRelease@DXGCOMPOSITIONSURFACEPROXY@@IEAAJXZ.c)
 */

void __fastcall DXGCOMPOSITIONSURFACEPROXY::UnPairAndRelease(DXGCOMPOSITIONSURFACEPROXY *this)
{
  DXGCOMPOSITIONSURFACEPROXY::SendUnPairAndRelease(this);
  DXGCOMPOSITIONSURFACEPROXY::CloseSelfHandle(this);
  DXGCOMPOSITIONSURFACEPROXY::Release(this);
}
