/*
 * XREFs of ??1_OUTPUTDUPL_CONTEXTLIST@@QEAA@XZ @ 0x1400763B0
 * Callers:
 *     <none>
 * Callees:
 *     ??1DXGFASTMUTEX@@QEAA@XZ @ 0x14005DA48 (--1DXGFASTMUTEX@@QEAA@XZ.c)
 */

void __fastcall _OUTPUTDUPL_CONTEXTLIST::~_OUTPUTDUPL_CONTEXTLIST(_OUTPUTDUPL_CONTEXTLIST *this)
{
  DXGFASTMUTEX::~DXGFASTMUTEX(this);
}
