/*
 * XREFs of ??_EDXGDISPLAYMANAGEROBJECT@@UEAAPEAXI@Z @ 0x14000FC00
 * Callers:
 *     <none>
 * Callees:
 *     ??3?$DXGQUOTAALLOCATOR@$0BAA@$0GNGCEDEG@@@SAXPEAX@Z @ 0x1400110B0 (--3-$DXGQUOTAALLOCATOR@$0BAA@$0GNGCEDEG@@@SAXPEAX@Z.c)
 *     ??1DXGDISPLAYMANAGEROBJECT@@UEAA@XZ @ 0x1403C85F8 (--1DXGDISPLAYMANAGEROBJECT@@UEAA@XZ.c)
 */

DXGDISPLAYMANAGEROBJECT *__fastcall DXGDISPLAYMANAGEROBJECT::`vector deleting destructor'(
        DXGDISPLAYMANAGEROBJECT *this,
        char a2)
{
  DXGDISPLAYMANAGEROBJECT::~DXGDISPLAYMANAGEROBJECT(this);
  if ( (a2 & 1) != 0 )
    DXGQUOTAALLOCATOR<256,1835156294>::operator delete(this);
  return this;
}
