/*
 * XREFs of Debug_FreAssertMsg @ 0x1C0012DEC
 * Callers:
 *     Controller_WdfEvtWatchdogTimerFunc @ 0x1C0001870 (Controller_WdfEvtWatchdogTimerFunc.c)
 *     Register_RestoreRyzenFeatureBitsPostReset @ 0x1C0003180 (Register_RestoreRyzenFeatureBitsPostReset.c)
 *     UsbDevice_CompleteConfigureEndpointRequest @ 0x1C00040A4 (UsbDevice_CompleteConfigureEndpointRequest.c)
 *     UsbDevice_HandleAssignPinsForEndpointsToOffloadState @ 0x1C0004364 (UsbDevice_HandleAssignPinsForEndpointsToOffloadState.c)
 *     UsbDevice_HandleSendStopEndpointToOffloadedEndpointsState @ 0x1C0004488 (UsbDevice_HandleSendStopEndpointToOffloadedEndpointsState.c)
 *     UsbDevice_HandleUnassignPinsForOffloadedEndpointsState @ 0x1C0004544 (UsbDevice_HandleUnassignPinsForOffloadedEndpointsState.c)
 *     UsbDevice_QueueConfigureEndpointEvent @ 0x1C0004D7C (UsbDevice_QueueConfigureEndpointEvent.c)
 *     UsbDevice_SetResourceAssignmentCompletion @ 0x1C0005400 (UsbDevice_SetResourceAssignmentCompletion.c)
 *     UsbDevice_StopEndpointToOffloadedEndpointCompletion @ 0x1C00054E0 (UsbDevice_StopEndpointToOffloadedEndpointCompletion.c)
 *     UsbDevice_ValidateEndpointConfigureRequest @ 0x1C0005530 (UsbDevice_ValidateEndpointConfigureRequest.c)
 *     Command_SendCommand @ 0x1C0008820 (Command_SendCommand.c)
 *     Command_WdfEvtWatchdogTimerFunction @ 0x1C0008950 (Command_WdfEvtWatchdogTimerFunction.c)
 *     XilCommand_AllocateSecureResources @ 0x1C0009CD4 (XilCommand_AllocateSecureResources.c)
 *     XilCommand_Create @ 0x1C0009E10 (XilCommand_Create.c)
 *     XilCommand_CreateSecureObject @ 0x1C0009E70 (XilCommand_CreateSecureObject.c)
 *     XilCommand_FreeSecureResources @ 0x1C0009FC0 (XilCommand_FreeSecureResources.c)
 *     XilCommand_InitializeSecureResources @ 0x1C000A130 (XilCommand_InitializeSecureResources.c)
 *     XilCommand_SendAbortRingCommandRequest @ 0x1C000A238 (XilCommand_SendAbortRingCommandRequest.c)
 *     XilCommand_SendAddCommandCRBToRingRequest @ 0x1C000A344 (XilCommand_SendAddCommandCRBToRingRequest.c)
 *     XilCommand_SendAdvanceDequeuePointerRequest @ 0x1C000A55C (XilCommand_SendAdvanceDequeuePointerRequest.c)
 *     XilCommand_SendQueryIsRingRunningRequest @ 0x1C000A66C (XilCommand_SendQueryIsRingRunningRequest.c)
 *     Controller_D0EntryRestoreState @ 0x1C000B688 (Controller_D0EntryRestoreState.c)
 *     Controller_D0ExitSaveState @ 0x1C000B9D4 (Controller_D0ExitSaveState.c)
 *     Controller_Start @ 0x1C000DCE8 (Controller_Start.c)
 *     Controller_WdfEvtDeviceArmWakeFromS0 @ 0x1C000FF70 (Controller_WdfEvtDeviceArmWakeFromS0.c)
 *     Controller_WdfEvtDeviceD0Entry @ 0x1C0010120 (Controller_WdfEvtDeviceD0Entry.c)
 *     Controller_WdfEvtDeviceDisarmWakeFromS0 @ 0x1C0010DB0 (Controller_WdfEvtDeviceDisarmWakeFromS0.c)
 *     DeviceSlot_GetXilCoreDeviceSlotData @ 0x1C00131F0 (DeviceSlot_GetXilCoreDeviceSlotData.c)
 *     XilDeviceSlot_AllocateSecureResources @ 0x1C0013310 (XilDeviceSlot_AllocateSecureResources.c)
 *     XilDeviceSlot_Create @ 0x1C001342C (XilDeviceSlot_Create.c)
 *     XilDeviceSlot_CreateSecureObject @ 0x1C001349C (XilDeviceSlot_CreateSecureObject.c)
 *     XilDeviceSlot_FreeSecureResources @ 0x1C00135C0 (XilDeviceSlot_FreeSecureResources.c)
 *     XilDeviceSlot_InitializeSecureResources @ 0x1C00136F4 (XilDeviceSlot_InitializeSecureResources.c)
 *     XilDeviceSlot_InitializeSecureScratchpadBuffers @ 0x1C0013804 (XilDeviceSlot_InitializeSecureScratchpadBuffers.c)
 *     XilDeviceSlot_PrepareHardware @ 0x1C0013910 (XilDeviceSlot_PrepareHardware.c)
 *     XilDeviceSlot_SendClearDeviceContextRequest @ 0x1C0013A68 (XilDeviceSlot_SendClearDeviceContextRequest.c)
 *     XilDeviceSlot_SendQueryEndpointContextInfoRequest @ 0x1C0013B7C (XilDeviceSlot_SendQueryEndpointContextInfoRequest.c)
 *     XilDeviceSlot_SendQuerySlotContextInfoRequest @ 0x1C0013CC8 (XilDeviceSlot_SendQuerySlotContextInfoRequest.c)
 *     XilDeviceSlot_SendSetDeviceContextRequest @ 0x1C0013E04 (XilDeviceSlot_SendSetDeviceContextRequest.c)
 *     XilDeviceSlot_SetDeviceContext @ 0x1C0013F38 (XilDeviceSlot_SetDeviceContext.c)
 *     XilEndpoint_AllocateStreamContextArray @ 0x1C0014130 (XilEndpoint_AllocateStreamContextArray.c)
 *     XilEndpoint_CommitStreamContextArrayUpdates @ 0x1C001430C (XilEndpoint_CommitStreamContextArrayUpdates.c)
 *     XilEndpoint_Create @ 0x1C00143A0 (XilEndpoint_Create.c)
 *     XilEndpoint_CreateSecureObject @ 0x1C0014468 (XilEndpoint_CreateSecureObject.c)
 *     XilEndpoint_FetchStreamContextArray @ 0x1C0014660 (XilEndpoint_FetchStreamContextArray.c)
 *     XilEndpoint_FreeStreamContextArray @ 0x1C001470C (XilEndpoint_FreeStreamContextArray.c)
 *     Endpoint_Disable @ 0x1C0015310 (Endpoint_Disable.c)
 *     Endpoint_UcxEvtEndpointReset @ 0x1C00193A0 (Endpoint_UcxEvtEndpointReset.c)
 *     RootHub_DetectAndAcknowledgePortResume @ 0x1C001D924 (RootHub_DetectAndAcknowledgePortResume.c)
 *     RootHub_HandlePortStatusChangeEvent @ 0x1C001E48C (RootHub_HandlePortStatusChangeEvent.c)
 *     RootHub_UcxEvtClearHubFeature @ 0x1C001ED30 (RootHub_UcxEvtClearHubFeature.c)
 *     RootHub_UcxEvtClearPortFeature @ 0x1C001EF80 (RootHub_UcxEvtClearPortFeature.c)
 *     RootHub_UcxEvtGetPortErrorCount @ 0x1C0020710 (RootHub_UcxEvtGetPortErrorCount.c)
 *     RootHub_UcxEvtGetPortStatus @ 0x1C0020A50 (RootHub_UcxEvtGetPortStatus.c)
 *     RootHub_UcxEvtInterruptTransfer @ 0x1C00213C0 (RootHub_UcxEvtInterruptTransfer.c)
 *     RootHub_UcxEvtSetPortFeature @ 0x1C00217F0 (RootHub_UcxEvtSetPortFeature.c)
 *     RootHub_WdfEvtTimer20PortResumeComplete @ 0x1C0022E94 (RootHub_WdfEvtTimer20PortResumeComplete.c)
 *     TR_AcquireSecureSegments @ 0x1C0023730 (TR_AcquireSecureSegments.c)
 *     TR_AddTRBRangeToSecureTransferRing @ 0x1C0023B94 (TR_AddTRBRangeToSecureTransferRing.c)
 *     TR_CreateSecureObject @ 0x1C0023FEC (TR_CreateSecureObject.c)
 *     TR_FreeSecureTransferSegments @ 0x1C0024884 (TR_FreeSecureTransferSegments.c)
 *     TR_InitializeTransferSegment @ 0x1C0024C0C (TR_InitializeTransferSegment.c)
 *     Control_Transfer_Map @ 0x1C0027110 (Control_Transfer_Map.c)
 *     Isoch_MapStage @ 0x1C0029B84 (Isoch_MapStage.c)
 *     Isoch_Stage_MapIntoRing @ 0x1C002C518 (Isoch_Stage_MapIntoRing.c)
 *     Isoch_WdfEvtIoQueueReadyNotification @ 0x1C002DC70 (Isoch_WdfEvtIoQueueReadyNotification.c)
 *     Bulk_MapStage @ 0x1C002FC50 (Bulk_MapStage.c)
 *     Bulk_WdfEvtIoQueueReadyNotification @ 0x1C0033430 (Bulk_WdfEvtIoQueueReadyNotification.c)
 *     XilUsbDevice_Create @ 0x1C00343E8 (XilUsbDevice_Create.c)
 *     XilUsbDevice_CreateSecureObject @ 0x1C00344E8 (XilUsbDevice_CreateSecureObject.c)
 *     UsbDevice_GetEndpointOffloadInformation @ 0x1C0035C6C (UsbDevice_GetEndpointOffloadInformation.c)
 *     UsbDevice_UcxEvtEndpointsConfigure @ 0x1C00376E0 (UsbDevice_UcxEvtEndpointsConfigure.c)
 *     Wmi_CreateControllerCapabilities @ 0x1C0039E98 (Wmi_CreateControllerCapabilities.c)
 *     DynamicLock_Acquire @ 0x1C0041760 (DynamicLock_Acquire.c)
 *     DynamicLock_Release @ 0x1C004195C (DynamicLock_Release.c)
 *     XilCoreDeviceSlot_SetDeviceContext @ 0x1C0042E20 (XilCoreDeviceSlot_SetDeviceContext.c)
 *     Controller_WdfEvtDevicePrepareHardware @ 0x1C005C350 (Controller_WdfEvtDevicePrepareHardware.c)
 *     Interrupter_PrepareHardware @ 0x1C005EB9C (Interrupter_PrepareHardware.c)
 *     Interrupter_PrepareInterrupter @ 0x1C005EFF0 (Interrupter_PrepareInterrupter.c)
 *     Register_ReadSecureMmio @ 0x1C0060404 (Register_ReadSecureMmio.c)
 *     Register_WriteSecureMmio @ 0x1C00606CC (Register_WriteSecureMmio.c)
 * Callees:
 *     WPP_RECORDER_SF_sds @ 0x1C0012E30 (WPP_RECORDER_SF_sds.c)
 */

void __fastcall Debug_FreAssertMsg(__int64 a1, char a2, int a3, int a4)
{
  if ( !a2 )
  {
    WPP_RECORDER_SF_sds(WPP_GLOBAL_Control->DeviceExtension, 0, a3, a4);
    if ( !KdRefreshDebuggerNotPresent() )
      __debugbreak();
  }
}
