/*
 * XREFs of __security_check_cookie @ 0x1C0041200
 * Callers:
 *     McTemplateK0 @ 0x1C0001318 (McTemplateK0.c)
 *     McTemplateK0pnq @ 0x1C0001358 (McTemplateK0pnq.c)
 *     McTemplateK0ppqzznhUR6zuqQ6qqqqqqqqqsssuuxttqq @ 0x1C00013D4 (McTemplateK0ppqzznhUR6zuqQ6qqqqqqqqqsssuuxttqq.c)
 *     McTemplateK0ppuq @ 0x1C00017D4 (McTemplateK0ppuq.c)
 *     McTemplateK0pq @ 0x1C0001864 (McTemplateK0pq.c)
 *     McTemplateK0pqn @ 0x1C00018D4 (McTemplateK0pqn.c)
 *     McTemplateK0pquuxqqqqqqqsss @ 0x1C0001950 (McTemplateK0pquuxqqqqqqqsss.c)
 *     McTemplateK0pqhh @ 0x1C0001D58 (McTemplateK0pqhh.c)
 *     McTemplateK0pqqq @ 0x1C0001DEC (McTemplateK0pqqq.c)
 *     McTemplateK0qhhhqhhh @ 0x1C0001E7C (McTemplateK0qhhhqhhh.c)
 *     HUBHTX_SendInterruptTransfer @ 0x1C0003364 (HUBHTX_SendInterruptTransfer.c)
 *     HUBHTX_CompleteGetPortStatusWithPortStatusResult @ 0x1C0005D10 (HUBHTX_CompleteGetPortStatusWithPortStatusResult.c)
 *     HUBHTX_CompleteGetPortStatusWithFailedStatus @ 0x1C0005F14 (HUBHTX_CompleteGetPortStatusWithFailedStatus.c)
 *     McTemplateK0p @ 0x1C0006A6C (McTemplateK0p.c)
 *     HUBPARENT_SetHubConfiguration @ 0x1C0006C58 (HUBPARENT_SetHubConfiguration.c)
 *     HUBPARENT_ResetInterruptPipe @ 0x1C0007300 (HUBPARENT_ResetInterruptPipe.c)
 *     HUBPARENT_ResetHub @ 0x1C00075F0 (HUBPARENT_ResetHub.c)
 *     HUBPARENT_GetInfoFromParentUsingParentIoctl @ 0x1C0007A1C (HUBPARENT_GetInfoFromParentUsingParentIoctl.c)
 *     McTemplateK0ppqqqq @ 0x1C00094E4 (McTemplateK0ppqqqq.c)
 *     McTemplateK0pqq @ 0x1C000B370 (McTemplateK0pqq.c)
 *     McTemplateK0pqqh @ 0x1C000B3E8 (McTemplateK0pqqh.c)
 *     HUBFDO_GetDeviceCapabilities @ 0x1C000B5A4 (HUBFDO_GetDeviceCapabilities.c)
 *     HUBFDO_EvtDeviceUsageNotification @ 0x1C000BE20 (HUBFDO_EvtDeviceUsageNotification.c)
 *     HUBFDO_EvtIoInternalDeviceControlFromPDO @ 0x1C000C4E0 (HUBFDO_EvtIoInternalDeviceControlFromPDO.c)
 *     HUBFDO_IoctlGetNodeConnectionInfo @ 0x1C000C8B4 (HUBFDO_IoctlGetNodeConnectionInfo.c)
 *     HUBFDO_CompleteGetDescriptorRequest @ 0x1C000CE84 (HUBFDO_CompleteGetDescriptorRequest.c)
 *     HUBFDO_PowerSettingCallback @ 0x1C000CFD0 (HUBFDO_PowerSettingCallback.c)
 *     HUBFDO_SetupHubPostErrataQuery @ 0x1C000D44C (HUBFDO_SetupHubPostErrataQuery.c)
 *     HUBFDO_CreateDeviceInterfaceForBillboard @ 0x1C000D9C4 (HUBFDO_CreateDeviceInterfaceForBillboard.c)
 *     HUBFDO_CleanupDeviceInterfaceForBillboard @ 0x1C000DBC8 (HUBFDO_CleanupDeviceInterfaceForBillboard.c)
 *     HUBMUX_CreatePSM @ 0x1C000E098 (HUBMUX_CreatePSM.c)
 *     McTemplateK0pjq @ 0x1C0012118 (McTemplateK0pjq.c)
 *     McTemplateK0ppn @ 0x1C0012198 (McTemplateK0ppn.c)
 *     McTemplateK0ppqq @ 0x1C0012218 (McTemplateK0ppqq.c)
 *     McTemplateK0pqhhh @ 0x1C00122A8 (McTemplateK0pqhhh.c)
 *     McTemplateK0pqhhhqqqqqqhhqhqqqqqqqssshhh @ 0x1C0012348 (McTemplateK0pqhhhqqqqqqhhqhqqqqqqqssshhh.c)
 *     McTemplateK0pqqhhhq @ 0x1C0012684 (McTemplateK0pqqhhhq.c)
 *     wil_details_FeaturePropertyCache_ReportUsageToServiceDirect @ 0x1C0013238 (wil_details_FeaturePropertyCache_ReportUsageToServiceDirect.c)
 *     HUBPDO_CompleteClientSerialRequestWithStatusSuccess @ 0x1C00136F4 (HUBPDO_CompleteClientSerialRequestWithStatusSuccess.c)
 *     HUBPDO_CompleteClientSerialRequestWithStatusFailed @ 0x1C00138D0 (HUBPDO_CompleteClientSerialRequestWithStatusFailed.c)
 *     HUBPDO_CompleteClientSerialRequestWithLastStatus @ 0x1C0013A70 (HUBPDO_CompleteClientSerialRequestWithLastStatus.c)
 *     HUBPDO_EvtIoInternalDeviceControl @ 0x1C0013D40 (HUBPDO_EvtIoInternalDeviceControl.c)
 *     HUBPDO_ValidateSelectConfigUrb @ 0x1C001497C (HUBPDO_ValidateSelectConfigUrb.c)
 *     HUBPDO_ValidateSelectInterfaceUrb @ 0x1C0014F88 (HUBPDO_ValidateSelectInterfaceUrb.c)
 *     HUBPDO_FindAndStoreMatchingInternalPipeHandle @ 0x1C0015300 (HUBPDO_FindAndStoreMatchingInternalPipeHandle.c)
 *     HUBPDO_EvtDeviceWdmIrpPreprocess @ 0x1C0016580 (HUBPDO_EvtDeviceWdmIrpPreprocess.c)
 *     HUBPDO_EvtDeviceD0Entry @ 0x1C0017830 (HUBPDO_EvtDeviceD0Entry.c)
 *     HUBPDO_EvtDeviceD0Exit @ 0x1C0017A20 (HUBPDO_EvtDeviceD0Exit.c)
 *     HUBPDO_RegisterForPowerSettingsForDevice @ 0x1C0018594 (HUBPDO_RegisterForPowerSettingsForDevice.c)
 *     HUBPDO_RegisterForPowerSettingsForHub @ 0x1C00186F8 (HUBPDO_RegisterForPowerSettingsForHub.c)
 *     HUBPDO_SubmitDeviceWakeNotificationIoctl @ 0x1C00191B0 (HUBPDO_SubmitDeviceWakeNotificationIoctl.c)
 *     HUBID_BuildDeviceID @ 0x1C001AA1C (HUBID_BuildDeviceID.c)
 *     HUBID_BuildHardwareID @ 0x1C001AC34 (HUBID_BuildHardwareID.c)
 *     HUBID_BuildDeviceCompatibleID @ 0x1C001AE1C (HUBID_BuildDeviceCompatibleID.c)
 *     HUBID_BuildHubCompatibleID @ 0x1C001AFC8 (HUBID_BuildHubCompatibleID.c)
 *     HUBID_BuildClassCompatibleID @ 0x1C001B0A4 (HUBID_BuildClassCompatibleID.c)
 *     HUBID_BuildCompatibleID @ 0x1C001B418 (HUBID_BuildCompatibleID.c)
 *     HUBID_BuildContainerID @ 0x1C001B504 (HUBID_BuildContainerID.c)
 *     HUBDSM_ResettingPipeInUCXOnClientReset @ 0x1C001C7A0 (HUBDSM_ResettingPipeInUCXOnClientReset.c)
 *     HUBDSM_ResettingPipeInUCXOnClientSyncResetPipe @ 0x1C001C940 (HUBDSM_ResettingPipeInUCXOnClientSyncResetPipe.c)
 *     HUBDSM_SettingConfigurationInformationInClientRequest @ 0x1C001CAF0 (HUBDSM_SettingConfigurationInformationInClientRequest.c)
 *     HUBDSM_SettingInterfaceInformationInClientRequest @ 0x1C001CD30 (HUBDSM_SettingInterfaceInformationInClientRequest.c)
 *     HUBDSM_CheckingIfExemptSecureBioDevice @ 0x1C001D9C0 (HUBDSM_CheckingIfExemptSecureBioDevice.c)
 *     HUBUCX_GetRootHubInfoUsingUCXIoctl @ 0x1C0023E94 (HUBUCX_GetRootHubInfoUsingUCXIoctl.c)
 *     HUBUCX_NotifyForwardProgress @ 0x1C0025854 (HUBUCX_NotifyForwardProgress.c)
 *     McTemplateK0phuzu @ 0x1C0025A38 (McTemplateK0phuzu.c)
 *     McTemplateK0puuhz @ 0x1C0025B10 (McTemplateK0puuhz.c)
 *     HUBDTX_ClearEndpointHaltUsingControlTransfer @ 0x1C002896C (HUBDTX_ClearEndpointHaltUsingControlTransfer.c)
 *     HUBDTX_LogBillboardEvent @ 0x1C0028FEC (HUBDTX_LogBillboardEvent.c)
 *     HUBDTX_LogAlternateMode @ 0x1C0029100 (HUBDTX_LogAlternateMode.c)
 *     McTemplateK0phhhquuuuu @ 0x1C0029AF0 (McTemplateK0phhhquuuuu.c)
 *     McTemplateK0psqzq @ 0x1C0029BEC (McTemplateK0psqzq.c)
 *     HUBMISC_PrepareEndpointAndInterfaceListsForConfiguringDeviceOnSelectConfiguration @ 0x1C002AB44 (HUBMISC_PrepareEndpointAndInterfaceListsForConfiguringDeviceOnSelectConfiguration.c)
 *     HUBMISC_PrepareEndpointAndInterfaceListsForConfiguringDeviceOnSelectInterface @ 0x1C002B7A8 (HUBMISC_PrepareEndpointAndInterfaceListsForConfiguringDeviceOnSelectInterface.c)
 *     HUBMISC_ControlTransfer @ 0x1C002E39C (HUBMISC_ControlTransfer.c)
 *     HUBREG_ValidateAndPopulateEndpointPriorities @ 0x1C0030984 (HUBREG_ValidateAndPopulateEndpointPriorities.c)
 *     HUBDESC_ValidateConfigurationDescriptorSet @ 0x1C0034BA4 (HUBDESC_ValidateConfigurationDescriptorSet.c)
 *     HUBDESC_ValidateMsOs20ConfigurationSubset @ 0x1C00397E0 (HUBDESC_ValidateMsOs20ConfigurationSubset.c)
 *     HUBDESC_ValidateMsOs20FunctionSubset @ 0x1C0039AB0 (HUBDESC_ValidateMsOs20FunctionSubset.c)
 *     HUBIDLE_AddEvent @ 0x1C003AB30 (HUBIDLE_AddEvent.c)
 *     WER_CreateReport @ 0x1C003BABC (WER_CreateReport.c)
 *     FWUPDATE_EvtIoInternalDeviceControl @ 0x1C003CB50 (FWUPDATE_EvtIoInternalDeviceControl.c)
 *     TelemetryData_CreateReport @ 0x1C003D880 (TelemetryData_CreateReport.c)
 *     MicrosoftTelemetryAssertTriggeredWorker @ 0x1C003D9FC (MicrosoftTelemetryAssertTriggeredWorker.c)
 *     USBD_CreateHandle @ 0x1C003E780 (USBD_CreateHandle.c)
 *     USBD_QueryUsbCapability @ 0x1C003EBC0 (USBD_QueryUsbCapability.c)
 *     MyRegQueryUlong @ 0x1C003FF58 (MyRegQueryUlong.c)
 *     WerStartSystemErrorHandler @ 0x1C00408E0 (WerStartSystemErrorHandler.c)
 *     WerKernelSubmitReport @ 0x1C0040ADC (WerKernelSubmitReport.c)
 *     __GSHandlerCheckCommon @ 0x1C004127C (__GSHandlerCheckCommon.c)
 *     HUBDRIVER_EtwRundownUsbDevice @ 0x1C006F960 (HUBDRIVER_EtwRundownUsbDevice.c)
 *     HUBDRIVER_EtwEnableCallback @ 0x1C006FFA0 (HUBDRIVER_EtwEnableCallback.c)
 *     HUBFDO_EvtDeviceAdd @ 0x1C00702C0 (HUBFDO_EvtDeviceAdd.c)
 *     HUBFDO_IoctlGetNodeInformation @ 0x1C0071BAC (HUBFDO_IoctlGetNodeInformation.c)
 *     HUBFDO_IoctlGetNodeConnectionDriverKeyName @ 0x1C0071D98 (HUBFDO_IoctlGetNodeConnectionDriverKeyName.c)
 *     HUBFDO_IoctlGetNodeConnectionAttributes @ 0x1C0072110 (HUBFDO_IoctlGetNodeConnectionAttributes.c)
 *     HUBFDO_IoctlGetHubCaps @ 0x1C0072350 (HUBFDO_IoctlGetHubCaps.c)
 *     HUBFDO_IoctlGetHubCapsEx @ 0x1C0072528 (HUBFDO_IoctlGetHubCapsEx.c)
 *     HUBFDO_IoctlGetNodeConnectionName @ 0x1C007275C (HUBFDO_IoctlGetNodeConnectionName.c)
 *     HUBFDO_IoctlGetDescriptorFromNodeConnection @ 0x1C0072B74 (HUBFDO_IoctlGetDescriptorFromNodeConnection.c)
 *     HUBFDO_IoctlGetHubInformationEx @ 0x1C007314C (HUBFDO_IoctlGetHubInformationEx.c)
 *     HUBFDO_IoctlGetPortConnectorProperties @ 0x1C0073400 (HUBFDO_IoctlGetPortConnectorProperties.c)
 *     HUBFDO_IoctlGetNodeConnectionInformationExV2 @ 0x1C00737D8 (HUBFDO_IoctlGetNodeConnectionInformationExV2.c)
 *     HUBFDO_IoctlCyclePort @ 0x1C0073C2C (HUBFDO_IoctlCyclePort.c)
 *     HUBFDO_IoctlResetHub @ 0x1C00740FC (HUBFDO_IoctlResetHub.c)
 *     HUBFDO_EvtIoDeviceControl @ 0x1C0074290 (HUBFDO_EvtIoDeviceControl.c)
 *     HUBFDO_QueryHubErrataFlags @ 0x1C0074514 (HUBFDO_QueryHubErrataFlags.c)
 *     HUBFDO_RegisterSleepstudyBlockerReasons @ 0x1C00746D4 (HUBFDO_RegisterSleepstudyBlockerReasons.c)
 *     HUBFDO_RegisterSleepstudyBlockerReason @ 0x1C0074970 (HUBFDO_RegisterSleepstudyBlockerReason.c)
 *     HUBPDO_EvtDevicePrepareHardware @ 0x1C0074BD0 (HUBPDO_EvtDevicePrepareHardware.c)
 *     HUBPDO_MakePdoName @ 0x1C00760C0 (HUBPDO_MakePdoName.c)
 *     HUBPDO_AssignPDOIds @ 0x1C00761BC (HUBPDO_AssignPDOIds.c)
 *     HUBPDO_CreatePdoInternal @ 0x1C0076434 (HUBPDO_CreatePdoInternal.c)
 *     HUBMISC_QueryAndCacheRegistryValuesForDevice @ 0x1C0079414 (HUBMISC_QueryAndCacheRegistryValuesForDevice.c)
 *     HUBMISC_ReportPnPFailureProblem @ 0x1C0079928 (HUBMISC_ReportPnPFailureProblem.c)
 *     HUBREG_OpenCreateUsbflagsDeviceKey @ 0x1C0079C4C (HUBREG_OpenCreateUsbflagsDeviceKey.c)
 *     HUBREG_QueryUsbHardwareVerifierValue @ 0x1C007A028 (HUBREG_QueryUsbHardwareVerifierValue.c)
 *     HUBREG_AssignUsbflagsValueForDevice @ 0x1C007A630 (HUBREG_AssignUsbflagsValueForDevice.c)
 *     HUBREG_QueryUsbflagsValuesForDevice @ 0x1C007A778 (HUBREG_QueryUsbflagsValuesForDevice.c)
 *     HUBREG_QueryUxdPortKey @ 0x1C007D08C (HUBREG_QueryUxdPortKey.c)
 *     HUBREG_QueryUxdDeviceKey @ 0x1C007D314 (HUBREG_QueryUxdDeviceKey.c)
 *     HUBREG_DeleteUxdDeviceKey @ 0x1C007D490 (HUBREG_DeleteUxdDeviceKey.c)
 *     HUBREG_UpdateUxdSettings @ 0x1C007D5F8 (HUBREG_UpdateUxdSettings.c)
 *     HUBREG_DeleteUxdPortKey @ 0x1C007D918 (HUBREG_DeleteUxdPortKey.c)
 *     HUBREG_DeleteUxdSubKeys @ 0x1C007DC24 (HUBREG_DeleteUxdSubKeys.c)
 *     HUBACPI_ExecuteDSM @ 0x1C007F670 (HUBACPI_ExecuteDSM.c)
 *     HUBACPI_EvaluateDsmMethod @ 0x1C007F978 (HUBACPI_EvaluateDsmMethod.c)
 *     HUBACPI_EvalAcpiMethodEx @ 0x1C007FE68 (HUBACPI_EvalAcpiMethodEx.c)
 *     HUBACPI_EnumChildren @ 0x1C00802A0 (HUBACPI_EnumChildren.c)
 *     WMI_AcquireBusInfo @ 0x1C0080FDC (WMI_AcquireBusInfo.c)
 *     WMI_RegisterHub @ 0x1C00816E4 (WMI_RegisterHub.c)
 *     WMI_RegisterDevice @ 0x1C00818E0 (WMI_RegisterDevice.c)
 *     WMI_RegisterSurpriseRemovalNotificationInstance @ 0x1C0081A30 (WMI_RegisterSurpriseRemovalNotificationInstance.c)
 *     WMI_FireNotification @ 0x1C0081BA0 (WMI_FireNotification.c)
 *     HUBWNF_PublishUsbPartnerDualRoleFeatures @ 0x1C0081D0C (HUBWNF_PublishUsbPartnerDualRoleFeatures.c)
 *     FWUPDATE_AddIdsForFirmwareUpdateDevice @ 0x1C0081E80 (FWUPDATE_AddIdsForFirmwareUpdateDevice.c)
 *     FWUPDATE_CreateFirmwareUpdateDevice @ 0x1C00821AC (FWUPDATE_CreateFirmwareUpdateDevice.c)
 *     TelemetryData_pCreateDumpFile @ 0x1C0082B40 (TelemetryData_pCreateDumpFile.c)
 *     TelemetryData_pInitWerContext @ 0x1C0082E88 (TelemetryData_pInitWerContext.c)
 *     QueryDeviceResetInterface @ 0x1C0083544 (QueryDeviceResetInterface.c)
 *     DriverEntry @ 0x1C0085008 (DriverEntry.c)
 * Callees:
 *     <none>
 */

void __cdecl _security_check_cookie(uintptr_t StackCookie)
{
  __int64 v1; // rcx

  if ( StackCookie != _security_cookie )
ReportFailure:
    _report_gsfailure(StackCookie);
  v1 = __ROL8__(StackCookie, 16);
  if ( (_WORD)v1 )
  {
    StackCookie = __ROR8__(v1, 16);
    goto ReportFailure;
  }
}
