/*
 * XREFs of ?IsWarpAdapter@DXGADAPTER@@QEBAEXZ @ 0x1C00060A8
 * Callers:
 *     ?OpenOneAllocation@VIDMM_GLOBAL@@QEAAJPEAVVIDMM_DEVICE@@PEAU_VIDMM_GLOBAL_ALLOC@@PEAXHPEAVDXGALLOCATION@@PEAPEAUVIDMM_ALLOC@@PEAE@Z @ 0x1C00341E0 (-OpenOneAllocation@VIDMM_GLOBAL@@QEAAJPEAVVIDMM_DEVICE@@PEAU_VIDMM_GLOBAL_ALLOC@@PEAXHPEAVDXGALL.c)
 * Callees:
 *     <none>
 */

bool __fastcall DXGADAPTER::IsWarpAdapter(DXGADAPTER *this)
{
  return (*((_BYTE *)this + 284) & 8) != 0;
}
