/*
 * XREFs of ?vUnlockFast@XDCOBJ@@IEAAXXZ @ 0x1C011C01C
 * Callers:
 *     GreEnumFonts @ 0x1C0003CEC (GreEnumFonts.c)
 *     NtGdiGetPixel @ 0x1C0005580 (NtGdiGetPixel.c)
 *     GreTransformPoints @ 0x1C0006CF4 (GreTransformPoints.c)
 *     ?GreSetICMMode@@YAHPEAUHDC__@@KK@Z @ 0x1C0007548 (-GreSetICMMode@@YAHPEAUHDC__@@KK@Z.c)
 *     GreSetBrushOrg @ 0x1C0007894 (GreSetBrushOrg.c)
 *     GreSetBoundsRect @ 0x1C00094E4 (GreSetBoundsRect.c)
 *     GreBeginGdiRenderingToDxSurface @ 0x1C00097F8 (GreBeginGdiRenderingToDxSurface.c)
 *     GreGetBoundsRect @ 0x1C0009A58 (GreGetBoundsRect.c)
 *     NtGdiSetMetaRgn @ 0x1C000A030 (NtGdiSetMetaRgn.c)
 *     ?GreGetCharWidthInfo@@YAHPEAUHDC__@@PEAU_CHWIDTHINFO@@W4EntryPoint@RFONTOBJ@@@Z @ 0x1C000E3D8 (-GreGetCharWidthInfo@@YAHPEAUHDC__@@PEAU_CHWIDTHINFO@@W4EntryPoint@RFONTOBJ@@@Z.c)
 *     GreCreateBitmapFromDxSurface @ 0x1C00140E4 (GreCreateBitmapFromDxSurface.c)
 *     GreGetBkColor @ 0x1C0014CC8 (GreGetBkColor.c)
 *     GreGetTextColor @ 0x1C0014D18 (GreGetTextColor.c)
 *     GreMaskBlt @ 0x1C001C9BC (GreMaskBlt.c)
 *     ?GreExtTextOutRect@@YAHPEAUHDC__@@PEAUtagRECT@@W4EntryPoint@RFONTOBJ@@@Z @ 0x1C001DC04 (-GreExtTextOutRect@@YAHPEAUHDC__@@PEAUtagRECT@@W4EntryPoint@RFONTOBJ@@@Z.c)
 *     GreGetSystemPaletteUse @ 0x1C001F4AC (GreGetSystemPaletteUse.c)
 *     GreGetLayout @ 0x1C0024844 (GreGetLayout.c)
 *     GreSetStretchBltMode @ 0x1C00276B0 (GreSetStretchBltMode.c)
 *     GreSetBkColor @ 0x1C0027760 (GreSetBkColor.c)
 *     ?GreCreateDIBitmapReal@@YAPEAUHBITMAP__@@PEAUHDC__@@KAEAV?$umptr_r@E@@PEAUtagBITMAPINFO@@KIPEAXK3K_KPEAPEAX@Z @ 0x1C002AB30 (-GreCreateDIBitmapReal@@YAPEAUHBITMAP__@@PEAUHDC__@@KAEAV-$umptr_r@E@@PEAUtagBITMAPINFO@@KIPEAXK.c)
 *     GreCreateCompatibleBitmapInternal @ 0x1C0057310 (GreCreateCompatibleBitmapInternal.c)
 *     ?GreGetGlyphOutlineInternal@@YAKPEAUHDC__@@GIPEAU_GLYPHMETRICS@@KPEAXPEAU_MAT2@@HW4EntryPoint@RFONTOBJ@@@Z @ 0x1C00745D4 (-GreGetGlyphOutlineInternal@@YAKPEAUHDC__@@GIPEAU_GLYPHMETRICS@@KPEAXPEAU_MAT2@@HW4EntryPoint@RF.c)
 *     ?GrepGetTextCharsetInfo@@YAHPEAUHDC__@@PEAUtagFONTSIGNATURE@@KW4EntryPoint@RFONTOBJ@@@Z @ 0x1C0076B44 (-GrepGetTextCharsetInfo@@YAHPEAUHDC__@@PEAUtagFONTSIGNATURE@@KW4EntryPoint@RFONTOBJ@@@Z.c)
 *     GreGetCharSet @ 0x1C0076CB8 (GreGetCharSet.c)
 *     ?GreGetRealizationInfo@@YAHPEAUHDC__@@PEAUtagFONT_REALIZATION_INFO2@@W4EntryPoint@RFONTOBJ@@@Z @ 0x1C007CF04 (-GreGetRealizationInfo@@YAHPEAUHDC__@@PEAUtagFONT_REALIZATION_INFO2@@W4EntryPoint@RFONTOBJ@@@Z.c)
 *     ?GreGetTextExtentExW@@YAHPEAUHDC__@@PEAGKKPEAK2PEAUtagSIZE@@KW4EntryPoint@RFONTOBJ@@@Z @ 0x1C007D494 (-GreGetTextExtentExW@@YAHPEAUHDC__@@PEAGKKPEAK2PEAUtagSIZE@@KW4EntryPoint@RFONTOBJ@@@Z.c)
 *     ?GrepGetTextMetricsW@@YAHPEAUHDC__@@PEAU_TMW_INTERNAL@@W4EntryPoint@RFONTOBJ@@@Z @ 0x1C007DC34 (-GrepGetTextMetricsW@@YAHPEAUHDC__@@PEAU_TMW_INTERNAL@@W4EntryPoint@RFONTOBJ@@@Z.c)
 *     ?ulGetFontData@@YAKPEAUHDC__@@KKPEAXKW4EntryPoint@RFONTOBJ@@@Z @ 0x1C007E98C (-ulGetFontData@@YAKPEAUHDC__@@KKPEAXKW4EntryPoint@RFONTOBJ@@@Z.c)
 *     ?GreGetOutlineTextMetricsInternalW@@YAKPEAUHDC__@@KPEAU_OUTLINETEXTMETRICW@@PEAU_TMDIFF@@W4EntryPoint@RFONTOBJ@@@Z @ 0x1C0081368 (-GreGetOutlineTextMetricsInternalW@@YAKPEAUHDC__@@KPEAU_OUTLINETEXTMETRICW@@PEAU_TMDIFF@@W4Entry.c)
 *     ?GrepGetTextExtentW@@YAHPEAUHDC__@@PEAGHPEAUtagSIZE@@IW4EntryPoint@RFONTOBJ@@@Z @ 0x1C00838A8 (-GrepGetTextExtentW@@YAHPEAUHDC__@@PEAGHPEAUtagSIZE@@IW4EntryPoint@RFONTOBJ@@@Z.c)
 *     ?GreFontIsLinked@@YAHPEAUHDC__@@W4EntryPoint@RFONTOBJ@@@Z @ 0x1C00AB5E8 (-GreFontIsLinked@@YAHPEAUHDC__@@W4EntryPoint@RFONTOBJ@@@Z.c)
 *     NtGdiQueryFontAssocInfo @ 0x1C00ABF60 (NtGdiQueryFontAssocInfo.c)
 *     GreOffsetClipRgn @ 0x1C00B51E4 (GreOffsetClipRgn.c)
 *     ?GreUpdateSpriteInternal@@YAHPEAUHDEV__@@PEAUHWND__@@PEAXPEAUHDC__@@PEAUtagPOINT@@PEAUtagSIZE@@34KPEAU_BLENDFUNCTION@@KPEAUtagRECT@@PEAUtagMINIWINDOWINFO@@HHK@Z @ 0x1C00D8400 (-GreUpdateSpriteInternal@@YAHPEAUHDEV__@@PEAUHWND__@@PEAXPEAUHDC__@@PEAUtagPOINT@@PEAUtagSIZE@@3.c)
 *     GreRectVisible @ 0x1C00DB850 (GreRectVisible.c)
 *     ?GreSetDIBitsToDeviceInternalImpl@@YAHPEAUHDC__@@HHKKHHKKAEAV?$umptr_r@E@@PEAUtagBITMAPINFO@@KIHPEAX@Z @ 0x1C00DD3B0 (-GreSetDIBitsToDeviceInternalImpl@@YAHPEAUHDC__@@HHKKHHKKAEAV-$umptr_r@E@@PEAUtagBITMAPINFO@@KIH.c)
 *     ?GreStretchDIBitsInternalImpl@@YAHPEAUHDC__@@HHHHHHHHAEAV?$umptr_r@E@@PEAUtagBITMAPINFO@@KKIPEAX@Z @ 0x1C00DF680 (-GreStretchDIBitsInternalImpl@@YAHPEAUHDC__@@HHHHHHHHAEAV-$umptr_r@E@@PEAUtagBITMAPINFO@@KKIPEAX.c)
 *     ??1DEVLOCKBLTOBJ@@QEAA@XZ @ 0x1C00F8B40 (--1DEVLOCKBLTOBJ@@QEAA@XZ.c)
 *     GreStretchBltInternal @ 0x1C00FF3A0 (GreStretchBltInternal.c)
 *     NtGdiBitBltInternal @ 0x1C01042C0 (NtGdiBitBltInternal.c)
 *     GreExtSelectClipRgnInternal @ 0x1C011A2F0 (GreExtSelectClipRgnInternal.c)
 *     GreSelectFont @ 0x1C011BD80 (GreSelectFont.c)
 *     ??1DCOBJ@@QEAA@XZ @ 0x1C011BFF0 (--1DCOBJ@@QEAA@XZ.c)
 *     ?vDestructor@DEVLOCKOBJ@@QEAAXXZ @ 0x1C011C160 (-vDestructor@DEVLOCKOBJ@@QEAAXXZ.c)
 *     ?UntrapAppContainerRenderingWorker@@YAXAEAPEAUHDC__@@AEAPEAUHSURF__@@1PEBK@Z @ 0x1C011C768 (-UntrapAppContainerRenderingWorker@@YAXAEAPEAUHDC__@@AEAPEAUHSURF__@@1PEBK@Z.c)
 *     ?bSpUpdateShape@@YAHPEAVSPRITE@@KPEAUHDC__@@1KPEAU_BLENDFUNCTION@@PEAU_POINTL@@PEAUtagSIZE@@PEAU_RECTL@@@Z @ 0x1C01366E0 (-bSpUpdateShape@@YAHPEAVSPRITE@@KPEAUHDC__@@1KPEAU_BLENDFUNCTION@@PEAU_POINTL@@PEAUtagSIZE@@PEAU.c)
 *     GreGetTransform @ 0x1C01405F4 (GreGetTransform.c)
 *     ?GreGetGlyphIndicesW@@YAKPEAUHDC__@@PEBGKPEAGKHW4EntryPoint@RFONTOBJ@@@Z @ 0x1C0140A1C (-GreGetGlyphIndicesW@@YAKPEAUHDC__@@PEBGKPEAGKHW4EntryPoint@RFONTOBJ@@@Z.c)
 *     DxgkEngAcquireStableVisRgn @ 0x1C0159F90 (DxgkEngAcquireStableVisRgn.c)
 *     DxgkEngWatchVisRgnChange @ 0x1C015A620 (DxgkEngWatchVisRgnChange.c)
 *     NtGdiLineTo @ 0x1C015AE20 (NtGdiLineTo.c)
 *     ?SpDdDestroyFullscreenSprite@@YAJPEAUHDC__@@PEAX@Z @ 0x1C0266060 (-SpDdDestroyFullscreenSprite@@YAJPEAUHDC__@@PEAX@Z.c)
 *     ?SpDdNotifyFullscreenSpriteUpdate@@YAJPEAUHDC__@@PEAX@Z @ 0x1C02661A8 (-SpDdNotifyFullscreenSpriteUpdate@@YAJPEAUHDC__@@PEAX@Z.c)
 *     GreSpDwmSyncCaptureSurfaceBits @ 0x1C0268210 (GreSpDwmSyncCaptureSurfaceBits.c)
 *     DxgkEngBltViaGDI @ 0x1C026F280 (DxgkEngBltViaGDI.c)
 *     DxgkEngColorFillViaGDI @ 0x1C026FAC0 (DxgkEngColorFillViaGDI.c)
 *     ??1XFERDCOBJ@@QEAA@XZ @ 0x1C0274F30 (--1XFERDCOBJ@@QEAA@XZ.c)
 *     ?GreDoBanding@@YAHPEAUHDC__@@HPEAU_POINTL@@PEAUtagSIZE@@@Z @ 0x1C0275338 (-GreDoBanding@@YAHPEAUHDC__@@HPEAU_POINTL@@PEAUtagSIZE@@@Z.c)
 *     ?GreDrawEscape@@YAHPEAUHDC__@@HAEBV?$umptr_r@D@@@Z @ 0x1C02754CC (-GreDrawEscape@@YAHPEAUHDC__@@HAEBV-$umptr_r@D@@@Z.c)
 *     ?GreExtEscape@@YAHPEAUHDC__@@HHPEADH1W4EntryPoint@RFONTOBJ@@@Z @ 0x1C02757EC (-GreExtEscape@@YAHPEAUHDC__@@HHPEADH1W4EntryPoint@RFONTOBJ@@@Z.c)
 *     ?GreGetPerBandInfo@@YAKPEAUHDC__@@PEAU_PERBANDINFO@@@Z @ 0x1C0275F90 (-GreGetPerBandInfo@@YAKPEAUHDC__@@PEAU_PERBANDINFO@@@Z.c)
 *     ?GreGetUFI@@YAHPEAUHDC__@@PEAU_UNIVERSAL_FONT_ID@@PEAUtagDESIGNVECTOR@@PEAK33PEAPEAXW4EntryPoint@RFONTOBJ@@@Z @ 0x1C0276040 (-GreGetUFI@@YAHPEAUHDC__@@PEAU_UNIVERSAL_FONT_ID@@PEAUtagDESIGNVECTOR@@PEAK33PEAPEAXW4EntryPoint.c)
 *     ?LookUpWndobjs@@YAHPEAVDCOBJ@@0PEAPEAUHDC__@@H@Z @ 0x1C0276514 (-LookUpWndobjs@@YAHPEAVDCOBJ@@0PEAPEAUHDC__@@H@Z.c)
 *     ?ThreadCleanup@XFERDCOBJ@@SAXPEAX@Z @ 0x1C0276610 (-ThreadCleanup@XFERDCOBJ@@SAXPEAX@Z.c)
 *     ?bEndDocInternal@@YAHPEAUHDC__@@KG@Z @ 0x1C0276684 (-bEndDocInternal@@YAHPEAUHDC__@@KG@Z.c)
 *     GreForceUFIMapping @ 0x1C0277B5C (GreForceUFIMapping.c)
 *     NtGdiEndPage @ 0x1C0278330 (NtGdiEndPage.c)
 *     NtGdiStartPage @ 0x1C0278EF0 (NtGdiStartPage.c)
 *     ?bSetPreviewRectContent@@YAHPEAU_SPRITESTATE@@PEBU_RECTL@@@Z @ 0x1C027D618 (-bSetPreviewRectContent@@YAHPEAU_SPRITESTATE@@PEBU_RECTL@@@Z.c)
 *     ?GreGetCharWidthW@@YAHPEAUHDC__@@IIPEAGKPEAXW4EntryPoint@RFONTOBJ@@@Z @ 0x1C028D974 (-GreGetCharWidthW@@YAHPEAUHDC__@@IIPEAGKPEAXW4EntryPoint@RFONTOBJ@@@Z.c)
 *     ?GreGetFontUnicodeRanges@@YAKPEAUHDC__@@PEAUtagGLYPHSET@@W4EntryPoint@RFONTOBJ@@@Z @ 0x1C028DCCC (-GreGetFontUnicodeRanges@@YAKPEAUHDC__@@PEAUtagGLYPHSET@@W4EntryPoint@RFONTOBJ@@@Z.c)
 *     GreGetAspectRatioFilter @ 0x1C028E450 (GreGetAspectRatioFilter.c)
 *     GreSetFontXform @ 0x1C028E7D8 (GreSetFontXform.c)
 *     GrePlgBlt @ 0x1C0290EF0 (GrePlgBlt.c)
 *     NtGdiTransparentBlt @ 0x1C0297970 (NtGdiTransparentBlt.c)
 *     ?GreGetStringBitmapW@@YAIPEAUHDC__@@PEAGIPEAUSTRINGBITMAP@@IW4EntryPoint@RFONTOBJ@@@Z @ 0x1C029EDCC (-GreGetStringBitmapW@@YAIPEAUHDC__@@PEAGIPEAUSTRINGBITMAP@@IW4EntryPoint@RFONTOBJ@@@Z.c)
 *     ?bPrepareDCForXfer@XFERDCOBJ@@SAHPEAUHDC__@@K@Z @ 0x1C02A79EC (-bPrepareDCForXfer@XFERDCOBJ@@SAHPEAUHDC__@@K@Z.c)
 *     GreGetColorAdjustment @ 0x1C02A7E60 (GreGetColorAdjustment.c)
 *     GreScaleRgn @ 0x1C02A8034 (GreScaleRgn.c)
 *     GreScaleValues @ 0x1C02A819C (GreScaleValues.c)
 *     GreSetColorAdjustment @ 0x1C02A82DC (GreSetColorAdjustment.c)
 *     ?NtGdiInvertRgnInternal@@YAHPEAUHDC__@@PEAUHRGN__@@@Z @ 0x1C02A8594 (-NtGdiInvertRgnInternal@@YAHPEAUHDC__@@PEAUHRGN__@@@Z.c)
 *     NtGdiFillRgn @ 0x1C02A8FD0 (NtGdiFillRgn.c)
 *     NtGdiFrameRgn @ 0x1C02A9590 (NtGdiFrameRgn.c)
 *     NtGdiInvertRgn @ 0x1C02A9D30 (NtGdiInvertRgn.c)
 *     NtGdiOffsetClipRgn @ 0x1C02A9E80 (NtGdiOffsetClipRgn.c)
 *     NtGdiPtVisible @ 0x1C02AA0E0 (NtGdiPtVisible.c)
 *     GreGetHFONT @ 0x1C02AA304 (GreGetHFONT.c)
 *     NtGdiComputeXformCoefficients @ 0x1C02AA360 (NtGdiComputeXformCoefficients.c)
 *     bUMPD @ 0x1C02AA5D4 (bUMPD.c)
 *     ?GreLineTo@@YAHPEAUHDC__@@HH@Z @ 0x1C02AA938 (-GreLineTo@@YAHPEAUHDC__@@HH@Z.c)
 *     ?GrePolyBezierInternal@@YAHPEAUHDC__@@PEAUtagPOINT@@K@Z @ 0x1C02AB188 (-GrePolyBezierInternal@@YAHPEAUHDC__@@PEAUtagPOINT@@K@Z.c)
 *     ?GrePolyDraw@@YAHPEAUHDC__@@AEAV?$umptr_r@UtagPOINT@@@@AEAV?$umptr_r@E@@K@Z @ 0x1C02AB378 (-GrePolyDraw@@YAHPEAUHDC__@@AEAV-$umptr_r@UtagPOINT@@@@AEAV-$umptr_r@E@@K@Z.c)
 *     GreAngleArc @ 0x1C02AB948 (GreAngleArc.c)
 *     GreMoveTo @ 0x1C02ABE70 (GreMoveTo.c)
 *     GrePolyBezier @ 0x1C02ABFF0 (GrePolyBezier.c)
 *     GrePolyBezierTo @ 0x1C02AC0F0 (GrePolyBezierTo.c)
 *     GrePolyPolygon @ 0x1C02AC330 (GrePolyPolygon.c)
 *     GrePolyPolygonInternal @ 0x1C02AC44C (GrePolyPolygonInternal.c)
 *     GrePolyPolyline @ 0x1C02AC620 (GrePolyPolyline.c)
 *     GrePolyPolylineInternal @ 0x1C02AC73C (GrePolyPolylineInternal.c)
 *     GrePolylineTo @ 0x1C02AC970 (GrePolylineTo.c)
 *     GreRectangle @ 0x1C02ACBA0 (GreRectangle.c)
 *     NtGdiEllipse @ 0x1C02AD420 (NtGdiEllipse.c)
 *     NtGdiRectangle @ 0x1C02AD690 (NtGdiRectangle.c)
 *     NtGdiRoundRect @ 0x1C02AD7B0 (NtGdiRoundRect.c)
 *     GreResetDCInternal @ 0x1C02ADB48 (GreResetDCInternal.c)
 *     GreGetMiterLimit @ 0x1C02C09B0 (GreGetMiterLimit.c)
 *     GreSetMiterLimit @ 0x1C02C0A1C (GreSetMiterLimit.c)
 *     NtGdiAbortPath @ 0x1C02C0AC0 (NtGdiAbortPath.c)
 *     NtGdiBeginPath @ 0x1C02C0B70 (NtGdiBeginPath.c)
 *     NtGdiCloseFigure @ 0x1C02C0C80 (NtGdiCloseFigure.c)
 *     NtGdiEndPath @ 0x1C02C0D50 (NtGdiEndPath.c)
 *     NtGdiFillPath @ 0x1C02C0DE0 (NtGdiFillPath.c)
 *     NtGdiFlattenPath @ 0x1C02C0F70 (NtGdiFlattenPath.c)
 *     NtGdiPathToRegion @ 0x1C02C1330 (NtGdiPathToRegion.c)
 *     NtGdiSelectClipPath @ 0x1C02C1490 (NtGdiSelectClipPath.c)
 *     NtGdiStrokeAndFillPath @ 0x1C02C1640 (NtGdiStrokeAndFillPath.c)
 *     NtGdiStrokePath @ 0x1C02C1810 (NtGdiStrokePath.c)
 *     NtGdiWidenPath @ 0x1C02C1980 (NtGdiWidenPath.c)
 *     ??1MDCOBJ@@QEAA@XZ @ 0x1C02C1B38 (--1MDCOBJ@@QEAA@XZ.c)
 *     NtGdiSelectBrush @ 0x1C02C4A40 (NtGdiSelectBrush.c)
 *     NtGdiSelectPen @ 0x1C02C4B50 (NtGdiSelectPen.c)
 *     NtGdiArcInternal @ 0x1C02C6710 (NtGdiArcInternal.c)
 *     ?GreCheckBitmapBits@@YAHPEAUHDC__@@PEAXPEAU_DEVBITMAPINFO@@1PEAE@Z @ 0x1C02CE430 (-GreCheckBitmapBits@@YAHPEAUHDC__@@PEAXPEAU_DEVBITMAPINFO@@1PEAE@Z.c)
 *     ?GreCreateColorTransform@@YAPEAXPEAUHDC__@@PEAUtagLOGCOLORSPACEW@@PEAXK2K2K@Z @ 0x1C02CE604 (-GreCreateColorTransform@@YAPEAXPEAUHDC__@@PEAUtagLOGCOLORSPACEW@@PEAXK2K2K@Z.c)
 *     ?GreDeleteColorTransform@@YAHPEAUHDC__@@PEAX@Z @ 0x1C02CE774 (-GreDeleteColorTransform@@YAHPEAUHDC__@@PEAX@Z.c)
 *     ?GreIcmQueryBrushBitmap@@YAHPEAUHDC__@@PEAUHBRUSH__@@PEAUtagBITMAPINFO@@PEAXPEAK4PEAH@Z @ 0x1C02CE840 (-GreIcmQueryBrushBitmap@@YAHPEAUHDC__@@PEAUHBRUSH__@@PEAUtagBITMAPINFO@@PEAXPEAK4PEAH@Z.c)
 *     ?GreIcmSetBrushBitmap@@YAHPEAUHDC__@@PEAUHBRUSH__@@PEAUtagBITMAPINFO@@PEAX@Z @ 0x1C02CEA50 (-GreIcmSetBrushBitmap@@YAHPEAUHDC__@@PEAUHBRUSH__@@PEAUtagBITMAPINFO@@PEAX@Z.c)
 *     NtGdiSetColorSpace @ 0x1C02CF7B0 (NtGdiSetColorSpace.c)
 *     GreGetMapMode @ 0x1C02D0428 (GreGetMapMode.c)
 *     GreScaleWindowExtEx @ 0x1C02D0474 (GreScaleWindowExtEx.c)
 *     GreSetViewportOrg @ 0x1C02D05C4 (GreSetViewportOrg.c)
 *     GreSetWindowOrg @ 0x1C02D075C (GreSetWindowOrg.c)
 *     NtGdiSetSizeDevice @ 0x1C02D0C60 (NtGdiSetSizeDevice.c)
 *     NtGdiSetVirtualResolution @ 0x1C02D0D00 (NtGdiSetVirtualResolution.c)
 *     NtGdiUpdateTransform @ 0x1C02D0E10 (NtGdiUpdateTransform.c)
 *     GreCreateHalftonePalette @ 0x1C02D14F0 (GreCreateHalftonePalette.c)
 *     GreGetSystemPaletteEntries @ 0x1C02D1750 (GreGetSystemPaletteEntries.c)
 *     GreRealizePalette @ 0x1C02D181C (GreRealizePalette.c)
 *     GreSetDIBColorTable @ 0x1C02D1F00 (GreSetDIBColorTable.c)
 *     IsDCCurrentPalette @ 0x1C02D25D0 (IsDCCurrentPalette.c)
 *     NtGdiResizePalette @ 0x1C02D2760 (NtGdiResizePalette.c)
 *     NtGdiUpdateColors @ 0x1C02D2A60 (NtGdiUpdateColors.c)
 *     NtGdiExtFloodFill @ 0x1C02D4500 (NtGdiExtFloodFill.c)
 *     NtGdiMakeInfoDC @ 0x1C02D5680 (NtGdiMakeInfoDC.c)
 *     NtGdiSetPixel @ 0x1C02D6E10 (NtGdiSetPixel.c)
 *     ?GrePolyTextOutW@@YAHPEAUHDC__@@PEAUtagPOLYTEXTW@@IKW4EntryPoint@RFONTOBJ@@@Z @ 0x1C02D7814 (-GrePolyTextOutW@@YAHPEAUHDC__@@PEAUtagPOLYTEXTW@@IKW4EntryPoint@RFONTOBJ@@@Z.c)
 *     GreGetTextCharacterExtra @ 0x1C02D7CB4 (GreGetTextCharacterExtra.c)
 *     GreSetTextAlign @ 0x1C02D7D04 (GreSetTextAlign.c)
 *     GreSetTextCharacterExtra @ 0x1C02D7D98 (GreSetTextCharacterExtra.c)
 *     NtGdiSetTextJustification @ 0x1C02D7E10 (NtGdiSetTextJustification.c)
 *     GreDescribePixelFormat @ 0x1C02D8008 (GreDescribePixelFormat.c)
 *     NtGdiSetPixelFormat @ 0x1C02D8200 (NtGdiSetPixelFormat.c)
 *     NtGdiSwapBuffers @ 0x1C02D84A0 (NtGdiSwapBuffers.c)
 *     GreSetGraphicsMode @ 0x1C02DDCEC (GreSetGraphicsMode.c)
 *     ?GreSetDIBitsInternal@@YAHPEAUHDC__@@PEAUHBITMAP__@@IIAEAV?$umptr_r@E@@PEAUtagBITMAPINFO@@IIPEAX@Z @ 0x1C02DDF50 (-GreSetDIBitsInternal@@YAHPEAUHDC__@@PEAUHBITMAP__@@IIAEAV-$umptr_r@E@@PEAUtagBITMAPINFO@@IIPEAX.c)
 * Callees:
 *     <none>
 */

void __fastcall XDCOBJ::vUnlockFast(XDCOBJ *this)
{
  __int64 *v2; // rcx
  __int64 v3; // rdi
  struct _DC_ATTR *UserAttr; // rax
  int v5; // [rsp+30h] [rbp+8h] BYREF

  if ( *((_DWORD *)this + 2) && (*(_DWORD *)(*(_QWORD *)this + 44LL) & 2) != 0 )
  {
    if ( !*((_DWORD *)this + 3) )
    {
      UserAttr = XDCOBJ::GetUserAttr(this);
      if ( UserAttr )
        DC::RestoreAttributes(*(DC **)this, UserAttr);
    }
    *(_DWORD *)(*(_QWORD *)this + 44LL) &= ~2u;
    *((_DWORD *)this + 2) = 0;
  }
  v2 = *(__int64 **)this;
  v5 = 0;
  v3 = *v2;
  HmgDecrementExclusiveReferenceCountEx(v2, *((unsigned int *)this + 3), &v5);
  if ( v5 )
    GrepDeleteDC(v3, 0x2000000LL);
}
