/*
 * XREFs of ?Return_CaughtException@in1diag3@details@wil@@YAJPEAXIPEBD@Z @ 0x1800BCB08
 * Callers:
 *     _CSleepStudyPowerReferenceManager::CreatePowerReferenceSubBlocker_::_1_::catch$19 @ 0x180162EF8 (_CSleepStudyPowerReferenceManager--CreatePowerReferenceSubBlocker_--_1_--catch$19.c)
 *     _CLockedList_UniqueValuesOnly_ATL::CComPtr_ISessionInternalEvents__0_::ForEachEntry_::_1_::catch$14 @ 0x180162FD0 (_CLockedList_UniqueValuesOnly_ATL--CComPtr_ISessionInternalEvents__0_--ForEachEntry_--_1_--catch.c)
 *     _CAudioSessionManager::CreateAudioSession_::_1_::catch$78 @ 0x180163350 (_CAudioSessionManager--CreateAudioSession_--_1_--catch$78.c)
 *     _CEndpointStoreCache::GetEndpointStore_::_1_::catch$17 @ 0x1801636F0 (_CEndpointStoreCache--GetEndpointStore_--_1_--catch$17.c)
 *     _CAudioSession::AddStream_::_1_::catch$13 @ 0x180163948 (_CAudioSession--AddStream_--_1_--catch$13.c)
 *     asm_GetApplicationSubmixes$catch$4 @ 0x180163A43 (asm_GetApplicationSubmixes$catch$4.c)
 *     _CAudioSession::FinishConstruction_::_1_::catch$10 @ 0x180163C41 (_CAudioSession--FinishConstruction_--_1_--catch$10.c)
 *     _CAudioStream::SetProcessingModeParameters_::_1_::catch$5 @ 0x1801641A4 (_CAudioStream--SetProcessingModeParameters_--_1_--catch$5.c)
 *     _StreamGroupParams::Clone_::_1_::catch$21 @ 0x180164204 (_StreamGroupParams--Clone_--_1_--catch$21.c)
 *     _DeriveAudioProcessingModeConfiguration_::_1_::catch$3 @ 0x180164252 (_DeriveAudioProcessingModeConfiguration_--_1_--catch$3.c)
 *     _CEndpointCharacteristics::GetEffectPacks_::_1_::catch$5 @ 0x18016443D (_CEndpointCharacteristics--GetEffectPacks_--_1_--catch$5.c)
 *     _CEndpointCharacteristics::DiscoverConnectorProcessingModeCharacteristics_::_1_::catch$8 @ 0x18016449D (_CEndpointCharacteristics--DiscoverConnectorProcessingModeCharacteristics_--_1_--catch$8.c)
 *     _DeserializeProcessingModeCharacteristics_::_1_::catch$2 @ 0x180164536 (_DeserializeProcessingModeCharacteristics_--_1_--catch$2.c)
 *     _CConnectorProcessingModeCharacteristics::AddConnectorFormat_::_1_::catch$5 @ 0x18016458A (_CConnectorProcessingModeCharacteristics--AddConnectorFormat_--_1_--catch$5.c)
 *     _CAudioStream::GetDiscoveredEffects_::_1_::catch$1 @ 0x180164762 (_CAudioStream--GetDiscoveredEffects_--_1_--catch$1.c)
 *     _CResourcePriorityTracker::AddResourcePriorityToMap_::_1_::catch$5 @ 0x180164B09 (_CResourcePriorityTracker--AddResourcePriorityToMap_--_1_--catch$5.c)
 *     _AudioModeEffectsWatcher::PopulateControllableEffects_::_1_::catch$6 @ 0x180164BA7 (_AudioModeEffectsWatcher--PopulateControllableEffects_--_1_--catch$6.c)
 *     _CAudioSessionManager::OnSessionStateChanged_::_1_::catch$26 @ 0x180164D8E (_CAudioSessionManager--OnSessionStateChanged_--_1_--catch$26.c)
 *     _CLockedList_UniqueValuesOnly_CAudioSessionNotificationProcess_0_::ForEachEntry_::_1_::catch$10 @ 0x180164DDF (_CLockedList_UniqueValuesOnly_CAudioSessionNotificationProcess_0_--ForEachEntry_--_1_--catch$10.c)
 *     _CPolicyConfig::GetAudioSessionPropertyStore_::_1_::catch$33 @ 0x180164F8A (_CPolicyConfig--GetAudioSessionPropertyStore_--_1_--catch$33.c)
 *     _CAudioSession::RegisterOwnerProcess_::_1_::catch$12 @ 0x180165064 (_CAudioSession--RegisterOwnerProcess_--_1_--catch$12.c)
 *     _CAudioSession::Disconnect_::_1_::catch$13 @ 0x1801650C4 (_CAudioSession--Disconnect_--_1_--catch$13.c)
 *     _CAudioSession::DisconnectStreamList_::_1_::catch$6 @ 0x180165118 (_CAudioSession--DisconnectStreamList_--_1_--catch$6.c)
 *     _CLockedList_UniqueValuesOnly_ATL::CComPtr_ISessionInternalEvents__0_::AddInterface_::_1_::catch$10 @ 0x180165370 (_CLockedList_UniqueValuesOnly_ATL--CComPtr_ISessionInternalEvents__0_--AddInterface_--_1_--catch.c)
 *     _CLockedList_UniqueValuesOnly_CMasterVolumeNotificationProcess_0_::ForEachEntry_::_1_::catch$6 @ 0x1801653BE (_CLockedList_UniqueValuesOnly_CMasterVolumeNotificationProcess_0_--ForEachEntry_--_1_--catch$6.c)
 *     _CLockedList_UniqueValuesOnly_ATL::CComPtr_IAudioEndpointVolumeCallback__0_::ForEachEntry_::_1_::catch$8 @ 0x18016540C (_CLockedList_UniqueValuesOnly_ATL--CComPtr_IAudioEndpointVolumeCallback__0_--ForEac_ea_18016540C.c)
 *     _EffectPackConfiguration::CreateDriverEffectPackConfiguration_::_1_::catch$12 @ 0x180165738 (_EffectPackConfiguration--CreateDriverEffectPackConfiguration_--_1_--catch$12.c)
 *     _EffectPack::CreateInstanceFromConfiguration_::_1_::catch$3 @ 0x18016579B (_EffectPack--CreateInstanceFromConfiguration_--_1_--catch$3.c)
 *     _EffectPackConfiguration::ReadConfiguration_::_1_::catch$42 @ 0x1801659A5 (_EffectPackConfiguration--ReadConfiguration_--_1_--catch$42.c)
 *     _CBaseStreamGroupProxy::InitializeAPOs_::_1_::catch$4 @ 0x180165B5A (_CBaseStreamGroupProxy--InitializeAPOs_--_1_--catch$4.c)
 *     _CBaseStreamGroupProxy::AddStream_::_1_::catch$8 @ 0x180165BAB (_CBaseStreamGroupProxy--AddStream_--_1_--catch$8.c)
 *     _CProcessSubmixProxy::AddStream_::_1_::catch$9 @ 0x180165BE7 (_CProcessSubmixProxy--AddStream_--_1_--catch$9.c)
 *     _CLockedList_UniqueValuesOnly_CMasterVolumeNotificationProcess_0_::AddInterface_::_1_::catch$5 @ 0x180166054 (_CLockedList_UniqueValuesOnly_CMasterVolumeNotificationProcess_0_--AddInterface_--_1_--catch$5.c)
 *     _CLockedList_UniqueValuesOnly_CAudioSessionNotificationProcess_0_::AddInterface_::_1_::catch$9 @ 0x180166130 (_CLockedList_UniqueValuesOnly_CAudioSessionNotificationProcess_0_--AddInterface_--_1_--catch$9.c)
 *     _AudioModeEffectsWatcherFactory::GetWatcher_::_1_::catch$19 @ 0x1801661E9 (_AudioModeEffectsWatcherFactory--GetWatcher_--_1_--catch$19.c)
 *     _CDeviceGraphObjectsStore::GetSaDevices_::_1_::catch$5 @ 0x18016628F (_CDeviceGraphObjectsStore--GetSaDevices_--_1_--catch$5.c)
 *     _CSharedStreamGroupProxy::CompareStreamingEffectsOverrideProcessingModeParameters_::_1_::catch$2 @ 0x1801662EF (_CSharedStreamGroupProxy--CompareStreamingEffectsOverrideProcessingModeParameters_--_1_--catch$2.c)
 *     _CAudioSessionManager::Initialize_::_1_::catch$7 @ 0x180166B60 (_CAudioSessionManager--Initialize_--_1_--catch$7.c)
 *     _CAudioStream::GetControllableEffects_::_1_::catch$9 @ 0x180166C39 (_CAudioStream--GetControllableEffects_--_1_--catch$9.c)
 *     _AtmosCheck::EndAppSvcCall_::_1_::catch$0 @ 0x180166CE1 (_AtmosCheck--EndAppSvcCall_--_1_--catch$0.c)
 *     _FilterSettableEffectsOverride_::_1_::catch$0 @ 0x180166D83 (_FilterSettableEffectsOverride_--_1_--catch$0.c)
 *     _CDeviceGraphObjectsStore::GetAllStreamGroups_::_1_::catch$15 @ 0x180166DBF (_CDeviceGraphObjectsStore--GetAllStreamGroups_--_1_--catch$15.c)
 *     _CAudioRenderEndpointChangeDelegator::RegisterForAudioRenderEndpointChangeNotifications_::_1_::catch$5 @ 0x180166E60 (_CAudioRenderEndpointChangeDelegator--RegisterForAudioRenderEndpointChangeNotifications_--_1_--c.c)
 *     _CSharedStreamGroupProxy::GetEffectsFromMFXInstantiatedForStreaming_::_1_::catch$2 @ 0x180166F35 (_CSharedStreamGroupProxy--GetEffectsFromMFXInstantiatedForStreaming_--_1_--catch$2.c)
 *     _AtmosCheck::GetCurrentEndpointsUnderLock_::_1_::catch$8 @ 0x180166F9B (_AtmosCheck--GetCurrentEndpointsUnderLock_--_1_--catch$8.c)
 *     _AtmosCheck::BeginAppSvcCall_::_1_::catch$0 @ 0x18016703E (_AtmosCheck--BeginAppSvcCall_--_1_--catch$0.c)
 *     _CAudioSession::GetOwningProcesses_::_1_::catch$5 @ 0x18016707A (_CAudioSession--GetOwningProcesses_--_1_--catch$5.c)
 *     _CProcessSubmixManager::GetAppSubmixClientContext_::_1_::catch$0 @ 0x18016763B (_CProcessSubmixManager--GetAppSubmixClientContext_--_1_--catch$0.c)
 *     _CProcessSubmixManager::GetAppSubmixClientContext_::_1_::catch$0_0 @ 0x180167677 (_CProcessSubmixManager--GetAppSubmixClientContext_--_1_--catch$0_0.c)
 *     _CProcessSubmixManager::GetAppSubmixClientContextHelper_::_1_::catch$23 @ 0x180167746 (_CProcessSubmixManager--GetAppSubmixClientContextHelper_--_1_--catch$23.c)
 *     asm_GetApplicationSubmixFromId$catch$4 @ 0x180167797 (asm_GetApplicationSubmixFromId$catch$4.c)
 *     _TokenManager_CAudioPumpDspResourceTracker_::AcquireToken_CAudioPumpDspResourceTracker::AudioPumpDspTokenAcquisitionContext__::_1_::catch$27 @ 0x18016790D (_TokenManager_CAudioPumpDspResourceTracker_--AcquireToken_CAudioPumpDspResourceTrac_ea_18016790D.c)
 *     _CAudioPumpDspResourceTracker::AcquireAudioPumpDspTokenForEndpoint_::_1_::catch$13 @ 0x180167A08 (_CAudioPumpDspResourceTracker--AcquireAudioPumpDspTokenForEndpoint_--_1_--catch$13.c)
 *     _CAudioResourceManager::CreateStream_::_1_::catch$133 @ 0x180167EFD (_CAudioResourceManager--CreateStream_--_1_--catch$133.c)
 *     _CAudioResourceManager::OnMfxDiscoveryEffectsChanged_::_1_::catch$3 @ 0x1801680D8 (_CAudioResourceManager--OnMfxDiscoveryEffectsChanged_--_1_--catch$3.c)
 *     _CAudioSession::AddDuckingManagerGainStage_::_1_::catch$7 @ 0x1801682B5 (_CAudioSession--AddDuckingManagerGainStage_--_1_--catch$7.c)
 *     _CAudioSession::DisconnectStreams_::_1_::catch$5 @ 0x1801682F1 (_CAudioSession--DisconnectStreams_--_1_--catch$5.c)
 *     _CAudioSession::ForEachOwningProcess_::_1_::catch$1 @ 0x18016832D (_CAudioSession--ForEachOwningProcess_--_1_--catch$1.c)
 *     _CAudioSessionManager::RegisterDisconnectNotificationClient_::_1_::catch$10 @ 0x18016838D (_CAudioSessionManager--RegisterDisconnectNotificationClient_--_1_--catch$10.c)
 *     _CAudioStream::GetEffectsFromApo_::_1_::catch$2 @ 0x1801685C1 (_CAudioStream--GetEffectsFromApo_--_1_--catch$2.c)
 *     _CAudioStream::InitializeAPOs_::_1_::catch$24 @ 0x180168603 (_CAudioStream--InitializeAPOs_--_1_--catch$24.c)
 *     _CAudioStream::MergeEffectsLists_::_1_::catch$0 @ 0x180168642 (_CAudioStream--MergeEffectsLists_--_1_--catch$0.c)
 *     _CAudioStream::RegisterStreamVolumeNotifications_::_1_::catch$7 @ 0x18016867E (_CAudioStream--RegisterStreamVolumeNotifications_--_1_--catch$7.c)
 *     _CAudioStream::SetEchoCancellationRenderEndpoint_::_1_::catch$28 @ 0x1801686CC (_CAudioStream--SetEchoCancellationRenderEndpoint_--_1_--catch$28.c)
 *     _BluetoothControls::BluetoothControl_IVolumeControlHandler_BluetoothControls::BluetoothVolume_::RuntimeClassInitialize_::_1_::catch$17 @ 0x18016885E (_BluetoothControls--BluetoothControl_IVolumeControlHandler_BluetoothControls--Bluet_ea_18016885E.c)
 *     _BluetoothControls::BluetoothControl_IVolumeControlHandler_BluetoothControls::BluetoothVolume_::RuntimeClassInitialize_::_1_::catch$3 @ 0x1801688A0 (_BluetoothControls--BluetoothControl_IVolumeControlHandler_BluetoothControls--Bluet_ea_1801688A0.c)
 *     _CBtAudioResourceManagerBase::CreateExclusiveSaDeviceOnRenderEndpoint_::_1_::catch$17 @ 0x18016895A (_CBtAudioResourceManagerBase--CreateExclusiveSaDeviceOnRenderEndpoint_--_1_--catch$17.c)
 *     _CBtAudioResourceManagerBase::CreateSaDeviceOnMicrophoneEndpoint_::_1_::catch$15 @ 0x1801689F6 (_CBtAudioResourceManagerBase--CreateSaDeviceOnMicrophoneEndpoint_--_1_--catch$15.c)
 *     _CBtAudioResourceManagerBase::CreateSaDeviceOnRenderEndpoint_::_1_::catch$42 @ 0x180168A47 (_CBtAudioResourceManagerBase--CreateSaDeviceOnRenderEndpoint_--_1_--catch$42.c)
 *     _CBtAudioResourceManagerBase::GetSaDeviceForExclusiveStream_::_1_::catch$3 @ 0x180168B97 (_CBtAudioResourceManagerBase--GetSaDeviceForExclusiveStream_--_1_--catch$3.c)
 *     _CBtAudioResourceManagerBase::GetSaDeviceForOffloadStream_::_1_::catch$18 @ 0x180168BE8 (_CBtAudioResourceManagerBase--GetSaDeviceForOffloadStream_--_1_--catch$18.c)
 *     _CBtAudioResourceManagerBase::GetSaDeviceForSharedStream_::_1_::catch$3 @ 0x180168C2A (_CBtAudioResourceManagerBase--GetSaDeviceForSharedStream_--_1_--catch$3.c)
 *     _CBtAudioResourceManagerBase::RefreshStreamsOnDevice_::_1_::catch$37 @ 0x180168D9B (_CBtAudioResourceManagerBase--RefreshStreamsOnDevice_--_1_--catch$37.c)
 *     _CBtAudioResourceManagerBase::RegisterBidirectionalModeChangedCallback_::_1_::catch$9 @ 0x180168DEF (_CBtAudioResourceManagerBase--RegisterBidirectionalModeChangedCallback_--_1_--catch$9.c)
 *     _CBtAudioResourceManagerBase::RegisterCallback_::_1_::catch$9 @ 0x180168E2B (_CBtAudioResourceManagerBase--RegisterCallback_--_1_--catch$9.c)
 *     __lambda_23a707cc6c78406526adb642245a01c2_::operator()_::_1_::catch$11 @ 0x180168FAB (__lambda_23a707cc6c78406526adb642245a01c2_--operator()_--_1_--catch$11.c)
 *     __lambda_82b4d950fa5d9eeb82537f57bcb68a2f_::operator()_::_1_::catch$19 @ 0x18016900E (__lambda_82b4d950fa5d9eeb82537f57bcb68a2f_--operator()_--_1_--catch$19.c)
 *     _BluetoothBroadcastSession::AddChildEndpointIdIfNotPresent_::_1_::catch$4 @ 0x18016904D (_BluetoothBroadcastSession--AddChildEndpointIdIfNotPresent_--_1_--catch$4.c)
 *     _BluetoothBroadcastProvider::AddEndpointToCompatibleList_::_1_::catch$10 @ 0x180169089 (_BluetoothBroadcastProvider--AddEndpointToCompatibleList_--_1_--catch$10.c)
 *     _BluetoothBroadcastProvider::OnBluetoothRenderEndpointActivation_::_1_::catch$7 @ 0x1801691A5 (_BluetoothBroadcastProvider--OnBluetoothRenderEndpointActivation_--_1_--catch$7.c)
 *     _BluetoothBroadcastProvider::OnMulticastChildSessionDescriptorKeyChanged_::_1_::catch$14 @ 0x1801692A3 (_BluetoothBroadcastProvider--OnMulticastChildSessionDescriptorKeyChanged_--_1_--catch$14.c)
 *     _BluetoothBroadcastProvider::RuntimeClassInitialize_::_1_::catch$6 @ 0x180169631 (_BluetoothBroadcastProvider--RuntimeClassInitialize_--_1_--catch$6.c)
 *     _TokenManager_CBluetoothAudioEndpointResourceManagerProvider_::AcquireToken_IBtAudioResourceManager____::_1_::catch$27 @ 0x180169BD3 (_TokenManager_CBluetoothAudioEndpointResourceManagerProvider_--AcquireToken_IBtAudi_ea_180169BD3.c)
 *     _CBluetoothAudioEndpointResourceManagerProvider::TryGetResourceManagerService_::_1_::catch$15 @ 0x180169D51 (_CBluetoothAudioEndpointResourceManagerProvider--TryGetResourceManagerService_--_1_--catch$15.c)
 *     _CBaseStreamGroupProxy::EnumerateProcessSubmixes_::_1_::catch$5 @ 0x180169EB0 (_CBaseStreamGroupProxy--EnumerateProcessSubmixes_--_1_--catch$5.c)
 *     _CSaDeviceProxy::GetCopyOfResourceTokens_::_1_::catch$0 @ 0x180169EEC (_CSaDeviceProxy--GetCopyOfResourceTokens_--_1_--catch$0.c)
 *     _CBaseStreamGroupProxy::GetProcessSubmix_::_1_::catch$26 @ 0x180169F28 (_CBaseStreamGroupProxy--GetProcessSubmix_--_1_--catch$26.c)
 *     _CBaseStreamGroupProxy::RuntimeClassInitialize_::_1_::catch$5 @ 0x18016A004 (_CBaseStreamGroupProxy--RuntimeClassInitialize_--_1_--catch$5.c)
 *     _CBaseStreamGroupProxy::SetProcessingModeParameters_::_1_::catch$0 @ 0x18016A08D (_CBaseStreamGroupProxy--SetProcessingModeParameters_--_1_--catch$0.c)
 *     _CDeviceGraphObjectsStore::FindPreferredStreamGroup_::_1_::catch$10 @ 0x18016A0DB (_CDeviceGraphObjectsStore--FindPreferredStreamGroup_--_1_--catch$10.c)
 *     _CDeviceGraphObjectsStore::FindStreamGroups_::_1_::catch$15 @ 0x18016A117 (_CDeviceGraphObjectsStore--FindStreamGroups_--_1_--catch$15.c)
 *     _DeviceGraphStore::GetAllStreamGroups_::_1_::catch$2 @ 0x18016A156 (_DeviceGraphStore--GetAllStreamGroups_--_1_--catch$2.c)
 *     _CDeviceGraphObjectsStore::GetConnectedStreamGroups_::_1_::catch$15 @ 0x18016A195 (_CDeviceGraphObjectsStore--GetConnectedStreamGroups_--_1_--catch$15.c)
 *     _CDeviceGraphObjectsStore::GetExclusiveSaDevices_::_1_::catch$5 @ 0x18016A1D1 (_CDeviceGraphObjectsStore--GetExclusiveSaDevices_--_1_--catch$5.c)
 *     _DeviceGraphStore::GetFilteredSubmixes_::_1_::catch$2 @ 0x18016A20D (_DeviceGraphStore--GetFilteredSubmixes_--_1_--catch$2.c)
 *     _CDeviceGraphObjectsStore::GetOffloadStreamGroups_::_1_::catch$13 @ 0x18016A24C (_CDeviceGraphObjectsStore--GetOffloadStreamGroups_--_1_--catch$13.c)
 *     _DeviceGraphStore::GetOffloadStreamGroups_::_1_::catch$2 @ 0x18016A288 (_DeviceGraphStore--GetOffloadStreamGroups_--_1_--catch$2.c)
 *     _CDeviceGraphObjectsStore::GetStreamGroupsConnectedToSaDevice_::_1_::catch$10 @ 0x18016A2C7 (_CDeviceGraphObjectsStore--GetStreamGroupsConnectedToSaDevice_--_1_--catch$10.c)
 *     _DeviceGraphStore::GetSubmixHelper_::_1_::catch$2 @ 0x18016A303 (_DeviceGraphStore--GetSubmixHelper_--_1_--catch$2.c)
 *     _DeviceGraphStore::GetSubmixesForApplication_::_1_::catch$2 @ 0x18016A342 (_DeviceGraphStore--GetSubmixesForApplication_--_1_--catch$2.c)
 *     _EffectPackConfigurationManager::AddEffectPackConfigurationToList_::_1_::catch$6 @ 0x18016A381 (_EffectPackConfigurationManager--AddEffectPackConfigurationToList_--_1_--catch$6.c)
 *     _EffectPackConfigurationManager::RemoveEffectPackConfigurationFromList_::_1_::catch$5 @ 0x18016A3BD (_EffectPackConfigurationManager--RemoveEffectPackConfigurationFromList_--_1_--catch$5.c)
 *     _CEndpointStore::RuntimeClassInitialize_::_1_::catch$5 @ 0x18016A465 (_CEndpointStore--RuntimeClassInitialize_--_1_--catch$5.c)
 *     _CMulticastSessionManager::ActivateMulticastSession_::_1_::catch$4 @ 0x18016A568 (_CMulticastSessionManager--ActivateMulticastSession_--_1_--catch$4.c)
 *     _CMulticastSessionManager::GetCompatibleMulticastProvider_::_1_::catch$5 @ 0x18016A5C8 (_CMulticastSessionManager--GetCompatibleMulticastProvider_--_1_--catch$5.c)
 *     _CMulticastSessionManager::GetMulticastCapableChildEndpoints_::_1_::catch$2 @ 0x18016A62B (_CMulticastSessionManager--GetMulticastCapableChildEndpoints_--_1_--catch$2.c)
 *     _CMulticastSessionManager::GetMulticastSessions_::_1_::catch$2 @ 0x18016A68B (_CMulticastSessionManager--GetMulticastSessions_--_1_--catch$2.c)
 *     _CMulticastSessionManager::RuntimeClassInitialize_::_1_::catch$2 @ 0x18016A6D9 (_CMulticastSessionManager--RuntimeClassInitialize_--_1_--catch$2.c)
 *     _CVADServer::GetStreamVpoContext_::_1_::catch$11 @ 0x18016A980 (_CVADServer--GetStreamVpoContext_--_1_--catch$11.c)
 *     AudioServerCreateStreamConnection$catch$4 @ 0x18016AA0A (AudioServerCreateStreamConnection$catch$4.c)
 *     AudioServerGetEndpointVpoContext$catch$6 @ 0x18016AA6D (AudioServerGetEndpointVpoContext$catch$6.c)
 *     _CLockedList_UniqueValuesOnly_ATL::CComPtr_IAudioEndpointVolumeCallback__0_::AddInterface_::_1_::catch$9 @ 0x18016AC19 (_CLockedList_UniqueValuesOnly_ATL--CComPtr_IAudioEndpointVolumeCallback__0_--AddInterface_--_1_-.c)
 *     _CMonitorManager::CreateMonitor_::_1_::catch$9 @ 0x18016ADF3 (_CMonitorManager--CreateMonitor_--_1_--catch$9.c)
 *     _CMonitorManager::CreateStreamConnection_::_1_::catch$14 @ 0x18016AE56 (_CMonitorManager--CreateStreamConnection_--_1_--catch$14.c)
 *     _Sarm::CSpatialAudioResourceManager::RegisterForApplicationPolicyChanges_::_1_::catch$7 @ 0x18016B3F2 (_Sarm--CSpatialAudioResourceManager--RegisterForApplicationPolicyChanges_--_1_--catch$7.c)
 *     _CEndpointCharacteristics::AddEffectPackConfigurationIfApplicable_::_1_::catch$6 @ 0x18016B756 (_CEndpointCharacteristics--AddEffectPackConfigurationIfApplicable_--_1_--catch$6.c)
 *     _CEndpointCharacteristicsCache::GetEndpointCharacteristics_::_1_::catch$2 @ 0x18016B820 (_CEndpointCharacteristicsCache--GetEndpointCharacteristics_--_1_--catch$2.c)
 *     _CEndpointCharacteristicsCache::GetEndpointCharacteristics_sanitizedId_::_1_::catch$15 @ 0x18016B85F (_CEndpointCharacteristicsCache--GetEndpointCharacteristics_sanitizedId_--_1_--catch$15.c)
 *     _CEndpointCharacteristics::RemoveEffectPack_::_1_::catch$9 @ 0x18016B938 (_CEndpointCharacteristics--RemoveEffectPack_--_1_--catch$9.c)
 *     _CEndpointCharacteristics::SetCurrentEffectPackInternal_::_1_::catch$6 @ 0x18016B989 (_CEndpointCharacteristics--SetCurrentEffectPackInternal_--_1_--catch$6.c)
 *     _CEndpointCharacteristics::SetCurrentEffectPackInternal_::_1_::catch$9 @ 0x18016B9DA (_CEndpointCharacteristics--SetCurrentEffectPackInternal_--_1_--catch$9.c)
 *     _EffectPackConfiguration::CreateGlobalEffectPackConfiguration_::_1_::catch$36 @ 0x18016BE10 (_EffectPackConfiguration--CreateGlobalEffectPackConfiguration_--_1_--catch$36.c)
 *     _GetRecordFromWnf_::_1_::catch$0 @ 0x18016BF7A (_GetRecordFromWnf_--_1_--catch$0.c)
 *     _AtmosCheck::AddArrayToLicenseMap_::_1_::catch$4 @ 0x18016C120 (_AtmosCheck--AddArrayToLicenseMap_--_1_--catch$4.c)
 *     _AtmosCheck::UpdateLicenseMapForAllEndpoints_::_1_::catch$10 @ 0x18016C294 (_AtmosCheck--UpdateLicenseMapForAllEndpoints_--_1_--catch$10.c)
 *     _CConstraintModel::Initialize_::_1_::catch$21 @ 0x18016C619 (_CConstraintModel--Initialize_--_1_--catch$21.c)
 *     _CConnectorProcessingModeCharacteristics::AddProbableConnectorFormat_::_1_::catch$2 @ 0x18016CA68 (_CConnectorProcessingModeCharacteristics--AddProbableConnectorFormat_--_1_--catch$2.c)
 *     _GetConnectorProcessingModeDataFormatsFromDriver_::_1_::catch$13 @ 0x18016CAA4 (_GetConnectorProcessingModeDataFormatsFromDriver_--_1_--catch$13.c)
 * Callees:
 *     ??$ReportFailure_CaughtException@$00@details@wil@@YAJPEAXIPEBD110W4SupportedExceptions@1@@Z @ 0x1800BAD48 (--$ReportFailure_CaughtException@$00@details@wil@@YAJPEAXIPEBD110W4SupportedExceptions@1@@Z.c)
 */

__int64 __fastcall wil::details::in1diag3::Return_CaughtException(
        wil::details::in1diag3 *this,
        void *a2,
        int a3,
        const char *a4)
{
  return wil::details::ReportFailure_CaughtException<1>((int)this, (int)a2, a3);
}
