/*
 * XREFs of RaidAllocatePool @ 0x1C0006850
 * Callers:
 *     RaBuildQueryPhysicalTopologyBufferForMiniport @ 0x1C00032F0 (RaBuildQueryPhysicalTopologyBufferForMiniport.c)
 *     RaidAllocateSrb @ 0x1C00066F0 (RaidAllocateSrb.c)
 *     RaidUnitCompleteRequest @ 0x1C0009590 (RaidUnitCompleteRequest.c)
 *     StorUnmapSenseInfo @ 0x1C000A980 (StorUnmapSenseInfo.c)
 *     StorpTelemetrySendUnitPerfData @ 0x1C000C9E4 (StorpTelemetrySendUnitPerfData.c)
 *     RaUnitAtaPassThroughIoctl @ 0x1C000F6CC (RaUnitAtaPassThroughIoctl.c)
 *     RaidBusEnumeratorProcessAtaInformation @ 0x1C00102D0 (RaidBusEnumeratorProcessAtaInformation.c)
 *     RaUnitScsiFreeDumpPointersIoctl @ 0x1C001105C (RaUnitScsiFreeDumpPointersIoctl.c)
 *     RaidpBuildAdapterBusRelations @ 0x1C0012B8C (RaidpBuildAdapterBusRelations.c)
 *     RaidBusEnumeratorVisitUnit @ 0x1C0013398 (RaidBusEnumeratorVisitUnit.c)
 *     RaidBusEnumeratorAllocateReportLunsResources @ 0x1C00146D8 (RaidBusEnumeratorAllocateReportLunsResources.c)
 *     RaidBusEnumeratorAllocateUnitResources @ 0x1C0014934 (RaidBusEnumeratorAllocateUnitResources.c)
 *     RaidBusEnumeratorProcessBusUnit @ 0x1C00150C8 (RaidBusEnumeratorProcessBusUnit.c)
 *     RaidUnitAllocateResources @ 0x1C00154BC (RaidUnitAllocateResources.c)
 *     RaUnitBuildDsmNotifyBufferForMiniport @ 0x1C001746C (RaUnitBuildDsmNotifyBufferForMiniport.c)
 *     RaUnitScsiGetDumpPointersIoctl @ 0x1C0017634 (RaUnitScsiGetDumpPointersIoctl.c)
 *     StorCreateAnsiString @ 0x1C001857C (StorCreateAnsiString.c)
 *     RaBuildHwFirmwareGetInfoBufferForMiniport @ 0x1C0018D94 (RaBuildHwFirmwareGetInfoBufferForMiniport.c)
 *     RaDuplicateUnicodeString @ 0x1C001B208 (RaDuplicateUnicodeString.c)
 *     RaidUnitGetDeviceId @ 0x1C001B43C (RaidUnitGetDeviceId.c)
 *     RaidUnitGetCompatibleIds @ 0x1C001B528 (RaidUnitGetCompatibleIds.c)
 *     RaidUnitGetHardwareIds @ 0x1C001B670 (RaidUnitGetHardwareIds.c)
 *     RaidUnitGetInstanceId @ 0x1C001BB5C (RaidUnitGetInstanceId.c)
 *     RaInitializeRaidResources @ 0x1C001BCB8 (RaInitializeRaidResources.c)
 *     RaidAdjustDeferredQueueDepth @ 0x1C001C1B0 (RaidAdjustDeferredQueueDepth.c)
 *     RaidGetD3ColdInterface @ 0x1C001D5C0 (RaidGetD3ColdInterface.c)
 *     RaidAllocateAddressMapping @ 0x1C001DC88 (RaidAllocateAddressMapping.c)
 *     StorpAdapterInitializePoFxPower @ 0x1C001E354 (StorpAdapterInitializePoFxPower.c)
 *     RaidRegisterForRuntimePowerManagement @ 0x1C001E684 (RaidRegisterForRuntimePowerManagement.c)
 *     RaidAdapterCheckWaitTimeout @ 0x1C001F238 (RaidAdapterCheckWaitTimeout.c)
 *     StorpInitializeTimer @ 0x1C0021990 (StorpInitializeTimer.c)
 *     RaUnitStreamsIoctl @ 0x1C002274C (RaUnitStreamsIoctl.c)
 *     RaidUnitLogSenseCommandSrb @ 0x1C0023488 (RaidUnitLogSenseCommandSrb.c)
 *     RaGetProtocolCommandEffects @ 0x1C0033F34 (RaGetProtocolCommandEffects.c)
 *     RaidAdapterAcquireCryptoKeyResources @ 0x1C00341E8 (RaidAdapterAcquireCryptoKeyResources.c)
 *     RaidAdapterSendRPMBCommandSynchronously @ 0x1C0036A18 (RaidAdapterSendRPMBCommandSynchronously.c)
 *     RaidInitializeCryptoEngine @ 0x1C0038428 (RaidInitializeCryptoEngine.c)
 *     RaidBusEnumeratorReAllocateDataBufferResource @ 0x1C00390A0 (RaidBusEnumeratorReAllocateDataBufferResource.c)
 *     StorpInitializeWorkItem @ 0x1C003EB84 (StorpInitializeWorkItem.c)
 *     StorpUnitInitializePoFxPower @ 0x1C003F4F4 (StorpUnitInitializePoFxPower.c)
 *     RaidRegisterPerfStates @ 0x1C0040DC4 (RaidRegisterPerfStates.c)
 *     RaBuildHwFirmwareActivateBufferForMiniport @ 0x1C0043504 (RaBuildHwFirmwareActivateBufferForMiniport.c)
 *     RaBuildHwFirmwareDownloadBufferForMiniport @ 0x1C0043638 (RaBuildHwFirmwareDownloadBufferForMiniport.c)
 *     RaBuildQueryBootLunsBufferForMiniport @ 0x1C0043858 (RaBuildQueryBootLunsBufferForMiniport.c)
 *     RaBuildQueryEnduranceInfoPropertyBufferForMiniport @ 0x1C0043904 (RaBuildQueryEnduranceInfoPropertyBufferForMiniport.c)
 *     RaBuildQueryProtocolSpecificPropertyBufferForMiniport @ 0x1C00439EC (RaBuildQueryProtocolSpecificPropertyBufferForMiniport.c)
 *     RaBuildQueryTemperaturePropertyBufferForMiniport @ 0x1C0043B1C (RaBuildQueryTemperaturePropertyBufferForMiniport.c)
 *     RaBuildSetBootLunBufferForMiniport @ 0x1C0043C04 (RaBuildSetBootLunBufferForMiniport.c)
 *     RaBuildSetProtocolSpecificPropertyBufferForMiniport @ 0x1C0043CF4 (RaBuildSetProtocolSpecificPropertyBufferForMiniport.c)
 *     RaBuildSetTemperatureThresholdBufferForMiniport @ 0x1C0043E30 (RaBuildSetTemperatureThresholdBufferForMiniport.c)
 *     RaUnitBuildDsmGeneralBufferForMiniport @ 0x1C0045164 (RaUnitBuildDsmGeneralBufferForMiniport.c)
 *     RaUnitSmartDataIoctl @ 0x1C0046560 (RaUnitSmartDataIoctl.c)
 *     RaidUnitHandleReportLunsDataChanged @ 0x1C00488D0 (RaidUnitHandleReportLunsDataChanged.c)
 *     RaidUnitSubmitResetRequest @ 0x1C0049C88 (RaidUnitSubmitResetRequest.c)
 *     RaidAdapterWmiDeferredRoutine @ 0x1C004A320 (RaidAdapterWmiDeferredRoutine.c)
 *     RaAttemptHighWaterMarkIncrease @ 0x1C004A700 (RaAttemptHighWaterMarkIncrease.c)
 *     RaUnitQueryDeviceRelationsIrp @ 0x1C006B0DC (RaUnitQueryDeviceRelationsIrp.c)
 *     RaInitializeTagList @ 0x1C006C090 (RaInitializeTagList.c)
 *     RaUnitQueryDeviceTextIrp @ 0x1C006EAE0 (RaUnitQueryDeviceTextIrp.c)
 *     RaUnitRegisterForIdleDetection @ 0x1C006EDD0 (RaUnitRegisterForIdleDetection.c)
 *     StorpInititalizePerUnitPerfTelemetry @ 0x1C006FFAC (StorpInititalizePerUnitPerfTelemetry.c)
 *     RaidAdapterCreateDriverInfo @ 0x1C00729F0 (RaidAdapterCreateDriverInfo.c)
 *     RaidAdapterCreateDumpInfo @ 0x1C0072CE4 (RaidAdapterCreateDumpInfo.c)
 *     RaidAdapterDiagnosticIoctl @ 0x1C0073120 (RaidAdapterDiagnosticIoctl.c)
 *     RaidAdapterFreeMiniportDumpInfo @ 0x1C0073748 (RaidAdapterFreeMiniportDumpInfo.c)
 *     RaidAdapterGetMiniportDumpInfo @ 0x1C0073A5C (RaidAdapterGetMiniportDumpInfo.c)
 *     RaidUnitCreateDumpData @ 0x1C00757F4 (RaidUnitCreateDumpData.c)
 *     RaidUnitCreateDumpInfo @ 0x1C0075938 (RaidUnitCreateDumpInfo.c)
 * Callees:
 *     RaidLogAllocationFailure @ 0x1C0044614 (RaidLogAllocationFailure.c)
 */

PVOID __fastcall RaidAllocatePool(POOL_TYPE a1, SIZE_T a2, ULONG a3, __int64 a4)
{
  PVOID PoolWithTag; // rbx

  PoolWithTag = ExAllocatePoolWithTag(a1, a2, a3);
  if ( !PoolWithTag )
    RaidLogAllocationFailure(a4, (unsigned int)a1, a2, a3);
  return PoolWithTag;
}
