/*
 * XREFs of ?vUnlockFast@XDCOBJ@@IEAAXXZ @ 0x1C011C72C
 * Callers:
 *     GreEnumFonts @ 0x1C0003CEC (GreEnumFonts.c)
 *     NtGdiGetPixel @ 0x1C0005580 (NtGdiGetPixel.c)
 *     GreTransformPoints @ 0x1C0006CF4 (GreTransformPoints.c)
 *     ?GreSetICMMode@@YAHPEAUHDC__@@KK@Z @ 0x1C0007548 (-GreSetICMMode@@YAHPEAUHDC__@@KK@Z.c)
 *     GreSetBrushOrg @ 0x1C0007894 (GreSetBrushOrg.c)
 *     GreSetBoundsRect @ 0x1C00094E4 (GreSetBoundsRect.c)
 *     GreBeginGdiRenderingToDxSurface @ 0x1C00097F8 (GreBeginGdiRenderingToDxSurface.c)
 *     GreGetBoundsRect @ 0x1C0009A58 (GreGetBoundsRect.c)
 *     NtGdiSetMetaRgn @ 0x1C000A030 (NtGdiSetMetaRgn.c)
 *     ?GreGetCharWidthInfo@@YAHPEAUHDC__@@PEAU_CHWIDTHINFO@@W4EntryPoint@RFONTOBJ@@@Z @ 0x1C000E3C8 (-GreGetCharWidthInfo@@YAHPEAUHDC__@@PEAU_CHWIDTHINFO@@W4EntryPoint@RFONTOBJ@@@Z.c)
 *     GreCreateBitmapFromDxSurface @ 0x1C00140D4 (GreCreateBitmapFromDxSurface.c)
 *     GreGetBkColor @ 0x1C0014CB8 (GreGetBkColor.c)
 *     GreGetTextColor @ 0x1C0014D08 (GreGetTextColor.c)
 *     GreCreateCompatibleBitmapInternal @ 0x1C0024FB0 (GreCreateCompatibleBitmapInternal.c)
 *     GreGetLayout @ 0x1C003CC34 (GreGetLayout.c)
 *     GreSetStretchBltMode @ 0x1C0041990 (GreSetStretchBltMode.c)
 *     GreSetBkColor @ 0x1C0041A40 (GreSetBkColor.c)
 *     ?GreCreateDIBitmapReal@@YAPEAUHBITMAP__@@PEAUHDC__@@KAEAV?$umptr_r@E@@PEAUtagBITMAPINFO@@KIPEAXK3K_KPEAPEAX@Z @ 0x1C00476E0 (-GreCreateDIBitmapReal@@YAPEAUHBITMAP__@@PEAUHDC__@@KAEAV-$umptr_r@E@@PEAUtagBITMAPINFO@@KIPEAXK.c)
 *     GreMaskBlt @ 0x1C0079B5C (GreMaskBlt.c)
 *     ?GreFontIsLinked@@YAHPEAUHDC__@@W4EntryPoint@RFONTOBJ@@@Z @ 0x1C0089AD8 (-GreFontIsLinked@@YAHPEAUHDC__@@W4EntryPoint@RFONTOBJ@@@Z.c)
 *     NtGdiQueryFontAssocInfo @ 0x1C008A5B0 (NtGdiQueryFontAssocInfo.c)
 *     GreOffsetClipRgn @ 0x1C00958C4 (GreOffsetClipRgn.c)
 *     GreGetSystemPaletteUse @ 0x1C0097B90 (GreGetSystemPaletteUse.c)
 *     ?GreUpdateSpriteInternal@@YAHPEAUHDEV__@@PEAUHWND__@@PEAXPEAUHDC__@@PEAUtagPOINT@@PEAUtagSIZE@@34KPEAU_BLENDFUNCTION@@KPEAUtagRECT@@PEAUtagMINIWINDOWINFO@@HHK@Z @ 0x1C00B9650 (-GreUpdateSpriteInternal@@YAHPEAUHDEV__@@PEAUHWND__@@PEAXPEAUHDC__@@PEAUtagPOINT@@PEAUtagSIZE@@3.c)
 *     GreRectVisible @ 0x1C00BD078 (GreRectVisible.c)
 *     ?GreSetDIBitsToDeviceInternalImpl@@YAHPEAUHDC__@@HHKKHHKKAEAV?$umptr_r@E@@PEAUtagBITMAPINFO@@KIHPEAX@Z @ 0x1C00BEBE0 (-GreSetDIBitsToDeviceInternalImpl@@YAHPEAUHDC__@@HHKKHHKKAEAV-$umptr_r@E@@PEAUtagBITMAPINFO@@KIH.c)
 *     ?GreStretchDIBitsInternalImpl@@YAHPEAUHDC__@@HHHHHHHHAEAV?$umptr_r@E@@PEAUtagBITMAPINFO@@KKIPEAX@Z @ 0x1C00C0EB0 (-GreStretchDIBitsInternalImpl@@YAHPEAUHDC__@@HHHHHHHHAEAV-$umptr_r@E@@PEAUtagBITMAPINFO@@KKIPEAX.c)
 *     ?GreExtTextOutRect@@YAHPEAUHDC__@@PEAUtagRECT@@W4EntryPoint@RFONTOBJ@@@Z @ 0x1C00C32F8 (-GreExtTextOutRect@@YAHPEAUHDC__@@PEAUtagRECT@@W4EntryPoint@RFONTOBJ@@@Z.c)
 *     ?GreGetRealizationInfo@@YAHPEAUHDC__@@PEAUtagFONT_REALIZATION_INFO2@@W4EntryPoint@RFONTOBJ@@@Z @ 0x1C00C6414 (-GreGetRealizationInfo@@YAHPEAUHDC__@@PEAUtagFONT_REALIZATION_INFO2@@W4EntryPoint@RFONTOBJ@@@Z.c)
 *     ?GreGetTextExtentExW@@YAHPEAUHDC__@@PEAGKKPEAK2PEAUtagSIZE@@KW4EntryPoint@RFONTOBJ@@@Z @ 0x1C00C69A4 (-GreGetTextExtentExW@@YAHPEAUHDC__@@PEAGKKPEAK2PEAUtagSIZE@@KW4EntryPoint@RFONTOBJ@@@Z.c)
 *     ?GrepGetTextMetricsW@@YAHPEAUHDC__@@PEAU_TMW_INTERNAL@@W4EntryPoint@RFONTOBJ@@@Z @ 0x1C00C7144 (-GrepGetTextMetricsW@@YAHPEAUHDC__@@PEAU_TMW_INTERNAL@@W4EntryPoint@RFONTOBJ@@@Z.c)
 *     ?ulGetFontData@@YAKPEAUHDC__@@KKPEAXKW4EntryPoint@RFONTOBJ@@@Z @ 0x1C00C7E9C (-ulGetFontData@@YAKPEAUHDC__@@KKPEAXKW4EntryPoint@RFONTOBJ@@@Z.c)
 *     ?GreGetOutlineTextMetricsInternalW@@YAKPEAUHDC__@@KPEAU_OUTLINETEXTMETRICW@@PEAU_TMDIFF@@W4EntryPoint@RFONTOBJ@@@Z @ 0x1C00CA878 (-GreGetOutlineTextMetricsInternalW@@YAKPEAUHDC__@@KPEAU_OUTLINETEXTMETRICW@@PEAU_TMDIFF@@W4Entry.c)
 *     ?GrepGetTextExtentW@@YAHPEAUHDC__@@PEAGHPEAUtagSIZE@@IW4EntryPoint@RFONTOBJ@@@Z @ 0x1C00CD004 (-GrepGetTextExtentW@@YAHPEAUHDC__@@PEAGHPEAUtagSIZE@@IW4EntryPoint@RFONTOBJ@@@Z.c)
 *     ?GrepGetTextCharsetInfo@@YAHPEAUHDC__@@PEAUtagFONTSIGNATURE@@KW4EntryPoint@RFONTOBJ@@@Z @ 0x1C00D17F4 (-GrepGetTextCharsetInfo@@YAHPEAUHDC__@@PEAUtagFONTSIGNATURE@@KW4EntryPoint@RFONTOBJ@@@Z.c)
 *     GreGetCharSet @ 0x1C00D1968 (GreGetCharSet.c)
 *     ?GreGetGlyphOutlineInternal@@YAKPEAUHDC__@@GIPEAU_GLYPHMETRICS@@KPEAXPEAU_MAT2@@HW4EntryPoint@RFONTOBJ@@@Z @ 0x1C00D3538 (-GreGetGlyphOutlineInternal@@YAKPEAUHDC__@@GIPEAU_GLYPHMETRICS@@KPEAXPEAU_MAT2@@HW4EntryPoint@RF.c)
 *     ??1DEVLOCKBLTOBJ@@QEAA@XZ @ 0x1C00F98B0 (--1DEVLOCKBLTOBJ@@QEAA@XZ.c)
 *     GreStretchBltInternal @ 0x1C0100110 (GreStretchBltInternal.c)
 *     NtGdiBitBltInternal @ 0x1C0105030 (NtGdiBitBltInternal.c)
 *     GreExtSelectClipRgnInternal @ 0x1C011B070 (GreExtSelectClipRgnInternal.c)
 *     GreSelectFont @ 0x1C011C490 (GreSelectFont.c)
 *     ??1DCOBJ@@QEAA@XZ @ 0x1C011C700 (--1DCOBJ@@QEAA@XZ.c)
 *     ?vDestructor@DEVLOCKOBJ@@QEAAXXZ @ 0x1C011C870 (-vDestructor@DEVLOCKOBJ@@QEAAXXZ.c)
 *     ?UntrapAppContainerRenderingWorker@@YAXAEAPEAUHDC__@@AEAPEAUHSURF__@@1PEBK@Z @ 0x1C011CE78 (-UntrapAppContainerRenderingWorker@@YAXAEAPEAUHDC__@@AEAPEAUHSURF__@@1PEBK@Z.c)
 *     ?bSpUpdateShape@@YAHPEAVSPRITE@@KPEAUHDC__@@1KPEAU_BLENDFUNCTION@@PEAU_POINTL@@PEAUtagSIZE@@PEAU_RECTL@@@Z @ 0x1C01364A0 (-bSpUpdateShape@@YAHPEAVSPRITE@@KPEAUHDC__@@1KPEAU_BLENDFUNCTION@@PEAU_POINTL@@PEAUtagSIZE@@PEAU.c)
 *     GreGetTransform @ 0x1C013FD0A (GreGetTransform.c)
 *     ?GreGetGlyphIndicesW@@YAKPEAUHDC__@@PEBGKPEAGKHW4EntryPoint@RFONTOBJ@@@Z @ 0x1C014012C (-GreGetGlyphIndicesW@@YAKPEAUHDC__@@PEBGKPEAGKHW4EntryPoint@RFONTOBJ@@@Z.c)
 *     DxgkEngAcquireStableVisRgn @ 0x1C01596E0 (DxgkEngAcquireStableVisRgn.c)
 *     DxgkEngWatchVisRgnChange @ 0x1C0159D70 (DxgkEngWatchVisRgnChange.c)
 *     NtGdiLineTo @ 0x1C015A570 (NtGdiLineTo.c)
 *     ?SpDdDestroyFullscreenSprite@@YAJPEAUHDC__@@PEAX@Z @ 0x1C02657B0 (-SpDdDestroyFullscreenSprite@@YAJPEAUHDC__@@PEAX@Z.c)
 *     ?SpDdNotifyFullscreenSpriteUpdate@@YAJPEAUHDC__@@PEAX@Z @ 0x1C02658F8 (-SpDdNotifyFullscreenSpriteUpdate@@YAJPEAUHDC__@@PEAX@Z.c)
 *     GreSpDwmSyncCaptureSurfaceBits @ 0x1C0267980 (GreSpDwmSyncCaptureSurfaceBits.c)
 *     DxgkEngBltViaGDI @ 0x1C026E9F0 (DxgkEngBltViaGDI.c)
 *     DxgkEngColorFillViaGDI @ 0x1C026F230 (DxgkEngColorFillViaGDI.c)
 *     ??1XFERDCOBJ@@QEAA@XZ @ 0x1C02746A0 (--1XFERDCOBJ@@QEAA@XZ.c)
 *     ?GreDoBanding@@YAHPEAUHDC__@@HPEAU_POINTL@@PEAUtagSIZE@@@Z @ 0x1C0274AA8 (-GreDoBanding@@YAHPEAUHDC__@@HPEAU_POINTL@@PEAUtagSIZE@@@Z.c)
 *     ?GreDrawEscape@@YAHPEAUHDC__@@HAEBV?$umptr_r@D@@@Z @ 0x1C0274C3C (-GreDrawEscape@@YAHPEAUHDC__@@HAEBV-$umptr_r@D@@@Z.c)
 *     ?GreExtEscape@@YAHPEAUHDC__@@HHPEADH1W4EntryPoint@RFONTOBJ@@@Z @ 0x1C0274F5C (-GreExtEscape@@YAHPEAUHDC__@@HHPEADH1W4EntryPoint@RFONTOBJ@@@Z.c)
 *     ?GreGetPerBandInfo@@YAKPEAUHDC__@@PEAU_PERBANDINFO@@@Z @ 0x1C0275700 (-GreGetPerBandInfo@@YAKPEAUHDC__@@PEAU_PERBANDINFO@@@Z.c)
 *     ?GreGetUFI@@YAHPEAUHDC__@@PEAU_UNIVERSAL_FONT_ID@@PEAUtagDESIGNVECTOR@@PEAK33PEAPEAXW4EntryPoint@RFONTOBJ@@@Z @ 0x1C02757B0 (-GreGetUFI@@YAHPEAUHDC__@@PEAU_UNIVERSAL_FONT_ID@@PEAUtagDESIGNVECTOR@@PEAK33PEAPEAXW4EntryPoint.c)
 *     ?LookUpWndobjs@@YAHPEAVDCOBJ@@0PEAPEAUHDC__@@H@Z @ 0x1C0275C84 (-LookUpWndobjs@@YAHPEAVDCOBJ@@0PEAPEAUHDC__@@H@Z.c)
 *     ?ThreadCleanup@XFERDCOBJ@@SAXPEAX@Z @ 0x1C0275D80 (-ThreadCleanup@XFERDCOBJ@@SAXPEAX@Z.c)
 *     ?bEndDocInternal@@YAHPEAUHDC__@@KG@Z @ 0x1C0275DF4 (-bEndDocInternal@@YAHPEAUHDC__@@KG@Z.c)
 *     GreForceUFIMapping @ 0x1C02772CC (GreForceUFIMapping.c)
 *     NtGdiEndPage @ 0x1C0277AA0 (NtGdiEndPage.c)
 *     NtGdiStartPage @ 0x1C0278660 (NtGdiStartPage.c)
 *     ?bSetPreviewRectContent@@YAHPEAU_SPRITESTATE@@PEBU_RECTL@@@Z @ 0x1C027CD88 (-bSetPreviewRectContent@@YAHPEAU_SPRITESTATE@@PEBU_RECTL@@@Z.c)
 *     ?GreGetCharWidthW@@YAHPEAUHDC__@@IIPEAGKPEAXW4EntryPoint@RFONTOBJ@@@Z @ 0x1C028D0E4 (-GreGetCharWidthW@@YAHPEAUHDC__@@IIPEAGKPEAXW4EntryPoint@RFONTOBJ@@@Z.c)
 *     ?GreGetFontUnicodeRanges@@YAKPEAUHDC__@@PEAUtagGLYPHSET@@W4EntryPoint@RFONTOBJ@@@Z @ 0x1C028D43C (-GreGetFontUnicodeRanges@@YAKPEAUHDC__@@PEAUtagGLYPHSET@@W4EntryPoint@RFONTOBJ@@@Z.c)
 *     GreGetAspectRatioFilter @ 0x1C028DBC0 (GreGetAspectRatioFilter.c)
 *     GreSetFontXform @ 0x1C028DF48 (GreSetFontXform.c)
 *     GrePlgBlt @ 0x1C0290660 (GrePlgBlt.c)
 *     NtGdiTransparentBlt @ 0x1C02970E0 (NtGdiTransparentBlt.c)
 *     ?GreGetStringBitmapW@@YAIPEAUHDC__@@PEAGIPEAUSTRINGBITMAP@@IW4EntryPoint@RFONTOBJ@@@Z @ 0x1C029E53C (-GreGetStringBitmapW@@YAIPEAUHDC__@@PEAGIPEAUSTRINGBITMAP@@IW4EntryPoint@RFONTOBJ@@@Z.c)
 *     ?bPrepareDCForXfer@XFERDCOBJ@@SAHPEAUHDC__@@K@Z @ 0x1C02A719C (-bPrepareDCForXfer@XFERDCOBJ@@SAHPEAUHDC__@@K@Z.c)
 *     GreGetColorAdjustment @ 0x1C02A7610 (GreGetColorAdjustment.c)
 *     GreScaleRgn @ 0x1C02A77E4 (GreScaleRgn.c)
 *     GreScaleValues @ 0x1C02A794C (GreScaleValues.c)
 *     GreSetColorAdjustment @ 0x1C02A7A8C (GreSetColorAdjustment.c)
 *     ?NtGdiInvertRgnInternal@@YAHPEAUHDC__@@PEAUHRGN__@@@Z @ 0x1C02A7D44 (-NtGdiInvertRgnInternal@@YAHPEAUHDC__@@PEAUHRGN__@@@Z.c)
 *     NtGdiFillRgn @ 0x1C02A8780 (NtGdiFillRgn.c)
 *     NtGdiFrameRgn @ 0x1C02A8D40 (NtGdiFrameRgn.c)
 *     NtGdiInvertRgn @ 0x1C02A94E0 (NtGdiInvertRgn.c)
 *     NtGdiOffsetClipRgn @ 0x1C02A9630 (NtGdiOffsetClipRgn.c)
 *     NtGdiPtVisible @ 0x1C02A9890 (NtGdiPtVisible.c)
 *     GreGetHFONT @ 0x1C02A9AB4 (GreGetHFONT.c)
 *     NtGdiComputeXformCoefficients @ 0x1C02A9B10 (NtGdiComputeXformCoefficients.c)
 *     bUMPD @ 0x1C02A9D84 (bUMPD.c)
 *     ?GreLineTo@@YAHPEAUHDC__@@HH@Z @ 0x1C02AA0E8 (-GreLineTo@@YAHPEAUHDC__@@HH@Z.c)
 *     ?GrePolyBezierInternal@@YAHPEAUHDC__@@PEAUtagPOINT@@K@Z @ 0x1C02AA938 (-GrePolyBezierInternal@@YAHPEAUHDC__@@PEAUtagPOINT@@K@Z.c)
 *     ?GrePolyDraw@@YAHPEAUHDC__@@AEAV?$umptr_r@UtagPOINT@@@@AEAV?$umptr_r@E@@K@Z @ 0x1C02AAB28 (-GrePolyDraw@@YAHPEAUHDC__@@AEAV-$umptr_r@UtagPOINT@@@@AEAV-$umptr_r@E@@K@Z.c)
 *     GreAngleArc @ 0x1C02AB0F8 (GreAngleArc.c)
 *     GreMoveTo @ 0x1C02AB620 (GreMoveTo.c)
 *     GrePolyBezier @ 0x1C02AB7A0 (GrePolyBezier.c)
 *     GrePolyBezierTo @ 0x1C02AB8A0 (GrePolyBezierTo.c)
 *     GrePolyPolygon @ 0x1C02ABAE0 (GrePolyPolygon.c)
 *     GrePolyPolygonInternal @ 0x1C02ABBFC (GrePolyPolygonInternal.c)
 *     GrePolyPolyline @ 0x1C02ABDD0 (GrePolyPolyline.c)
 *     GrePolyPolylineInternal @ 0x1C02ABEEC (GrePolyPolylineInternal.c)
 *     GrePolylineTo @ 0x1C02AC120 (GrePolylineTo.c)
 *     GreRectangle @ 0x1C02AC350 (GreRectangle.c)
 *     NtGdiEllipse @ 0x1C02ACBD0 (NtGdiEllipse.c)
 *     NtGdiRectangle @ 0x1C02ACE40 (NtGdiRectangle.c)
 *     NtGdiRoundRect @ 0x1C02ACF60 (NtGdiRoundRect.c)
 *     GreResetDCInternal @ 0x1C02AD2F8 (GreResetDCInternal.c)
 *     GreGetMiterLimit @ 0x1C02C0290 (GreGetMiterLimit.c)
 *     GreSetMiterLimit @ 0x1C02C02FC (GreSetMiterLimit.c)
 *     NtGdiAbortPath @ 0x1C02C03A0 (NtGdiAbortPath.c)
 *     NtGdiBeginPath @ 0x1C02C0450 (NtGdiBeginPath.c)
 *     NtGdiCloseFigure @ 0x1C02C0560 (NtGdiCloseFigure.c)
 *     NtGdiEndPath @ 0x1C02C0630 (NtGdiEndPath.c)
 *     NtGdiFillPath @ 0x1C02C06C0 (NtGdiFillPath.c)
 *     NtGdiFlattenPath @ 0x1C02C0850 (NtGdiFlattenPath.c)
 *     NtGdiPathToRegion @ 0x1C02C0C10 (NtGdiPathToRegion.c)
 *     NtGdiSelectClipPath @ 0x1C02C0D70 (NtGdiSelectClipPath.c)
 *     NtGdiStrokeAndFillPath @ 0x1C02C0F20 (NtGdiStrokeAndFillPath.c)
 *     NtGdiStrokePath @ 0x1C02C10F0 (NtGdiStrokePath.c)
 *     NtGdiWidenPath @ 0x1C02C1260 (NtGdiWidenPath.c)
 *     ??1MDCOBJ@@QEAA@XZ @ 0x1C02C1418 (--1MDCOBJ@@QEAA@XZ.c)
 *     NtGdiSelectBrush @ 0x1C02C4320 (NtGdiSelectBrush.c)
 *     NtGdiSelectPen @ 0x1C02C4430 (NtGdiSelectPen.c)
 *     NtGdiArcInternal @ 0x1C02C6000 (NtGdiArcInternal.c)
 *     ?GreCheckBitmapBits@@YAHPEAUHDC__@@PEAXPEAU_DEVBITMAPINFO@@1PEAE@Z @ 0x1C02CD940 (-GreCheckBitmapBits@@YAHPEAUHDC__@@PEAXPEAU_DEVBITMAPINFO@@1PEAE@Z.c)
 *     ?GreCreateColorTransform@@YAPEAXPEAUHDC__@@PEAUtagLOGCOLORSPACEW@@PEAXK2K2K@Z @ 0x1C02CDB14 (-GreCreateColorTransform@@YAPEAXPEAUHDC__@@PEAUtagLOGCOLORSPACEW@@PEAXK2K2K@Z.c)
 *     ?GreDeleteColorTransform@@YAHPEAUHDC__@@PEAX@Z @ 0x1C02CDC84 (-GreDeleteColorTransform@@YAHPEAUHDC__@@PEAX@Z.c)
 *     ?GreIcmQueryBrushBitmap@@YAHPEAUHDC__@@PEAUHBRUSH__@@PEAUtagBITMAPINFO@@PEAXPEAK4PEAH@Z @ 0x1C02CDD50 (-GreIcmQueryBrushBitmap@@YAHPEAUHDC__@@PEAUHBRUSH__@@PEAUtagBITMAPINFO@@PEAXPEAK4PEAH@Z.c)
 *     ?GreIcmSetBrushBitmap@@YAHPEAUHDC__@@PEAUHBRUSH__@@PEAUtagBITMAPINFO@@PEAX@Z @ 0x1C02CDF60 (-GreIcmSetBrushBitmap@@YAHPEAUHDC__@@PEAUHBRUSH__@@PEAUtagBITMAPINFO@@PEAX@Z.c)
 *     NtGdiSetColorSpace @ 0x1C02CECC0 (NtGdiSetColorSpace.c)
 *     GreGetMapMode @ 0x1C02CF938 (GreGetMapMode.c)
 *     GreScaleWindowExtEx @ 0x1C02CF984 (GreScaleWindowExtEx.c)
 *     GreSetViewportOrg @ 0x1C02CFAD4 (GreSetViewportOrg.c)
 *     GreSetWindowOrg @ 0x1C02CFC6C (GreSetWindowOrg.c)
 *     NtGdiSetSizeDevice @ 0x1C02D0170 (NtGdiSetSizeDevice.c)
 *     NtGdiSetVirtualResolution @ 0x1C02D0210 (NtGdiSetVirtualResolution.c)
 *     NtGdiUpdateTransform @ 0x1C02D0320 (NtGdiUpdateTransform.c)
 *     GreCreateHalftonePalette @ 0x1C02D0A00 (GreCreateHalftonePalette.c)
 *     GreGetSystemPaletteEntries @ 0x1C02D0C60 (GreGetSystemPaletteEntries.c)
 *     GreRealizePalette @ 0x1C02D0D2C (GreRealizePalette.c)
 *     GreSetDIBColorTable @ 0x1C02D1410 (GreSetDIBColorTable.c)
 *     IsDCCurrentPalette @ 0x1C02D1AE0 (IsDCCurrentPalette.c)
 *     NtGdiResizePalette @ 0x1C02D1C70 (NtGdiResizePalette.c)
 *     NtGdiUpdateColors @ 0x1C02D1F70 (NtGdiUpdateColors.c)
 *     NtGdiExtFloodFill @ 0x1C02D3A10 (NtGdiExtFloodFill.c)
 *     NtGdiMakeInfoDC @ 0x1C02D4B90 (NtGdiMakeInfoDC.c)
 *     NtGdiSetPixel @ 0x1C02D6320 (NtGdiSetPixel.c)
 *     ?GrePolyTextOutW@@YAHPEAUHDC__@@PEAUtagPOLYTEXTW@@IKW4EntryPoint@RFONTOBJ@@@Z @ 0x1C02D6D24 (-GrePolyTextOutW@@YAHPEAUHDC__@@PEAUtagPOLYTEXTW@@IKW4EntryPoint@RFONTOBJ@@@Z.c)
 *     GreGetTextCharacterExtra @ 0x1C02D71C4 (GreGetTextCharacterExtra.c)
 *     GreSetTextAlign @ 0x1C02D7214 (GreSetTextAlign.c)
 *     GreSetTextCharacterExtra @ 0x1C02D72A8 (GreSetTextCharacterExtra.c)
 *     NtGdiSetTextJustification @ 0x1C02D7320 (NtGdiSetTextJustification.c)
 *     GreDescribePixelFormat @ 0x1C02D7518 (GreDescribePixelFormat.c)
 *     NtGdiSetPixelFormat @ 0x1C02D7710 (NtGdiSetPixelFormat.c)
 *     NtGdiSwapBuffers @ 0x1C02D79B0 (NtGdiSwapBuffers.c)
 *     GreSetGraphicsMode @ 0x1C02DD1FC (GreSetGraphicsMode.c)
 *     ?GreSetDIBitsInternal@@YAHPEAUHDC__@@PEAUHBITMAP__@@IIAEAV?$umptr_r@E@@PEAUtagBITMAPINFO@@IIPEAX@Z @ 0x1C02DD460 (-GreSetDIBitsInternal@@YAHPEAUHDC__@@PEAUHBITMAP__@@IIAEAV-$umptr_r@E@@PEAUtagBITMAPINFO@@IIPEAX.c)
 * Callees:
 *     <none>
 */

void __fastcall XDCOBJ::vUnlockFast(XDCOBJ *this)
{
  __int64 *v2; // rcx
  __int64 v3; // rdi
  struct _DC_ATTR *UserAttr; // rax
  int v5; // [rsp+30h] [rbp+8h] BYREF

  if ( *((_DWORD *)this + 2) && (*(_DWORD *)(*(_QWORD *)this + 44LL) & 2) != 0 )
  {
    if ( !*((_DWORD *)this + 3) )
    {
      UserAttr = XDCOBJ::GetUserAttr(this);
      if ( UserAttr )
        DC::RestoreAttributes(*(DC **)this, UserAttr);
    }
    *(_DWORD *)(*(_QWORD *)this + 44LL) &= ~2u;
    *((_DWORD *)this + 2) = 0;
  }
  v2 = *(__int64 **)this;
  v5 = 0;
  v3 = *v2;
  HmgDecrementExclusiveReferenceCountEx(v2, *((unsigned int *)this + 3), &v5);
  if ( v5 )
    GrepDeleteDC(v3, 0x2000000LL);
}
