/*
 * XREFs of DxgkSkipProcessingDisplayBatches @ 0x1400272E8
 * Callers:
 *     DxgkProcessDisplayCalloutBatch @ 0x14038E4E0 (DxgkProcessDisplayCalloutBatch.c)
 * Callees:
 *     ?Acquire@DXGAUTOMUTEX@@QEAAXXZ @ 0x14000A0F0 (-Acquire@DXGAUTOMUTEX@@QEAAXXZ.c)
 *     ??1DXGPROCESSCOPYPROTECTIONMUTEX@@QEAA@XZ @ 0x14000B9E0 (--1DXGPROCESSCOPYPROTECTIONMUTEX@@QEAA@XZ.c)
 *     ??0DXGAUTOMUTEX@@QEAA@QEAVDXGFASTMUTEX@@E@Z @ 0x140028A90 (--0DXGAUTOMUTEX@@QEAA@QEAVDXGFASTMUTEX@@E@Z.c)
 */

char DxgkSkipProcessingDisplayBatches()
{
  DISPLAY_MUX_MGR *v0; // rbx
  _BYTE v2[24]; // [rsp+20h] [rbp-18h] BYREF

  v0 = qword_140161380;
  DXGAUTOMUTEX::DXGAUTOMUTEX((DXGAUTOMUTEX *)v2, (DISPLAY_MUX_MGR *)((char *)qword_140161380 + 16), 0);
  DXGAUTOMUTEX::Acquire((DXGAUTOMUTEX *)v2);
  LOBYTE(v0) = *((_BYTE *)v0 + 112);
  DXGPROCESSCOPYPROTECTIONMUTEX::~DXGPROCESSCOPYPROTECTIONMUTEX((DXGPROCESSCOPYPROTECTIONMUTEX *)v2);
  return (char)v0;
}
