/*
 * XREFs of ??_EDMMVIDPNTOPOLOGY@@UEAAPEAXI@Z @ 0x1C005C9E0
 * Callers:
 *     ??_EDMMVIDPNTOPOLOGY@@WDI@EAAPEAXI@Z @ 0x1C0027880 (--_EDMMVIDPNTOPOLOGY@@WDI@EAAPEAXI@Z.c)
 *     ??_EDMMVIDPNTOPOLOGY@@WKA@EAAPEAXI@Z @ 0x1C0027890 (--_EDMMVIDPNTOPOLOGY@@WKA@EAAPEAXI@Z.c)
 *     ??_EDMMVIDPNTOPOLOGY@@WLA@EAAPEAXI@Z @ 0x1C00278A0 (--_EDMMVIDPNTOPOLOGY@@WLA@EAAPEAXI@Z.c)
 * Callees:
 *     ??1DMMVIDPNTOPOLOGY@@UEAA@XZ @ 0x1C0008D2C (--1DMMVIDPNTOPOLOGY@@UEAA@XZ.c)
 */

DMMVIDPNTOPOLOGY *__fastcall DMMVIDPNTOPOLOGY::`vector deleting destructor'(DMMVIDPNTOPOLOGY *P, char a2)
{
  DMMVIDPNTOPOLOGY::~DMMVIDPNTOPOLOGY(P);
  if ( (a2 & 1) != 0 && P )
    ExFreePoolWithTag(P, 0);
  return P;
}
