/*
 * XREFs of ?_Add_vtordisp2@?$basic_ios@GU?$char_traits@G@std@@@std@@UEAAXXZ @ 0x180001760
 * Callers:
 *     ?s_ThreadProc@CThread@ComTaskPool@Internal@Windows@@CAKPEAX@Z @ 0x180004EC0 (-s_ThreadProc@CThread@ComTaskPool@Internal@Windows@@CAKPEAX@Z.c)
 *     ?_Add_vtordisp1@?$basic_istream@GU?$char_traits@G@std@@@std@@$4PPPPPPPM@HI@EAAXXZ @ 0x180037EB0 (-_Add_vtordisp1@-$basic_istream@GU-$char_traits@G@std@@@std@@$4PPPPPPPM@HI@EAAXXZ.c)
 *     ?_Add_vtordisp2@?$basic_ostream@GU?$char_traits@G@std@@@std@@$4PPPPPPPM@A@EAAXXZ @ 0x180037EE0 (-_Add_vtordisp2@-$basic_ostream@GU-$char_traits@G@std@@@std@@$4PPPPPPPM@A@EAAXXZ.c)
 *     ?_Add_vtordisp1@?$basic_istream@GU?$char_traits@G@std@@@std@@$4PPPPPPPM@IA@EAAXXZ @ 0x18003F7C0 (-_Add_vtordisp1@-$basic_istream@GU-$char_traits@G@std@@@std@@$4PPPPPPPM@IA@EAAXXZ.c)
 *     ?_Add_vtordisp1@?$basic_istream@GU?$char_traits@G@std@@@std@@$4PPPPPPPM@7EAAXXZ @ 0x18003F800 (-_Add_vtordisp1@-$basic_istream@GU-$char_traits@G@std@@@std@@$4PPPPPPPM@7EAAXXZ.c)
 *     _std::make_shared_ContentDeliveryManager::Background::CorrelationVectorWrapper__::_1_::dtor$3 @ 0x18007186C (_std--make_shared_ContentDeliveryManager--Background--CorrelationVectorWrapper__--_1_--dtor$3.c)
 *     _std::make_shared_CreativeFramework::Health::details::BaseEventsWithEvaluation_1__std::basic_string_unsigned_short_std::char_traits_unsigned_short__std::allocator_unsigned_short____const_&___ptr64_bool_const_&___ptr64__::_1_::dtor$3 @ 0x180071B7E (_std--make_shared_CreativeFramework--Health--details--BaseEventsWithEvaluation_1__s_ea_180071B7E.c)
 *     _std::make_shared_ContentManagement::TargetedContent::Internal::SubscriptionManagerImpl::SubscriptionMapValue_unsigned_short_const_____ptr64__FILETIME__::_1_::dtor$3 @ 0x180072289 (_std--make_shared_ContentManagement--TargetedContent--Internal--SubscriptionManager_ea_180072289.c)
 *     _Microsoft::WRL::Details::MakeAndInitialize_ContentManagement::TargetedContent::Internal::SubscriptionManagerImpl_ContentManagement::TargetedContent::Internal::ISubscriptionManager__::_1_::dtor$2 @ 0x1800722E7 (_Microsoft--WRL--Details--MakeAndInitialize_ContentManagement--TargetedContent--Int_ea_1800722E7.c)
 *     _Windows::Services::TargetedContent::Internal::TargetedContentActionStatics::CreateAction_::_1_::dtor$4 @ 0x1800725A9 (_Windows--Services--TargetedContent--Internal--TargetedContentActionStatics--Create_ea_1800725A9.c)
 *     _std::_Tree_buy_std::pair_std::basic_string_unsigned_short_std::char_traits_unsigned_short__std::allocator_unsigned_short____const__std::basic_string_unsigned_short_std::char_traits_unsigned_short__std::allocator_unsigned_short______std::allocator_std::pair_std::basic_string_unsigned_short_std::char_traits_unsigned_short__std::allocator_unsigned_short____const__std::basic_string_unsigned_short_std::char_traits_unsigned_short__std::allocator_unsigned_short_________::_Buynode_std::pair_unsigned_short_const_____ptr64_unsigned_short_const_____ptr64____::_1_::dtor$0 @ 0x18007277C (_std--_Tree_buy_std--pair_std--basic_string_unsigned_short_std--char_traits_unsigne_ea_18007277C.c)
 *     _std::_Tree_buy_std::pair_std::basic_string_unsigned_short_std::char_traits_unsigned_short__std::allocator_unsigned_short____const__std::basic_string_unsigned_short_std::char_traits_unsigned_short__std::allocator_unsigned_short______std::allocator_std::pair_std::basic_string_unsigned_short_std::char_traits_unsigned_short__std::allocator_unsigned_short____const__std::basic_string_unsigned_short_std::char_traits_unsigned_short__std::allocator_unsigned_short_________::_Buynode_std::pair_std::basic_string_unsigned_short_std::char_traits_unsigned_short__std::allocator_unsigned_short____const__std::basic_string_unsigned_short_std::char_traits_unsigned_short__std::allocator_unsigned_short______&___ptr64__::_1_::dtor$0 @ 0x180072851 (_std--_Tree_buy_std--pair_std--basic_string_unsigned_short_std--char_traits_unsigne_ea_180072851.c)
 *     _std::_Ref_count_obj_CreativeFramework::RuleSetHandlers::CreativeRule_::_Ref_count_obj_CreativeFramework::RuleSetHandlers::CreativeRule__wchar_t_const_____ptr64_wchar_t_const_____ptr64_wchar_t_const_____ptr64__::_1_::dtor$1 @ 0x180072DB0 (_std--_Ref_count_obj_CreativeFramework--RuleSetHandlers--CreativeRule_--_Ref_count__ea_180072DB0.c)
 *     _wistd::_Func_impl_wistd::_Callable_obj__lambda_54b1615c74727b96cfd9244fd3177ed2__0__wistd::details::function_allocator_wistd::_Func_class_void_long_Windows::Storage::IStorageFolder_____ptr64_wistd::_Nil_wistd::_Nil_wistd::_Nil_wistd::_Nil_wistd::_Nil____void_long_Windows::Storage::IStorageFolder_____ptr64_wistd::_Nil_wistd::_Nil_wistd::_Nil_wistd::_Nil_wistd::_Nil_::_Copy_::_1_::dtor$0 @ 0x180073580 (_wistd--_Func_impl_wistd--_Callable_obj__lambda_54b1615c74727b96cfd9244fd3177ed2__0__wistd--deta.c)
 *     _std::_Tree_buy_std::pair_std::basic_string_wchar_t_std::char_traits_wchar_t__std::allocator_wchar_t____const__std::basic_string_wchar_t_std::char_traits_wchar_t__std::allocator_wchar_t______std::allocator_std::pair_std::basic_string_wchar_t_std::char_traits_wchar_t__std::allocator_wchar_t____const__std::basic_string_wchar_t_std::char_traits_wchar_t__std::allocator_wchar_t_________::_Buynode_std::pair_wchar_t_____ptr64_wchar_t_____ptr64____::_1_::dtor$0 @ 0x180073740 (_std--_Tree_buy_std--pair_std--basic_string_wchar_t_std--char_traits_wchar_t__std--allocator_wch.c)
 *     _std::make_shared_CreativeFramework::Actions::AppUninstallService_wchar_t_const_____ptr64__::_1_::dtor$3 @ 0x180073BAF (_std--make_shared_CreativeFramework--Actions--AppUninstallService_wchar_t_const_____ea_180073BAF.c)
 *     _std::_Ref_count_obj_CreativeFramework::Actions::TaskbarPinService_::_Ref_count_obj_CreativeFramework::Actions::TaskbarPinService__wchar_t_const_____ptr64_wchar_t_const_____ptr64_bool__::_1_::dtor$1 @ 0x180073C0D (_std--_Ref_count_obj_CreativeFramework--Actions--TaskbarPinService_--_Ref_count_obj_ea_180073C0D.c)
 *     _std::make_shared_CreativeFramework::Actions::SwapStartTileService_wchar_t_const_____ptr64_wchar_t_const_____ptr64__::_1_::dtor$3 @ 0x180073E4D (_std--make_shared_CreativeFramework--Actions--SwapStartTileService_wchar_t_const____ea_180073E4D.c)
 *     _std::_Ref_count_obj_CreativeFramework::Actions::PinToStartService_::_Ref_count_obj_CreativeFramework::Actions::PinToStartService__wchar_t_const_____ptr64_wchar_t_const_____ptr64_wchar_t_const_____ptr64_bool__::_1_::dtor$1 @ 0x180073F69 (_std--_Ref_count_obj_CreativeFramework--Actions--PinToStartService_--_Ref_count_obj_ea_180073F69.c)
 *     _std::make_shared_CreativeFramework::Actions::SetDefaultApplicationService_wchar_t_const_____ptr64_wchar_t_const_____ptr64_wchar_t_const_____ptr64__::_1_::dtor$3 @ 0x1800740DA (_std--make_shared_CreativeFramework--Actions--SetDefaultApplicationService_wchar_t__ea_1800740DA.c)
 *     _std::make_shared_CreativeFramework::Actions::LaunchAppByIdService_wchar_t_const_____ptr64__::_1_::dtor$3 @ 0x18007431B (_std--make_shared_CreativeFramework--Actions--LaunchAppByIdService_wchar_t_const____ea_18007431B.c)
 *     _std::make_shared_CreativeFramework::Actions::TaskbarPinService_wchar_t_const_____ptr64_bool__::_1_::dtor$3 @ 0x180074492 (_std--make_shared_CreativeFramework--Actions--TaskbarPinService_wchar_t_const_____p_ea_180074492.c)
 *     _std::make_shared_CreativeFramework::Actions::NotificationManagerService_CreativeFramework::Actions::ActionContext_const_&___ptr64_std::map_std::basic_string_wchar_t_std::char_traits_wchar_t__std::allocator_wchar_t____std::basic_string_wchar_t_std::char_traits_wchar_t__std::allocator_wchar_t____std::less_std::basic_string_wchar_t_std::char_traits_wchar_t__std::allocator_wchar_t______std::allocator_std::pair_std::basic_string_wchar_t_std::char_traits_wchar_t__std::allocator_wchar_t____const__std::basic_string_wchar_t_std::char_traits_wchar_t__std::allocator_wchar_t__________const_&___ptr64__::_1_::dtor$3 @ 0x180074768 (_std--make_shared_CreativeFramework--Actions--NotificationManagerService_CreativeFr_ea_180074768.c)
 *     _std::_Tree_buy_std::pair_std::basic_string_wchar_t_std::char_traits_wchar_t__std::allocator_wchar_t____const__std::basic_string_wchar_t_std::char_traits_wchar_t__std::allocator_wchar_t______std::allocator_std::pair_std::basic_string_wchar_t_std::char_traits_wchar_t__std::allocator_wchar_t____const__std::basic_string_wchar_t_std::char_traits_wchar_t__std::allocator_wchar_t_________::_Buynode_std::pair_std::basic_string_wchar_t_std::char_traits_wchar_t__std::allocator_wchar_t____const__std::basic_string_wchar_t_std::char_traits_wchar_t__std::allocator_wchar_t______&___ptr64__::_1_::dtor$0 @ 0x1800747D2 (_std--_Tree_buy_std--pair_std--basic_string_wchar_t_std--char_traits_wchar_t__std--_ea_1800747D2.c)
 *     _std::make_shared_CreativeFramework::Actions::PublishWindowsTipService_wchar_t_const_____ptr64_wchar_t_const_____ptr64__::_1_::dtor$3 @ 0x180074936 (_std--make_shared_CreativeFramework--Actions--PublishWindowsTipService_wchar_t_cons_ea_180074936.c)
 *     _std::_Ref_count_obj_CreativeFramework::Actions::PublishSystemStateService_::_Ref_count_obj_CreativeFramework::Actions::PublishSystemStateService__std::basic_string_wchar_t_std::char_traits_wchar_t__std::allocator_wchar_t____std::basic_string_wchar_t_std::char_traits_wchar_t__std::allocator_wchar_t______::_1_::dtor$1 @ 0x1800749D4 (_std--_Ref_count_obj_CreativeFramework--Actions--PublishSystemStateService_--_Ref_c_ea_1800749D4.c)
 *     _std::_List_buy_std::basic_string_wchar_t_std::char_traits_wchar_t__std::allocator_wchar_t____std::allocator_std::basic_string_wchar_t_std::char_traits_wchar_t__std::allocator_wchar_t_______::_Buynode_std::basic_string_wchar_t_std::char_traits_wchar_t__std::allocator_wchar_t____const_&___ptr64__::_1_::dtor$0 @ 0x180074DFC (_std--_List_buy_std--basic_string_wchar_t_std--char_traits_wchar_t__std--allocator_wchar_t____st.c)
 *     _std::make_shared_CreativeFramework::CommonHelper::SettingsContainer_Windows::Storage::IApplicationDataContainer_____ptr64_&___ptr64__::_1_::dtor$3 @ 0x1800750F0 (_std--make_shared_CreativeFramework--CommonHelper--SettingsContainer_Windows--Stora_ea_1800750F0.c)
 *     _std::_Tree_buy_std::pair_std::basic_string_wchar_t_std::char_traits_wchar_t__std::allocator_wchar_t____const__std::shared_ptr_CreativeFramework::CommonHelper::ISettingsContainer____std::allocator_std::pair_std::basic_string_wchar_t_std::char_traits_wchar_t__std::allocator_wchar_t____const__std::shared_ptr_CreativeFramework::CommonHelper::ISettingsContainer_______::_Buynode_std::pair_std::basic_string_wchar_t_std::char_traits_wchar_t__std::allocator_wchar_t____const__std::shared_ptr_CreativeFramework::CommonHelper::ISettingsContainer____&___ptr64__::_1_::dtor$0 @ 0x1800751CD (_std--_Tree_buy_std--pair_std--basic_string_wchar_t_std--char_traits_wchar_t__std--_ea_1800751CD.c)
 * Callees:
 *     <none>
 */

void std::basic_ios<unsigned short>::_Add_vtordisp2()
{
  ;
}
