/*
 * XREFs of ??_GDXGPROTECTEDSESSION@@QEAAPEAXI@Z @ 0x1C0048DFC
 * Callers:
 *     ?CreateProtectedSession@ADAPTER_DISPLAY@@QEAAJPEAPEAVDXGSYNCOBJECT@@PEAPEAXI1IPEAPEAVDXGPROTECTEDSESSION@@@Z @ 0x1C02881B0 (-CreateProtectedSession@ADAPTER_DISPLAY@@QEAAJPEAPEAVDXGSYNCOBJECT@@PEAPEAXI1IPEAPEAVDXGPROTECTE.c)
 *     ?DestroyProtectedSession@ADAPTER_DISPLAY@@QEAAXPEAVDXGPROTECTEDSESSION@@@Z @ 0x1C028833C (-DestroyProtectedSession@ADAPTER_DISPLAY@@QEAAXPEAVDXGPROTECTEDSESSION@@@Z.c)
 * Callees:
 *     ??1DXGPROTECTEDSESSION@@QEAA@XZ @ 0x1C0048CC8 (--1DXGPROTECTEDSESSION@@QEAA@XZ.c)
 */

struct DXGSYNCOBJECT **__fastcall DXGPROTECTEDSESSION::`scalar deleting destructor'(
        struct DXGSYNCOBJECT **P,
        __int64 a2)
{
  DXGPROTECTEDSESSION::~DXGPROTECTEDSESSION(P, a2);
  if ( P )
    ExFreePoolWithTag(P, 0);
  return P;
}
