/*
 * XREFs of ??_GDXGADAPTER@@QEAAPEAXI@Z @ 0x1C0027EE4
 * Callers:
 *     ?CreateAdapter@DXGGLOBAL@@QEAAJPEAU_DEVICE_OBJECT@@PEAPEAVDXGADAPTER@@PEAU_DXGK_ADAPTER_CAPS@@PEAU_DXGK_DISPLAY_SCENARIO_CONTEXT@@@Z @ 0x1C0119870 (-CreateAdapter@DXGGLOBAL@@QEAAJPEAU_DEVICE_OBJECT@@PEAPEAVDXGADAPTER@@PEAU_DXGK_ADAPTER_CAPS@@PE.c)
 *     ?DestroyAdapter@DXGGLOBAL@@QEAAXPEAVDXGADAPTER@@@Z @ 0x1C01A9EA0 (-DestroyAdapter@DXGGLOBAL@@QEAAXPEAVDXGADAPTER@@@Z.c)
 * Callees:
 *     ??3@YAXPEAX@Z @ 0x1C00A3070 (--3@YAXPEAX@Z.c)
 *     ??1DXGADAPTER@@QEAA@XZ @ 0x1C0170ABC (--1DXGADAPTER@@QEAA@XZ.c)
 */

DXGADAPTER *__fastcall DXGADAPTER::`scalar deleting destructor'(DXGADAPTER *this)
{
  DXGADAPTER::~DXGADAPTER(this);
  operator delete(this);
  return this;
}
