/*
 * XREFs of ?reset@?$auto_ptr@VDXGFASTMUTEX@@@@QEAAXPEAVDXGFASTMUTEX@@@Z @ 0x1C0013E30
 * Callers:
 *     ??0Lockable@@QEAA@XZ @ 0x1C01225AC (--0Lockable@@QEAA@XZ.c)
 *     ??0DXGDISPLAYMANAGEROBJECT@@QEAA@_N@Z @ 0x1C01D9168 (--0DXGDISPLAYMANAGEROBJECT@@QEAA@_N@Z.c)
 *     ??0DXGDISPLAYMANAGERSOURCEOBJECT@@QEAA@PEAVDXGDISPLAYMANAGEROBJECT@@U_LUID@@I@Z @ 0x1C01D9258 (--0DXGDISPLAYMANAGERSOURCEOBJECT@@QEAA@PEAVDXGDISPLAYMANAGEROBJECT@@U_LUID@@I@Z.c)
 * Callees:
 *     ??_GDXGFASTMUTEX@@QEAAPEAXI@Z @ 0x1C0007DC4 (--_GDXGFASTMUTEX@@QEAAPEAXI@Z.c)
 */

DXGFASTMUTEX *__fastcall auto_ptr<DXGFASTMUTEX>::reset(DXGFASTMUTEX **a1, DXGFASTMUTEX *a2)
{
  DXGFASTMUTEX *v4; // rcx
  DXGFASTMUTEX *result; // rax

  v4 = *a1;
  if ( a2 != v4 && v4 )
    result = DXGFASTMUTEX::`scalar deleting destructor'(v4);
  *a1 = a2;
  return result;
}
