/*
 * XREFs of ??1?$AutoValue@PEAUIOnlineIdServiceTicketRequest@OnlineId@Authentication@Security@Windows@@U?$DefaultLifetimeTraits@PEAVOnlineIdServiceTicketRequest@OnlineId@Authentication@Security@Windows@@@Internal@Collections@Foundation@5@@XWinRT@@QEAA@XZ @ 0x18001A864
 * Callers:
 *     _Windows::Foundation::Collections::Internal::Vector_Windows::Security::Authentication::OnlineId::OnlineIdServiceTicketRequest___Windows::Foundation::Collections::Internal::DefaultEqualityPredicate_Windows::Security::Authentication::OnlineId::OnlineIdServiceTicketRequest____Windows::Foundation::Collections::Internal::DefaultLifetimeTraits_Windows::Security::Authentication::OnlineId::OnlineIdServiceTicketRequest____Windows::Foundation::Collections::Internal::DefaultVectorOptions_Windows::Security::Authentication::OnlineId::OnlineIdServiceTicketRequest_____::SetAt_::_1_::dtor$0 @ 0x1800CF878 (_Windows--Foundation--Collections--Internal--Vector_Windows--Security--Authenticati_ea_1800CF878.c)
 *     _Windows::Foundation::Collections::Internal::Vector_Windows::Security::Authentication::OnlineId::OnlineIdServiceTicketRequest___Windows::Foundation::Collections::Internal::DefaultEqualityPredicate_Windows::Security::Authentication::OnlineId::OnlineIdServiceTicketRequest____Windows::Foundation::Collections::Internal::DefaultLifetimeTraits_Windows::Security::Authentication::OnlineId::OnlineIdServiceTicketRequest____Windows::Foundation::Collections::Internal::DefaultVectorOptions_Windows::Security::Authentication::OnlineId::OnlineIdServiceTicketRequest_____::SetAt_::_1_::dtor$1 @ 0x1800CF88A (_Windows--Foundation--Collections--Internal--Vector_Windows--Security--Authenticati_ea_1800CF88A.c)
 *     _Windows::Foundation::Collections::Internal::Vector_Windows::ApplicationModel::Store::Preview::InstallControl::Internal::InstallAppInfo___Windows::Foundation::Collections::Internal::DefaultEqualityPredicate_Windows::ApplicationModel::Store::Preview::InstallControl::Internal::InstallAppInfo____Windows::Foundation::Collections::Internal::DefaultLifetimeTraits_Windows::ApplicationModel::Store::Preview::InstallControl::Internal::InstallAppInfo____Windows::Foundation::Collections::Internal::DefaultVectorOptions_Windows::ApplicationModel::Store::Preview::InstallControl::Internal::InstallAppInfo_____::SetAt_::_1_::dtor$0 @ 0x1800D263C (_Windows--Foundation--Collections--Internal--Vector_Windows--ApplicationModel--Stor_ea_1800D263C.c)
 *     _Windows::Foundation::Collections::Internal::Vector_Windows::ApplicationModel::Store::Preview::InstallControl::Internal::InstallAppInfo___Windows::Foundation::Collections::Internal::DefaultEqualityPredicate_Windows::ApplicationModel::Store::Preview::InstallControl::Internal::InstallAppInfo____Windows::Foundation::Collections::Internal::DefaultLifetimeTraits_Windows::ApplicationModel::Store::Preview::InstallControl::Internal::InstallAppInfo____Windows::Foundation::Collections::Internal::DefaultVectorOptions_Windows::ApplicationModel::Store::Preview::InstallControl::Internal::InstallAppInfo_____::SetAt_::_1_::dtor$1 @ 0x1800D264E (_Windows--Foundation--Collections--Internal--Vector_Windows--ApplicationModel--Stor_ea_1800D264E.c)
 *     _Windows::Foundation::Collections::Internal::Vector_ContentManagement::AppInstallInfoRecord___Windows::Foundation::Collections::Internal::DefaultEqualityPredicate_ContentManagement::AppInstallInfoRecord____Windows::Foundation::Collections::Internal::DefaultLifetimeTraits_ContentManagement::AppInstallInfoRecord____Windows::Foundation::Collections::Internal::VectorOptions_ContentManagement::AppInstallInfoRecord___0_1_0___::IndexOfInternal_::_1_::dtor$2 @ 0x1800D274E (_Windows--Foundation--Collections--Internal--Vector_ContentManagement--AppInstallIn_ea_1800D274E.c)
 *     _Windows::Foundation::Collections::Internal::Vector_Windows::Services::TargetedContent::Internal::TargetedContentTriggerStateTransition___Windows::Foundation::Collections::Internal::DefaultEqualityPredicate_Windows::Services::TargetedContent::Internal::TargetedContentTriggerStateTransition____Windows::Foundation::Collections::Internal::DefaultLifetimeTraits_Windows::Services::TargetedContent::Internal::TargetedContentTriggerStateTransition____Windows::Foundation::Collections::Internal::DefaultVectorOptions_Windows::Services::TargetedContent::Internal::TargetedContentTriggerStateTransition_____::SetAt_::_1_::dtor$0 @ 0x1800D295E (_Windows--Foundation--Collections--Internal--Vector_Windows--Services--TargetedCont_ea_1800D295E.c)
 *     _Windows::Foundation::Collections::Internal::Vector_Windows::Services::TargetedContent::Internal::TargetedContentTriggerStateTransition___Windows::Foundation::Collections::Internal::DefaultEqualityPredicate_Windows::Services::TargetedContent::Internal::TargetedContentTriggerStateTransition____Windows::Foundation::Collections::Internal::DefaultLifetimeTraits_Windows::Services::TargetedContent::Internal::TargetedContentTriggerStateTransition____Windows::Foundation::Collections::Internal::DefaultVectorOptions_Windows::Services::TargetedContent::Internal::TargetedContentTriggerStateTransition_____::SetAt_::_1_::dtor$1 @ 0x1800D2970 (_Windows--Foundation--Collections--Internal--Vector_Windows--Services--TargetedCont_ea_1800D2970.c)
 *     _Windows::Foundation::Collections::Internal::Vector_Windows::Services::TargetedContent::Internal::TargetedContentTriggerStateTransition___Windows::Foundation::Collections::Internal::DefaultEqualityPredicate_Windows::Services::TargetedContent::Internal::TargetedContentTriggerStateTransition____Windows::Foundation::Collections::Internal::DefaultLifetimeTraits_Windows::Services::TargetedContent::Internal::TargetedContentTriggerStateTransition____Windows::Foundation::Collections::Internal::VectorOptions_Windows::Services::TargetedContent::Internal::TargetedContentTriggerStateTransition___0_1_0___::IndexOfInternal_::_1_::dtor$2 @ 0x1800D2994 (_Windows--Foundation--Collections--Internal--Vector_Windows--Services--TargetedCont_ea_1800D2994.c)
 *     _Windows::Foundation::Collections::Internal::Vector_Windows::Services::TargetedContent::Internal::TargetedContentTriggerInternal___Windows::Foundation::Collections::Internal::DefaultEqualityPredicate_Windows::Services::TargetedContent::Internal::TargetedContentTriggerInternal____Windows::Foundation::Collections::Internal::DefaultLifetimeTraits_Windows::Services::TargetedContent::Internal::TargetedContentTriggerInternal____Windows::Foundation::Collections::Internal::VectorOptions_Windows::Services::TargetedContent::Internal::TargetedContentTriggerInternal___0_1_0___::IndexOfInternal_::_1_::dtor$2 @ 0x1800D310E (_Windows--Foundation--Collections--Internal--Vector_Windows--Services--TargetedCont_ea_1800D310E.c)
 * Callees:
 *     _guard_dispatch_icall_nop @ 0x1800CEB10 (_guard_dispatch_icall_nop.c)
 */

__int64 __fastcall XWinRT::AutoValue<Windows::Security::Authentication::OnlineId::IOnlineIdServiceTicketRequest *,Windows::Foundation::Collections::Internal::DefaultLifetimeTraits<Windows::Security::Authentication::OnlineId::OnlineIdServiceTicketRequest *>>::~AutoValue<Windows::Security::Authentication::OnlineId::IOnlineIdServiceTicketRequest *,Windows::Foundation::Collections::Internal::DefaultLifetimeTraits<Windows::Security::Authentication::OnlineId::OnlineIdServiceTicketRequest *>>(
        __int64 *a1)
{
  __int64 v2; // rcx
  __int64 result; // rax

  v2 = *a1;
  if ( v2 )
  {
    result = (*(__int64 (__fastcall **)(__int64))(*(_QWORD *)v2 + 16LL))(v2);
    *a1 = 0LL;
  }
  return result;
}
