/*
 * XREFs of __security_check_cookie @ 0x140045CC0
 * Callers:
 *     ??$Write@U?$_tlgWrapperByVal@$07@@U?$_tlgWrapperByVal@$03@@U2@U?$_tlgWrapperByVal@$00@@U?$_tlgWrapperByRef@$0BA@@@U_tlgWrapperBinary@@U1@U3@U5@U1@U3@U5@U1@U3@U5@U1@U3@U5@U1@U3@U5@U1@U3@U5@U1@U3@U5@U1@U3@U5@U2@U3@@?$_tlgWriteTemplate@$$A6AJPEBU_tlgProvider_t@@PEBXPEBU_GUID@@2IPEAU_EVENT_DATA_DESCRIPTOR@@@Z$1?_tlgWriteTransfer_EtwWriteTransfer@@YAJ0122I3@ZPEBU2@PEBU2@@@SAJPEBU_tlgProvider_t@@PEBXPEBU_GUID@@2AEBU?$_tlgWrapperByVal@$07@@AEBU?$_tlgWrapperByVal@$03@@4AEBU?$_tlgWrapperByVal@$00@@AEBU?$_tlgWrapperByRef@$0BA@@@AEBU_tlgWrapperBinary@@35735735735735735735735745@Z @ 0x1400010AC (--$Write@U-$_tlgWrapperByVal@$07@@U-$_tlgWrapperByVal@$03@@U2@U-$_tlgWrapperByVal@$00@@U-$_tlgWr.c)
 *     McTemplateK0_EtwWriteTransfer @ 0x140001A94 (McTemplateK0_EtwWriteTransfer.c)
 *     McTemplateK0pnq_EtwWriteTransfer @ 0x140001AD8 (McTemplateK0pnq_EtwWriteTransfer.c)
 *     McTemplateK0ppqzznhUR6zuqQ6qqqqqqqqqsssuuxttqq_EtwWriteTransfer @ 0x140001B54 (McTemplateK0ppqzznhUR6zuqQ6qqqqqqqqqsssuuxttqq_EtwWriteTransfer.c)
 *     McTemplateK0ppuq_EtwWriteTransfer @ 0x140001F58 (McTemplateK0ppuq_EtwWriteTransfer.c)
 *     McTemplateK0pq_EtwWriteTransfer @ 0x140001FE8 (McTemplateK0pq_EtwWriteTransfer.c)
 *     McTemplateK0pqn_EtwWriteTransfer @ 0x140002058 (McTemplateK0pqn_EtwWriteTransfer.c)
 *     McTemplateK0pqun_EtwWriteTransfer @ 0x1400020D4 (McTemplateK0pqun_EtwWriteTransfer.c)
 *     McTemplateK0pquuuuuuuuxqqqqqqqsss_EtwWriteTransfer @ 0x140002164 (McTemplateK0pquuuuuuuuxqqqqqqqsss_EtwWriteTransfer.c)
 *     McTemplateK0pqz_EtwWriteTransfer @ 0x1400023C8 (McTemplateK0pqz_EtwWriteTransfer.c)
 *     wil_details_RecordCachedUsage @ 0x140002778 (wil_details_RecordCachedUsage.c)
 *     HUBHTX_CompleteGetPortStatusWithFailedStatus @ 0x1400032F4 (HUBHTX_CompleteGetPortStatusWithFailedStatus.c)
 *     HUBHTX_CompleteGetPortStatusWithPortStatusResult @ 0x1400033D4 (HUBHTX_CompleteGetPortStatusWithPortStatusResult.c)
 *     HUBHTX_SendInterruptTransfer @ 0x140005C54 (HUBHTX_SendInterruptTransfer.c)
 *     McTemplateK0pqhh_EtwWriteTransfer @ 0x140006790 (McTemplateK0pqhh_EtwWriteTransfer.c)
 *     McTemplateK0pqqq_EtwWriteTransfer @ 0x140006824 (McTemplateK0pqqq_EtwWriteTransfer.c)
 *     McTemplateK0qhhhqhhh_EtwWriteTransfer @ 0x1400068B4 (McTemplateK0qhhhqhhh_EtwWriteTransfer.c)
 *     HUBPARENT_GetInfoFromParentUsingParentIoctl @ 0x14000761C (HUBPARENT_GetInfoFromParentUsingParentIoctl.c)
 *     HUBPARENT_ResetHub @ 0x140007B10 (HUBPARENT_ResetHub.c)
 *     HUBPARENT_ResetInterruptPipe @ 0x140007EDC (HUBPARENT_ResetInterruptPipe.c)
 *     HUBPARENT_SetHubConfiguration @ 0x140008210 (HUBPARENT_SetHubConfiguration.c)
 *     McTemplateK0p_EtwWriteTransfer @ 0x1400087B4 (McTemplateK0p_EtwWriteTransfer.c)
 *     McTemplateK0ppqqqq_EtwWriteTransfer @ 0x14000C5B4 (McTemplateK0ppqqqq_EtwWriteTransfer.c)
 *     HUBFDO_CleanupDeviceInterfaceForBillboard @ 0x14000CB90 (HUBFDO_CleanupDeviceInterfaceForBillboard.c)
 *     HUBFDO_CompleteGetDescriptorRequest @ 0x14000CDAC (HUBFDO_CompleteGetDescriptorRequest.c)
 *     HUBFDO_CreateDeviceInterfaceForBillboard @ 0x14000CEEC (HUBFDO_CreateDeviceInterfaceForBillboard.c)
 *     HUBFDO_EvtDeviceUsageNotification @ 0x14000DC30 (HUBFDO_EvtDeviceUsageNotification.c)
 *     HUBFDO_EvtIoInternalDeviceControlFromPDO @ 0x14000DDB0 (HUBFDO_EvtIoInternalDeviceControlFromPDO.c)
 *     HUBFDO_GetDeviceCapabilities @ 0x14000DFF4 (HUBFDO_GetDeviceCapabilities.c)
 *     HUBFDO_IoctlGetNodeConnectionInfo @ 0x14000E440 (HUBFDO_IoctlGetNodeConnectionInfo.c)
 *     HUBFDO_PowerSettingCallback @ 0x14000EBE0 (HUBFDO_PowerSettingCallback.c)
 *     HUBFDO_SetupHubPostErrataQuery @ 0x14000EFF4 (HUBFDO_SetupHubPostErrataQuery.c)
 *     McTemplateK0pqq_EtwWriteTransfer @ 0x14000F5EC (McTemplateK0pqq_EtwWriteTransfer.c)
 *     McTemplateK0pqqh_EtwWriteTransfer @ 0x14000F664 (McTemplateK0pqqh_EtwWriteTransfer.c)
 *     wil_details_FeatureReporting_ReportUsageToServiceDirect @ 0x1400101AC (wil_details_FeatureReporting_ReportUsageToServiceDirect.c)
 *     wil_details_FeatureStateCache_ReevaluateCachedFeatureEnabledState @ 0x14001029C (wil_details_FeatureStateCache_ReevaluateCachedFeatureEnabledState.c)
 *     HUBMUX_CreatePSM @ 0x140010E5C (HUBMUX_CreatePSM.c)
 *     HUBPDO_CompleteClientSerialRequestWithLastStatus @ 0x140014BBC (HUBPDO_CompleteClientSerialRequestWithLastStatus.c)
 *     HUBPDO_CompleteClientSerialRequestWithStatusFailed @ 0x140014D74 (HUBPDO_CompleteClientSerialRequestWithStatusFailed.c)
 *     HUBPDO_CompleteClientSerialRequestWithStatusSuccess @ 0x140014F14 (HUBPDO_CompleteClientSerialRequestWithStatusSuccess.c)
 *     HUBPDO_EvtDeviceD0Entry @ 0x140015860 (HUBPDO_EvtDeviceD0Entry.c)
 *     HUBPDO_EvtDeviceD0Exit @ 0x140015AF0 (HUBPDO_EvtDeviceD0Exit.c)
 *     HUBPDO_EvtDeviceWdmIrpPreprocess @ 0x140016B00 (HUBPDO_EvtDeviceWdmIrpPreprocess.c)
 *     HUBPDO_EvtIoInternalDeviceControl @ 0x140018680 (HUBPDO_EvtIoInternalDeviceControl.c)
 *     HUBPDO_FindAndStoreMatchingInternalPipeHandle @ 0x140018A58 (HUBPDO_FindAndStoreMatchingInternalPipeHandle.c)
 *     HUBPDO_HandlePLDRRecovery @ 0x140018FF4 (HUBPDO_HandlePLDRRecovery.c)
 *     HUBPDO_RegisterForPowerSettingsForDevice @ 0x14001A4F0 (HUBPDO_RegisterForPowerSettingsForDevice.c)
 *     HUBPDO_RegisterForPowerSettingsForHub @ 0x14001A654 (HUBPDO_RegisterForPowerSettingsForHub.c)
 *     HUBPDO_ReportDeviceFailure @ 0x14001A920 (HUBPDO_ReportDeviceFailure.c)
 *     HUBPDO_SubmitDeviceWakeNotificationIoctl @ 0x14001BB84 (HUBPDO_SubmitDeviceWakeNotificationIoctl.c)
 *     HUBPDO_ValidateSelectConfigUrb @ 0x14001C038 (HUBPDO_ValidateSelectConfigUrb.c)
 *     HUBPDO_ValidateSelectInterfaceUrb @ 0x14001C3DC (HUBPDO_ValidateSelectInterfaceUrb.c)
 *     McTemplateK0pjq_EtwWriteTransfer @ 0x14001CB9C (McTemplateK0pjq_EtwWriteTransfer.c)
 *     McTemplateK0ppn_EtwWriteTransfer @ 0x14001CC20 (McTemplateK0ppn_EtwWriteTransfer.c)
 *     McTemplateK0ppqq_EtwWriteTransfer @ 0x14001CCA0 (McTemplateK0ppqq_EtwWriteTransfer.c)
 *     McTemplateK0pqhhh_EtwWriteTransfer @ 0x14001CD30 (McTemplateK0pqhhh_EtwWriteTransfer.c)
 *     McTemplateK0pqhhhqqqqqqhhqhqqqqqqqssshhh_EtwWriteTransfer @ 0x14001CDD0 (McTemplateK0pqhhhqqqqqqhhqhqqqqqqqssshhh_EtwWriteTransfer.c)
 *     McTemplateK0pqqhhhq_EtwWriteTransfer @ 0x14001D10C (McTemplateK0pqqhhhq_EtwWriteTransfer.c)
 *     McTemplateK0pthhhtq_EtwWriteTransfer @ 0x14001D1D0 (McTemplateK0pthhhtq_EtwWriteTransfer.c)
 *     HUBID_BuildClassCompatibleID @ 0x14001E360 (HUBID_BuildClassCompatibleID.c)
 *     HUBID_BuildCompatibleID @ 0x14001E7B4 (HUBID_BuildCompatibleID.c)
 *     HUBID_BuildContainerID @ 0x14001E89C (HUBID_BuildContainerID.c)
 *     HUBID_BuildDeviceCompatibleID @ 0x14001ED6C (HUBID_BuildDeviceCompatibleID.c)
 *     HUBID_BuildDeviceID @ 0x14001EFD4 (HUBID_BuildDeviceID.c)
 *     HUBID_BuildHardwareID @ 0x14001F16C (HUBID_BuildHardwareID.c)
 *     HUBID_BuildHubCompatibleID @ 0x14001F358 (HUBID_BuildHubCompatibleID.c)
 *     HUBDSM_CheckingIfExemptSecureBioDevice @ 0x140020790 (HUBDSM_CheckingIfExemptSecureBioDevice.c)
 *     HUBDSM_ResettingPipeInUCXOnClientReset @ 0x140023BB0 (HUBDSM_ResettingPipeInUCXOnClientReset.c)
 *     HUBDSM_ResettingPipeInUCXOnClientSyncResetPipe @ 0x140023D50 (HUBDSM_ResettingPipeInUCXOnClientSyncResetPipe.c)
 *     HUBDSM_SettingConfigurationInformationInClientRequest @ 0x1400244D0 (HUBDSM_SettingConfigurationInformationInClientRequest.c)
 *     HUBDSM_SettingInterfaceInformationInClientRequest @ 0x140024790 (HUBDSM_SettingInterfaceInformationInClientRequest.c)
 *     HUBUCX_GetRootHubInfoUsingUCXIoctl @ 0x140028194 (HUBUCX_GetRootHubInfoUsingUCXIoctl.c)
 *     HUBUCX_NotifyForwardProgress @ 0x140028688 (HUBUCX_NotifyForwardProgress.c)
 *     HUBDTX_ClearEndpointHaltUsingControlTransfer @ 0x14002A184 (HUBDTX_ClearEndpointHaltUsingControlTransfer.c)
 *     HUBDTX_LogAlternateMode @ 0x14002BA08 (HUBDTX_LogAlternateMode.c)
 *     HUBDTX_LogBillboardEvent @ 0x14002BBD8 (HUBDTX_LogBillboardEvent.c)
 *     McTemplateK0phuzu_EtwWriteTransfer @ 0x14002E0D8 (McTemplateK0phuzu_EtwWriteTransfer.c)
 *     McTemplateK0puuhz_EtwWriteTransfer @ 0x14002E1AC (McTemplateK0puuhz_EtwWriteTransfer.c)
 *     HUBMISC_ControlTransfer @ 0x14002EC7C (HUBMISC_ControlTransfer.c)
 *     HUBMISC_PrepareEndpointAndInterfaceListsForConfiguringDeviceOnSelectConfiguration @ 0x1400313D8 (HUBMISC_PrepareEndpointAndInterfaceListsForConfiguringDeviceOnSelectConfiguration.c)
 *     HUBMISC_PrepareEndpointAndInterfaceListsForConfiguringDeviceOnSelectInterface @ 0x1400320F0 (HUBMISC_PrepareEndpointAndInterfaceListsForConfiguringDeviceOnSelectInterface.c)
 *     McTemplateK0phhhquuuuu_EtwWriteTransfer @ 0x140034058 (McTemplateK0phhhquuuuu_EtwWriteTransfer.c)
 *     McTemplateK0psqzq_EtwWriteTransfer @ 0x140034158 (McTemplateK0psqzq_EtwWriteTransfer.c)
 *     HUBREG_ValidateAndPopulateEndpointPriorities @ 0x1400350CC (HUBREG_ValidateAndPopulateEndpointPriorities.c)
 *     HUBDESC_ValidateConfigurationDescriptorSet @ 0x14003D35C (HUBDESC_ValidateConfigurationDescriptorSet.c)
 *     HUBDESC_ValidateMsOs20ConfigurationSubset @ 0x14003E5B0 (HUBDESC_ValidateMsOs20ConfigurationSubset.c)
 *     HUBDESC_ValidateMsOs20FunctionSubset @ 0x14003ED10 (HUBDESC_ValidateMsOs20FunctionSubset.c)
 *     HUBIDLE_AddEvent @ 0x14003FADC (HUBIDLE_AddEvent.c)
 *     FWUPDATE_EvtIoInternalDeviceControl @ 0x140041040 (FWUPDATE_EvtIoInternalDeviceControl.c)
 *     McTemplateK0ppp_EtwWriteTransfer @ 0x140041E14 (McTemplateK0ppp_EtwWriteTransfer.c)
 *     McTemplateK0ppq_EtwWriteTransfer @ 0x140041E9C (McTemplateK0ppq_EtwWriteTransfer.c)
 *     MicrosoftTelemetryAssertTriggeredWorker @ 0x140042754 (MicrosoftTelemetryAssertTriggeredWorker.c)
 *     USBD_CreateHandle @ 0x140043628 (USBD_CreateHandle.c)
 *     USBD_QueryUsbCapability @ 0x140043A38 (USBD_QueryUsbCapability.c)
 *     MyRegQueryUlong @ 0x140044E38 (MyRegQueryUlong.c)
 *     EnableFlushTimer @ 0x14004541C (EnableFlushTimer.c)
 *     __GSHandlerCheckCommon @ 0x140045C4C (__GSHandlerCheckCommon.c)
 *     HUBDRIVER_EtwEnableCallback @ 0x140079008 (HUBDRIVER_EtwEnableCallback.c)
 *     HUBDRIVER_EtwRundownUsbDevice @ 0x14007991C (HUBDRIVER_EtwRundownUsbDevice.c)
 *     wil_details_ReevaluateOnFeatureConfigurationChange @ 0x14007A6E0 (wil_details_ReevaluateOnFeatureConfigurationChange.c)
 *     HUBFDO_EvtDeviceAdd @ 0x14007ABE0 (HUBFDO_EvtDeviceAdd.c)
 *     HUBFDO_EvtIoDeviceControl @ 0x14007C7A0 (HUBFDO_EvtIoDeviceControl.c)
 *     HUBFDO_IoctlCyclePort @ 0x14007C9FC (HUBFDO_IoctlCyclePort.c)
 *     HUBFDO_IoctlGetDescriptorFromNodeConnection @ 0x14007CEB8 (HUBFDO_IoctlGetDescriptorFromNodeConnection.c)
 *     HUBFDO_IoctlGetHubCaps @ 0x14007D494 (HUBFDO_IoctlGetHubCaps.c)
 *     HUBFDO_IoctlGetHubCapsEx @ 0x14007D66C (HUBFDO_IoctlGetHubCapsEx.c)
 *     HUBFDO_IoctlGetHubInformationEx @ 0x14007D8A4 (HUBFDO_IoctlGetHubInformationEx.c)
 *     HUBFDO_IoctlGetNodeConnectionAttributes @ 0x14007DB58 (HUBFDO_IoctlGetNodeConnectionAttributes.c)
 *     HUBFDO_IoctlGetNodeConnectionDriverKeyName @ 0x14007DD94 (HUBFDO_IoctlGetNodeConnectionDriverKeyName.c)
 *     HUBFDO_IoctlGetNodeConnectionInformationExV2 @ 0x14007E100 (HUBFDO_IoctlGetNodeConnectionInformationExV2.c)
 *     HUBFDO_IoctlGetNodeConnectionName @ 0x14007E524 (HUBFDO_IoctlGetNodeConnectionName.c)
 *     HUBFDO_IoctlGetNodeConnectionSuperSpeedPlusInformation @ 0x14007E900 (HUBFDO_IoctlGetNodeConnectionSuperSpeedPlusInformation.c)
 *     HUBFDO_IoctlGetNodeInformation @ 0x14007EDCC (HUBFDO_IoctlGetNodeInformation.c)
 *     HUBFDO_IoctlGetPortConnectorProperties @ 0x14007EFB4 (HUBFDO_IoctlGetPortConnectorProperties.c)
 *     HUBFDO_IoctlResetHub @ 0x14007F55C (HUBFDO_IoctlResetHub.c)
 *     HUBFDO_MapDvsecUsb4Hosts @ 0x14007FD00 (HUBFDO_MapDvsecUsb4Hosts.c)
 *     HUBFDO_QueryHubErrataFlags @ 0x1400801E0 (HUBFDO_QueryHubErrataFlags.c)
 *     HUBFDO_RegisterSleepstudyBlockerReason @ 0x14008039C (HUBFDO_RegisterSleepstudyBlockerReason.c)
 *     HUBFDO_RegisterSleepstudyBlockerReasons @ 0x1400804F0 (HUBFDO_RegisterSleepstudyBlockerReasons.c)
 *     HUBPDO_AssignPDOIds @ 0x140080A64 (HUBPDO_AssignPDOIds.c)
 *     HUBPDO_CreatePdoInternal @ 0x1400811E8 (HUBPDO_CreatePdoInternal.c)
 *     HUBPDO_EvtDevicePrepareHardware @ 0x140082630 (HUBPDO_EvtDevicePrepareHardware.c)
 *     HUBPDO_EvtDeviceReleaseHardware @ 0x1400837B0 (HUBPDO_EvtDeviceReleaseHardware.c)
 *     HUBPDO_InvokePortPLDRRecovery @ 0x1400843FC (HUBPDO_InvokePortPLDRRecovery.c)
 *     HUBPDO_MakePdoName @ 0x140084984 (HUBPDO_MakePdoName.c)
 *     HUBPDO_RegisterPortPLDRCapability @ 0x140084E20 (HUBPDO_RegisterPortPLDRCapability.c)
 *     HUBPDO_UnregisterPortPLDRCapability @ 0x140085620 (HUBPDO_UnregisterPortPLDRCapability.c)
 *     HUBMISC_QueryAndCacheRegistryValuesForDevice @ 0x140086FD8 (HUBMISC_QueryAndCacheRegistryValuesForDevice.c)
 *     HUBMISC_ReportPnPFailureProblem @ 0x1400870D4 (HUBMISC_ReportPnPFailureProblem.c)
 *     HUBREG_AssignUsbflagsValueForDevice @ 0x14008766C (HUBREG_AssignUsbflagsValueForDevice.c)
 *     HUBREG_DeleteUxdDeviceKey @ 0x1400877B4 (HUBREG_DeleteUxdDeviceKey.c)
 *     HUBREG_DeleteUxdPortKey @ 0x140087918 (HUBREG_DeleteUxdPortKey.c)
 *     HUBREG_DeleteUxdSubKeys @ 0x140087C20 (HUBREG_DeleteUxdSubKeys.c)
 *     HUBREG_GetVidPidRevForPort @ 0x140088424 (HUBREG_GetVidPidRevForPort.c)
 *     HUBREG_OpenCreateUsbflagsDeviceKey @ 0x1400886B4 (HUBREG_OpenCreateUsbflagsDeviceKey.c)
 *     HUBREG_OpenPortSubkey @ 0x140088AF0 (HUBREG_OpenPortSubkey.c)
 *     HUBREG_QueryHubErrataFlags @ 0x140089C2C (HUBREG_QueryHubErrataFlags.c)
 *     HUBREG_QueryUsbHardwareVerifierValue @ 0x14008A2F8 (HUBREG_QueryUsbHardwareVerifierValue.c)
 *     HUBREG_QueryUsbflagsValuesForDevice @ 0x14008A8C0 (HUBREG_QueryUsbflagsValuesForDevice.c)
 *     HUBREG_QueryUxdDeviceKey @ 0x14008B3D4 (HUBREG_QueryUxdDeviceKey.c)
 *     HUBREG_QueryUxdPortKey @ 0x14008B550 (HUBREG_QueryUxdPortKey.c)
 *     HUBREG_SetVidPidRevForPort @ 0x14008C380 (HUBREG_SetVidPidRevForPort.c)
 *     HUBREG_UpdateUxdSettings @ 0x14008CEA4 (HUBREG_UpdateUxdSettings.c)
 *     HUBACPI_EnumChildren @ 0x14008D684 (HUBACPI_EnumChildren.c)
 *     HUBACPI_EvalAcpiMethodEx @ 0x14008DA90 (HUBACPI_EvalAcpiMethodEx.c)
 *     HUBACPI_EvaluateDsmMethod @ 0x14008E29C (HUBACPI_EvaluateDsmMethod.c)
 *     HUBACPI_ExecuteDSM @ 0x14008E7FC (HUBACPI_ExecuteDSM.c)
 *     WMI_AcquireBusInfo @ 0x14008F768 (WMI_AcquireBusInfo.c)
 *     WMI_FireNotification @ 0x14008FB20 (WMI_FireNotification.c)
 *     WMI_RegisterDevice @ 0x140090068 (WMI_RegisterDevice.c)
 *     WMI_RegisterHub @ 0x1400901A0 (WMI_RegisterHub.c)
 *     WMI_RegisterSurpriseRemovalNotificationInstance @ 0x140090384 (WMI_RegisterSurpriseRemovalNotificationInstance.c)
 *     HUBWNF_PublishUsbPartnerDualRoleFeatures @ 0x140090674 (HUBWNF_PublishUsbPartnerDualRoleFeatures.c)
 *     FWUPDATE_AddIdsForFirmwareUpdateDevice @ 0x1400906DC (FWUPDATE_AddIdsForFirmwareUpdateDevice.c)
 *     FWUPDATE_CreateFirmwareUpdateDevice @ 0x140090AAC (FWUPDATE_CreateFirmwareUpdateDevice.c)
 *     TUNNEL_EvtInterfaceChange @ 0x140091960 (TUNNEL_EvtInterfaceChange.c)
 *     TUNNEL_EvtWorkitemPnpInterfaceNotification @ 0x140092510 (TUNNEL_EvtWorkitemPnpInterfaceNotification.c)
 *     TraceLoggingRegisterEx_EtwRegister_EtwSetInformation @ 0x140093720 (TraceLoggingRegisterEx_EtwRegister_EtwSetInformation.c)
 *     QueryDeviceResetInterface @ 0x140093CB0 (QueryDeviceResetInterface.c)
 *     LookUpTableFlushComplete @ 0x140094200 (LookUpTableFlushComplete.c)
 *     TlgRegisterAggregateProviderEx @ 0x140094824 (TlgRegisterAggregateProviderEx.c)
 *     DriverEntry @ 0x14009603C (DriverEntry.c)
 *     wil_details_PopulateInitialConfiguredFeatureStates @ 0x1400967C4 (wil_details_PopulateInitialConfiguredFeatureStates.c)
 * Callees:
 *     <none>
 */

void __cdecl _security_check_cookie(uintptr_t StackCookie)
{
  __int64 v1; // rcx

  if ( StackCookie != _security_cookie )
ReportFailure:
    _report_gsfailure(StackCookie);
  v1 = __ROL8__(StackCookie, 16);
  if ( (_WORD)v1 )
  {
    StackCookie = __ROR8__(v1, 16);
    goto ReportFailure;
  }
}
