/*
 * XREFs of ?FxPoolFree@@YAXPEAX@Z @ 0x1C0005638
 * Callers:
 *     ??_EFxInternalIoctlOthersContext@@UEAAPEAXI@Z @ 0x1C0001A60 (--_EFxInternalIoctlOthersContext@@UEAAPEAXI@Z.c)
 *     ?Release@FxRequest@@UEAAKPEAXJPEBD@Z @ 0x1C00021D0 (-Release@FxRequest@@UEAAKPEAXJPEBD@Z.c)
 *     ?Release@FxObject@@UEAAKPEAXJPEBD@Z @ 0x1C0002940 (-Release@FxObject@@UEAAKPEAXJPEBD@Z.c)
 *     ?_VerifyStateSeparationRegistryPolicy@FxRegKey@@SAXPEAU_FX_DRIVER_GLOBALS@@PEAX@Z @ 0x1C0004440 (-_VerifyStateSeparationRegistryPolicy@FxRegKey@@SAXPEAU_FX_DRIVER_GLOBALS@@PEAX@Z.c)
 *     ??_GFxMemoryBuffer@@MEAAPEAXI@Z @ 0x1C0004FE0 (--_GFxMemoryBuffer@@MEAAPEAXI@Z.c)
 *     ?ProcessDestroy@FxObject@@AEAAXXZ @ 0x1C0005034 (-ProcessDestroy@FxObject@@AEAAXXZ.c)
 *     ??1FxIoContext@@UEAA@XZ @ 0x1C000528C (--1FxIoContext@@UEAA@XZ.c)
 *     ??_GFxIoContext@@UEAAPEAXI@Z @ 0x1C00052F0 (--_GFxIoContext@@UEAAPEAXI@Z.c)
 *     ??_EFxRequestFromLookaside@@UEAAPEAXI@Z @ 0x1C0005690 (--_EFxRequestFromLookaside@@UEAAPEAXI@Z.c)
 *     ??_GFxRegKey@@UEAAPEAXI@Z @ 0x1C0005A80 (--_GFxRegKey@@UEAAPEAXI@Z.c)
 *     ?FormatIoctlRequest@FxIoTarget@@QEAAJPEAVFxRequestBase@@KEPEAUFxRequestBuffer@@1PEAVFxFileObject@@@Z @ 0x1C000AD0C (-FormatIoctlRequest@FxIoTarget@@QEAAJPEAVFxRequestBase@@KEPEAUFxRequestBuffer@@1PEAVFxFileObject.c)
 *     ?DrainFreeListHead@FxChildList@@IEAAXPEAU_LIST_ENTRY@@@Z @ 0x1C0010CA8 (-DrainFreeListHead@FxChildList@@IEAAXPEAU_LIST_ENTRY@@@Z.c)
 *     ??_EFxWorkItem@@UEAAPEAXI@Z @ 0x1C0014230 (--_EFxWorkItem@@UEAAPEAXI@Z.c)
 *     ?FxLibraryCleanup@@YAXXZ @ 0x1C002CDBC (-FxLibraryCleanup@@YAXXZ.c)
 *     ??_EFxDmaEnabler@@UEAAPEAXI@Z @ 0x1C0030DD0 (--_EFxDmaEnabler@@UEAAPEAXI@Z.c)
 *     ??_EFxDmaSystemTransaction@@UEAAPEAXI@Z @ 0x1C0030E60 (--_EFxDmaSystemTransaction@@UEAAPEAXI@Z.c)
 *     ??_GFxVerifierLock@@QEAAPEAXI@Z @ 0x1C0030EA0 (--_GFxVerifierLock@@QEAAPEAXI@Z.c)
 *     ??_GFxDpc@@UEAAPEAXI@Z @ 0x1C0039A60 (--_GFxDpc@@UEAAPEAXI@Z.c)
 *     ??_EFxWmiProvider@@UEAAPEAXI@Z @ 0x1C003D6E0 (--_EFxWmiProvider@@UEAAPEAXI@Z.c)
 *     ??_EFxWmiInstanceExternal@@UEAAPEAXI@Z @ 0x1C003E0B0 (--_EFxWmiInstanceExternal@@UEAAPEAXI@Z.c)
 *     ??_GFxWmiIrpHandler@@UEAAPEAXI@Z @ 0x1C003F010 (--_GFxWmiIrpHandler@@UEAAPEAXI@Z.c)
 *     ??_GFxQueryInterface@@QEAAPEAXI@Z @ 0x1C0040704 (--_GFxQueryInterface@@QEAAPEAXI@Z.c)
 *     ?IsCompanionRequiredForDevice@FxCompanionLibrary@@QEAAEPEAVFxDevice@@PEAPEBG@Z @ 0x1C0041DE4 (-IsCompanionRequiredForDevice@FxCompanionLibrary@@QEAAEPEAVFxDevice@@PEAPEBG@Z.c)
 *     ?LoadCompanion@FxCompanionLibrary@@QEAAJPEAU_FX_DRIVER_GLOBALS@@PEAU_DEVICE_OBJECT@@PEAUIDeviceCompanionCallbacks@@PEAPEAUIDeviceCompanion@@@Z @ 0x1C0042358 (-LoadCompanion@FxCompanionLibrary@@QEAAJPEAU_FX_DRIVER_GLOBALS@@PEAU_DEVICE_OBJECT@@PEAUIDeviceC.c)
 *     ??_GFxCompanionTarget@@UEAAPEAXI@Z @ 0x1C0042C60 (--_GFxCompanionTarget@@UEAAPEAXI@Z.c)
 *     ??1Info@FxIrpPreprocessInfo@@QEAA@XZ @ 0x1C0043820 (--1Info@FxIrpPreprocessInfo@@QEAA@XZ.c)
 *     ??_GFxDeviceText@@QEAAPEAXI@Z @ 0x1C0043840 (--_GFxDeviceText@@QEAAPEAXI@Z.c)
 *     ??_GWDFDEVICE_INIT@@QEAAPEAXI@Z @ 0x1C0043888 (--_GWDFDEVICE_INIT@@QEAAPEAXI@Z.c)
 *     ??1FxAutoString@@QEAA@XZ @ 0x1C00461B0 (--1FxAutoString@@QEAA@XZ.c)
 *     ??_GFxDeviceBase@@MEAAPEAXI@Z @ 0x1C004C450 (--_GFxDeviceBase@@MEAAPEAXI@Z.c)
 *     ??_EFxCallbackLock@@UEAAPEAXI@Z @ 0x1C004CC40 (--_EFxCallbackLock@@UEAAPEAXI@Z.c)
 *     ??_GFxCallbackMutexLock@@UEAAPEAXI@Z @ 0x1C004CC70 (--_GFxCallbackMutexLock@@UEAAPEAXI@Z.c)
 *     ??_EFxCallbackSpinLock@@UEAAPEAXI@Z @ 0x1C004CCB0 (--_EFxCallbackSpinLock@@UEAAPEAXI@Z.c)
 *     ??1WDFDEVICE_INIT@@QEAA@XZ @ 0x1C004F1C4 (--1WDFDEVICE_INIT@@QEAA@XZ.c)
 *     ??_GFxIrpPreprocessInfo@@QEAAPEAXI@Z @ 0x1C004F334 (--_GFxIrpPreprocessInfo@@QEAAPEAXI@Z.c)
 *     ?CreateSymbolicLink@FxDevice@@QEAAJPEAU_FX_DRIVER_GLOBALS@@PEBU_UNICODE_STRING@@@Z @ 0x1C004FA60 (-CreateSymbolicLink@FxDevice@@QEAAJPEAU_FX_DRIVER_GLOBALS@@PEBU_UNICODE_STRING@@@Z.c)
 *     ?DeleteSymbolicLink@FxDevice@@QEAAXXZ @ 0x1C004FCD0 (-DeleteSymbolicLink@FxDevice@@QEAAXXZ.c)
 *     ?Destroy@FxDevice@@QEAAXXZ @ 0x1C004FD2C (-Destroy@FxDevice@@QEAAXXZ.c)
 *     ??1FxDevice@@UEAA@XZ @ 0x1C0050AD0 (--1FxDevice@@UEAA@XZ.c)
 *     ??_GFxDevice@@UEAAPEAXI@Z @ 0x1C0050D90 (--_GFxDevice@@UEAAPEAXI@Z.c)
 *     ??_EFxObject@@UEAAPEAXI@Z @ 0x1C0052620 (--_EFxObject@@UEAAPEAXI@Z.c)
 *     ??_EFxUsbUrb@@MEAAPEAXI@Z @ 0x1C0052B40 (--_EFxUsbUrb@@MEAAPEAXI@Z.c)
 *     ??_GFxRequestTimer@@QEAAPEAXI@Z @ 0x1C0052C0C (--_GFxRequestTimer@@QEAAPEAXI@Z.c)
 *     ??1FxDriver@@UEAA@XZ @ 0x1C0053100 (--1FxDriver@@UEAA@XZ.c)
 *     ??_EFxDriver@@UEAAPEAXI@Z @ 0x1C00531D0 (--_EFxDriver@@UEAAPEAXI@Z.c)
 *     ??_EFxTimer@@UEAAPEAXI@Z @ 0x1C0053A50 (--_EFxTimer@@UEAAPEAXI@Z.c)
 *     ??_EFxNPagedLookasideList@@MEAAPEAXI@Z @ 0x1C0053C30 (--_EFxNPagedLookasideList@@MEAAPEAXI@Z.c)
 *     ??_EFxNPagedLookasideListFromPool@@MEAAPEAXI@Z @ 0x1C0053CB0 (--_EFxNPagedLookasideListFromPool@@MEAAPEAXI@Z.c)
 *     ??_EFxMemoryBufferFromLookaside@@MEAAPEAXI@Z @ 0x1C0054110 (--_EFxMemoryBufferFromLookaside@@MEAAPEAXI@Z.c)
 *     ??_GFxPagedLookasideListFromPool@@MEAAPEAXI@Z @ 0x1C0054170 (--_GFxPagedLookasideListFromPool@@MEAAPEAXI@Z.c)
 *     ??_GFxDisposeList@@UEAAPEAXI@Z @ 0x1C0054760 (--_GFxDisposeList@@UEAAPEAXI@Z.c)
 *     ??_EFxRequestMemory@@UEAAPEAXI@Z @ 0x1C0054E80 (--_EFxRequestMemory@@UEAAPEAXI@Z.c)
 *     ??_EFxMemoryBufferFromPool@@MEAAPEAXI@Z @ 0x1C0055340 (--_EFxMemoryBufferFromPool@@MEAAPEAXI@Z.c)
 *     ??_GFxSystemWorkItem@@UEAAPEAXI@Z @ 0x1C0055580 (--_GFxSystemWorkItem@@UEAAPEAXI@Z.c)
 *     ??_GFxLookasideList@@MEAAPEAXI@Z @ 0x1C00558D0 (--_GFxLookasideList@@MEAAPEAXI@Z.c)
 *     ?FxObjectAllocateContext@@YAJPEAVFxObject@@PEAU_WDF_OBJECT_ATTRIBUTES@@EPEAPEAX@Z @ 0x1C0055CC4 (-FxObjectAllocateContext@@YAJPEAVFxObject@@PEAU_WDF_OBJECT_ATTRIBUTES@@EPEAPEAX@Z.c)
 *     ??1FxTagHistory@@QEAA@XZ @ 0x1C0059210 (--1FxTagHistory@@QEAA@XZ.c)
 *     ??_GFxTagTracker@@QEAAPEAXI@Z @ 0x1C005923C (--_GFxTagTracker@@QEAAPEAXI@Z.c)
 *     ?FreeThreadTable@FxVerifierLock@@SAXPEAU_FX_DRIVER_GLOBALS@@@Z @ 0x1C0059E54 (-FreeThreadTable@FxVerifierLock@@SAXPEAU_FX_DRIVER_GLOBALS@@@Z.c)
 *     ??_GFxTagTrackingBlock@@QEAAPEAXI@Z @ 0x1C005AC5C (--_GFxTagTrackingBlock@@QEAAPEAXI@Z.c)
 *     ??_EFxIoResList@@UEAAPEAXI@Z @ 0x1C005B870 (--_EFxIoResList@@UEAAPEAXI@Z.c)
 *     ??_GFxDeviceInterface@@QEAAPEAXI@Z @ 0x1C005C7D4 (--_GFxDeviceInterface@@QEAAPEAXI@Z.c)
 *     imp_WdfRegistryAssignMultiString @ 0x1C005D030 (imp_WdfRegistryAssignMultiString.c)
 *     imp_WdfRegistryAssignUnicodeString @ 0x1C005D4D0 (imp_WdfRegistryAssignUnicodeString.c)
 *     imp_WdfRegistryQueryMemory @ 0x1C005D8E0 (imp_WdfRegistryQueryMemory.c)
 *     imp_WdfRegistryQueryMultiString @ 0x1C005DBA0 (imp_WdfRegistryQueryMultiString.c)
 *     imp_WdfRegistryQueryString @ 0x1C005DFA0 (imp_WdfRegistryQueryString.c)
 *     imp_WdfRegistryQueryUnicodeString @ 0x1C005E280 (imp_WdfRegistryQueryUnicodeString.c)
 *     ??1FxPagedObject@@UEAA@XZ @ 0x1C005ED54 (--1FxPagedObject@@UEAA@XZ.c)
 *     ??_GFxPagedObject@@UEAAPEAXI@Z @ 0x1C005ED90 (--_GFxPagedObject@@UEAAPEAXI@Z.c)
 *     FxGetDevicePropertyString @ 0x1C005F024 (FxGetDevicePropertyString.c)
 *     GetImageName @ 0x1C005F478 (GetImageName.c)
 *     QueryAndAllocString @ 0x1C005FAD8 (QueryAndAllocString.c)
 *     ?_IsAffectedByStateSeparationRegistryPolicy@FxRegKey@@SAJPEAU_FX_DRIVER_GLOBALS@@PEAXPEAE@Z @ 0x1C0060360 (-_IsAffectedByStateSeparationRegistryPolicy@FxRegKey@@SAJPEAU_FX_DRIVER_GLOBALS@@PEAXPEAE@Z.c)
 *     ?AddAt@FxResourceCollection@@QEAAJKPEAVFxObject@@@Z @ 0x1C0060734 (-AddAt@FxResourceCollection@@QEAAJKPEAVFxObject@@@Z.c)
 *     ?CleanupEntry@FxCollectionInternal@@QEAAXPEAVFxCollectionEntry@@@Z @ 0x1C0060F84 (-CleanupEntry@FxCollectionInternal@@QEAAXPEAVFxCollectionEntry@@@Z.c)
 *     ??_GFxString@@UEAAPEAXI@Z @ 0x1C0061110 (--_GFxString@@UEAAPEAXI@Z.c)
 *     ?FxDuplicateUnicodeString@@YAJPEAU_FX_DRIVER_GLOBALS@@PEBU_UNICODE_STRING@@PEAU2@@Z @ 0x1C00612BC (-FxDuplicateUnicodeString@@YAJPEAU_FX_DRIVER_GLOBALS@@PEBU_UNICODE_STRING@@PEAU2@@Z.c)
 *     ??_GFxSpinLock@@UEAAPEAXI@Z @ 0x1C0061AD0 (--_GFxSpinLock@@UEAAPEAXI@Z.c)
 *     ??_GFxIoTargetRemote@@UEAAPEAXI@Z @ 0x1C0063EC0 (--_GFxIoTargetRemote@@UEAAPEAXI@Z.c)
 *     ?Clear@FxIoTargetRemoveOpenParams@@QEAAXXZ @ 0x1C00661A4 (-Clear@FxIoTargetRemoveOpenParams@@QEAAXXZ.c)
 *     ?Open@FxIoTargetRemote@@QEAAJPEAU_WDF_IO_TARGET_OPEN_PARAMS@@@Z @ 0x1C0066750 (-Open@FxIoTargetRemote@@QEAAJPEAU_WDF_IO_TARGET_OPEN_PARAMS@@@Z.c)
 *     ?FormatIoRequest@FxIoTarget@@QEAAJPEAVFxRequestBase@@EPEAUFxRequestBuffer@@PEA_JPEAVFxFileObject@@@Z @ 0x1C0067200 (-FormatIoRequest@FxIoTarget@@QEAAJPEAVFxRequestBase@@EPEAUFxRequestBuffer@@PEA_JPEAVFxFileObject.c)
 *     ??_GFxUsbPipe@@MEAAPEAXI@Z @ 0x1C006C030 (--_GFxUsbPipe@@MEAAPEAXI@Z.c)
 *     ??_GFxUsbPipeContinuousReader@@QEAAPEAXI@Z @ 0x1C006C070 (--_GFxUsbPipeContinuousReader@@QEAAPEAXI@Z.c)
 *     ??_EFxUsbPipeRequestContext@@UEAAPEAXI@Z @ 0x1C006C0A0 (--_EFxUsbPipeRequestContext@@UEAAPEAXI@Z.c)
 *     ??_EFxUsbPipeTransferContext@@UEAAPEAXI@Z @ 0x1C006C0E0 (--_EFxUsbPipeTransferContext@@UEAAPEAXI@Z.c)
 *     ??1FxUsbDevice@@MEAA@XZ @ 0x1C006EC40 (--1FxUsbDevice@@MEAA@XZ.c)
 *     ??_EFxUsbDevice@@MEAAPEAXI@Z @ 0x1C006ED30 (--_EFxUsbDevice@@MEAAPEAXI@Z.c)
 *     ??_EFxUsbDeviceControlContext@@UEAAPEAXI@Z @ 0x1C006ED70 (--_EFxUsbDeviceControlContext@@UEAAPEAXI@Z.c)
 *     ??_GFxUsbDeviceStringContext@@UEAAPEAXI@Z @ 0x1C006EDB0 (--_GFxUsbDeviceStringContext@@UEAAPEAXI@Z.c)
 *     ?AllocateDescriptor@FxUsbDeviceStringContext@@QEAAJPEAU_FX_DRIVER_GLOBALS@@_K@Z @ 0x1C006EE44 (-AllocateDescriptor@FxUsbDeviceStringContext@@QEAAJPEAU_FX_DRIVER_GLOBALS@@_K@Z.c)
 *     ?SelectConfig@FxUsbDevice@@QEAAJPEAU_WDF_OBJECT_ATTRIBUTES@@PEAU_URB@@W4_FX_URB_TYPE@@PEAE@Z @ 0x1C007056C (-SelectConfig@FxUsbDevice@@QEAAJPEAU_WDF_OBJECT_ATTRIBUTES@@PEAU_URB@@W4_FX_URB_TYPE@@PEAE@Z.c)
 *     ?SelectConfigDescriptor@FxUsbDevice@@QEAAJPEAU_WDF_OBJECT_ATTRIBUTES@@PEAU_WDF_USB_DEVICE_SELECT_CONFIG_PARAMS@@@Z @ 0x1C0070C78 (-SelectConfigDescriptor@FxUsbDevice@@QEAAJPEAU_WDF_OBJECT_ATTRIBUTES@@PEAU_WDF_USB_DEVICE_SELECT.c)
 *     ??1FxUsbInterface@@MEAA@XZ @ 0x1C0071238 (--1FxUsbInterface@@MEAA@XZ.c)
 *     ??_EFxUsbInterface@@MEAAPEAXI@Z @ 0x1C00712F0 (--_EFxUsbInterface@@MEAAPEAXI@Z.c)
 *     ?CleanUpAndDelete@FxUsbInterface@@QEAAXE@Z @ 0x1C0071330 (-CleanUpAndDelete@FxUsbInterface@@QEAAXE@Z.c)
 *     ?SelectSetting@FxUsbInterface@@QEAAJPEAU_WDF_OBJECT_ATTRIBUTES@@PEAU_URB@@@Z @ 0x1C0071954 (-SelectSetting@FxUsbInterface@@QEAAJPEAU_WDF_OBJECT_ATTRIBUTES@@PEAU_URB@@@Z.c)
 *     ?SelectSettingByDescriptor@FxUsbInterface@@QEAAJPEAU_WDF_OBJECT_ATTRIBUTES@@PEAU_USB_INTERFACE_DESCRIPTOR@@@Z @ 0x1C0071CCC (-SelectSettingByDescriptor@FxUsbInterface@@QEAAJPEAU_WDF_OBJECT_ATTRIBUTES@@PEAU_USB_INTERFACE_D.c)
 *     ?SelectSettingByIndex@FxUsbInterface@@QEAAJPEAU_WDF_OBJECT_ATTRIBUTES@@E@Z @ 0x1C0071DE8 (-SelectSettingByIndex@FxUsbInterface@@QEAAJPEAU_WDF_OBJECT_ATTRIBUTES@@E@Z.c)
 *     ?GetString@FxUsbDevice@@QEAAJPEAG0EGPEAUWDFREQUEST__@@PEAU_WDF_REQUEST_SEND_OPTIONS@@@Z @ 0x1C00725A0 (-GetString@FxUsbDevice@@QEAAJPEAG0EGPEAUWDFREQUEST__@@PEAU_WDF_REQUEST_SEND_OPTIONS@@@Z.c)
 *     ?SelectConfigMulti@FxUsbDevice@@QEAAJPEAU_WDF_OBJECT_ATTRIBUTES@@PEAU_WDF_USB_DEVICE_SELECT_CONFIG_PARAMS@@@Z @ 0x1C0072F6C (-SelectConfigMulti@FxUsbDevice@@QEAAJPEAU_WDF_OBJECT_ATTRIBUTES@@PEAU_WDF_USB_DEVICE_SELECT_CONF.c)
 *     ?SelectConfigSingle@FxUsbDevice@@QEAAJPEAU_WDF_OBJECT_ATTRIBUTES@@PEAU_WDF_USB_DEVICE_SELECT_CONFIG_PARAMS@@@Z @ 0x1C0073240 (-SelectConfigSingle@FxUsbDevice@@QEAAJPEAU_WDF_OBJECT_ATTRIBUTES@@PEAU_WDF_USB_DEVICE_SELECT_CON.c)
 *     ??1FxPkgIo@@UEAA@XZ @ 0x1C0073EE8 (--1FxPkgIo@@UEAA@XZ.c)
 *     ??_EFxPkgIo@@UEAAPEAXI@Z @ 0x1C0073FC0 (--_EFxPkgIo@@UEAAPEAXI@Z.c)
 *     ??_EFxIoQueue@@UEAAPEAXI@Z @ 0x1C0074FE0 (--_EFxIoQueue@@UEAAPEAXI@Z.c)
 *     ?Dispose@FxIoQueue@@UEAAEXZ @ 0x1C0075640 (-Dispose@FxIoQueue@@UEAAEXZ.c)
 *     ?AssignForwardProgressPolicy@FxIoQueue@@QEAAJPEAU_WDF_IO_QUEUE_FORWARD_PROGRESS_POLICY@@@Z @ 0x1C0076E64 (-AssignForwardProgressPolicy@FxIoQueue@@QEAAJPEAU_WDF_IO_QUEUE_FORWARD_PROGRESS_POLICY@@@Z.c)
 *     ??1FxPkgPdo@@UEAA@XZ @ 0x1C0078318 (--1FxPkgPdo@@UEAA@XZ.c)
 *     ??_EFxPkgPdo@@UEAAPEAXI@Z @ 0x1C00783B0 (--_EFxPkgPdo@@UEAAPEAXI@Z.c)
 *     ??_GFxRelatedDeviceList@@QEAAPEAXI@Z @ 0x1C00783F0 (--_GFxRelatedDeviceList@@QEAAPEAXI@Z.c)
 *     ??1FxPkgPnp@@MEAA@XZ @ 0x1C007E590 (--1FxPkgPnp@@MEAA@XZ.c)
 *     ??_GFxCmResList@@MEAAPEAXI@Z @ 0x1C007E7B0 (--_GFxCmResList@@MEAAPEAXI@Z.c)
 *     ??_GFxEnumerationInfo@@QEAAPEAXI@Z @ 0x1C007E7FC (--_GFxEnumerationInfo@@QEAAPEAXI@Z.c)
 *     ??_EFxPkgPnp@@MEAAPEAXI@Z @ 0x1C007E830 (--_EFxPkgPnp@@MEAAPEAXI@Z.c)
 *     ?PostCreateDeviceInitialize@FxPkgPnp@@QEAAJXZ @ 0x1C00811F4 (-PostCreateDeviceInitialize@FxPkgPnp@@QEAAJXZ.c)
 *     ??_GFxFilteredStartContext@@QEAAPEAXI@Z @ 0x1C0083734 (--_GFxFilteredStartContext@@QEAAPEAXI@Z.c)
 *     ??_EFxPkgFdo@@MEAAPEAXI@Z @ 0x1C0083790 (--_EFxPkgFdo@@MEAAPEAXI@Z.c)
 *     ??_GFxUsbIdleInfo@@QEAAPEAXI@Z @ 0x1C0085A34 (--_GFxUsbIdleInfo@@QEAAPEAXI@Z.c)
 *     ??_EFxInterrupt@@UEAAPEAXI@Z @ 0x1C0088740 (--_EFxInterrupt@@UEAAPEAXI@Z.c)
 *     ??_GFxWakeInterruptMachine@@QEAAPEAXI@Z @ 0x1C0088780 (--_GFxWakeInterruptMachine@@QEAAPEAXI@Z.c)
 *     ??_EFxPkgGeneral@@UEAAPEAXI@Z @ 0x1C008CCA0 (--_EFxPkgGeneral@@UEAAPEAXI@Z.c)
 *     ??_GFxSystemThread@@UEAAPEAXI@Z @ 0x1C0090520 (--_GFxSystemThread@@UEAAPEAXI@Z.c)
 *     ??_EFxRelatedDevice@@UEAAPEAXI@Z @ 0x1C0090C40 (--_EFxRelatedDevice@@UEAAPEAXI@Z.c)
 *     ??_GFxSyncRequest@@UEAAPEAXI@Z @ 0x1C0090CA0 (--_GFxSyncRequest@@UEAAPEAXI@Z.c)
 *     AddEventHooksWdfDeviceCreate @ 0x1C00BFC90 (AddEventHooksWdfDeviceCreate.c)
 *     AddEventHooksWdfIoQueueCreate @ 0x1C00C0070 (AddEventHooksWdfIoQueueCreate.c)
 *     VfAddContextToHandle @ 0x1C00C02D4 (VfAddContextToHandle.c)
 * Callees:
 *     ?FxIsPagedPoolType@@YAEW4_POOL_TYPE@@@Z @ 0x1C0004E28 (-FxIsPagedPoolType@@YAEW4_POOL_TYPE@@@Z.c)
 *     memset @ 0x1C001CA80 (memset.c)
 *     ?FxPoolRemoveNonPagedAllocateTracker@@YAXPEAUFX_POOL_TRACKER@@@Z @ 0x1C004E4A4 (-FxPoolRemoveNonPagedAllocateTracker@@YAXPEAUFX_POOL_TRACKER@@@Z.c)
 *     ?FxPoolRemovePagedAllocateTracker@@YAXPEAUFX_POOL_TRACKER@@@Z @ 0x1C005445C (-FxPoolRemovePagedAllocateTracker@@YAXPEAUFX_POOL_TRACKER@@@Z.c)
 */

void __fastcall FxPoolFree(FX_POOL_TRACKER *ptr)
{
  FX_POOL_TRACKER *CallersAddress; // rbx
  ULONG_PTR retaddr; // [rsp+38h] [rbp+0h]

  if ( !ptr )
    KeBugCheckEx(0x10Du, 4uLL, 0LL, retaddr, 0LL);
  if ( ((unsigned __int16)ptr & 0xFFF) != 0 )
  {
    CallersAddress = (FX_POOL_TRACKER *)ptr[-1].CallersAddress;
    if ( *(_BYTE *)(*((_QWORD *)&ptr[-1].CallersAddress + 1) + 264LL) )
    {
      if ( FxIsPagedPoolType(CallersAddress->PoolType) )
        FxPoolRemovePagedAllocateTracker(CallersAddress);
      else
        FxPoolRemoveNonPagedAllocateTracker(CallersAddress);
      memset(CallersAddress, 0, CallersAddress->Size + 64);
    }
    ptr = CallersAddress;
  }
  ExFreePoolWithTag(ptr, 0);
}
