/*
 * XREFs of ??1?$DynArrayImpl@$0A@@@IEAA@XZ @ 0x180027988
 * Callers:
 *     ??_GCAnimationResource@@IEAAPEAXI@Z @ 0x180007A2C (--_GCAnimationResource@@IEAAPEAXI@Z.c)
 *     ??_GCCrossFade@@UEAAPEAXI@Z @ 0x180008BC0 (--_GCCrossFade@@UEAAPEAXI@Z.c)
 *     ?StartAnimation@CLoginTransition@@QEAAJHPEAVCVisual@@0_K@Z @ 0x18000B148 (-StartAnimation@CLoginTransition@@QEAAJHPEAVCVisual@@0_K@Z.c)
 *     ??_GCPropertyChangeRecord@CWindowPropertyTracker@@QEAAPEAXI@Z @ 0x18000BD78 (--_GCPropertyChangeRecord@CWindowPropertyTracker@@QEAAPEAXI@Z.c)
 *     ?NotifyRepresentationChanged@CWindowData@@QEAAJXZ @ 0x180016B00 (-NotifyRepresentationChanged@CWindowData@@QEAAJXZ.c)
 *     ?UpdateScene@CWindowList@@UEAAJXZ @ 0x180018490 (-UpdateScene@CWindowList@@UEAAJXZ.c)
 *     ?MoveTransitionAndTouchVisualToFront@CWindowList@@QEAAJXZ @ 0x18001A650 (-MoveTransitionAndTouchVisualToFront@CWindowList@@QEAAJXZ.c)
 *     ?GDISurfaceChange@CWindowList@@UEAAJPEAUIDwmWindow@@@Z @ 0x18001A880 (-GDISurfaceChange@CWindowList@@UEAAJPEAUIDwmWindow@@@Z.c)
 *     ??1CSecondaryWindowRepresentation@@MEAA@XZ @ 0x180027564 (--1CSecondaryWindowRepresentation@@MEAA@XZ.c)
 *     ??1CButton@@MEAA@XZ @ 0x1800278B4 (--1CButton@@MEAA@XZ.c)
 *     ?ScheduleStartAnimation@CStoryboard@@QEAAJXZ @ 0x180035ABC (-ScheduleStartAnimation@CStoryboard@@QEAAJXZ.c)
 *     ?Release@CAnimationEngine@@UEAAKXZ @ 0x180035CA0 (-Release@CAnimationEngine@@UEAAKXZ.c)
 *     ??1CDWMDXGIEnumeration@@MEAA@XZ @ 0x1800379D8 (--1CDWMDXGIEnumeration@@MEAA@XZ.c)
 *     ?CreateMonitorRenderTargetsLegacy@CDesktopManager@@AEAAJXZ @ 0x180037AFC (-CreateMonitorRenderTargetsLegacy@CDesktopManager@@AEAAJXZ.c)
 *     ??1CDWMDXGIAdapter@@EEAA@XZ @ 0x1800384D8 (--1CDWMDXGIAdapter@@EEAA@XZ.c)
 *     ??_GCDWMDisplaySet@@QEAAPEAXI@Z @ 0x1800394B0 (--_GCDWMDisplaySet@@QEAAPEAXI@Z.c)
 *     ?IsEquivalentRotated@CDWMDisplaySet@@QEBA_NPEBV1@@Z @ 0x1800399AC (-IsEquivalentRotated@CDWMDisplaySet@@QEBA_NPEBV1@@Z.c)
 *     ?FireTimeEvents@CDesktopManager@@AEAAJPEA_N@Z @ 0x18003B878 (-FireTimeEvents@CDesktopManager@@AEAAJPEA_N@Z.c)
 *     ??_GCImmersiveState@@EEAAPEAXI@Z @ 0x18003C5D0 (--_GCImmersiveState@@EEAAPEAXI@Z.c)
 *     ??1CWindowIconic@@MEAA@XZ @ 0x180044378 (--1CWindowIconic@@MEAA@XZ.c)
 *     ??1WindowFrame@CTopLevelWindow@@UEAA@XZ @ 0x18004F158 (--1WindowFrame@CTopLevelWindow@@UEAA@XZ.c)
 *     ??1CBitmap@@UEAA@XZ @ 0x1800509E0 (--1CBitmap@@UEAA@XZ.c)
 *     ??1DPIImages@WindowFrame@CTopLevelWindow@@QEAA@XZ @ 0x180051160 (--1DPIImages@WindowFrame@CTopLevelWindow@@QEAA@XZ.c)
 *     ?OnProcessDisconnected@CProjectionBorderManager@@UEAAJK@Z @ 0x1800572C0 (-OnProcessDisconnected@CProjectionBorderManager@@UEAAJK@Z.c)
 *     ??1?$DynArray@PEAUUnifiedTargetRect@CStoryboard@@$0A@@@QEAA@XZ @ 0x180057CA4 (--1-$DynArray@PEAUUnifiedTargetRect@CStoryboard@@$0A@@@QEAA@XZ.c)
 *     ??_GUnifiedTargetRect@CStoryboard@@QEAAPEAXI@Z @ 0x180057CC4 (--_GUnifiedTargetRect@CStoryboard@@QEAAPEAXI@Z.c)
 *     _dynamic_atexit_destructor_for__CTopLevelWindow::s_rgpwfWindowFrames__ @ 0x180058AF0 (_dynamic_atexit_destructor_for__CTopLevelWindow--s_rgpwfWindowFrames__.c)
 *     _dynamic_atexit_destructor_for__CWindowIconic::s_rgpBitmapPendingImages__ @ 0x180058B00 (_dynamic_atexit_destructor_for__CWindowIconic--s_rgpBitmapPendingImages__.c)
 *     ?CalculateRotationAngles@CDWMDisplaySet@@SAJPEBV1@0PEAH1@Z @ 0x180080774 (-CalculateRotationAngles@CDWMDisplaySet@@SAJPEBV1@0PEAH1@Z.c)
 *     ??1AtlasedRects@@QEAA@XZ @ 0x180080894 (--1AtlasedRects@@QEAA@XZ.c)
 *     ??1CLivePreview@@MEAA@XZ @ 0x18008169C (--1CLivePreview@@MEAA@XZ.c)
 *     ?_AnimateOpaqueVisuals@CLivePreview@@AEAAJPEAVCWindowData@@@Z @ 0x18008231C (-_AnimateOpaqueVisuals@CLivePreview@@AEAAJPEAVCWindowData@@@Z.c)
 *     ?_CollectWindows@CLivePreview@@AEAAJXZ @ 0x180082A5C (-_CollectWindows@CLivePreview@@AEAAJXZ.c)
 *     ?_FadeOutToGlass@CLivePreview@@AEAAJPEBVCWindowData@@@Z @ 0x180082FA8 (-_FadeOutToGlass@CLivePreview@@AEAAJPEBVCWindowData@@@Z.c)
 *     ?_StartAnimateOpaqueVisuals@CLivePreview@@AEAAJAEBV?$DynArray@PEAVCWindowData@@$0A@@@_N@Z @ 0x180084094 (-_StartAnimateOpaqueVisuals@CLivePreview@@AEAAJAEBV-$DynArray@PEAVCWindowData@@$0A@@@_N@Z.c)
 *     ??1CDesktopManager@@EEAA@XZ @ 0x180085860 (--1CDesktopManager@@EEAA@XZ.c)
 *     ??_GCAnimationClockCoordinator@@QEAAPEAXI@Z @ 0x180085B74 (--_GCAnimationClockCoordinator@@QEAAPEAXI@Z.c)
 *     ??_GCTransitionVisualController@@QEAAPEAXI@Z @ 0x180085D38 (--_GCTransitionVisualController@@QEAAPEAXI@Z.c)
 *     ?CreateMonitorRenderTargetsDDisplay@CDesktopManager@@AEAAJXZ @ 0x1800860C8 (-CreateMonitorRenderTargetsDDisplay@CDesktopManager@@AEAAJXZ.c)
 *     ?ReleaseDCompResources@CDesktopManager@@AEAAXXZ @ 0x180087328 (-ReleaseDCompResources@CDesktopManager@@AEAAXXZ.c)
 *     ?ReleaseMonitorRenderTargets@CDesktopManager@@AEAAJXZ @ 0x180087558 (-ReleaseMonitorRenderTargets@CDesktopManager@@AEAAJXZ.c)
 *     ?RemoveElement@?$CGenericTableMap@T_LARGE_INTEGER@@UCAPTURE_DISPLAY_MAP_ENTRY@CProjectionBorderManager@@@@QEAAHPEAUCAPTURE_DISPLAY_MAP_ENTRY@CProjectionBorderManager@@@Z @ 0x180087618 (-RemoveElement@-$CGenericTableMap@T_LARGE_INTEGER@@UCAPTURE_DISPLAY_MAP_ENTRY@CProjectionBorderM.c)
 *     ?UpdateEnableClearForRenderTargets@CDesktopManager@@QEAAXXZ @ 0x180087764 (-UpdateEnableClearForRenderTargets@CDesktopManager@@QEAAXXZ.c)
 *     ?UpdateSDRToHDRBoost@CDesktopManager@@QEAAJPEAUHMONITOR__@@M@Z @ 0x180087824 (-UpdateSDRToHDRBoost@CDesktopManager@@QEAAJPEAUHMONITOR__@@M@Z.c)
 *     ??1CIconicBitmapRegistry@@UEAA@XZ @ 0x180089598 (--1CIconicBitmapRegistry@@UEAA@XZ.c)
 *     ??1CImmersiveIconicBitmapRegistry@@UEAA@XZ @ 0x18008A028 (--1CImmersiveIconicBitmapRegistry@@UEAA@XZ.c)
 *     ??_GCImmersiveIconicResource@CImmersiveIconicBitmapRegistry@@QEAAPEAXI@Z @ 0x18008A08C (--_GCImmersiveIconicResource@CImmersiveIconicBitmapRegistry@@QEAAPEAXI@Z.c)
 *     ?FindElement@?$CGenericTableMap@T_LARGE_INTEGER@@UCAPTURE_DISPLAY_MAP_ENTRY@CProjectionBorderManager@@@@QEAAPEAUCAPTURE_DISPLAY_MAP_ENTRY@CProjectionBorderManager@@T_LARGE_INTEGER@@@Z @ 0x18008E8D8 (-FindElement@-$CGenericTableMap@T_LARGE_INTEGER@@UCAPTURE_DISPLAY_MAP_ENTRY@CProjectionBorderMan.c)
 *     ?_AddDisplayCaptureEntry@CProjectionBorderManager@@AEAAJPEAUHMONITOR__@@PEAVCCaptureControllerProxy@@AEBUDWM_CAPTURE_TOKEN@@_N@Z @ 0x1800917AC (-_AddDisplayCaptureEntry@CProjectionBorderManager@@AEAAJPEAUHMONITOR__@@PEAVCCaptureControllerPr.c)
 *     ?_AddProjectionBorderForAllDisplays@CProjectionBorderManager@@AEAAJAEBUDWM_CAPTURE_TOKEN@@@Z @ 0x180091928 (-_AddProjectionBorderForAllDisplays@CProjectionBorderManager@@AEAAJAEBUDWM_CAPTURE_TOKEN@@@Z.c)
 *     ??1CAccentBlurBehind@@EEAA@XZ @ 0x180093A70 (--1CAccentBlurBehind@@EEAA@XZ.c)
 *     ??_GVisualCollection@@UEAAPEAXI@Z @ 0x180095E50 (--_GVisualCollection@@UEAAPEAXI@Z.c)
 *     ??1CWindowList@@UEAA@XZ @ 0x1800960E4 (--1CWindowList@@UEAA@XZ.c)
 *     ??_GCDCompVirtualDesktopThumbnailData@@UEAAPEAXI@Z @ 0x180096450 (--_GCDCompVirtualDesktopThumbnailData@@UEAAPEAXI@Z.c)
 *     ??1CContactManager@@QEAA@XZ @ 0x18009D668 (--1CContactManager@@QEAA@XZ.c)
 *     ??1CContactStationaryVisual@@MEAA@XZ @ 0x1800A1A38 (--1CContactStationaryVisual@@MEAA@XZ.c)
 *     ?TriangulatePathGeometry@CTouchDragVisualHelper@@SAJMPEBV?$DynArray@UTOUCH_DRAG_POINT@@$0A@@@PEBUtagRECT@@PEAV?$DynArray@UMilPoint3F@@$0A@@@PEAV?$DynArray@UMilPoint2D@@$0A@@@PEAV?$DynArray@I$0A@@@PEAV?$DynArray@K$0A@@@@Z @ 0x1800A35A4 (-TriangulatePathGeometry@CTouchDragVisualHelper@@SAJMPEBV-$DynArray@UTOUCH_DRAG_POINT@@$0A@@@PEB.c)
 *     ??1CTouchDragVisual@@MEAA@XZ @ 0x1800A4224 (--1CTouchDragVisual@@MEAA@XZ.c)
 *     ??1Mesh2D@@QEAA@XZ @ 0x1800A42BC (--1Mesh2D@@QEAA@XZ.c)
 *     ??1CPenPressHoldVisual@@MEAA@XZ @ 0x1800A694C (--1CPenPressHoldVisual@@MEAA@XZ.c)
 *     ?MidDelayExpired@CScreenRotation@@AEAAJXZ @ 0x1800ACAB0 (-MidDelayExpired@CScreenRotation@@AEAAJXZ.c)
 *     ?PreDelayExpired@CScreenRotation@@AEAAJXZ @ 0x1800ACF4C (-PreDelayExpired@CScreenRotation@@AEAAJXZ.c)
 *     ??1CIndirectTouchVisual@@MEAA@XZ @ 0x1800AD9EC (--1CIndirectTouchVisual@@MEAA@XZ.c)
 *     ??1CAnimationScheduler@@QEAA@XZ @ 0x1800AE5A0 (--1CAnimationScheduler@@QEAA@XZ.c)
 *     ??1CAppArrangementImmediate@@UEAA@XZ @ 0x1800AE89C (--1CAppArrangementImmediate@@UEAA@XZ.c)
 *     ??_GCAppArrangementDelayed@@UEAAPEAXI@Z @ 0x1800AEA70 (--_GCAppArrangementDelayed@@UEAAPEAXI@Z.c)
 *     ??_GCAppSwitch@@UEAAPEAXI@Z @ 0x1800AEB80 (--_GCAppSwitch@@UEAAPEAXI@Z.c)
 *     ??_ECVirtualDesktopSwitch@@UEAAPEAXI@Z @ 0x1800AEC40 (--_ECVirtualDesktopSwitch@@UEAAPEAXI@Z.c)
 *     ?StartAnimation@CAccentTransition@@QEAAJPEBUACCENT_POLICY@@PEAVCAccent@@@Z @ 0x1800B5D24 (-StartAnimation@CAccentTransition@@QEAAJPEBUACCENT_POLICY@@PEAVCAccent@@@Z.c)
 *     ??1CDesktopThumbnailBase@@MEAA@XZ @ 0x1800B6198 (--1CDesktopThumbnailBase@@MEAA@XZ.c)
 *     ??_ECDesktopThumbnail@@MEAAPEAXI@Z @ 0x1800B6310 (--_ECDesktopThumbnail@@MEAAPEAXI@Z.c)
 *     ??1CPerMonitorWindowRepresentation@@MEAA@XZ @ 0x1800BEA38 (--1CPerMonitorWindowRepresentation@@MEAA@XZ.c)
 *     ?Validate@CPerMonitorWindowRepresentation@@QEAAJPEAVCWindowData@@@Z @ 0x1800BF14C (-Validate@CPerMonitorWindowRepresentation@@QEAAJPEAVCWindowData@@@Z.c)
 * Callees:
 *     _guard_dispatch_icall_nop @ 0x1800581D0 (_guard_dispatch_icall_nop.c)
 */

__int64 __fastcall DynArrayImpl<0>::~DynArrayImpl<0>(_QWORD *a1)
{
  __int64 result; // rax

  if ( *a1 != a1[1] )
  {
    result = (*(__int64 (__fastcall **)(WPF::HeapBase *))(*(_QWORD *)WPF::g_pProcessHeap + 32LL))(WPF::g_pProcessHeap);
    *a1 = 0LL;
  }
  return result;
}
