/*
 * XREFs of ZwUpdateWnfStateData @ 0x1406AAFD0
 * Callers:
 *     FsRtlSendModernAppTermination @ 0x14048F270 (FsRtlSendModernAppTermination.c)
 *     PopDevicePowerTransitionInProgressWorker @ 0x140493870 (PopDevicePowerTransitionInProgressWorker.c)
 *     BapdWriteEtwEvents @ 0x14049F614 (BapdWriteEtwEvents.c)
 *     PpmPerfUpdateMultimediaPowerModel @ 0x1404AA2EC (PpmPerfUpdateMultimediaPowerModel.c)
 *     PopFxClearDeviceConstraints @ 0x1404CDF98 (PopFxClearDeviceConstraints.c)
 *     PopThermalStandbyNotify @ 0x1405D14B0 (PopThermalStandbyNotify.c)
 *     PopThermalSxExit @ 0x1405D1508 (PopThermalSxExit.c)
 *     PopPepPlatformStateRegistered @ 0x1405D8BE8 (PopPepPlatformStateRegistered.c)
 *     RtlRaiseCustomSystemEventTrigger @ 0x1405ED4D0 (RtlRaiseCustomSystemEventTrigger.c)
 *     ExpSetSoftRebootFlags @ 0x14065186C (ExpSetSoftRebootFlags.c)
 *     ExpPlProcessNotifications @ 0x1406538D0 (ExpPlProcessNotifications.c)
 *     MiBadPageSignaler @ 0x140674790 (MiBadPageSignaler.c)
 *     MmMarkPhysicalMemoryAsBad @ 0x140675D20 (MmMarkPhysicalMemoryAsBad.c)
 *     PpDevCfgRequestDeviceInstall @ 0x1406F8BD0 (PpDevCfgRequestDeviceInstall.c)
 *     FsRtlpDedupChangeRegisterVolume @ 0x14070A880 (FsRtlpDedupChangeRegisterVolume.c)
 *     FsRtlpHeatRegisterVolume @ 0x14070B27C (FsRtlpHeatRegisterVolume.c)
 *     PiUEventBroadcastHardwareProfilesChangedEvent @ 0x140722408 (PiUEventBroadcastHardwareProfilesChangedEvent.c)
 *     PiUEventBroadcastPortsChangedEvent @ 0x140722498 (PiUEventBroadcastPortsChangedEvent.c)
 *     PiUEventBroadcastVolumesChangedEvent @ 0x1407225F4 (PiUEventBroadcastVolumesChangedEvent.c)
 *     PiNotifyCiDriverBlocked @ 0x140722830 (PiNotifyCiDriverBlocked.c)
 *     PiDrvDbDriverStoreNodesUpdated @ 0x140734B7C (PiDrvDbDriverStoreNodesUpdated.c)
 *     PopSetupMixedRealitytNotification @ 0x14074715C (PopSetupMixedRealitytNotification.c)
 *     PopThermalHandlePreviousShutdown @ 0x14075265C (PopThermalHandlePreviousShutdown.c)
 *     PopUpdateOverThrottledCount @ 0x140752E84 (PopUpdateOverThrottledCount.c)
 *     PopPowerAggregatorEngageModernStandby @ 0x140757974 (PopPowerAggregatorEngageModernStandby.c)
 *     PopCheckCachedPowerSourceStateUpdates @ 0x140759BB0 (PopCheckCachedPowerSourceStateUpdates.c)
 *     PopEvaluateWeakChargerStateV1 @ 0x140759DB0 (PopEvaluateWeakChargerStateV1.c)
 *     PopPowerAdapterAdd @ 0x14075A030 (PopPowerAdapterAdd.c)
 *     PopPowerAdapterPublishRecState @ 0x14075A5D4 (PopPowerAdapterPublishRecState.c)
 *     PopPowerAdapterReinitialize @ 0x14075AA58 (PopPowerAdapterReinitialize.c)
 *     PopPowerAdapterRemove @ 0x14075AD90 (PopPowerAdapterRemove.c)
 *     PopNetDisengageNetworkRefresh @ 0x14075B798 (PopNetDisengageNetworkRefresh.c)
 *     PopNetRefreshTimerWorkerCallback @ 0x14075B920 (PopNetRefreshTimerWorkerCallback.c)
 *     PopPublishPowerButtonState @ 0x14075BC84 (PopPublishPowerButtonState.c)
 *     PopSendFanNoiseChangeWnf @ 0x14075BF00 (PopSendFanNoiseChangeWnf.c)
 *     PdcPoNetworkResiliency @ 0x14075C0B0 (PdcPoNetworkResiliency.c)
 *     PopEsPublishStateV2 @ 0x14075C528 (PopEsPublishStateV2.c)
 *     PopEsUpdateSetting @ 0x14075C768 (PopEsUpdateSetting.c)
 *     PopModernStandbyNotificationCallback @ 0x14075D970 (PopModernStandbyNotificationCallback.c)
 *     PopDripsWatchdogCheckHwDivergence @ 0x14075EE54 (PopDripsWatchdogCheckHwDivergence.c)
 *     TtmpUpdatePrimaryDisplayWnf @ 0x140769CAC (TtmpUpdatePrimaryDisplayWnf.c)
 *     TtmpTerminalInactivityWorkerRoutine @ 0x140770650 (TtmpTerminalInactivityWorkerRoutine.c)
 *     PspSendNoWakeChargeLimitNotification @ 0x140777E50 (PspSendNoWakeChargeLimitNotification.c)
 *     EtwpNotifyProcessTracingChange @ 0x1407AA6B8 (EtwpNotifyProcessTracingChange.c)
 *     ExpCrossVmIntHostCallback @ 0x1407C5950 (ExpCrossVmIntHostCallback.c)
 *     MiNotifyMemoryChange @ 0x1407EA2CC (MiNotifyMemoryChange.c)
 *     PspClearNoWakeChargeLimitNotification @ 0x14085F384 (PspClearNoWakeChargeLimitNotification.c)
 *     PspChargeProcessWakeCounter @ 0x1408999A0 (PspChargeProcessWakeCounter.c)
 *     PiUEventNotifyTargetDeviceChange @ 0x1408CFD00 (PiUEventNotifyTargetDeviceChange.c)
 *     PspAllocateAndQueryProcessNotificationChannel @ 0x140912870 (PspAllocateAndQueryProcessNotificationChannel.c)
 *     SPCallServerHandleQueryPolicy @ 0x14095F70C (SPCallServerHandleQueryPolicy.c)
 *     PipCallDriverAddDevice @ 0x140980ED0 (PipCallDriverAddDevice.c)
 *     TtmNotifySessionDisplayRequiredChange @ 0x14099D3C4 (TtmNotifySessionDisplayRequiredChange.c)
 *     PopSetPowerSettingValue @ 0x1409A2EB4 (PopSetPowerSettingValue.c)
 *     PopEvaluateGlobalUserStatus @ 0x1409A35E8 (PopEvaluateGlobalUserStatus.c)
 *     PopDispatchNotificationsToList @ 0x1409A4CC8 (PopDispatchNotificationsToList.c)
 *     DbgkpStartSystemErrorHandler @ 0x1409E9F88 (DbgkpStartSystemErrorHandler.c)
 *     PiUEventNotifyUserMode @ 0x1409ECA04 (PiUEventNotifyUserMode.c)
 *     NtPowerInformation @ 0x1409EDB00 (NtPowerInformation.c)
 *     PiUEventNotifyClientPendingEvent @ 0x140A0B608 (PiUEventNotifyClientPendingEvent.c)
 *     PopPolicyTimeChange @ 0x140A0C160 (PopPolicyTimeChange.c)
 *     PopUpdateConsoleDisplayState @ 0x140A1B91C (PopUpdateConsoleDisplayState.c)
 *     CmFcpManagerPublishChangeNotifications @ 0x140A2B2EC (CmFcpManagerPublishChangeNotifications.c)
 *     RtlpFcNotifyFeatureUsageTarget @ 0x140A2B8E4 (RtlpFcNotifyFeatureUsageTarget.c)
 *     PopBatteryApplyCompositeState @ 0x140A304E8 (PopBatteryApplyCompositeState.c)
 *     PopSetBatteryDischargingState @ 0x140A31788 (PopSetBatteryDischargingState.c)
 *     PiDcGenerateConfigNotificationIfContainerRequiresConfiguration @ 0x140A3802C (PiDcGenerateConfigNotificationIfContainerRequiresConfiguration.c)
 *     PspJobNotificationWorker @ 0x140A3AAD0 (PspJobNotificationWorker.c)
 *     PopPowerAggregatorHandleActiveIntent @ 0x140A3ABE0 (PopPowerAggregatorHandleActiveIntent.c)
 *     PiUEventBroadcastDevnodesChangedEvent @ 0x140A568C0 (PiUEventBroadcastDevnodesChangedEvent.c)
 *     PopEvaluateWeakChargerState @ 0x140A67028 (PopEvaluateWeakChargerState.c)
 *     PopPowerAggregatorDisengageModernStandby @ 0x140A6DED8 (PopPowerAggregatorDisengageModernStandby.c)
 *     PopSleepstudySendSessionChangeWnf @ 0x140A74190 (PopSleepstudySendSessionChangeWnf.c)
 *     ExpRefreshTimeZoneInformation @ 0x140A7981C (ExpRefreshTimeZoneInformation.c)
 *     CmFcpManagerPublishFeatureUsageDataBuffers @ 0x140A7ABB4 (CmFcpManagerPublishFeatureUsageDataBuffers.c)
 *     PopPowerRequestCallbackPerfBoostRequired @ 0x140A91980 (PopPowerRequestCallbackPerfBoostRequired.c)
 *     PopNetPublishWnfStateUpdate @ 0x140A93E94 (PopNetPublishWnfStateUpdate.c)
 *     PopFxUpdateVetoMaskWork @ 0x140A97B30 (PopFxUpdateVetoMaskWork.c)
 *     PiDcContainerRequiresConfiguration @ 0x140A99C50 (PiDcContainerRequiresConfiguration.c)
 *     PopSleepstudySendWnfNotification @ 0x140AA915C (PopSleepstudySendWnfNotification.c)
 *     PopUpdateBackgroundCoolingStatus @ 0x140AB7704 (PopUpdateBackgroundCoolingStatus.c)
 *     PopPowerInformationInternal @ 0x140AC2410 (PopPowerInformationInternal.c)
 *     PopEvaluateInputSuppressionAction @ 0x140AC5570 (PopEvaluateInputSuppressionAction.c)
 *     PopBatteryWorker @ 0x140AC5DB0 (PopBatteryWorker.c)
 *     PopTransitionSystemPowerStateEx @ 0x140B6891C (PopTransitionSystemPowerStateEx.c)
 *     Phase1InitializationDiscard @ 0x140C0E048 (Phase1InitializationDiscard.c)
 *     PopInitVideoWnfState @ 0x140C2F384 (PopInitVideoWnfState.c)
 *     PopCheckShutdownMarker @ 0x140C2F7D4 (PopCheckShutdownMarker.c)
 *     PopNetInitialize @ 0x140C34034 (PopNetInitialize.c)
 *     PopAdaptiveInitializeBootContext @ 0x140C3570C (PopAdaptiveInitializeBootContext.c)
 *     EtwpInitialize @ 0x140C3F24C (EtwpInitialize.c)
 *     CmFcManagerStartRuntimePhase @ 0x140C4F31C (CmFcManagerStartRuntimePhase.c)
 *     PoInitSystem @ 0x140C63AE4 (PoInitSystem.c)
 *     PopPowerAggregatorInitialize @ 0x140C6A210 (PopPowerAggregatorInitialize.c)
 * Callees:
 *     <none>
 */

NTSTATUS __cdecl ZwUpdateWnfStateData(
        PCWNF_STATE_NAME StateName,
        const void *Buffer,
        ULONG Length,
        PCWNF_TYPE_ID TypeId,
        const void *ExplicitScope,
        WNF_CHANGE_STAMP MatchingChangeStamp,
        LOGICAL CheckStamp)
{
  _disable();
  __readeflags();
  return KiServiceInternal(StateName);
}
