/*
 * XREFs of atexit @ 0x180060F5C
 * Callers:
 *     wil::details::_dynamic_initializer_for__g_processLocalData__ @ 0x1800010A0 (wil--details--_dynamic_initializer_for__g_processLocalData__.c)
 *     wil::details::_dynamic_initializer_for__g_threadFailureCallbacks__ @ 0x1800010B0 (wil--details--_dynamic_initializer_for__g_threadFailureCallbacks__.c)
 *     _dynamic_initializer_for__ApoDataTemplate__ @ 0x1800010E0 (_dynamic_initializer_for__ApoDataTemplate__.c)
 *     _dynamic_initializer_for__TheAudioEffectsWatcherFactory__ @ 0x1800010F0 (_dynamic_initializer_for__TheAudioEffectsWatcherFactory__.c)
 *     wil::details::_dynamic_initializer_for__g_enabledStateManager__ @ 0x180001110 (wil--details--_dynamic_initializer_for__g_enabledStateManager__.c)
 *     wil::details::_dynamic_initializer_for__g_featureStateManager__ @ 0x180001130 (wil--details--_dynamic_initializer_for__g_featureStateManager__.c)
 *     _dynamic_initializer_for__g_SessionManagerProviderLock__ @ 0x1800011B0 (_dynamic_initializer_for__g_SessionManagerProviderLock__.c)
 *     _dynamic_initializer_for__g_VADServerList__ @ 0x1800011D0 (_dynamic_initializer_for__g_VADServerList__.c)
 *     _dynamic_initializer_for__g_csVadList__ @ 0x1800011E0 (_dynamic_initializer_for__g_csVadList__.c)
 *     _dynamic_initializer_for__g_powerReferenceManager__ @ 0x180001200 (_dynamic_initializer_for__g_powerReferenceManager__.c)
 *     _dynamic_initializer_for__g_AudioJournal__ @ 0x180001210 (_dynamic_initializer_for__g_AudioJournal__.c)
 *     _dynamic_initializer_for__g_EndpointCharacteristicsTelemetryProviderRegistration__ @ 0x180001230 (_dynamic_initializer_for__g_EndpointCharacteristicsTelemetryProviderRegistration__.c)
 *     _dynamic_initializer_for__g_lstKsNotificationMonitors__ @ 0x180001250 (_dynamic_initializer_for__g_lstKsNotificationMonitors__.c)
 *     _dynamic_initializer_for__g_SarmTelemetryProviderRegistration__ @ 0x180001260 (_dynamic_initializer_for__g_SarmTelemetryProviderRegistration__.c)
 *     _dynamic_initializer_for__Sarm::CEndpointResourcePool::s_sharedPool__ @ 0x180001280 (_dynamic_initializer_for__Sarm--CEndpointResourcePool--s_sharedPool__.c)
 *     _dynamic_initializer_for__g_ListOfSpatialTech__ @ 0x180001290 (_dynamic_initializer_for__g_ListOfSpatialTech__.c)
 *     _dynamic_initializer_for__CSpatialAudioTech::s_atmosLock__ @ 0x1800012B0 (_dynamic_initializer_for__CSpatialAudioTech--s_atmosLock__.c)
 *     _dynamic_initializer_for__CSpatialAudioTech::s_spAtmosCheck__ @ 0x1800012E0 (_dynamic_initializer_for__CSpatialAudioTech--s_spAtmosCheck__.c)
 *     _dynamic_initializer_for__g_AtmosCheckCallback__ @ 0x1800012F0 (_dynamic_initializer_for__g_AtmosCheckCallback__.c)
 *     _dynamic_initializer_for__g_SpatialAudioTraceLoggingProviderRegistration__ @ 0x180001300 (_dynamic_initializer_for__g_SpatialAudioTraceLoggingProviderRegistration__.c)
 *     _dynamic_initializer_for__g_AudioEngineUtilTelemetryProviderRegistration__ @ 0x180001320 (_dynamic_initializer_for__g_AudioEngineUtilTelemetryProviderRegistration__.c)
 *     ATL::_dynamic_initializer_for___AtlComModule__ @ 0x180001340 (ATL--_dynamic_initializer_for___AtlComModule__.c)
 *     ATL::_dynamic_initializer_for__g_strheap__ @ 0x180001360 (ATL--_dynamic_initializer_for__g_strheap__.c)
 *     ATL::_dynamic_initializer_for__g_strmgr__ @ 0x1800013A0 (ATL--_dynamic_initializer_for__g_strmgr__.c)
 *     ATL::_dynamic_initializer_for___AtlBaseModule__ @ 0x1800013C0 (ATL--_dynamic_initializer_for___AtlBaseModule__.c)
 *     ATL::_dynamic_initializer_for___AtlWinModule__ @ 0x1800013E0 (ATL--_dynamic_initializer_for___AtlWinModule__.c)
 *     _dynamic_initializer_for__gEventList__ @ 0x180001400 (_dynamic_initializer_for__gEventList__.c)
 *     _dynamic_initializer_for__g_AudioLicenseTraceLoggingProviderRegistration__ @ 0x180001410 (_dynamic_initializer_for__g_AudioLicenseTraceLoggingProviderRegistration__.c)
 *     AudioServerGetAllVolumes @ 0x180003B40 (AudioServerGetAllVolumes.c)
 *     ?get@?$static_lazy@VAudioSrvTelemetryProvider@@@details@wil@@QEAAPEAVAudioSrvTelemetryProvider@@P6AXXZ@Z @ 0x180008688 (-get@-$static_lazy@VAudioSrvTelemetryProvider@@@details@wil@@QEAAPEAVAudioSrvTelemetryProvider@@.c)
 *     AudioVolumeConnect @ 0x180008720 (AudioVolumeConnect.c)
 *     s_pbmReportHostedAppStateChange @ 0x1800141B0 (s_pbmReportHostedAppStateChange.c)
 *     s_tsSessionGetAudioProtocol @ 0x180014360 (s_tsSessionGetAudioProtocol.c)
 *     s_pbmCastingAppStateChanged @ 0x180014D20 (s_pbmCastingAppStateChanged.c)
 *     s_pbmReportAppInteractivityChange @ 0x180015290 (s_pbmReportAppInteractivityChange.c)
 *     AudioServerDeriveStreamCategory @ 0x180016300 (AudioServerDeriveStreamCategory.c)
 *     s_tsRegisterAudioProtocolNotification @ 0x180016930 (s_tsRegisterAudioProtocolNotification.c)
 *     s_tsUnregisterAudioProtocolNotification @ 0x180016AB0 (s_tsUnregisterAudioProtocolNotification.c)
 *     s_pbmReportApplicationState @ 0x180016D20 (s_pbmReportApplicationState.c)
 *     ?UpdateAudioPlaybackStatus@CPlaybackNotifier@@AEAAXW4REFERENCE_OPERATION@@PEBG@Z @ 0x1800193A0 (-UpdateAudioPlaybackStatus@CPlaybackNotifier@@AEAAXW4REFERENCE_OPERATION@@PEBG@Z.c)
 *     ?GetStreamGroup@CDeviceGraphManager@@UEAAJPEAUStreamGroupParams@@KPEAUAUDIO_DEVICE_MODE_DESCRIPTOR@@PEAPEAUIStreamGroupProxy@@@Z @ 0x180019FB0 (-GetStreamGroup@CDeviceGraphManager@@UEAAJPEAUStreamGroupParams@@KPEAUAUDIO_DEVICE_MODE_DESCRIPT.c)
 *     ?ConnectStreamGroupToSaDevice@CDeviceGraphManager@@UEAAJPEAUIStreamGroupProxy@@PEAUISaDeviceProxy@@W4SUBMIX_CONNECT_OPTIONS@@PEAUSYSTEM_AUDIO_STREAM@@@Z @ 0x18001A800 (-ConnectStreamGroupToSaDevice@CDeviceGraphManager@@UEAAJPEAUIStreamGroupProxy@@PEAUISaDeviceProx.c)
 *     ?GetSaDevice@CDeviceGraphManager@@UEAAJPEAVCEndpointCharacteristics@@PEAUSaDeviceParams@@KW4_AUDCLNT_SHAREMODE@@AEAUSaDeviceResourceParams@@PEAPEAUISaDeviceProxy@@@Z @ 0x18001A970 (-GetSaDevice@CDeviceGraphManager@@UEAAJPEAVCEndpointCharacteristics@@PEAUSaDeviceParams@@KW4_AUD.c)
 *     ?CreateStream@CProcessSubmixProxy@@UEAAJPEAUIAudioStreamInfo@@PEAUSYSTEM_AUDIO_STREAM_DESCRIPTOR@@PEAUIAudioGraphCallback@@KPEAUSYSTEM_AUDIO_STREAM@@@Z @ 0x18001CEE0 (-CreateStream@CProcessSubmixProxy@@UEAAJPEAUIAudioStreamInfo@@PEAUSYSTEM_AUDIO_STREAM_DESCRIPTOR.c)
 *     ?RuntimeClassInitialize@CProcessSubmixProxy@@QEAAJPEBUProcessSubmixParams@@PEAUPROCESS_SUBMIX_DESCRIPTOR@@PEAUIStreamGroupProxy@@K@Z @ 0x18001D2B0 (-RuntimeClassInitialize@CProcessSubmixProxy@@QEAAJPEBUProcessSubmixParams@@PEAUPROCESS_SUBMIX_DE.c)
 *     ?CreateStream@CAudioResourceManager@@UEAAJPEAUIAudioProcess@@PEAUIAudioStreamInfo@@KHHHHHPEAVCEndpointCharacteristics@@KW4_AUDCLNT_SHAREMODE@@PEAUIAudioGraphCallback@@PEAUtWAVEFORMATEX@@_J6PEBU_GUID@@KPEBGKHPEBUSPATIAL_STREAM_PROPERTIES@@PEAUIProcessSubmixProxy@@PEAUSYSTEM_AUDIO_STREAM@@@Z @ 0x18001FFE0 (-CreateStream@CAudioResourceManager@@UEAAJPEAUIAudioProcess@@PEAUIAudioStreamInfo@@KHHHHHPEAVCEn.c)
 *     AudioServerCreateStream @ 0x180023040 (AudioServerCreateStream.c)
 *     AudioServerStartStream @ 0x180023310 (AudioServerStartStream.c)
 *     ?StartStream@CVADServer@@UEAAJ_KW4VadStreamStateChangeReason@@@Z @ 0x180023500 (-StartStream@CVADServer@@UEAAJ_KW4VadStreamStateChangeReason@@@Z.c)
 *     ?RecalculateVolume@CAudioStream@@UEAAJ_N_J@Z @ 0x18002E010 (-RecalculateVolume@CAudioStream@@UEAAJ_N_J@Z.c)
 *     ??0CAudioStream@@QEAA@PEAUIAudioProcess@@_NKPEAUVadServerSettings@@W4SYSTEM_AUDIO_STREAM_TYPE@@@Z @ 0x18002F260 (--0CAudioStream@@QEAA@PEAUIAudioProcess@@_NKPEAUVadServerSettings@@W4SYSTEM_AUDIO_STREAM_TYPE@@@.c)
 *     ?AudioServerInitialize_Internal@@YAJPEAXPEBGW4_AUDCLNT_SHAREMODE@@KPEBUtWAVEFORMATEX@@PEBU_GUID@@KPEAUVadServerSettings@@PEAPEAGPEAUIProcessSubmixProxy@@PEAPEAX@Z @ 0x18002F7B0 (-AudioServerInitialize_Internal@@YAJPEAXPEBGW4_AUDCLNT_SHAREMODE@@KPEBUtWAVEFORMATEX@@PEBU_GUID@.c)
 *     ?AddStream@CPerStreamVolumeAudioSession@@EEAAJPEAVCAudioStream@@@Z @ 0x180035930 (-AddStream@CPerStreamVolumeAudioSession@@EEAAJPEAVCAudioStream@@@Z.c)
 *     s_rtgGetDefaultAudioEndpoint @ 0x180036970 (s_rtgGetDefaultAudioEndpoint.c)
 *     ?SafeRegCreateKeyEx@@YAJPEAUHKEY__@@PEBGKPEAGKKPEAU_SECURITY_ATTRIBUTES@@PEAPEAU1@PEAK@Z @ 0x1800415DC (-SafeRegCreateKeyEx@@YAJPEAUHKEY__@@PEBGKPEAGKKPEAU_SECURITY_ATTRIBUTES@@PEAPEAU1@PEAK@Z.c)
 *     AudioServerStopStream @ 0x180043420 (AudioServerStopStream.c)
 *     AudioServerDestroyStream @ 0x180043620 (AudioServerDestroyStream.c)
 *     ?DestroyStream@CProcessSubmixProxy@@UEAAJPEAUIAudioStreamInfo@@@Z @ 0x1800448C0 (-DestroyStream@CProcessSubmixProxy@@UEAAJPEAUIAudioStreamInfo@@@Z.c)
 *     ??1CProcessSubmixProxy@@MEAA@XZ @ 0x180044CC0 (--1CProcessSubmixProxy@@MEAA@XZ.c)
 *     ?DestroyStream@CAudioResourceManager@@UEAAJPEAUISubmixProxy@@PEAUIAudioStreamInfo@@@Z @ 0x1800452B0 (-DestroyStream@CAudioResourceManager@@UEAAJPEAUISubmixProxy@@PEAUIAudioStreamInfo@@@Z.c)
 *     ??1CSaDeviceProxy@@MEAA@XZ @ 0x180045E20 (--1CSaDeviceProxy@@MEAA@XZ.c)
 *     ?StopStream@CVADServer@@UEAAJ_KW4VadStreamStateChangeReason@@@Z @ 0x180048360 (-StopStream@CVADServer@@UEAAJ_KW4VadStreamStateChangeReason@@@Z.c)
 *     AudioServerDisconnect @ 0x180049220 (AudioServerDisconnect.c)
 *     __scrt_initialize_thread_safe_statics @ 0x180061050 (__scrt_initialize_thread_safe_statics.c)
 *     ?get@?$static_lazy@VNUIAudioTracing@@@details@wil@@QEAAPEAVNUIAudioTracing@@P6AXXZ@Z @ 0x18010E104 (-get@-$static_lazy@VNUIAudioTracing@@@details@wil@@QEAAPEAVNUIAudioTracing@@P6AXXZ@Z.c)
 * Callees:
 *     _onexit @ 0x180060F0C (_onexit.c)
 */

int __cdecl atexit(void (__cdecl *a1)())
{
  return (onexit((_onexit_t)a1) != 0LL) - 1;
}
