/*
 * XREFs of PopFxBugCheck @ 0x1405890D0
 * Callers:
 *     PoFxActivateComponent @ 0x140287520 (PoFxActivateComponent.c)
 *     PopFxHandleReportDevicePoweredOn @ 0x14028D2E0 (PopFxHandleReportDevicePoweredOn.c)
 *     PopFxCompleteDevicePowerRequired @ 0x140310D70 (PopFxCompleteDevicePowerRequired.c)
 *     PopFxDispatchPluginWorkOnce @ 0x140311E14 (PopFxDispatchPluginWorkOnce.c)
 *     PopFxDisableWorkOrderWatchdog @ 0x140312058 (PopFxDisableWorkOrderWatchdog.c)
 *     PopFxAddRefDevice @ 0x140312734 (PopFxAddRefDevice.c)
 *     PopFxProcessWork @ 0x1403128C4 (PopFxProcessWork.c)
 *     PopFxIdleComponent @ 0x140313250 (PopFxIdleComponent.c)
 *     PopPluginDevicePower @ 0x140313500 (PopPluginDevicePower.c)
 *     PopPluginComponentActive @ 0x140313A1C (PopPluginComponentActive.c)
 *     PopPepCompleteActivity @ 0x1403142B0 (PopPepCompleteActivity.c)
 *     PopPepTriggerActivity @ 0x14031438C (PopPepTriggerActivity.c)
 *     PopPluginNotifyActive @ 0x140314B24 (PopPluginNotifyActive.c)
 *     PopPluginPrepareDevice @ 0x140321C30 (PopPluginPrepareDevice.c)
 *     PopFxActivateDevice @ 0x140322EF0 (PopFxActivateDevice.c)
 *     PoFxCompleteIdleCondition @ 0x1403574A0 (PoFxCompleteIdleCondition.c)
 *     PopPluginComponentIdleState @ 0x14035C600 (PopPluginComponentIdleState.c)
 *     PopPepUpdateIdleStateRefCount @ 0x14035E14C (PopPepUpdateIdleStateRefCount.c)
 *     PopFxIdleTimeoutDpcRoutine @ 0x14036C130 (PopFxIdleTimeoutDpcRoutine.c)
 *     PoFxCompleteDevicePowerNotRequired @ 0x14036E940 (PoFxCompleteDevicePowerNotRequired.c)
 *     PopPluginRegisterDevice @ 0x140397930 (PopPluginRegisterDevice.c)
 *     PoFxRegisterDripsWatchdogCallback @ 0x1403B44D0 (PoFxRegisterDripsWatchdogCallback.c)
 *     PoFxIssueComponentPerfStateChangeMultiple @ 0x1405883F0 (PoFxIssueComponentPerfStateChangeMultiple.c)
 *     PopFxCompleteDirectedPowerTransition @ 0x140589B8C (PopFxCompleteDirectedPowerTransition.c)
 *     PopFxDerefAndCompleteDirectedPowerTransition @ 0x14058A068 (PopFxDerefAndCompleteDirectedPowerTransition.c)
 *     PopFxIssueComponentPerfStateChanges @ 0x14058B0A8 (PopFxIssueComponentPerfStateChanges.c)
 *     PopFxIssueDirectedPowerTransition @ 0x14058B2E4 (PopFxIssueDirectedPowerTransition.c)
 *     PopFxTransitionCriticalResource @ 0x14058C540 (PopFxTransitionCriticalResource.c)
 *     PopFxWorkOrderWatchdog @ 0x14058CB10 (PopFxWorkOrderWatchdog.c)
 *     PopPluginAbandonDevice @ 0x14058CB38 (PopPluginAbandonDevice.c)
 *     PopPluginQueryComponentPerfSet @ 0x14058CBDC (PopPluginQueryComponentPerfSet.c)
 *     PopPluginQueryComponentPerfSetName @ 0x14058CC88 (PopPluginQueryComponentPerfSetName.c)
 *     PopPluginQueryComponentPerfStates @ 0x14058CD14 (PopPluginQueryComponentPerfStates.c)
 *     PopPluginQueryCurrentComponentPerfState @ 0x14058CD6C (PopPluginQueryCurrentComponentPerfState.c)
 *     PopPluginRequestComponentPerfState @ 0x14058CED8 (PopPluginRequestComponentPerfState.c)
 *     PopPluginUnregisterDevice @ 0x14058D06C (PopPluginUnregisterDevice.c)
 *     PopTranslateDependencyArray @ 0x14058D46C (PopTranslateDependencyArray.c)
 *     PopFxDebuggerPowerCriticalTransitionCallback @ 0x14059A030 (PopFxDebuggerPowerCriticalTransitionCallback.c)
 *     PopPepInitializeDebuggerMasks @ 0x14059F6B0 (PopPepInitializeDebuggerMasks.c)
 *     PopPepInitializeVetoMasks @ 0x14059F7B4 (PopPepInitializeVetoMasks.c)
 *     PopFxAcpiForwardPepAcpiNotifyRequest @ 0x1405A113C (PopFxAcpiForwardPepAcpiNotifyRequest.c)
 *     PopFxAcpiForwardPepWorkRequest @ 0x1405A11D8 (PopFxAcpiForwardPepWorkRequest.c)
 *     PopPluginAcpiNotificationStrict @ 0x1405A311C (PopPluginAcpiNotificationStrict.c)
 *     PopFxRegisterDevice @ 0x14083681C (PopFxRegisterDevice.c)
 *     PopFxRegisterDeviceWorker @ 0x1408369AC (PopFxRegisterDeviceWorker.c)
 *     PoFxRegisterComponentPerfStates @ 0x140984A10 (PoFxRegisterComponentPerfStates.c)
 *     PopFxInitializeSocSubsystemStaticInfo @ 0x140984E30 (PopFxInitializeSocSubsystemStaticInfo.c)
 *     PopFxLogSocSubsystemMetadata @ 0x1409853EC (PopFxLogSocSubsystemMetadata.c)
 *     PopFxPepPerfInfoQuery @ 0x140985944 (PopFxPepPerfInfoQuery.c)
 *     PopFxResetSocSubsystemAccounting @ 0x140985F5C (PopFxResetSocSubsystemAccounting.c)
 *     PopPluginInitializeSocSubsystemStaticInfo @ 0x140986548 (PopPluginInitializeSocSubsystemStaticInfo.c)
 *     PopPluginQuerySocSubsystemBlockingTime @ 0x140986678 (PopPluginQuerySocSubsystemBlockingTime.c)
 *     PopPluginQuerySocSubsystemCount @ 0x140986754 (PopPluginQuerySocSubsystemCount.c)
 *     PopPluginQuerySocSubsystemMetadata @ 0x1409867B4 (PopPluginQuerySocSubsystemMetadata.c)
 *     PopDripsWatchdogTakeAction @ 0x1409A13AC (PopDripsWatchdogTakeAction.c)
 * Callees:
 *     KeBugCheckEx @ 0x14041EDE0 (KeBugCheckEx.c)
 */

void __fastcall __noreturn PopFxBugCheck(
        ULONG_PTR BugCheckParameter1,
        ULONG_PTR BugCheckParameter2,
        ULONG_PTR BugCheckParameter3,
        ULONG_PTR BugCheckParameter4)
{
  KeBugCheckEx(0xA0u, BugCheckParameter1, BugCheckParameter2, BugCheckParameter3, BugCheckParameter4);
}
