/*
 * XREFs of ACPIInternalGetDeviceExtension @ 0x1C0001CF0
 * Callers:
 *     ACPIIoctlRegisterOpRegionHandler @ 0x1C00058B0 (ACPIIoctlRegisterOpRegionHandler.c)
 *     ACPICMButtonStartWorker @ 0x1C0007290 (ACPICMButtonStartWorker.c)
 *     ACPIProcessorStartDevice @ 0x1C0007460 (ACPIProcessorStartDevice.c)
 *     ACPIInternalSetDeviceInterface @ 0x1C00075FC (ACPIInternalSetDeviceInterface.c)
 *     ACPIFanDeviceControl @ 0x1C00077B0 (ACPIFanDeviceControl.c)
 *     ACPIRegisterForDeviceNotifications @ 0x1C0007D20 (ACPIRegisterForDeviceNotifications.c)
 *     ACPIIoctlEnumChildren @ 0x1C000819C (ACPIIoctlEnumChildren.c)
 *     ACPIThermalDeviceControl @ 0x1C0008730 (ACPIThermalDeviceControl.c)
 *     ACPIThermalCompletePendingIrps @ 0x1C00090A0 (ACPIThermalCompletePendingIrps.c)
 *     ACPIFilterIrpDeviceUsageNotificationCompletion @ 0x1C000A610 (ACPIFilterIrpDeviceUsageNotificationCompletion.c)
 *     AcpiFanEjectInterface @ 0x1C000AD24 (AcpiFanEjectInterface.c)
 *     ACPIBusIrpQueryInterface @ 0x1C000B2A0 (ACPIBusIrpQueryInterface.c)
 *     OSConvertDeviceHandleToNSHANDLE @ 0x1C000BF00 (OSConvertDeviceHandleToNSHANDLE.c)
 *     ACPIInitStartDevice @ 0x1C000BF1C (ACPIInitStartDevice.c)
 *     ACPIDetectFilterDevices @ 0x1C000CF60 (ACPIDetectFilterDevices.c)
 *     ACPIDetectPdoDevices @ 0x1C000D28C (ACPIDetectPdoDevices.c)
 *     ACPIIoctlEvalPreProcessingV1 @ 0x1C000E4C8 (ACPIIoctlEvalPreProcessingV1.c)
 *     ACPIIoctlEvalPreProcessingV1Ex @ 0x1C0010284 (ACPIIoctlEvalPreProcessingV1Ex.c)
 *     ACPIPowerNodeDiscoverDependencies @ 0x1C0027DF4 (ACPIPowerNodeDiscoverDependencies.c)
 *     ACPIBusIrpUnhandled @ 0x1C002A400 (ACPIBusIrpUnhandled.c)
 *     ACPIWakeInitializePciDevice @ 0x1C002ABE8 (ACPIWakeInitializePciDevice.c)
 *     ACPIDispatchIrpDepFilterQueryID @ 0x1C002B5E0 (ACPIDispatchIrpDepFilterQueryID.c)
 *     ACPIDispatchIrpDepPdoQueryID @ 0x1C002B6B0 (ACPIDispatchIrpDepPdoQueryID.c)
 *     ACPIFilterIrpRemoveDevice @ 0x1C002B860 (ACPIFilterIrpRemoveDevice.c)
 *     ACPIFilterFastIoDetachCallback @ 0x1C002BA80 (ACPIFilterFastIoDetachCallback.c)
 *     ACPIThermalReevaluateConstraintsWorker @ 0x1C002C450 (ACPIThermalReevaluateConstraintsWorker.c)
 *     ACPIIoctlGetDeviceSpecificData @ 0x1C002CC78 (ACPIIoctlGetDeviceSpecificData.c)
 *     ACPIFilterIrpSetPower @ 0x1C002D400 (ACPIFilterIrpSetPower.c)
 *     ACPIDockIrpSetDevicePower @ 0x1C002D594 (ACPIDockIrpSetDevicePower.c)
 *     ACPIDeviceIrpDeviceRequest @ 0x1C002D5F0 (ACPIDeviceIrpDeviceRequest.c)
 *     ACPIWakeWaitIrp @ 0x1C002DF30 (ACPIWakeWaitIrp.c)
 *     ACPIDispatchForwardOrFailPowerIrp @ 0x1C002E05C (ACPIDispatchForwardOrFailPowerIrp.c)
 *     ACPIDeviceIrpWaitWakeRequest @ 0x1C002E0E0 (ACPIDeviceIrpWaitWakeRequest.c)
 *     ACPIButtonDeviceControl @ 0x1C002FBD0 (ACPIButtonDeviceControl.c)
 *     ACPIButtonEvent @ 0x1C002FCF8 (ACPIButtonEvent.c)
 *     AcpiPccEjectInterface @ 0x1C0030558 (AcpiPccEjectInterface.c)
 *     ACPIDeviceIrpDeviceFilterRequest @ 0x1C0030ED0 (ACPIDeviceIrpDeviceFilterRequest.c)
 *     ACPIDispatchForwardPowerIrp @ 0x1C0031140 (ACPIDispatchForwardPowerIrp.c)
 *     ACPIDockIntfDereference @ 0x1C004A180 (ACPIDockIntfDereference.c)
 *     ACPIDockIrpQueryPower @ 0x1C004A1E0 (ACPIDockIrpQueryPower.c)
 *     ACPIDockIrpRemoveDevice @ 0x1C004A340 (ACPIDockIrpRemoveDevice.c)
 *     ACPIDockIrpSetSystemPower @ 0x1C004A5B4 (ACPIDockIrpSetSystemPower.c)
 *     ACPIBusIrpSetSystemPowerComplete @ 0x1C004A7E0 (ACPIBusIrpSetSystemPowerComplete.c)
 *     ACPIBuildRegRequest @ 0x1C004BF5C (ACPIBuildRegRequest.c)
 *     ACPIBusAndFilterIrpQueryRemovalRelations @ 0x1C004CCA0 (ACPIBusAndFilterIrpQueryRemovalRelations.c)
 *     ACPIBusIrpQueryPower @ 0x1C004D070 (ACPIBusIrpQueryPower.c)
 *     ACPIBusIrpRemoveDevice @ 0x1C004D150 (ACPIBusIrpRemoveDevice.c)
 *     ACPIBusIrpSetSystemPower @ 0x1C004D544 (ACPIBusIrpSetSystemPower.c)
 *     ACPIBusIrpSurpriseRemoval @ 0x1C004D790 (ACPIBusIrpSurpriseRemoval.c)
 *     ACPIDispatchIrpDepRemoveDevice @ 0x1C004DAF0 (ACPIDispatchIrpDepRemoveDevice.c)
 *     ACPICMButtonNotifyByDeviceObject @ 0x1C004E5B0 (ACPICMButtonNotifyByDeviceObject.c)
 *     ACPICMButtonSetPower @ 0x1C004E5F0 (ACPICMButtonSetPower.c)
 *     ACPICMButtonWaitWakeComplete @ 0x1C004E7D0 (ACPICMButtonWaitWakeComplete.c)
 *     ACPICMLidSetPower @ 0x1C004EB10 (ACPICMLidSetPower.c)
 *     ACPICMLidSetPowerCompletion @ 0x1C004EBB0 (ACPICMLidSetPowerCompletion.c)
 *     ACPIDeviceCancelWaitWakeIrp @ 0x1C004FDF0 (ACPIDeviceCancelWaitWakeIrp.c)
 *     ACPIDeviceIrpSystemRequest @ 0x1C0050538 (ACPIDeviceIrpSystemRequest.c)
 *     ACPIDispatchForwardIrpWithExceptions @ 0x1C0052A30 (ACPIDispatchForwardIrpWithExceptions.c)
 *     ACPIEcRemoveDevice @ 0x1C00535B0 (ACPIEcRemoveDevice.c)
 *     ACPIEcStartDevice @ 0x1C0053640 (ACPIEcStartDevice.c)
 *     ACPIEcStartDeviceWorker @ 0x1C0053890 (ACPIEcStartDeviceWorker.c)
 *     ACPIEcStopDevice @ 0x1C0053A40 (ACPIEcStopDevice.c)
 *     ACPIFanCancelRequest @ 0x1C0054DC0 (ACPIFanCancelRequest.c)
 *     ACPIFanEvent @ 0x1C0054EF0 (ACPIFanEvent.c)
 *     ACPIFilterIrpQueryPower @ 0x1C00553F0 (ACPIFilterIrpQueryPower.c)
 *     ACPIFilterIrpStopDeviceCompletion @ 0x1C00554C0 (ACPIFilterIrpStopDeviceCompletion.c)
 *     ACPIIoctlEvalPreProcessingV2 @ 0x1C00575AC (ACPIIoctlEvalPreProcessingV2.c)
 *     ACPIIoctlEvalPreProcessingV2Ex @ 0x1C0057920 (ACPIIoctlEvalPreProcessingV2Ex.c)
 *     ACPIIoctlGetDeviceInformation @ 0x1C0057C80 (ACPIIoctlGetDeviceInformation.c)
 *     ACPIIoctlUnRegisterOpRegionHandler @ 0x1C0057F9C (ACPIIoctlUnRegisterOpRegionHandler.c)
 *     AcpiPccGetInterfaceInformation @ 0x1C0059AA4 (AcpiPccGetInterfaceInformation.c)
 *     ACPIUnregisterForDeviceNotifications @ 0x1C005C260 (ACPIUnregisterForDeviceNotifications.c)
 *     ACPIProcessorContainerStartDeviceWorker @ 0x1C005D3F0 (ACPIProcessorContainerStartDeviceWorker.c)
 *     ACPIRootEvent @ 0x1C005E740 (ACPIRootEvent.c)
 *     ACPIRootIrpQueryPower @ 0x1C005E830 (ACPIRootIrpQueryPower.c)
 *     ACPIRootIrpRemoveDevice @ 0x1C005E9E0 (ACPIRootIrpRemoveDevice.c)
 *     ACPIRootIrpSetPower @ 0x1C005EC20 (ACPIRootIrpSetPower.c)
 *     ACPIThermalCancelRequest @ 0x1C005F8E0 (ACPIThermalCancelRequest.c)
 *     ACPIThermalEvent @ 0x1C005FAB0 (ACPIThermalEvent.c)
 *     ACPIBusIrpQueryDeviceRelations @ 0x1C008F010 (ACPIBusIrpQueryDeviceRelations.c)
 *     ACPIBusIrpQueryTargetRelation @ 0x1C008F1A8 (ACPIBusIrpQueryTargetRelation.c)
 *     ACPIBusIrpQueryId @ 0x1C008F640 (ACPIBusIrpQueryId.c)
 *     ACPIFilterIrpQueryDeviceRelations @ 0x1C008F850 (ACPIFilterIrpQueryDeviceRelations.c)
 *     ACPIFanStartDevice @ 0x1C0091220 (ACPIFanStartDevice.c)
 *     ACPIThermalStartDevice @ 0x1C0091630 (ACPIThermalStartDevice.c)
 *     ACPIProcessorDeviceControl @ 0x1C0091C40 (ACPIProcessorDeviceControl.c)
 *     ACPIIrpCompletionRoutineWorker @ 0x1C0093210 (ACPIIrpCompletionRoutineWorker.c)
 *     IsPciBus @ 0x1C00939A8 (IsPciBus.c)
 *     ACPIFilterIrpFilterResourceRequirements @ 0x1C00939D0 (ACPIFilterIrpFilterResourceRequirements.c)
 *     ACPIFilterIrpStartDevice @ 0x1C0093BE0 (ACPIFilterIrpStartDevice.c)
 *     AcpiQueryPciBusInterface @ 0x1C0093E0C (AcpiQueryPciBusInterface.c)
 *     ACPIFilterQueryBusD3ColdSupport @ 0x1C0093FF4 (ACPIFilterQueryBusD3ColdSupport.c)
 *     ACPIBusIrpQueryResources @ 0x1C00940E0 (ACPIBusIrpQueryResources.c)
 *     ACPIFilterIrpQueryPnpLocationInterface @ 0x1C00944B0 (ACPIFilterIrpQueryPnpLocationInterface.c)
 *     ACPIRootIrpQueryInterface @ 0x1C00945B0 (ACPIRootIrpQueryInterface.c)
 *     ACPIFilterIrpQueryInterface @ 0x1C00947C0 (ACPIFilterIrpQueryInterface.c)
 *     ACPIEjectPnpLocationInterface @ 0x1C0094A0C (ACPIEjectPnpLocationInterface.c)
 *     ACPIFilterIrpQueryIommuInterface @ 0x1C0094B04 (ACPIFilterIrpQueryIommuInterface.c)
 *     ACPIBusIommuBusInterface @ 0x1C0094BFC (ACPIBusIommuBusInterface.c)
 *     ACPIBusIrpDeviceEnumerated @ 0x1C0094D90 (ACPIBusIrpDeviceEnumerated.c)
 *     ACPIFilterIrpQueryResourceRequirements @ 0x1C0095310 (ACPIFilterIrpQueryResourceRequirements.c)
 *     ACPIBusIrpQueryResourceRequirements @ 0x1C0095390 (ACPIBusIrpQueryResourceRequirements.c)
 *     PnpBiosGetDeviceResourceList @ 0x1C0095674 (PnpBiosGetDeviceResourceList.c)
 *     PnpBiosResourcesToNtResources @ 0x1C0095CE4 (PnpBiosResourcesToNtResources.c)
 *     ACPIRootIrpQueryBusRelations @ 0x1C0096794 (ACPIRootIrpQueryBusRelations.c)
 *     ACPIBusAndFilterIrpQueryPnpDeviceState @ 0x1C0097350 (ACPIBusAndFilterIrpQueryPnpDeviceState.c)
 *     ACPIBusAndFilterIrpQueryCapabilities @ 0x1C0097710 (ACPIBusAndFilterIrpQueryCapabilities.c)
 *     ACPIBusIrpStartDeviceWorker @ 0x1C009D030 (ACPIBusIrpStartDeviceWorker.c)
 *     ACPIFilterIrpQueryCapabilities @ 0x1C009E6F0 (ACPIFilterIrpQueryCapabilities.c)
 *     ACPIIrpSetPagableCompletionRoutineAndForward @ 0x1C009F02C (ACPIIrpSetPagableCompletionRoutineAndForward.c)
 *     ACPIInternalDeviceQueryDeviceRelations @ 0x1C009F160 (ACPIInternalDeviceQueryDeviceRelations.c)
 *     ACPIInternalDeviceQueryCapabilities @ 0x1C009F7F0 (ACPIInternalDeviceQueryCapabilities.c)
 *     ACPIFilterIrpStartDeviceWorker @ 0x1C009F8C0 (ACPIFilterIrpStartDeviceWorker.c)
 *     ACPIRootIrpQueryCapabilities @ 0x1C009FF90 (ACPIRootIrpQueryCapabilities.c)
 *     ACPIIrpInvokeDispatchRoutine @ 0x1C00A02B0 (ACPIIrpInvokeDispatchRoutine.c)
 *     ACPIFilterIrpDeviceUsageNotification @ 0x1C00A03B0 (ACPIFilterIrpDeviceUsageNotification.c)
 *     TranslateEjectInterface @ 0x1C00A04E8 (TranslateEjectInterface.c)
 *     ACPIBusIrpDeviceUsageNotification @ 0x1C00A1570 (ACPIBusIrpDeviceUsageNotification.c)
 *     ACPIBusIrpQueryBusRelations @ 0x1C00A1AF0 (ACPIBusIrpQueryBusRelations.c)
 *     ACPIRootIrpQueryDeviceRelations @ 0x1C00A1B90 (ACPIRootIrpQueryDeviceRelations.c)
 *     ACPIBusIrpStartDevice @ 0x1C00A2450 (ACPIBusIrpStartDevice.c)
 *     PcisuppAcquirePciInterfaces @ 0x1C00A25F0 (PcisuppAcquirePciInterfaces.c)
 *     ACPIInternalIsPci @ 0x1C00A2790 (ACPIInternalIsPci.c)
 *     ACPIFilterIrpSurpriseRemoval @ 0x1C00A29C0 (ACPIFilterIrpSurpriseRemoval.c)
 *     PciBusEjectInterface @ 0x1C00A2A8C (PciBusEjectInterface.c)
 *     ACPIThermalWmi @ 0x1C00A2ED0 (ACPIThermalWmi.c)
 *     AcpiEjectBusNumberTranslator @ 0x1C00A3048 (AcpiEjectBusNumberTranslator.c)
 *     ACPICMButtonStart @ 0x1C00A310C (ACPICMButtonStart.c)
 *     ACPIDockIntfReference @ 0x1C00AADE0 (ACPIDockIntfReference.c)
 *     ACPIDockIntfSetMode @ 0x1C00AAE30 (ACPIDockIntfSetMode.c)
 *     ACPIDockIntfUpdateDeparture @ 0x1C00AAE70 (ACPIDockIntfUpdateDeparture.c)
 *     ACPIDockIrpEject @ 0x1C00AAF40 (ACPIDockIrpEject.c)
 *     ACPIDockIrpQueryCapabilities @ 0x1C00AB1F0 (ACPIDockIrpQueryCapabilities.c)
 *     ACPIDockIrpQueryDeviceRelations @ 0x1C00AB4C0 (ACPIDockIrpQueryDeviceRelations.c)
 *     ACPIDockIrpQueryEjectRelations @ 0x1C00AB6F8 (ACPIDockIrpQueryEjectRelations.c)
 *     ACPIDockIrpQueryID @ 0x1C00AB910 (ACPIDockIrpQueryID.c)
 *     ACPIDockIrpQueryInterface @ 0x1C00ABC70 (ACPIDockIrpQueryInterface.c)
 *     ACPIDockIrpQueryPnpDeviceState @ 0x1C00ABE30 (ACPIDockIrpQueryPnpDeviceState.c)
 *     ACPIDockIrpStartDevice @ 0x1C00ABF60 (ACPIDockIrpStartDevice.c)
 *     AcpiArblibEjectInterface @ 0x1C00ACB7C (AcpiArblibEjectInterface.c)
 *     ACPIBusAndFilterIrpEject @ 0x1C00AD080 (ACPIBusAndFilterIrpEject.c)
 *     ACPIBusAndFilterIrpQueryEjectRelations @ 0x1C00AD35C (ACPIBusAndFilterIrpQueryEjectRelations.c)
 *     ACPIBusAndFilterIrpSetLock @ 0x1C00AD4F0 (ACPIBusAndFilterIrpSetLock.c)
 *     ACPIBusIrpCancelRemoveOrStopDevice @ 0x1C00AD5D0 (ACPIBusIrpCancelRemoveOrStopDevice.c)
 *     ACPIBusIrpQueryRemoveOrStopDevice @ 0x1C00AD860 (ACPIBusIrpQueryRemoveOrStopDevice.c)
 *     ACPIBusIrpStopDevice @ 0x1C00AD9E0 (ACPIBusIrpStopDevice.c)
 *     ACPIEcInternalControl @ 0x1C00AE030 (ACPIEcInternalControl.c)
 *     ACPIEcReadWrite @ 0x1C00AE100 (ACPIEcReadWrite.c)
 *     AcpiExternalTranslateBiosToNtResources @ 0x1C00AEB4C (AcpiExternalTranslateBiosToNtResources.c)
 *     ACPIFilterIrpQueryIdCompletion @ 0x1C00AF240 (ACPIFilterIrpQueryIdCompletion.c)
 *     ACPIFilterIrpStopDevice @ 0x1C00AF490 (ACPIFilterIrpStopDevice.c)
 *     ACPIEjectPartitionUnitInterface @ 0x1C00AFBD8 (ACPIEjectPartitionUnitInterface.c)
 *     ACPIProcessorContainerStartDevice @ 0x1C00B1AB0 (ACPIProcessorContainerStartDevice.c)
 *     ACPIRootIrpCancelRemoveOrStopDevice @ 0x1C00B47A0 (ACPIRootIrpCancelRemoveOrStopDevice.c)
 *     ACPIRootIrpQueryRemoveOrStopDevice @ 0x1C00B48E0 (ACPIRootIrpQueryRemoveOrStopDevice.c)
 *     ACPIRootIrpStopDevice @ 0x1C00B4A30 (ACPIRootIrpStopDevice.c)
 *     AcpiSdevIdentifierInterface @ 0x1C00B4E34 (AcpiSdevIdentifierInterface.c)
 *     ACPIThermalQueryWmiDataBlock @ 0x1C00B4FE0 (ACPIThermalQueryWmiDataBlock.c)
 *     ACPIRootIrpStartDevice @ 0x1C00BB190 (ACPIRootIrpStartDevice.c)
 *     ACPIInitialize @ 0x1C00BE114 (ACPIInitialize.c)
 *     OSInterruptVector @ 0x1C00BE308 (OSInterruptVector.c)
 *     ACPIInitStartACPI @ 0x1C00BEF3C (ACPIInitStartACPI.c)
 * Callees:
 *     <none>
 */

__int64 __fastcall ACPIInternalGetDeviceExtension(ULONG_PTR BugCheckParameter3)
{
  KIRQL v2; // al
  __int64 v3; // rbx

  v2 = KeAcquireSpinLockRaiseToDpc(&AcpiDeviceTreeLock);
  v3 = *(_QWORD *)(BugCheckParameter3 + 64);
  if ( v3 && *(_DWORD *)(v3 + 16) != 1599293264 )
    KeBugCheckEx(0xA3u, 2uLL, 0x901A5uLL, BugCheckParameter3, *(_QWORD *)(BugCheckParameter3 + 64));
  KeReleaseSpinLock(&AcpiDeviceTreeLock, v2);
  return v3;
}
