/*
 * XREFs of ??_GDXGFASTMUTEX@@QEAAPEAXI@Z @ 0x1C001E3AC
 * Callers:
 *     ?CreateOneAllocation@VIDMM_GLOBAL@@QEAAJPEAVVIDMM_DEVICE@@K_K1KKKU_D3DDDI_SEGMENTPREFERENCE@@U_DXGK_ALLOCATIONINFOFLAGS@@PEAVDXGADAPTERALLOCATION@@PEAX5KE5EPEAPEAU_VIDMM_GLOBAL_ALLOC@@@Z @ 0x1C00602A0 (-CreateOneAllocation@VIDMM_GLOBAL@@QEAAJPEAVVIDMM_DEVICE@@K_K1KKKU_D3DDDI_SEGMENTPREFERENCE@@U_D.c)
 *     ??1VIDMM_PROCESS_HEAP@@UEAA@XZ @ 0x1C00A6BF0 (--1VIDMM_PROCESS_HEAP@@UEAA@XZ.c)
 * Callees:
 *     ??1DXGFASTMUTEX@@QEAA@XZ @ 0x1C000178C (--1DXGFASTMUTEX@@QEAA@XZ.c)
 */

DXGFASTMUTEX *__fastcall DXGFASTMUTEX::`scalar deleting destructor'(DXGFASTMUTEX *P)
{
  DXGFASTMUTEX::~DXGFASTMUTEX(P);
  if ( P )
    ExFreePoolWithTag(P, 0);
  return P;
}
