/*
 * XREFs of PopFxBugCheck @ 0x14056791C
 * Callers:
 *     PoFxActivateComponent @ 0x140245E90 (PoFxActivateComponent.c)
 *     PopFxCompleteDevicePowerRequired @ 0x140246034 (PopFxCompleteDevicePowerRequired.c)
 *     PopFxAddRefDevice @ 0x1402461CC (PopFxAddRefDevice.c)
 *     PopFxProcessWork @ 0x140246294 (PopFxProcessWork.c)
 *     PopFxIdleComponent @ 0x140246C40 (PopFxIdleComponent.c)
 *     PopPluginComponentActive @ 0x140246E60 (PopPluginComponentActive.c)
 *     PopPluginDevicePower @ 0x140246F08 (PopPluginDevicePower.c)
 *     PopPepCompleteActivity @ 0x1402D59D4 (PopPepCompleteActivity.c)
 *     PopPepTriggerActivity @ 0x1402D5AB0 (PopPepTriggerActivity.c)
 *     PoFxCompleteIdleCondition @ 0x140323130 (PoFxCompleteIdleCondition.c)
 *     PopFxDispatchPluginWorkOnce @ 0x14033D854 (PopFxDispatchPluginWorkOnce.c)
 *     PopFxDisableWorkOrderWatchdog @ 0x14033EEA8 (PopFxDisableWorkOrderWatchdog.c)
 *     PopFxActivateDevice @ 0x14036D700 (PopFxActivateDevice.c)
 *     PoFxReportDevicePoweredOn @ 0x14039C2E0 (PoFxReportDevicePoweredOn.c)
 *     PopPepUpdateIdleStateRefCount @ 0x14039CEC4 (PopPepUpdateIdleStateRefCount.c)
 *     PopPluginComponentIdleState @ 0x1403A40C4 (PopPluginComponentIdleState.c)
 *     PopFxIdleTimeoutDpcRoutine @ 0x1403A5800 (PopFxIdleTimeoutDpcRoutine.c)
 *     PoFxCompleteDevicePowerNotRequired @ 0x1403A6E20 (PoFxCompleteDevicePowerNotRequired.c)
 *     PoFxRegisterDripsWatchdogCallback @ 0x1403CAB80 (PoFxRegisterDripsWatchdogCallback.c)
 *     PoFxIssueComponentPerfStateChangeMultiple @ 0x1405675A0 (PoFxIssueComponentPerfStateChangeMultiple.c)
 *     PopFxCompleteDirectedPowerTransition @ 0x140568A8C (PopFxCompleteDirectedPowerTransition.c)
 *     PopFxDerefAndCompleteDirectedPowerTransition @ 0x140568D24 (PopFxDerefAndCompleteDirectedPowerTransition.c)
 *     PopFxIssueComponentPerfStateChanges @ 0x140569940 (PopFxIssueComponentPerfStateChanges.c)
 *     PopFxIssueDirectedPowerTransition @ 0x140569B7C (PopFxIssueDirectedPowerTransition.c)
 *     PopFxTransitionCriticalResource @ 0x14056BA00 (PopFxTransitionCriticalResource.c)
 *     PopFxWorkOrderWatchdog @ 0x14056BED0 (PopFxWorkOrderWatchdog.c)
 *     PopPluginAbandonDevice @ 0x14056BEF8 (PopPluginAbandonDevice.c)
 *     PopPluginNotifyActive @ 0x14056BF4C (PopPluginNotifyActive.c)
 *     PopPluginPrepareDevice @ 0x14056C054 (PopPluginPrepareDevice.c)
 *     PopPluginQueryComponentPerfSet @ 0x14056C164 (PopPluginQueryComponentPerfSet.c)
 *     PopPluginQueryComponentPerfSetName @ 0x14056C210 (PopPluginQueryComponentPerfSetName.c)
 *     PopPluginQueryComponentPerfStates @ 0x14056C29C (PopPluginQueryComponentPerfStates.c)
 *     PopPluginQueryCurrentComponentPerfState @ 0x14056C2F4 (PopPluginQueryCurrentComponentPerfState.c)
 *     PopPluginRegisterDevice @ 0x14056C414 (PopPluginRegisterDevice.c)
 *     PopPluginRequestComponentPerfState @ 0x14056C558 (PopPluginRequestComponentPerfState.c)
 *     PopPluginUnregisterDevice @ 0x14056C6EC (PopPluginUnregisterDevice.c)
 *     PopTranslateDependencyArray @ 0x14056CAEC (PopTranslateDependencyArray.c)
 *     PopPepInitializeDebuggerMasks @ 0x14057328C (PopPepInitializeDebuggerMasks.c)
 *     PopPepInitializeVetoMasks @ 0x14057338C (PopPepInitializeVetoMasks.c)
 *     PopFxDebuggerPowerCriticalTransitionCallback @ 0x140577830 (PopFxDebuggerPowerCriticalTransitionCallback.c)
 *     PopFxAcpiForwardPepAcpiNotifyRequest @ 0x14057C400 (PopFxAcpiForwardPepAcpiNotifyRequest.c)
 *     PopFxAcpiForwardPepWorkRequest @ 0x14057C494 (PopFxAcpiForwardPepWorkRequest.c)
 *     PopPluginAcpiNotificationStrict @ 0x14057E18C (PopPluginAcpiNotificationStrict.c)
 *     PopFxRegisterDevice @ 0x1407AFD4C (PopFxRegisterDevice.c)
 *     PopFxRegisterDeviceWorker @ 0x1407AFEEC (PopFxRegisterDeviceWorker.c)
 *     PoFxRegisterComponentPerfStates @ 0x1408E6B70 (PoFxRegisterComponentPerfStates.c)
 *     PopFxInitializeSocSubsystemStaticInfo @ 0x1408E6F20 (PopFxInitializeSocSubsystemStaticInfo.c)
 *     PopFxLogSocSubsystemMetadata @ 0x1408E74C0 (PopFxLogSocSubsystemMetadata.c)
 *     PopFxPepPerfInfoQuery @ 0x1408E796C (PopFxPepPerfInfoQuery.c)
 *     PopFxResetSocSubsystemAccounting @ 0x1408E7FA8 (PopFxResetSocSubsystemAccounting.c)
 *     PopPluginInitializeSocSubsystemStaticInfo @ 0x1408E840C (PopPluginInitializeSocSubsystemStaticInfo.c)
 *     PopPluginQuerySocSubsystemBlockingTime @ 0x1408E853C (PopPluginQuerySocSubsystemBlockingTime.c)
 *     PopPluginQuerySocSubsystemCount @ 0x1408E8618 (PopPluginQuerySocSubsystemCount.c)
 *     PopPluginQuerySocSubsystemMetadata @ 0x1408E868C (PopPluginQuerySocSubsystemMetadata.c)
 *     PopDripsWatchdogTakeAction @ 0x1408FCEF0 (PopDripsWatchdogTakeAction.c)
 * Callees:
 *     KeBugCheckEx @ 0x1403FBCA0 (KeBugCheckEx.c)
 */

void __fastcall __noreturn PopFxBugCheck(
        ULONG_PTR BugCheckParameter1,
        ULONG_PTR BugCheckParameter2,
        ULONG_PTR BugCheckParameter3,
        ULONG_PTR BugCheckParameter4)
{
  KeBugCheckEx(0xA0u, BugCheckParameter1, BugCheckParameter2, BugCheckParameter3, BugCheckParameter4);
}
