/*
 * XREFs of ?ReleaseReference@DXGHWQUEUE@@QEAAXXZ @ 0x140017920
 * Callers:
 *     DxgkDestroyHwQueueInternal @ 0x1403F0AA8 (DxgkDestroyHwQueueInternal.c)
 * Callees:
 *     ??1DXGADAPTERSTOPRESETLOCKSHARED@@QEAA@XZ @ 0x140017020 (--1DXGADAPTERSTOPRESETLOCKSHARED@@QEAA@XZ.c)
 *     ??1COREDEVICEACCESS@@QEAA@XZ @ 0x1400170E0 (--1COREDEVICEACCESS@@QEAA@XZ.c)
 *     ??1COREACCESS@@QEAA@XZ @ 0x140017110 (--1COREACCESS@@QEAA@XZ.c)
 *     ?AcquireSharedUncheck@COREDEVICEACCESS@@QEAAXPEBD@Z @ 0x1400171A4 (-AcquireSharedUncheck@COREDEVICEACCESS@@QEAAXPEBD@Z.c)
 *     ??1DXGDEVICEACCESSLOCKEXCLUSIVE@@QEAA@XZ @ 0x140017370 (--1DXGDEVICEACCESSLOCKEXCLUSIVE@@QEAA@XZ.c)
 *     ??0COREACCESS@@QEAA@QEAVDXGADAPTER@@_N@Z @ 0x1400174D0 (--0COREACCESS@@QEAA@QEAVDXGADAPTER@@_N@Z.c)
 *     ??0DXGDEVICEACCESSLOCKEXCLUSIVE@@QEAA@PEAVDXGDEVICE@@@Z @ 0x140017CB8 (--0DXGDEVICEACCESSLOCKEXCLUSIVE@@QEAA@PEAVDXGDEVICE@@@Z.c)
 *     ?Acquire@DXGADAPTERSTOPRESETLOCKSHARED@@QEAAXXZ @ 0x140017DC0 (-Acquire@DXGADAPTERSTOPRESETLOCKSHARED@@QEAAXXZ.c)
 *     ??0COREDEVICEACCESS@@QEAA@QEAVDXGDEVICE@@W4_DXGDEVICEACCESS_TYPE@@I_N@Z @ 0x1400182F0 (--0COREDEVICEACCESS@@QEAA@QEAVDXGDEVICE@@W4_DXGDEVICEACCESS_TYPE@@I_N@Z.c)
 *     ??0DXGADAPTERSTOPRESETLOCKSHARED@@QEAA@PEAVDXGADAPTER@@E@Z @ 0x140018480 (--0DXGADAPTERSTOPRESETLOCKSHARED@@QEAA@PEAVDXGADAPTER@@E@Z.c)
 *     DxgkLogInternalTriageEvent @ 0x14002BDA0 (DxgkLogInternalTriageEvent.c)
 *     __security_check_cookie @ 0x1400A59A0 (__security_check_cookie.c)
 *     ?DestroyDeviceNoLocks@ADAPTER_RENDER@@QEAAXPEAVDXGDEVICE@@@Z @ 0x140290178 (-DestroyDeviceNoLocks@ADAPTER_RENDER@@QEAAXPEAVDXGDEVICE@@@Z.c)
 *     ?DestroyContext@DXGDEVICE@@QEAAXPEAVDXGCONTEXT@@PEAVCOREDEVICEACCESS@@@Z @ 0x1403A62FC (-DestroyContext@DXGDEVICE@@QEAAXPEAVDXGCONTEXT@@PEAVCOREDEVICEACCESS@@@Z.c)
 *     ?DestroyHwQueue@DXGCONTEXT@@QEAAXPEAVDXGHWQUEUE@@PEAVCOREDEVICEACCESS@@@Z @ 0x1403A7B58 (-DestroyHwQueue@DXGCONTEXT@@QEAAXPEAVDXGHWQUEUE@@PEAVCOREDEVICEACCESS@@@Z.c)
 */

void __fastcall DXGHWQUEUE::ReleaseReference(DXGHWQUEUE *this)
{
  __int64 v2; // rax
  __int64 v3; // rsi
  struct DXGDEVICE *v4; // rbp
  __int64 v5; // rax
  struct DXGADAPTER *v6; // rdx
  const char *v7; // rdx
  __int64 v8; // rax
  __int64 v9; // rcx
  unsigned __int64 v10; // rdx
  unsigned __int64 v11; // rdx
  __int64 v12; // rbx
  const char *v13; // rdx
  _BYTE v14[16]; // [rsp+50h] [rbp-E8h] BYREF
  _BYTE v15[8]; // [rsp+60h] [rbp-D8h] BYREF
  __int64 v16; // [rsp+68h] [rbp-D0h]
  char v17; // [rsp+70h] [rbp-C8h]
  _BYTE v18[8]; // [rsp+80h] [rbp-B8h] BYREF
  _BYTE v19[64]; // [rsp+88h] [rbp-B0h] BYREF
  _BYTE v20[64]; // [rsp+C8h] [rbp-70h] BYREF
  struct DXGDEVICE *v21; // [rsp+108h] [rbp-30h]
  bool v22; // [rsp+110h] [rbp-28h]

  v2 = _InterlockedDecrement64((volatile signed __int64 *)this + 14);
  if ( v2 < 0 )
  {
    WdLogSingleEntry0(1LL);
    WdLogGlobalForLineNumber = 151;
    DxgkLogInternalTriageEvent(0, 262146, -1, (unsigned int)L"NewReferenceCount >= 0", 151LL, 0LL, 0LL, 0LL, 0LL);
  }
  else if ( !v2 )
  {
    v3 = *((_QWORD *)this + 2);
    v4 = *(struct DXGDEVICE **)(v3 + 16);
    DXGDEVICEACCESSLOCKEXCLUSIVE::DXGDEVICEACCESSLOCKEXCLUSIVE((DXGDEVICEACCESSLOCKEXCLUSIVE *)v14, v4);
    v5 = *((_QWORD *)v4 + 2);
    v17 = 0;
    v16 = *(_QWORD *)(v5 + 16);
    DXGADAPTERSTOPRESETLOCKSHARED::Acquire((DXGADAPTERSTOPRESETLOCKSHARED *)v15);
    COREACCESS::COREACCESS((COREACCESS *)v19, *(struct DXGADAPTER *const *)(*((_QWORD *)v4 + 2) + 16LL));
    v6 = (struct DXGADAPTER *)*((_QWORD *)v4 + 237);
    if ( !v6 )
      v6 = *(struct DXGADAPTER **)(*((_QWORD *)v4 + 2) + 16LL);
    COREACCESS::COREACCESS((COREACCESS *)v20, v6);
    v8 = *((_QWORD *)v4 + 2);
    v9 = *((_QWORD *)v4 + 237);
    v21 = v4;
    v22 = v9 != *(_QWORD *)(v8 + 16) && v9;
    COREDEVICEACCESS::AcquireSharedUncheck((COREDEVICEACCESS *)v18, v7);
    if ( *(_DWORD *)(*(_QWORD *)(*((_QWORD *)v4 + 2) + 16LL) + 200LL) != 4 )
      DXGCONTEXT::DestroyHwQueue((DXGCONTEXT *)v3, this, (struct COREDEVICEACCESS *)v18);
    COREACCESS::~COREACCESS((COREACCESS *)v20, v10);
    COREACCESS::~COREACCESS((COREACCESS *)v19, v11);
    DXGADAPTERSTOPRESETLOCKSHARED::~DXGADAPTERSTOPRESETLOCKSHARED((DXGADAPTERSTOPRESETLOCKSHARED *)v15);
    DXGDEVICEACCESSLOCKEXCLUSIVE::~DXGDEVICEACCESSLOCKEXCLUSIVE((DXGDEVICEACCESSLOCKEXCLUSIVE *)v14);
    if ( _InterlockedExchangeAdd64((volatile signed __int64 *)(v3 + 32), 0xFFFFFFFFFFFFFFFFuLL) == 1 )
    {
      v12 = *(_QWORD *)(v3 + 16);
      DXGDEVICEACCESSLOCKEXCLUSIVE::DXGDEVICEACCESSLOCKEXCLUSIVE(
        (DXGDEVICEACCESSLOCKEXCLUSIVE *)v14,
        (struct DXGDEVICE *)v12);
      DXGADAPTERSTOPRESETLOCKSHARED::DXGADAPTERSTOPRESETLOCKSHARED(
        (DXGADAPTERSTOPRESETLOCKSHARED *)v15,
        *(struct DXGADAPTER **)(*(_QWORD *)(*(_QWORD *)(v3 + 16) + 16LL) + 16LL),
        1u);
      COREDEVICEACCESS::COREDEVICEACCESS(v18, v12, 2LL);
      COREDEVICEACCESS::AcquireSharedUncheck((COREDEVICEACCESS *)v18, v13);
      if ( *(_DWORD *)(*(_QWORD *)(*(_QWORD *)(v12 + 16) + 16LL) + 200LL) != 4 )
        DXGDEVICE::DestroyContext((DXGDEVICE *)v12, (struct DXGCONTEXT *)v3, (struct COREDEVICEACCESS *)v18);
      COREDEVICEACCESS::~COREDEVICEACCESS((COREDEVICEACCESS *)v18);
      DXGADAPTERSTOPRESETLOCKSHARED::~DXGADAPTERSTOPRESETLOCKSHARED((DXGADAPTERSTOPRESETLOCKSHARED *)v15);
      DXGDEVICEACCESSLOCKEXCLUSIVE::~DXGDEVICEACCESSLOCKEXCLUSIVE((DXGDEVICEACCESSLOCKEXCLUSIVE *)v14);
      if ( _InterlockedExchangeAdd64((volatile signed __int64 *)(v12 + 64), 0xFFFFFFFFFFFFFFFFuLL) == 1 )
        ADAPTER_RENDER::DestroyDeviceNoLocks(*(ADAPTER_RENDER **)(v12 + 16), (struct DXGDEVICE *)v12);
    }
  }
}
