/*
 * XREFs of ?ReleaseDdiEnumerator@DMMVIDEOPRESENTTARGETSET@@QEAAJPEBU_D3DKMDT_VIDEO_PRESENT_TARGET@@@Z @ 0x1402607D0
 * Callers:
 *     ?ReleaseTargetInfo@DXGDMM_VIDEOPRESENTTARGETSET_INTERFACE_V1_IMPL@@YAJQEAUD3DKMDT_HVIDEOPRESENTTARGETSET__@@QEBU_D3DKMDT_VIDEO_PRESENT_TARGET@@@Z @ 0x140264150 (-ReleaseTargetInfo@DXGDMM_VIDEOPRESENTTARGETSET_INTERFACE_V1_IMPL@@YAJQEAUD3DKMDT_HVIDEOPRESENTT.c)
 *     ?AddStaticTarget@DXGPORTDMM_VIDEOPRESENTTARGETSET_INTERFACE_V1_IMPL@@YAJQEAUD3DKMDT_HVIDEOPRESENTTARGETSET__@@PEBU_D3DKMDT_VIDEO_PRESENT_TARGET@@@Z @ 0x140267E30 (-AddStaticTarget@DXGPORTDMM_VIDEOPRESENTTARGETSET_INTERFACE_V1_IMPL@@YAJQEAUD3DKMDT_HVIDEOPRESEN.c)
 *     ?ReleaseTargetInfo@DXGPORTDMM_VIDEOPRESENTTARGETSET_INTERFACE_V1_IMPL@@YAJQEAUD3DKMDT_HVIDEOPRESENTTARGETSET__@@PEBU_D3DKMDT_VIDEO_PRESENT_TARGET@@@Z @ 0x1402682C0 (-ReleaseTargetInfo@DXGPORTDMM_VIDEOPRESENTTARGETSET_INTERFACE_V1_IMPL@@YAJQEAUD3DKMDT_HVIDEOPRES.c)
 * Callees:
 *     ??3?$DXGQUOTAALLOCATOR@$0BAA@$0GNGCEDEG@@@SAXPEAX@Z @ 0x14001D870 (--3-$DXGQUOTAALLOCATOR@$0BAA@$0GNGCEDEG@@@SAXPEAX@Z.c)
 *     ?ContainsByReference@?$DoublyLinkedList@VDMMVIDEOPRESENTTARGET@@U?$DoubleLinkedListElementDeleter@VDMMVIDEOPRESENTTARGET@@@@@@QEAAEQEBVDMMVIDEOPRESENTTARGET@@@Z @ 0x14004FB10 (-ContainsByReference@-$DoublyLinkedList@VDMMVIDEOPRESENTTARGET@@U-$DoubleLinkedListElementDelete.c)
 */

__int64 __fastcall DMMVIDEOPRESENTTARGETSET::ReleaseDdiEnumerator(
        DMMVIDEOPRESENTTARGETSET *this,
        const struct _D3DKMDT_VIDEO_PRESENT_TARGET *a2)
{
  D3DKMDT_VIDEO_OUTPUT_TECHNOLOGY *p_VideoOutputTechnology; // r11
  __int64 v3; // rdx

  if ( !a2 )
    return 3223192325LL;
  p_VideoOutputTechnology = &a2[-1].VideoOutputTechnology;
  if ( a2[-1].VideoOutputTechnology != 305419896 )
    return 3223192325LL;
  v3 = *(_QWORD *)&a2[-1].MonitorOrientationAwareness;
  if ( v3
    && !DoublyLinkedList<DMMVIDEOPRESENTTARGET,DoubleLinkedListElementDeleter<DMMVIDEOPRESENTTARGET>>::ContainsByReference(
          (__int64)this + 8,
          v3) )
  {
    return 3223192368LL;
  }
  DXGQUOTAALLOCATOR<256,1835156294>::operator delete(p_VideoOutputTechnology);
  return 0LL;
}
