/*
 * XREFs of ??$CastToVmBusCommand@UDXGKVMB_COMMAND_GETREGISTRYKEYS@@@@YAPEAUDXGKVMB_COMMAND_GETREGISTRYKEYS@@PEAUDXGADAPTER_VMBUS_PACKET@@@Z @ 0x1C005AD64
 * Callers:
 *     ?VmBusGetRegistryKeys@DXG_HOST_VIRTUALGPU_VMBUS@@SAEPEAUDXGADAPTER_VMBUS_PACKET@@@Z @ 0x1C037B110 (-VmBusGetRegistryKeys@DXG_HOST_VIRTUALGPU_VMBUS@@SAEPEAUDXGADAPTER_VMBUS_PACKET@@@Z.c)
 * Callees:
 *     ?LogPacketLengthError@@YAXPEAUDXGADAPTER_VMBUS_PACKET@@_K@Z @ 0x1C03717AC (-LogPacketLengthError@@YAXPEAUDXGADAPTER_VMBUS_PACKET@@_K@Z.c)
 */

__int64 __fastcall CastToVmBusCommand<DXGKVMB_COMMAND_GETREGISTRYKEYS>(__int64 a1)
{
  if ( *(_DWORD *)(a1 + 144) >= 0x220u )
    return *(_QWORD *)(a1 + 136);
  LogPacketLengthError((struct DXGADAPTER_VMBUS_PACKET *)a1, 0x220uLL);
  return 0LL;
}
