/*
 * XREFs of ??1DXGVALIDATIONPROCESSATTACH@@QEAA@XZ @ 0x1C0025230
 * Callers:
 *     ?DdiRenderGdi@ADAPTER_RENDER@@QEAAJPEAXPEAU_DXGKARG_RENDERGDI@@@Z @ 0x1C01A0930 (-DdiRenderGdi@ADAPTER_RENDER@@QEAAJPEAXPEAU_DXGKARG_RENDERGDI@@@Z.c)
 * Callees:
 *     <none>
 */

void __fastcall DXGVALIDATIONPROCESSATTACH::~DXGVALIDATIONPROCESSATTACH(DXGVALIDATIONPROCESSATTACH *this)
{
  if ( *(_BYTE *)this )
    KeUnstackDetachProcess((PRKAPC_STATE)((char *)this + 8));
}
