/*
 * XREFs of ??_EDMMVIDEOPRESENTSOURCE@@UEAAPEAXI@Z @ 0x1C006A670
 * Callers:
 *     ??_EDMMVIDEOPRESENTSOURCE@@WCA@EAAPEAXI@Z @ 0x1C0027EC0 (--_EDMMVIDEOPRESENTSOURCE@@WCA@EAAPEAXI@Z.c)
 *     ??_EDMMVIDEOPRESENTSOURCE@@WDA@EAAPEAXI@Z @ 0x1C0027ED0 (--_EDMMVIDEOPRESENTSOURCE@@WDA@EAAPEAXI@Z.c)
 *     ??_EDMMVIDEOPRESENTSOURCE@@WEA@EAAPEAXI@Z @ 0x1C0027EE0 (--_EDMMVIDEOPRESENTSOURCE@@WEA@EAAPEAXI@Z.c)
 * Callees:
 *     ??1DMMVIDEOPRESENTSOURCE@@UEAA@XZ @ 0x1C006A528 (--1DMMVIDEOPRESENTSOURCE@@UEAA@XZ.c)
 */

DMMVIDEOPRESENTSOURCE *__fastcall DMMVIDEOPRESENTSOURCE::`vector deleting destructor'(
        DMMVIDEOPRESENTSOURCE *P,
        char a2)
{
  DMMVIDEOPRESENTSOURCE::~DMMVIDEOPRESENTSOURCE(P);
  if ( (a2 & 1) != 0 && P )
    ExFreePoolWithTag(P, 0);
  return P;
}
