/*
 * XREFs of ??_GDXGDEVICE@@QEAAPEAXI@Z @ 0x1C00419D0
 * Callers:
 *     ?CreateDevice@ADAPTER_RENDER@@QEAAJPEAPEAVDXGDEVICE@@U_D3DKMT_CREATEDEVICEFLAGS@@W4DXGDEVICECLIENT_TYPE@@PEAVDXGADAPTER@@EEEPEAUDXGK_VIRTUAL_GPU_PARAV@@PEAPEAUDXG_SET_GUEST_DATA@@E@Z @ 0x1C01B70A8 (-CreateDevice@ADAPTER_RENDER@@QEAAJPEAPEAVDXGDEVICE@@U_D3DKMT_CREATEDEVICEFLAGS@@W4DXGDEVICECLIE.c)
 * Callees:
 *     ??1DXGDEVICE@@QEAA@XZ @ 0x1C01887C0 (--1DXGDEVICE@@QEAA@XZ.c)
 */

DXGDEVICE *__fastcall DXGDEVICE::`scalar deleting destructor'(DXGDEVICE *P)
{
  DXGDEVICE::~DXGDEVICE(P);
  if ( P )
    ExFreePoolWithTag(P, 0);
  return P;
}
