/*
 * XREFs of ??1ContextualProcessorEntry@ContextualProcessorManager@@QEAA@XZ @ 0x1800419E0
 * Callers:
 *     __lambda_a3b8ebf0ea7227d18a15fa2b24c62f92_::operator()_::_1_::dtor$0 @ 0x1800414B7 (__lambda_a3b8ebf0ea7227d18a15fa2b24c62f92_--operator()_--_1_--dtor$0.c)
 *     __lambda_a3b8ebf0ea7227d18a15fa2b24c62f92_::operator()_::_1_::dtor$1 @ 0x1800414C3 (__lambda_a3b8ebf0ea7227d18a15fa2b24c62f92_--operator()_--_1_--dtor$1.c)
 *     _DWMInputRouter::GetTargetWithFocus_::_1_::dtor$0 @ 0x180048534 (_DWMInputRouter--GetTargetWithFocus_--_1_--dtor$0.c)
 *     _ContextualProcessorManager::RegisterProcessor_::_1_::dtor$1 @ 0x180048E54 (_ContextualProcessorManager--RegisterProcessor_--_1_--dtor$1.c)
 *     _DWMCursor::SetPosition_::_1_::dtor$1 @ 0x18004E120 (_DWMCursor--SetPosition_--_1_--dtor$1.c)
 *     _Win32kInterop::Win32kInterop_::_1_::dtor$7 @ 0x18004E5B6 (_Win32kInterop--Win32kInterop_--_1_--dtor$7.c)
 *     _Win32kInterop::Win32kInterop_::_1_::dtor$8 @ 0x18004E5CF (_Win32kInterop--Win32kInterop_--_1_--dtor$8.c)
 *     _InputContext::InputContext_::_1_::dtor$1 @ 0x18004E982 (_InputContext--InputContext_--_1_--dtor$1.c)
 *     _DWMInputRouter::DWMInputRouter_::_1_::dtor$10 @ 0x18004EC19 (_DWMInputRouter--DWMInputRouter_--_1_--dtor$10.c)
 *     _ContextualProcessorBuffer::ContextualProcessorMetadata::ContextualProcessorMetadata_::_1_::dtor$0 @ 0x18004EFF0 (_ContextualProcessorBuffer--ContextualProcessorMetadata--ContextualProcessorMetadata_--_1_--dtor.c)
 *     _ContextualProcessorBuffer::AddProcessor_::_1_::dtor$1 @ 0x18004F0D0 (_ContextualProcessorBuffer--AddProcessor_--_1_--dtor$1.c)
 *     _std::vector_ContextualProcessorBuffer::ContextualProcessorMetadata_std::allocator_ContextualProcessorBuffer::ContextualProcessorMetadata___::_Emplace_reallocate_ContextualProcessorBuffer::ContextualProcessorMetadata_const_&__::_1_::dtor$21 @ 0x18004F190 (_std--vector_ContextualProcessorBuffer--ContextualProcessorMetadata_std--allocator__ea_18004F190.c)
 *     _DWMInputRouter::OnFocusedThreadChanged_::_1_::dtor$1 @ 0x18004F420 (_DWMInputRouter--OnFocusedThreadChanged_--_1_--dtor$1.c)
 *     _DWMInputRouter::OnFocusedThreadChanged_::_1_::dtor$5 @ 0x18004F460 (_DWMInputRouter--OnFocusedThreadChanged_--_1_--dtor$5.c)
 *     _NonPointerProcessor::OnTargetWithFocusChanged_::_1_::dtor$2 @ 0x18004F870 (_NonPointerProcessor--OnTargetWithFocusChanged_--_1_--dtor$2.c)
 *     _DWMInputRouter::GetTargetListFromHitTestResult_::_1_::dtor$1 @ 0x18004F920 (_DWMInputRouter--GetTargetListFromHitTestResult_--_1_--dtor$1.c)
 *     _DWMInputRouter::GetTargetFromInputSite_::_1_::dtor$0 @ 0x18004F940 (_DWMInputRouter--GetTargetFromInputSite_--_1_--dtor$0.c)
 *     _DWMInputRouter::UpdateFocusedInputTarget_::_1_::dtor$1 @ 0x18004F970 (_DWMInputRouter--UpdateFocusedInputTarget_--_1_--dtor$1.c)
 *     _ContextualProcessorManager::OnFocusRequest_::_1_::dtor$1 @ 0x18004F9D0 (_ContextualProcessorManager--OnFocusRequest_--_1_--dtor$1.c)
 *     _DWMInputRouter::Initialize_::_1_::dtor$26 @ 0x18004FA10 (_DWMInputRouter--Initialize_--_1_--dtor$26.c)
 *     _DWMInputRouter::UpdateFocusedInputTarget_::_1_::dtor$0 @ 0x18004FA30 (_DWMInputRouter--UpdateFocusedInputTarget_--_1_--dtor$0.c)
 *     _DWMInputRouter::UpdateFocusedInputTarget_::_1_::dtor$16 @ 0x18004FAB0 (_DWMInputRouter--UpdateFocusedInputTarget_--_1_--dtor$16.c)
 *     _MPCInputRouter::UpdateFocusedInputTarget_::_1_::dtor$2 @ 0x18004FB50 (_MPCInputRouter--UpdateFocusedInputTarget_--_1_--dtor$2.c)
 *     _MPCInputRouter::UpdateFocusedInputTarget_::_1_::dtor$4 @ 0x18004FB90 (_MPCInputRouter--UpdateFocusedInputTarget_--_1_--dtor$4.c)
 *     _DWMInputRouter::Initialize_::_1_::dtor$9 @ 0x18004FFDB (_DWMInputRouter--Initialize_--_1_--dtor$9.c)
 *     _DWMInputRouter::Initialize_::_1_::dtor$18 @ 0x180050011 (_DWMInputRouter--Initialize_--_1_--dtor$18.c)
 *     _DWMInputRouter::Initialize_::_1_::dtor$22 @ 0x180050035 (_DWMInputRouter--Initialize_--_1_--dtor$22.c)
 *     _DWMInputRouter::Initialize_::_1_::dtor$24 @ 0x180050059 (_DWMInputRouter--Initialize_--_1_--dtor$24.c)
 *     _DWMInputRouter::Initialize_::_1_::dtor$28 @ 0x18005008F (_DWMInputRouter--Initialize_--_1_--dtor$28.c)
 *     _DWMInputRouter::Initialize_::_1_::dtor$30 @ 0x1800500B3 (_DWMInputRouter--Initialize_--_1_--dtor$30.c)
 *     _DWMInputRouter::Initialize_::_1_::dtor$33 @ 0x1800500E9 (_DWMInputRouter--Initialize_--_1_--dtor$33.c)
 *     _DWMInputRouter::Initialize_::_1_::dtor$36 @ 0x18005011F (_DWMInputRouter--Initialize_--_1_--dtor$36.c)
 *     _DWMInputRouter::Initialize_::_1_::dtor$38 @ 0x180050143 (_DWMInputRouter--Initialize_--_1_--dtor$38.c)
 *     _DWMInputRouter::Initialize_::_1_::dtor$40 @ 0x180050167 (_DWMInputRouter--Initialize_--_1_--dtor$40.c)
 *     _DWMInputRouter::Initialize_::_1_::dtor$42 @ 0x18005018B (_DWMInputRouter--Initialize_--_1_--dtor$42.c)
 *     _DWMFocusedInputTarget::DWMFocusedInputTarget_::_1_::dtor$1 @ 0x180050210 (_DWMFocusedInputTarget--DWMFocusedInputTarget_--_1_--dtor$1.c)
 *     _Win32kInterop::DeliverInputToAllTargets_::_1_::dtor$3 @ 0x1800AF955 (_Win32kInterop--DeliverInputToAllTargets_--_1_--dtor$3.c)
 *     _Win32kInterop::DeliverInputToTarget_::_1_::dtor$0 @ 0x1800AFC62 (_Win32kInterop--DeliverInputToTarget_--_1_--dtor$0.c)
 *     ?DeliverToContextualProcessing@Win32kInterop@@AEAAXPEAUInputInfo@@V?$function@$$A6AXPEAVInputContext@@@Z@std@@V?$function@$$A6AXPEAUIInputTarget@@@Z@4@@Z @ 0x1800AFC80 (-DeliverToContextualProcessing@Win32kInterop@@AEAAXPEAUInputInfo@@V-$function@$$A6AXPEAVInputCon.c)
 *     _Win32kInterop::DeliverToContextualProcessing_::_1_::dtor$5 @ 0x1800B0036 (_Win32kInterop--DeliverToContextualProcessing_--_1_--dtor$5.c)
 *     _InitializeTargetInfoWithPointerInfo_::_1_::dtor$0 @ 0x1800B07AB (_InitializeTargetInfoWithPointerInfo_--_1_--dtor$0.c)
 *     _InitializeTargetInfoWithPointerInfo_::_1_::dtor$1 @ 0x1800B07B7 (_InitializeTargetInfoWithPointerInfo_--_1_--dtor$1.c)
 *     _Win32kInterop::MakeRoutingDecisionsForAllFrames_::_1_::dtor$1 @ 0x1800B0BC3 (_Win32kInterop--MakeRoutingDecisionsForAllFrames_--_1_--dtor$1.c)
 *     _Win32kInterop::ProcessInputMessage_::_1_::dtor$6 @ 0x1800B180A (_Win32kInterop--ProcessInputMessage_--_1_--dtor$6.c)
 *     _Win32kInterop::ProcessMouseInputMessage_::_1_::dtor$0 @ 0x1800B2084 (_Win32kInterop--ProcessMouseInputMessage_--_1_--dtor$0.c)
 *     _Win32kInterop::RouteCachedInput_::_1_::dtor$0 @ 0x1800B2758 (_Win32kInterop--RouteCachedInput_--_1_--dtor$0.c)
 *     _ISMTracing::GetPIDOfTarget_::_1_::dtor$0 @ 0x1800B7CD8 (_ISMTracing--GetPIDOfTarget_--_1_--dtor$0.c)
 *     _ISMTracing::GetVIDOfTarget_::_1_::dtor$0 @ 0x1800B7D70 (_ISMTracing--GetVIDOfTarget_--_1_--dtor$0.c)
 *     _MPCInputRouter::Initialize3DComponents_::_1_::dtor$0 @ 0x1800B83DC (_MPCInputRouter--Initialize3DComponents_--_1_--dtor$0.c)
 *     _MPCInputRouter::Initialize3DComponents_::_1_::dtor$1 @ 0x1800B83E8 (_MPCInputRouter--Initialize3DComponents_--_1_--dtor$1.c)
 *     _MPCInputRouter::OnExclusiveModeStateChangedInputThread_::_1_::dtor$0 @ 0x1800B9099 (_MPCInputRouter--OnExclusiveModeStateChangedInputThread_--_1_--dtor$0.c)
 *     _GetContainerIdFromInputTarget_::_1_::dtor$0 @ 0x18010191B (_GetContainerIdFromInputTarget_--_1_--dtor$0.c)
 *     _Windows::Internal::AsyncBaseWithProgressFTM_Windows::Foundation::IAsyncActionCompletedHandler_Windows::Internal::INilDelegate_1_Microsoft::WRL::AsyncCausalityOptions_&SetConstantToDefaultAsyncCasualityName_&GUID_CAUSALITY_WINDOWS_PLATFORM_ID_2___::FireProgress_::_1_::dtor$1 @ 0x18011489C (_Windows--Internal--AsyncBaseWithProgressFTM_Windows--Foundation--IAsyncActionCompl_ea_18011489C.c)
 *     ?OnInputReport@KeyboardProcessor@@UEAAJPEAUInputInfo@@@Z @ 0x1801352E0 (-OnInputReport@KeyboardProcessor@@UEAAJPEAUInputInfo@@@Z.c)
 *     _KeyboardProcessor::OnInputReport_::_1_::dtor$0 @ 0x1801355C2 (_KeyboardProcessor--OnInputReport_--_1_--dtor$0.c)
 *     _DWMInputRouter::GetTargetFromInputDest_::_1_::dtor$0 @ 0x1801382EC (_DWMInputRouter--GetTargetFromInputDest_--_1_--dtor$0.c)
 *     _DWMFocusedInputTarget::GetInputSink_::_1_::dtor$0 @ 0x180139E01 (_DWMFocusedInputTarget--GetInputSink_--_1_--dtor$0.c)
 *     _DWMFocusedInputTarget::GetInteractionObject_::_1_::dtor$0 @ 0x180139ECF (_DWMFocusedInputTarget--GetInteractionObject_--_1_--dtor$0.c)
 *     _DWMFocusedInputTarget::GetRoutingInfo_::_1_::dtor$0 @ 0x180139FF5 (_DWMFocusedInputTarget--GetRoutingInfo_--_1_--dtor$0.c)
 *     _DWMFocusedInputTarget::IsSameAsTarget_::_1_::dtor$0 @ 0x18013A075 (_DWMFocusedInputTarget--IsSameAsTarget_--_1_--dtor$0.c)
 *     _DWMFocusedInputTarget::IsSameAsTarget_::_1_::dtor$0_0 @ 0x18013A104 (_DWMFocusedInputTarget--IsSameAsTarget_--_1_--dtor$0_0.c)
 *     _DWMFocusedInputTarget::IsSameByLuid_::_1_::dtor$0 @ 0x18013A185 (_DWMFocusedInputTarget--IsSameByLuid_--_1_--dtor$0.c)
 *     _DWMFocusedInputTarget::SetInteractionObject_::_1_::dtor$0 @ 0x18013A203 (_DWMFocusedInputTarget--SetInteractionObject_--_1_--dtor$0.c)
 *     _DWMFocusedInputTarget::ShouldRedirectToManipulationThread_::_1_::dtor$0 @ 0x18013A27F (_DWMFocusedInputTarget--ShouldRedirectToManipulationThread_--_1_--dtor$0.c)
 *     _ContextualProcessorManager::OnHitTest_::_1_::dtor$3 @ 0x180149786 (_ContextualProcessorManager--OnHitTest_--_1_--dtor$3.c)
 *     _std::_Uninitialized_move_ContextualProcessorBuffer::ContextualProcessorMetadata___ContextualProcessorBuffer::ContextualProcessorMetadata___std::allocator_ContextualProcessorBuffer::ContextualProcessorMetadata____::_1_::dtor$1 @ 0x18014A6D2 (_std--_Uninitialized_move_ContextualProcessorBuffer--ContextualProcessorMetadata____ea_18014A6D2.c)
 *     _ContextualProcessorBuffer::DeliverInput_::_1_::dtor$3 @ 0x18014B827 (_ContextualProcessorBuffer--DeliverInput_--_1_--dtor$3.c)
 *     _ContextualProcessorBuffer::DeliverInput_::_1_::dtor$5 @ 0x18014B83F (_ContextualProcessorBuffer--DeliverInput_--_1_--dtor$5.c)
 *     _ContextualProcessorBuffer::DeliverInput_::_1_::dtor$10 @ 0x18014B86F (_ContextualProcessorBuffer--DeliverInput_--_1_--dtor$10.c)
 *     _ContextualProcessorBuffer::DeliverInput_::_1_::dtor$12 @ 0x18014B887 (_ContextualProcessorBuffer--DeliverInput_--_1_--dtor$12.c)
 *     ?DeliverInputToTarget@ContextualProcessorBuffer@@AEAAJPEAUInputInfo@@AEAV?$unordered_map@KV?$ComPtr@UIInputTarget@@@WRL@Microsoft@@U?$hash@K@std@@U?$equal_to@K@5@V?$allocator@U?$pair@$$CBKV?$ComPtr@UIInputTarget@@@WRL@Microsoft@@@std@@@5@@std@@1AEAV?$unordered_set@KU?$hash@K@std@@U?$equal_to@K@2@V?$allocator@K@2@@4@@Z @ 0x18014B91C (-DeliverInputToTarget@ContextualProcessorBuffer@@AEAAJPEAUInputInfo@@AEAV-$unordered_map@KV-$Com.c)
 *     _ContextualProcessorBuffer::DeliverInputToTarget_::_1_::dtor$0 @ 0x18014BCF9 (_ContextualProcessorBuffer--DeliverInputToTarget_--_1_--dtor$0.c)
 *     ?GetInputSink@ContextualProcessorBuffer@@UEBAPEAXXZ @ 0x18014BF40 (-GetInputSink@ContextualProcessorBuffer@@UEBAPEAXXZ.c)
 *     _ContextualProcessorBuffer::GetInputSink_::_1_::dtor$0 @ 0x18014BF94 (_ContextualProcessorBuffer--GetInputSink_--_1_--dtor$0.c)
 *     ?GetInteractionObject@ContextualProcessorBuffer@@UEBAIXZ @ 0x18014BFB0 (-GetInteractionObject@ContextualProcessorBuffer@@UEBAIXZ.c)
 *     _ContextualProcessorBuffer::GetInteractionObject_::_1_::dtor$0 @ 0x18014C002 (_ContextualProcessorBuffer--GetInteractionObject_--_1_--dtor$0.c)
 *     _ContextualProcessorBuffer::GetRoutingInfo_::_1_::dtor$0 @ 0x18014C109 (_ContextualProcessorBuffer--GetRoutingInfo_--_1_--dtor$0.c)
 *     ?IsSameAsTarget@ContextualProcessorBuffer@@UEBA_NAEBUtagMsgRoutingInfo@@@Z @ 0x18014C310 (-IsSameAsTarget@ContextualProcessorBuffer@@UEBA_NAEBUtagMsgRoutingInfo@@@Z.c)
 *     _ContextualProcessorBuffer::IsSameAsTarget_::_1_::dtor$0 @ 0x18014C371 (_ContextualProcessorBuffer--IsSameAsTarget_--_1_--dtor$0.c)
 *     ?IsSameAsTarget@ContextualProcessorBuffer@@UEBA_NAEBUtagMsgRoutingInfo@@PEAX@Z @ 0x18014C390 (-IsSameAsTarget@ContextualProcessorBuffer@@UEBA_NAEBUtagMsgRoutingInfo@@PEAX@Z.c)
 *     _ContextualProcessorBuffer::IsSameAsTarget_::_1_::dtor$0_0 @ 0x18014C400 (_ContextualProcessorBuffer--IsSameAsTarget_--_1_--dtor$0_0.c)
 *     ?IsSameByLuid@ContextualProcessorBuffer@@UEBA_NPEAX@Z @ 0x18014C420 (-IsSameByLuid@ContextualProcessorBuffer@@UEBA_NPEAX@Z.c)
 *     _ContextualProcessorBuffer::IsSameByLuid_::_1_::dtor$0 @ 0x18014C481 (_ContextualProcessorBuffer--IsSameByLuid_--_1_--dtor$0.c)
 *     _ContextualProcessorBuffer::OnDeferredContextualProcessorResponse_::_1_::dtor$7 @ 0x18014CA43 (_ContextualProcessorBuffer--OnDeferredContextualProcessorResponse_--_1_--dtor$7.c)
 *     ?SetInteractionObject@ContextualProcessorBuffer@@UEAAJI@Z @ 0x18014D470 (-SetInteractionObject@ContextualProcessorBuffer@@UEAAJI@Z.c)
 *     _ContextualProcessorBuffer::SetInteractionObject_::_1_::dtor$0 @ 0x18014D4CD (_ContextualProcessorBuffer--SetInteractionObject_--_1_--dtor$0.c)
 *     ?ShouldRedirectToManipulationThread@ContextualProcessorBuffer@@UEBA_NXZ @ 0x18014D4E0 (-ShouldRedirectToManipulationThread@ContextualProcessorBuffer@@UEBA_NXZ.c)
 *     _ContextualProcessorBuffer::ShouldRedirectToManipulationThread_::_1_::dtor$0 @ 0x18014D532 (_ContextualProcessorBuffer--ShouldRedirectToManipulationThread_--_1_--dtor$0.c)
 *     _ContextualProcessorBuffer::TryAddProcessorAndContact_::_1_::dtor$1 @ 0x18014D6CF (_ContextualProcessorBuffer--TryAddProcessorAndContact_--_1_--dtor$1.c)
 *     _ThreadHelpers::ChainedThreadpoolWorker::Then_::_1_::dtor$2 @ 0x180166213 (_ThreadHelpers--ChainedThreadpoolWorker--Then_--_1_--dtor$2.c)
 *     _ThreadHelpers::ChainedThreadpoolWorker::WorkCallback_::_1_::dtor$1 @ 0x180166AA4 (_ThreadHelpers--ChainedThreadpoolWorker--WorkCallback_--_1_--dtor$1.c)
 *     _ThreadHelpers::ChainedThreadpoolWorker::WorkCallback_::_1_::dtor$2 @ 0x180166AB0 (_ThreadHelpers--ChainedThreadpoolWorker--WorkCallback_--_1_--dtor$2.c)
 *     _InputForwardProcessor::OnHitTest_::_1_::dtor$1 @ 0x180176AEC (_InputForwardProcessor--OnHitTest_--_1_--dtor$1.c)
 *     _InputForwardProcessor::OnInput_::_1_::dtor$0 @ 0x180176CB4 (_InputForwardProcessor--OnInput_--_1_--dtor$0.c)
 *     _EdgyProcessorTarget::UpdateInputTarget_::_1_::dtor$0 @ 0x18017B519 (_EdgyProcessorTarget--UpdateInputTarget_--_1_--dtor$0.c)
 *     _EdgyProcessorTarget::UpdateInputTarget_::_1_::dtor$1 @ 0x18017B525 (_EdgyProcessorTarget--UpdateInputTarget_--_1_--dtor$1.c)
 *     _EdgyImpl::EnsureInputTargeting_::_1_::dtor$1 @ 0x18017B8EE (_EdgyImpl--EnsureInputTargeting_--_1_--dtor$1.c)
 *     _EdgyImpl::EnsureInputTargeting_::_1_::dtor$2 @ 0x18017B8FA (_EdgyImpl--EnsureInputTargeting_--_1_--dtor$2.c)
 *     _GetContainerGuidFromInputTarget_::_1_::dtor$0 @ 0x18017FFDB (_GetContainerGuidFromInputTarget_--_1_--dtor$0.c)
 *     _GazeProcessor::GazeProcessor_::_1_::dtor$1 @ 0x18018836C (_GazeProcessor--GazeProcessor_--_1_--dtor$1.c)
 *     _GazeProcessor::OnInputReport_::_1_::dtor$0 @ 0x180188CF7 (_GazeProcessor--OnInputReport_--_1_--dtor$0.c)
 *     _MPCMouseProcessor::PopulateTargetingData_::_1_::dtor$1 @ 0x1801967E5 (_MPCMouseProcessor--PopulateTargetingData_--_1_--dtor$1.c)
 * Callees:
 *     <none>
 */

// attributes: thunk
void __fastcall ContextualProcessorManager::ContextualProcessorEntry::~ContextualProcessorEntry(__int64 *this)
{
  Microsoft::WRL::ComPtr<IUnknown>::InternalRelease(this);
}
