/*
 * XREFs of ?IsRotateVAD@VIDMM_RECYCLE_MULTIRANGE@@QEAAEXZ @ 0x1C006BCC4
 * Callers:
 *     ?Rotate@VIDMM_RECYCLE_MULTIRANGE@@QEAAJPEAVVIDMM_GLOBAL@@W4_MM_ROTATE_DIRECTION@@PEAU_MDL@@_KP6AJ22PEAX@Z4TVIDMM_ROTATE_FLAGS@@PEAU_VIDMM_GLOBAL_ALLOC@@@Z @ 0x1C006BA90 (-Rotate@VIDMM_RECYCLE_MULTIRANGE@@QEAAJPEAVVIDMM_GLOBAL@@W4_MM_ROTATE_DIRECTION@@PEAU_MDL@@_KP6A.c)
 *     ?VidMmFindAlignedRange@@YAJPEAXPEAU_RTL_BALANCED_NODE@@@Z @ 0x1C006C4AC (-VidMmFindAlignedRange@@YAJPEAXPEAU_RTL_BALANCED_NODE@@@Z.c)
 * Callees:
 *     ?GetNextRange@VIDMM_RECYCLE_RANGE@@QEAAPEAV1@XZ @ 0x1C006CEB8 (-GetNextRange@VIDMM_RECYCLE_RANGE@@QEAAPEAV1@XZ.c)
 */

unsigned __int8 __fastcall VIDMM_RECYCLE_MULTIRANGE::IsRotateVAD(struct VIDMM_RECYCLE_RANGE **this)
{
  VIDMM_RECYCLE_MULTIRANGE *v1; // r8
  struct VIDMM_RECYCLE_RANGE *i; // rcx

  v1 = (VIDMM_RECYCLE_MULTIRANGE *)this;
  for ( i = this[8]; ; i = VIDMM_RECYCLE_RANGE::GetNextRange(i) )
  {
    if ( (*((_DWORD *)i + 20) & 0x800000) == 0 )
      return 0;
    if ( i == *((struct VIDMM_RECYCLE_RANGE **)v1 + 9) )
      break;
  }
  return 1;
}
