/*
 * XREFs of ??0DWMSCREENREADMODIFYWRITEASSIST@@QEAA@AEAVXDCOBJ@@@Z @ 0x1C015E3AC
 * Callers:
 *     NtGdiPolyPatBlt @ 0x1C0043A80 (NtGdiPolyPatBlt.c)
 * Callees:
 *     <none>
 */

DWMSCREENREADMODIFYWRITEASSIST *__fastcall DWMSCREENREADMODIFYWRITEASSIST::DWMSCREENREADMODIFYWRITEASSIST(
        DWMSCREENREADMODIFYWRITEASSIST *this,
        struct XDCOBJ *a2)
{
  *((_QWORD *)this + 3) = a2;
  return this;
}
