/*
 * XREFs of ?ReleaseDdiEnumerator@DMMVIDEOPRESENTTARGETSET@@QEAAJPEBU_D3DKMDT_VIDEO_PRESENT_TARGET@@@Z @ 0x1C00F5E8C
 * Callers:
 *     ?AddTarget@DXGPORTDMM_VIDEOPRESENTTARGETSET_INTERFACE_V1_IMPL@@YAJQEAUD3DKMDT_HVIDEOPRESENTTARGETSET__@@PEBU_D3DKMDT_VIDEO_PRESENT_TARGET@@@Z @ 0x1C00F5CD0 (-AddTarget@DXGPORTDMM_VIDEOPRESENTTARGETSET_INTERFACE_V1_IMPL@@YAJQEAUD3DKMDT_HVIDEOPRESENTTARGE.c)
 *     ?ReleaseTargetInfo@DXGDMM_VIDEOPRESENTTARGETSET_INTERFACE_V1_IMPL@@YAJQEAUD3DKMDT_HVIDEOPRESENTTARGETSET__@@QEBU_D3DKMDT_VIDEO_PRESENT_TARGET@@@Z @ 0x1C01A6EF0 (-ReleaseTargetInfo@DXGDMM_VIDEOPRESENTTARGETSET_INTERFACE_V1_IMPL@@YAJQEAUD3DKMDT_HVIDEOPRESENTT.c)
 *     ?ReleaseTargetInfo@DXGPORTDMM_VIDEOPRESENTTARGETSET_INTERFACE_V1_IMPL@@YAJQEAUD3DKMDT_HVIDEOPRESENTTARGETSET__@@PEBU_D3DKMDT_VIDEO_PRESENT_TARGET@@@Z @ 0x1C01AA1A0 (-ReleaseTargetInfo@DXGPORTDMM_VIDEOPRESENTTARGETSET_INTERFACE_V1_IMPL@@YAJQEAUD3DKMDT_HVIDEOPRES.c)
 * Callees:
 *     ?ContainsByReference@?$DoublyLinkedList@VDMMVIDEOPRESENTTARGET@@@@QEAAEQEBVDMMVIDEOPRESENTTARGET@@@Z @ 0x1C000FE88 (-ContainsByReference@-$DoublyLinkedList@VDMMVIDEOPRESENTTARGET@@@@QEAAEQEBVDMMVIDEOPRESENTTARGET.c)
 *     ??3@YAXPEAX@Z @ 0x1C007F918 (--3@YAXPEAX@Z.c)
 */

__int64 __fastcall DMMVIDEOPRESENTTARGETSET::ReleaseDdiEnumerator(
        DMMVIDEOPRESENTTARGETSET *this,
        const struct _D3DKMDT_VIDEO_PRESENT_TARGET *a2)
{
  D3DKMDT_VIDEO_OUTPUT_TECHNOLOGY *p_VideoOutputTechnology; // r9
  __int64 v3; // rdx

  if ( !a2 )
    return 3223192325LL;
  p_VideoOutputTechnology = &a2[-1].VideoOutputTechnology;
  if ( a2[-1].VideoOutputTechnology != 305419896 )
    return 3223192325LL;
  v3 = *((_QWORD *)p_VideoOutputTechnology + 1);
  if ( v3 && !DoublyLinkedList<DMMVIDEOPRESENTTARGET>::ContainsByReference((__int64)this + 8, v3) )
    return 3223192368LL;
  operator delete(p_VideoOutputTechnology);
  return 0LL;
}
