/*
 * XREFs of ??$Win32HM_UnlockFromThread@$0A@@@YAPEAU_HEAD@@PEAUtagTHREADINFO@@PEAU_Win32HMThreadLockItem@@@Z @ 0x14001BB04
 * Callers:
 *     NtUserDrainThreadCoreMessagingCompletions2 @ 0x14001A430 (NtUserDrainThreadCoreMessagingCompletions2.c)
 *     NtUserMessageCall @ 0x14001B730 (NtUserMessageCall.c)
 *     ??1?$Win32HMThreadLockAlways@UtagWND@@@@QEAA@XZ @ 0x14001BAA0 (--1-$Win32HMThreadLockAlways@UtagWND@@@@QEAA@XZ.c)
 *     ??1?$Win32HMOptionalThreadLockAlways@UtagMENU@@@@QEAA@XZ @ 0x14001BAD0 (--1-$Win32HMOptionalThreadLockAlways@UtagMENU@@@@QEAA@XZ.c)
 *     zzzLockDisplayAreaAndInvalidateDCCache @ 0x14001C3E0 (zzzLockDisplayAreaAndInvalidateDCCache.c)
 *     NtUserLayoutCompleted @ 0x140023670 (NtUserLayoutCompleted.c)
 *     xxxProcessAsyncSendMessage @ 0x14002FF54 (xxxProcessAsyncSendMessage.c)
 *     xxxInternalDoSyncPaint @ 0x1400356D0 (xxxInternalDoSyncPaint.c)
 *     ?xxxImeWindowPosChanged@@YAXPEAUtagSMWP@@@Z @ 0x140035D3C (-xxxImeWindowPosChanged@@YAXPEAUtagSMWP@@@Z.c)
 *     xxxGetMenuItemRect @ 0x14003D798 (xxxGetMenuItemRect.c)
 *     ??1?$Win32HMThreadLockBase@UtagKL@@$0A@$0A@@@QEAA@XZ @ 0x14003D91C (--1-$Win32HMThreadLockBase@UtagKL@@$0A@$0A@@@QEAA@XZ.c)
 *     NtUserPaintMenuBar @ 0x14003DEB0 (NtUserPaintMenuBar.c)
 *     xxxPaintMenuBar @ 0x14003F7B0 (xxxPaintMenuBar.c)
 *     ?xxxSendMenuDrawItemMessage@@YAXPEAUHDC__@@IAEBV?$SmartObjStackRef@UtagMENU@@@@PEAUtagITEM@@HHPEAUtagWND@@@Z @ 0x14004047C (-xxxSendMenuDrawItemMessage@@YAXPEAUHDC__@@IAEBV-$SmartObjStackRef@UtagMENU@@@@PEAUtagITEM@@HHPE.c)
 *     xxxMNFindWindowFromPoint @ 0x14004476C (xxxMNFindWindowFromPoint.c)
 *     xxxSetSysMenu @ 0x140046248 (xxxSetSysMenu.c)
 *     xxxCalcClientRect @ 0x140047B98 (xxxCalcClientRect.c)
 *     xxxInitSendValidateMinMaxInfoEx @ 0x14004A6D4 (xxxInitSendValidateMinMaxInfoEx.c)
 *     NtUserEndDeferWindowPosEx @ 0x14004C490 (NtUserEndDeferWindowPosEx.c)
 *     NtUserMoveWindow @ 0x14004C540 (NtUserMoveWindow.c)
 *     ?zzzAnimateCursor@@YAXPEAUtagWND@@I_K_J@Z @ 0x14004C710 (-zzzAnimateCursor@@YAXPEAUtagWND@@I_K_J@Z.c)
 *     NtUserGetUpdateRgn @ 0x14004DE20 (NtUserGetUpdateRgn.c)
 *     ?xxxFocusSetInputContext@@YAXPEAUtagWND@@HH@Z @ 0x14004E56C (-xxxFocusSetInputContext@@YAXPEAUtagWND@@HH@Z.c)
 *     xxxDW_DestroyOwnedWindows @ 0x14004E938 (xxxDW_DestroyOwnedWindows.c)
 *     ?xxxUpdateWindow2@@YAXPEAUtagWND@@K@Z @ 0x14004F8CC (-xxxUpdateWindow2@@YAXPEAUtagWND@@K@Z.c)
 *     xxxCalcMenuBar @ 0x140050EB4 (xxxCalcMenuBar.c)
 *     NtUserUpdateLayeredWindow @ 0x140051B10 (NtUserUpdateLayeredWindow.c)
 *     ?xxxFW_DestroyAllChildren@@YAXPEAUtagWND@@@Z @ 0x140058F0C (-xxxFW_DestroyAllChildren@@YAXPEAUtagWND@@@Z.c)
 *     NtUserSetParent @ 0x140060E30 (NtUserSetParent.c)
 *     xxxDW_SendDestroyMessages @ 0x140062AC0 (xxxDW_SendDestroyMessages.c)
 *     xxxInternalEnumWindow @ 0x14006337C (xxxInternalEnumWindow.c)
 *     xxxInheritWindowMonitor @ 0x140064724 (xxxInheritWindowMonitor.c)
 *     NtUserSetLayeredWindowAttributes @ 0x1400E0EB0 (NtUserSetLayeredWindowAttributes.c)
 *     NtUserShowWindowAsync @ 0x140129240 (NtUserShowWindowAsync.c)
 *     xxxBroadcastMessageEx @ 0x1401293EC (xxxBroadcastMessageEx.c)
 *     ?xxxSendBSMtoDesktop@@YAHPEAUtagWND@@I_K_JPEAUtagBROADCASTSYSTEMMSGPARAMS@@H@Z @ 0x140129E38 (-xxxSendBSMtoDesktop@@YAHPEAUtagWND@@I_K_JPEAUtagBROADCASTSYSTEMMSGPARAMS@@H@Z.c)
 *     NtUserScheduleDispatchNotification @ 0x14012A7E0 (NtUserScheduleDispatchNotification.c)
 *     ?xxxWrapSendNotifyMessage@@YA_JPEAUtagWND@@I_K_J1@Z @ 0x14012B440 (-xxxWrapSendNotifyMessage@@YA_JPEAUtagWND@@I_K_J1@Z.c)
 *     ?xxxWrapSendMessageCallback@@YA_JPEAUtagWND@@I_K_J1@Z @ 0x14012B690 (-xxxWrapSendMessageCallback@@YA_JPEAUtagWND@@I_K_J1@Z.c)
 *     ?xxxNotifyShellOfWallpaperChange@@YAHXZ @ 0x14012F610 (-xxxNotifyShellOfWallpaperChange@@YAHXZ.c)
 *     NtUserBuildPropList @ 0x140143470 (NtUserBuildPropList.c)
 *     xxxTrackPopupMenuEx @ 0x14015AE18 (xxxTrackPopupMenuEx.c)
 *     NtUserSendEventMessage @ 0x14015C0A0 (NtUserSendEventMessage.c)
 *     NtUserSetWindowBand @ 0x14015C390 (NtUserSetWindowBand.c)
 *     ?xxxSetWindowBand@@YAHPEAUtagWND@@0W4ZBID@@W4WindowBandOptions@@@Z @ 0x14015CF34 (-xxxSetWindowBand@@YAHPEAUtagWND@@0W4ZBID@@W4WindowBandOptions@@@Z.c)
 *     NtUserShowWindow @ 0x140170070 (NtUserShowWindow.c)
 *     xxxCsDdeInitialize @ 0x14017DC44 (xxxCsDdeInitialize.c)
 *     NtUserSetWindowLongPtr @ 0x14017DF80 (NtUserSetWindowLongPtr.c)
 *     NtUserSetWindowLong @ 0x140180160 (NtUserSetWindowLong.c)
 *     ?xxxDestroyCorrespondingGhostWindow@@YAHPEAUtagWND@@@Z @ 0x1401809E0 (-xxxDestroyCorrespondingGhostWindow@@YAHPEAUtagWND@@@Z.c)
 *     xxxFindNCHitEx @ 0x1401848B4 (xxxFindNCHitEx.c)
 *     NtUserGetModernAppWindow @ 0x140187720 (NtUserGetModernAppWindow.c)
 *     xxxShowOwnedWindows @ 0x14018786C (xxxShowOwnedWindows.c)
 *     ??$ManualUnlock@X@?$Win32HMThreadLockBase@UtagMENU@@$0A@$00@@QEAAPEAUtagMENU@@XZ @ 0x140187B78 (--$ManualUnlock@X@-$Win32HMThreadLockBase@UtagMENU@@$0A@$00@@QEAAPEAUtagMENU@@XZ.c)
 *     xxxActiveWindowTracking @ 0x14018CE4C (xxxActiveWindowTracking.c)
 *     NtUserIsChildWindowDpiMessageEnabled @ 0x14019C360 (NtUserIsChildWindowDpiMessageEnabled.c)
 *     NtUserIsNonClientDpiScalingEnabled @ 0x14019C4E0 (NtUserIsNonClientDpiScalingEnabled.c)
 *     NtUserDeregisterShellHookWindow @ 0x14019F020 (NtUserDeregisterShellHookWindow.c)
 *     ?xxxActivateOnMinimize@@YAHPEAUtagWND@@@Z @ 0x1401A77E4 (-xxxActivateOnMinimize@@YAHPEAUtagWND@@@Z.c)
 *     NtUserIsWindowBroadcastingDpiToChildren @ 0x1401A91C0 (NtUserIsWindowBroadcastingDpiToChildren.c)
 *     xxxLoadSysMenu @ 0x1401B260C (xxxLoadSysMenu.c)
 *     ?TestWindowForCompositionTarget@@YAJPEAUHWND__@@K@Z @ 0x1401B8960 (-TestWindowForCompositionTarget@@YAJPEAUHWND__@@K@Z.c)
 *     ?AttachWindowCompositionTarget@@YAJPEAUHWND__@@KPEAUCompositionObject@@@Z @ 0x1401B8A54 (-AttachWindowCompositionTarget@@YAJPEAUHWND__@@KPEAUCompositionObject@@@Z.c)
 *     NtUserRegisterShellHookWindow @ 0x1401BE620 (NtUserRegisterShellHookWindow.c)
 *     ?GetResizeDCompositionSynchronizationObject@@YAHPEAUHWND__@@PEAPEAUCompositionObject@@@Z @ 0x1401C7FCC (-GetResizeDCompositionSynchronizationObject@@YAHPEAUHWND__@@PEAPEAUCompositionObject@@@Z.c)
 *     NtUserSetWindowRgn @ 0x1401C8AA0 (NtUserSetWindowRgn.c)
 *     NtUserNotifyIMEStatus @ 0x1401C8EF0 (NtUserNotifyIMEStatus.c)
 *     NtUserDWP_GetEnabledPopupOffset @ 0x1401CB3F0 (NtUserDWP_GetEnabledPopupOffset.c)
 *     xxxDWP_UpdateUIState @ 0x1401CE994 (xxxDWP_UpdateUIState.c)
 *     ?xxxDWPPrint@@YAHPEAUtagWND@@PEAUHDC__@@_J@Z @ 0x1401CF77C (-xxxDWPPrint@@YAHPEAUtagWND@@PEAUHDC__@@_J@Z.c)
 *     NtUserInvalidateRgn @ 0x1401D0770 (NtUserInvalidateRgn.c)
 *     NtUserShowScrollBar @ 0x1401D4110 (NtUserShowScrollBar.c)
 *     NtUserFillWindow @ 0x1401D4B80 (NtUserFillWindow.c)
 *     ?DetachWindowCompositionTarget@@YAJPEAUHWND__@@K@Z @ 0x1401D633C (-DetachWindowCompositionTarget@@YAJPEAUHWND__@@K@Z.c)
 *     NtUserCreateCaret @ 0x1401DBA50 (NtUserCreateCaret.c)
 *     NtUserfnDDEINIT @ 0x1401E2A50 (NtUserfnDDEINIT.c)
 *     NtUserGetControlBrush @ 0x1401E36A0 (NtUserGetControlBrush.c)
 *     NtUserEnableMenuItem @ 0x1401E53F0 (NtUserEnableMenuItem.c)
 *     NtUserEnableNonClientDpiScaling @ 0x1401E69C0 (NtUserEnableNonClientDpiScaling.c)
 *     NtUserEnableChildWindowDpiMessage @ 0x1401E8A10 (NtUserEnableChildWindowDpiMessage.c)
 *     NtUserEnableScrollBar @ 0x1401E8BE0 (NtUserEnableScrollBar.c)
 *     NtUserBeginLayoutUpdate @ 0x1401E9650 (NtUserBeginLayoutUpdate.c)
 *     NtUserEnableMouseInPointerForWindow @ 0x1401E9CC0 (NtUserEnableMouseInPointerForWindow.c)
 *     ?xxxSendDpiChangedMessageToChildWindow@@YAHPEAUHWND__@@H@Z @ 0x1401EB2CC (-xxxSendDpiChangedMessageToChildWindow@@YAHPEAUHWND__@@H@Z.c)
 *     NtUserInheritWindowMonitor @ 0x1401ED620 (NtUserInheritWindowMonitor.c)
 *     NtUserSetMenu @ 0x1401FBBA0 (NtUserSetMenu.c)
 *     NtUserEnableResizeLayoutSynchronization @ 0x140201610 (NtUserEnableResizeLayoutSynchronization.c)
 *     xxxMenuBarDraw @ 0x14020258C (xxxMenuBarDraw.c)
 *     NtUserSetWindowWord @ 0x140203A60 (NtUserSetWindowWord.c)
 *     ?xxxSendDpiChangedMessageToTopLevelWindow@@YAHPEAUtagWND@@PEAUtagRECT@@@Z @ 0x140205018 (-xxxSendDpiChangedMessageToTopLevelWindow@@YAHPEAUtagWND@@PEAUtagRECT@@@Z.c)
 *     NtUserSetClassLong @ 0x140205300 (NtUserSetClassLong.c)
 *     xxxTurnOffCompositing @ 0x1402062A8 (xxxTurnOffCompositing.c)
 *     NtUserGetControlColor @ 0x140206420 (NtUserGetControlColor.c)
 *     NtUserDeferWindowDpiChanges @ 0x14020D890 (NtUserDeferWindowDpiChanges.c)
 *     ?xxxImmActivateLayout@@YAXPEAUtagTHREADINFO@@PEAUtagKL@@@Z @ 0x1402120C8 (-xxxImmActivateLayout@@YAXPEAUtagTHREADINFO@@PEAUtagKL@@@Z.c)
 *     NtUserMenuItemFromPoint @ 0x1402151F0 (NtUserMenuItemFromPoint.c)
 *     NtUserSetChildWindowNoActivate @ 0x140219B90 (NtUserSetChildWindowNoActivate.c)
 *     EditionSendIMENotification @ 0x140225450 (EditionSendIMENotification.c)
 *     _anonymous_namespace_::xxxSetForegroundCheckNoActivate @ 0x14026AB74 (_anonymous_namespace_--xxxSetForegroundCheckNoActivate.c)
 *     ??1?$Win32HMThreadLockBase@UtagDDECONV@@$0A@$00@@QEAA@XZ @ 0x1402B10D0 (--1-$Win32HMThreadLockBase@UtagDDECONV@@$0A@$00@@QEAA@XZ.c)
 * Callees:
 *     <none>
 */

__int64 __fastcall Win32HM_UnlockFromThread<0>(ULONG_PTR BugCheckParameter2, _QWORD *BugCheckParameter3)
{
  _QWORD *v2; // r8

  v2 = *(_QWORD **)(BugCheckParameter2 + 456);
  if ( v2 != BugCheckParameter3 )
    KeBugCheckEx(0x164u, 0x3BuLL, BugCheckParameter2, (ULONG_PTR)BugCheckParameter3, 0LL);
  *(_QWORD *)(BugCheckParameter2 + 456) = *v2;
  return HMUnlockObject(v2[1]);
}
