/*
 * XREFs of ??_GDXGCONTEXT@@QEAAPEAXI@Z @ 0x1C004981C
 * Callers:
 *     ?CreateContext@DXGDEVICE@@QEAAJPEAPEAVDXGCONTEXT@@IIU_D3DDDI_CREATECONTEXTFLAGS@@PEAXIW4_D3DKMT_CLIENTHINT@@E@Z @ 0x1C018F760 (-CreateContext@DXGDEVICE@@QEAAJPEAPEAVDXGCONTEXT@@IIU_D3DDDI_CREATECONTEXTFLAGS@@PEAXIW4_D3DKMT_.c)
 * Callees:
 *     ??1DXGCONTEXT@@QEAA@XZ @ 0x1C018E26C (--1DXGCONTEXT@@QEAA@XZ.c)
 */

DXGCONTEXT *__fastcall DXGCONTEXT::`scalar deleting destructor'(DXGCONTEXT *P)
{
  DXGCONTEXT::~DXGCONTEXT(P);
  if ( P )
    ExFreePoolWithTag(P, 0);
  return P;
}
