/*
 * XREFs of ??1?$CComPtr@UIMMDeviceEnumerator@@@ATL@@QEAA@XZ @ 0x1400260C0
 * Callers:
 *     _CStreamInstance::GetOta_::_1_::dtor$1 @ 0x14001AB09 (_CStreamInstance--GetOta_--_1_--dtor$1.c)
 *     _CStreamInstance::DisconnectFromSaDevice_::_1_::dtor$0 @ 0x14001AB1B (_CStreamInstance--DisconnectFromSaDevice_--_1_--dtor$0.c)
 *     _CStreamInstance::ConnectToSaDevice_::_1_::dtor$0 @ 0x14001AB2D (_CStreamInstance--ConnectToSaDevice_--_1_--dtor$0.c)
 *     _CStreamGroup::CreateStream_::_1_::dtor$8 @ 0x14001ABBC (_CStreamGroup--CreateStream_--_1_--dtor$8.c)
 *     _CStreamGroup::CreateStream_::_1_::dtor$9 @ 0x14001ABFF (_CStreamGroup--CreateStream_--_1_--dtor$9.c)
 *     _CStreamGroup::Initialize_::_1_::dtor$0 @ 0x14001AC20 (_CStreamGroup--Initialize_--_1_--dtor$0.c)
 *     _CStreamGroup::_CStreamGroup_::_1_::dtor$4 @ 0x14001ACC0 (_CStreamGroup--_CStreamGroup_--_1_--dtor$4.c)
 *     _CStreamGroup::_CStreamGroup_::_1_::dtor$8 @ 0x14001AD0C (_CStreamGroup--_CStreamGroup_--_1_--dtor$8.c)
 *     _CStreamGroup::_CStreamGroup_::_1_::dtor$9 @ 0x14001AD1F (_CStreamGroup--_CStreamGroup_--_1_--dtor$9.c)
 *     _CStreamGroup::_CStreamGroup_::_1_::dtor$11 @ 0x14001AD45 (_CStreamGroup--_CStreamGroup_--_1_--dtor$11.c)
 *     _CStreamGroup::CStreamGroup_::_1_::dtor$4 @ 0x14001AD97 (_CStreamGroup--CStreamGroup_--_1_--dtor$4.c)
 *     _CPipeInstance::ActivateAPOs_::_1_::dtor$0 @ 0x14001AE40 (_CPipeInstance--ActivateAPOs_--_1_--dtor$0.c)
 *     _CSystemAudioDeviceBase::_CSystemAudioDeviceBase_::_1_::dtor$5 @ 0x14001AEAB (_CSystemAudioDeviceBase--_CSystemAudioDeviceBase_--_1_--dtor$5.c)
 *     _CSystemAudioDeviceBase::_CSystemAudioDeviceBase_::_1_::dtor$6 @ 0x14001AEBE (_CSystemAudioDeviceBase--_CSystemAudioDeviceBase_--_1_--dtor$6.c)
 *     _CSystemAudioDeviceBase::_CSystemAudioDeviceBase_::_1_::dtor$7 @ 0x14001AED1 (_CSystemAudioDeviceBase--_CSystemAudioDeviceBase_--_1_--dtor$7.c)
 *     _GetStreamingResourceManager_::_1_::dtor$0 @ 0x14001AF30 (_GetStreamingResourceManager_--_1_--dtor$0.c)
 *     _CSystemAudioDeviceSharedBase::_CSystemAudioDeviceSharedBase_::_1_::dtor$1 @ 0x14001AF4E (_CSystemAudioDeviceSharedBase--_CSystemAudioDeviceSharedBase_--_1_--dtor$1.c)
 *     _CSystemAudioDeviceSharedBase::_CSystemAudioDeviceSharedBase_::_1_::dtor$2 @ 0x14001AF61 (_CSystemAudioDeviceSharedBase--_CSystemAudioDeviceSharedBase_--_1_--dtor$2.c)
 *     _CAudioDeviceGraph::InitializePump_::_1_::dtor$0 @ 0x14001AF98 (_CAudioDeviceGraph--InitializePump_--_1_--dtor$0.c)
 *     _CAudioDeviceGraph::InitializePump_::_1_::dtor$1 @ 0x14001AFA4 (_CAudioDeviceGraph--InitializePump_--_1_--dtor$1.c)
 *     _CAudioDeviceGraph::Initialize_::_1_::dtor$0 @ 0x14001AFC0 (_CAudioDeviceGraph--Initialize_--_1_--dtor$0.c)
 *     _CAudioDeviceGraph::_CAudioDeviceGraph_::_1_::dtor$1 @ 0x14001B02E (_CAudioDeviceGraph--_CAudioDeviceGraph_--_1_--dtor$1.c)
 *     _CAudioDeviceGraph::_CAudioDeviceGraph_::_1_::dtor$2 @ 0x14001B03E (_CAudioDeviceGraph--_CAudioDeviceGraph_--_1_--dtor$2.c)
 *     _CAudioDeviceGraph::_CAudioDeviceGraph_::_1_::dtor$7 @ 0x14001B09A (_CAudioDeviceGraph--_CAudioDeviceGraph_--_1_--dtor$7.c)
 *     _CAudioDeviceGraph::_CAudioDeviceGraph_::_1_::dtor$8 @ 0x14001B0AD (_CAudioDeviceGraph--_CAudioDeviceGraph_--_1_--dtor$8.c)
 *     _CAudioDeviceGraph::CAudioDeviceGraph_::_1_::dtor$1 @ 0x14001B0D6 (_CAudioDeviceGraph--CAudioDeviceGraph_--_1_--dtor$1.c)
 *     _CAudioDeviceGraph::CAudioDeviceGraph_::_1_::dtor$2 @ 0x14001B0E6 (_CAudioDeviceGraph--CAudioDeviceGraph_--_1_--dtor$2.c)
 *     _CEndpointInstance::CreateStreamEndpointInstance_::_1_::dtor$0 @ 0x14001B430 (_CEndpointInstance--CreateStreamEndpointInstance_--_1_--dtor$0.c)
 *     _CEndpointInstance::CreateStreamEndpointInstance_::_1_::dtor$1 @ 0x14001B43C (_CEndpointInstance--CreateStreamEndpointInstance_--_1_--dtor$1.c)
 *     _TrackSystemEffectBehavior_::_1_::dtor$0 @ 0x14001B450 (_TrackSystemEffectBehavior_--_1_--dtor$0.c)
 *     _TrackSystemEffectBehavior_::_1_::dtor$1 @ 0x14001B45C (_TrackSystemEffectBehavior_--_1_--dtor$1.c)
 *     _TrackSystemEffectBehavior_::_1_::dtor$0_0 @ 0x14001B470 (_TrackSystemEffectBehavior_--_1_--dtor$0_0.c)
 *     _CPipeInstance::ResetAPOs_::_1_::dtor$0 @ 0x14001B620 (_CPipeInstance--ResetAPOs_--_1_--dtor$0.c)
 *     _CPipeInstance::ResetAPOs_::_1_::dtor$1 @ 0x14001B62C (_CPipeInstance--ResetAPOs_--_1_--dtor$1.c)
 *     _CPipeInstance::_CPipeInstance_::_1_::dtor$2 @ 0x14001B660 (_CPipeInstance--_CPipeInstance_--_1_--dtor$2.c)
 *     _CPipeInstance::_CPipeInstance_::_1_::dtor$3 @ 0x14001B673 (_CPipeInstance--_CPipeInstance_--_1_--dtor$3.c)
 *     _CPipeInstance::_CPipeInstance_::_1_::dtor$4 @ 0x14001B686 (_CPipeInstance--_CPipeInstance_--_1_--dtor$4.c)
 *     _CPipeInstance::_CPipeInstance_::_1_::dtor$6 @ 0x14001B6AC (_CPipeInstance--_CPipeInstance_--_1_--dtor$6.c)
 *     _CPipeInstance::OnDisconnectedFromPump_::_1_::dtor$1 @ 0x14001B6EC (_CPipeInstance--OnDisconnectedFromPump_--_1_--dtor$1.c)
 *     _CPipeInstance::OnConnectedToPump_::_1_::dtor$1 @ 0x14001B70C (_CPipeInstance--OnConnectedToPump_--_1_--dtor$1.c)
 *     _CPipeInstance::InitializeAPOInterfaces_::_1_::dtor$0 @ 0x14001B740 (_CPipeInstance--InitializeAPOInterfaces_--_1_--dtor$0.c)
 *     _CPipeInstance::InitializeAPOInterfaces_::_1_::dtor$2 @ 0x14001B758 (_CPipeInstance--InitializeAPOInterfaces_--_1_--dtor$2.c)
 *     _CPipeInstance::InitializeAPOInterfaces_::_1_::dtor$4 @ 0x14001B770 (_CPipeInstance--InitializeAPOInterfaces_--_1_--dtor$4.c)
 *     _CPipeInstance::InitializeAPOInterfaces_::_1_::dtor$5 @ 0x14001B77C (_CPipeInstance--InitializeAPOInterfaces_--_1_--dtor$5.c)
 *     _CPipeInstance::InitializeAPOInterfaces_::_1_::dtor$6 @ 0x14001B788 (_CPipeInstance--InitializeAPOInterfaces_--_1_--dtor$6.c)
 *     _CPipeInstance::InitializeAPOInterfaces_::_1_::dtor$7 @ 0x14001B794 (_CPipeInstance--InitializeAPOInterfaces_--_1_--dtor$7.c)
 *     _CPipeInstance::InitializeAPOInterfaces_::_1_::dtor$10 @ 0x14001B7B8 (_CPipeInstance--InitializeAPOInterfaces_--_1_--dtor$10.c)
 *     _CPipeInstance::InitializeAPOInterfaces_::_1_::dtor$12 @ 0x14001B7D0 (_CPipeInstance--InitializeAPOInterfaces_--_1_--dtor$12.c)
 *     _CPipeInstance::InitializeAPOInterfaces_::_1_::dtor$13 @ 0x14001B7DC (_CPipeInstance--InitializeAPOInterfaces_--_1_--dtor$13.c)
 *     _CPipeInstance::InitializeAPOInterfaces_::_1_::dtor$14 @ 0x14001B7E8 (_CPipeInstance--InitializeAPOInterfaces_--_1_--dtor$14.c)
 *     _CPipeInstance::InitializeAPOInterfaces_::_1_::dtor$15 @ 0x14001B7F4 (_CPipeInstance--InitializeAPOInterfaces_--_1_--dtor$15.c)
 *     _CPipeInstance::InitializeRateConverterInterface_::_1_::dtor$0 @ 0x14001B810 (_CPipeInstance--InitializeRateConverterInterface_--_1_--dtor$0.c)
 *     _CPipeInstance::DeactivateAPOsAndRemoveConnections_::_1_::dtor$0 @ 0x14001B840 (_CPipeInstance--DeactivateAPOsAndRemoveConnections_--_1_--dtor$0.c)
 *     _CPipeInstance::DeactivateAPOsAndRemoveConnections_::_1_::dtor$1 @ 0x14001B84C (_CPipeInstance--DeactivateAPOsAndRemoveConnections_--_1_--dtor$1.c)
 *     _CPipeInstance::CreateAPOConnectionList_::_1_::dtor$0 @ 0x14001B8A0 (_CPipeInstance--CreateAPOConnectionList_--_1_--dtor$0.c)
 *     _CPipeInstance::ResolveFormatConflictsLeftRight_::_1_::dtor$3 @ 0x14001B994 (_CPipeInstance--ResolveFormatConflictsLeftRight_--_1_--dtor$3.c)
 *     _CPipeInstance::ResolveFormatConflictsLeftRight_::_1_::dtor$4 @ 0x14001B9A0 (_CPipeInstance--ResolveFormatConflictsLeftRight_--_1_--dtor$4.c)
 *     _CPipeInstance::ResolveFormatConflictsRightLeft_::_1_::dtor$1 @ 0x14001BA6C (_CPipeInstance--ResolveFormatConflictsRightLeft_--_1_--dtor$1.c)
 *     _CPipeInstance::ResolveFormatConflictsRightLeft_::_1_::dtor$2 @ 0x14001BA78 (_CPipeInstance--ResolveFormatConflictsRightLeft_--_1_--dtor$2.c)
 *     _CPipeInstance::Cleanup_::_1_::dtor$0 @ 0x14001BB00 (_CPipeInstance--Cleanup_--_1_--dtor$0.c)
 *     _CPipeInstance::Cleanup_::_1_::dtor$1 @ 0x14001BB10 (_CPipeInstance--Cleanup_--_1_--dtor$1.c)
 *     _CConnectionInstance::AddRenderConnection_::_1_::dtor$0 @ 0x14001BB30 (_CConnectionInstance--AddRenderConnection_--_1_--dtor$0.c)
 *     _CStreamProcessNode::_CStreamProcessNode_::_1_::dtor$2 @ 0x14001BD1A (_CStreamProcessNode--_CStreamProcessNode_--_1_--dtor$2.c)
 *     _FillAPOInitSystemEffectsStructure_::_1_::dtor$0 @ 0x14001BD30 (_FillAPOInitSystemEffectsStructure_--_1_--dtor$0.c)
 *     _FillAPOInitSystemEffectsStructure_::_1_::dtor$1 @ 0x14001BD3C (_FillAPOInitSystemEffectsStructure_--_1_--dtor$1.c)
 *     _FillAPOInitSystemEffectsStructure_::_1_::dtor$2 @ 0x14001BD48 (_FillAPOInitSystemEffectsStructure_--_1_--dtor$2.c)
 *     _FillAPOInitSystemEffectsStructure_::_1_::dtor$3 @ 0x14001BD54 (_FillAPOInitSystemEffectsStructure_--_1_--dtor$3.c)
 *     _FillAPOInitSystemEffectsStructure_::_1_::dtor$4 @ 0x14001BD60 (_FillAPOInitSystemEffectsStructure_--_1_--dtor$4.c)
 *     _FillAPOInitSystemEffectsStructure_::_1_::dtor$5 @ 0x14001BD6C (_FillAPOInitSystemEffectsStructure_--_1_--dtor$5.c)
 *     _FillAPOInitSystemEffectsStructure_::_1_::dtor$6 @ 0x14001BD78 (_FillAPOInitSystemEffectsStructure_--_1_--dtor$6.c)
 *     _CEndpointInstance::CreateDeviceEndpointInstance_::_1_::dtor$0 @ 0x14001BE70 (_CEndpointInstance--CreateDeviceEndpointInstance_--_1_--dtor$0.c)
 *     _CEndpointInstance::CreateDeviceEndpointInstance_::_1_::dtor$1 @ 0x14001BE7C (_CEndpointInstance--CreateDeviceEndpointInstance_--_1_--dtor$1.c)
 *     _CEndpointInstance::CreateDeviceEndpointInstance_::_1_::dtor$3 @ 0x14001BE94 (_CEndpointInstance--CreateDeviceEndpointInstance_--_1_--dtor$3.c)
 *     _CEndpointInstance::CreateDeviceEndpointInstance_::_1_::dtor$4 @ 0x14001BEA0 (_CEndpointInstance--CreateDeviceEndpointInstance_--_1_--dtor$4.c)
 *     _CEndpointInstance::CreateDeviceEndpointInstance_::_1_::dtor$5 @ 0x14001BEAC (_CEndpointInstance--CreateDeviceEndpointInstance_--_1_--dtor$5.c)
 *     _CEndpointInstance::CreateDeviceEndpointInstance_::_1_::dtor$6 @ 0x14001BEB8 (_CEndpointInstance--CreateDeviceEndpointInstance_--_1_--dtor$6.c)
 *     _CEndpointInstance::CreateDeviceEndpointInstance_::_1_::dtor$7 @ 0x14001BEC4 (_CEndpointInstance--CreateDeviceEndpointInstance_--_1_--dtor$7.c)
 *     _CConnectionInstance::_CConnectionInstance_::_1_::dtor$0 @ 0x14002636C (_CConnectionInstance--_CConnectionInstance_--_1_--dtor$0.c)
 *     _CInPlaceBuffer::_scalar_deleting_destructor__::_1_::dtor$0 @ 0x140026542 (_CInPlaceBuffer--_scalar_deleting_destructor__--_1_--dtor$0.c)
 *     _CSystemAudioDeviceBase::ActivateEndpoint_::_1_::dtor$0 @ 0x14002A4B2 (_CSystemAudioDeviceBase--ActivateEndpoint_--_1_--dtor$0.c)
 *     _CSystemAudioDeviceBase::ActivateEndpoint_::_1_::dtor$1 @ 0x14002A4BE (_CSystemAudioDeviceBase--ActivateEndpoint_--_1_--dtor$1.c)
 *     _CSystemAudioDeviceBase::ActivateEndpoint_::_1_::dtor$2 @ 0x14002A4CA (_CSystemAudioDeviceBase--ActivateEndpoint_--_1_--dtor$2.c)
 *     _CSystemAudioDeviceBase::ActivateEndpoint_::_1_::dtor$3 @ 0x14002A4D6 (_CSystemAudioDeviceBase--ActivateEndpoint_--_1_--dtor$3.c)
 *     _CSystemAudioDeviceBase::ActivateEndpoint_::_1_::dtor$4 @ 0x14002A4E2 (_CSystemAudioDeviceBase--ActivateEndpoint_--_1_--dtor$4.c)
 *     _CSystemAudioDeviceBase::ActivateEndpoint_::_1_::dtor$5 @ 0x14002A4EE (_CSystemAudioDeviceBase--ActivateEndpoint_--_1_--dtor$5.c)
 *     _CSystemAudioDeviceOffload::_CSystemAudioDeviceOffload_::_1_::dtor$2 @ 0x14002D1F7 (_CSystemAudioDeviceOffload--_CSystemAudioDeviceOffload_--_1_--dtor$2.c)
 *     _CSystemAudioDeviceOffload::_CSystemAudioDeviceOffload_::_1_::dtor$3 @ 0x14002D20A (_CSystemAudioDeviceOffload--_CSystemAudioDeviceOffload_--_1_--dtor$3.c)
 *     _CSystemAudioDeviceOffload::_CSystemAudioDeviceOffload_::_1_::dtor$4 @ 0x14002D21D (_CSystemAudioDeviceOffload--_CSystemAudioDeviceOffload_--_1_--dtor$4.c)
 *     _CSystemAudioDeviceOffload::_CSystemAudioDeviceOffload_::_1_::dtor$5 @ 0x14002D230 (_CSystemAudioDeviceOffload--_CSystemAudioDeviceOffload_--_1_--dtor$5.c)
 *     _CSystemAudioDeviceOffloadGraph::_CSystemAudioDeviceOffloadGraph_::_1_::dtor$2 @ 0x14002E93B (_CSystemAudioDeviceOffloadGraph--_CSystemAudioDeviceOffloadGraph_--_1_--dtor$2.c)
 *     _CSystemAudioDeviceOffloadGraph::_CSystemAudioDeviceOffloadGraph_::_1_::dtor$3 @ 0x14002E94E (_CSystemAudioDeviceOffloadGraph--_CSystemAudioDeviceOffloadGraph_--_1_--dtor$3.c)
 *     _CSystemAudioDeviceOffloadGraph::_CSystemAudioDeviceOffloadGraph_::_1_::dtor$4 @ 0x14002E961 (_CSystemAudioDeviceOffloadGraph--_CSystemAudioDeviceOffloadGraph_--_1_--dtor$4.c)
 *     _CSystemAudioDeviceOffloadGraph::_CSystemAudioDeviceOffloadGraph_::_1_::dtor$5 @ 0x14002E974 (_CSystemAudioDeviceOffloadGraph--_CSystemAudioDeviceOffloadGraph_--_1_--dtor$5.c)
 *     _CPipeInstance::GetAPONodeAndConnection_::_1_::dtor$0 @ 0x140030F36 (_CPipeInstance--GetAPONodeAndConnection_--_1_--dtor$0.c)
 *     _CPipeInstance::GetAPONodeAndConnection_::_1_::dtor$1 @ 0x140030F42 (_CPipeInstance--GetAPONodeAndConnection_--_1_--dtor$1.c)
 *     _CConnectionInstance::AddCaptureConnection_::_1_::dtor$0 @ 0x1400335C0 (_CConnectionInstance--AddCaptureConnection_--_1_--dtor$0.c)
 *     _CConnectionInstance::RemoveCaptureConnection_::_1_::dtor$0 @ 0x1400337E0 (_CConnectionInstance--RemoveCaptureConnection_--_1_--dtor$0.c)
 * Callees:
 *     ??1?$CComObjectRootEx@VCComMultiThreadModelNoCS@ATL@@@ATL@@QEAA@XZ @ 0x140026C60 (--1-$CComObjectRootEx@VCComMultiThreadModelNoCS@ATL@@@ATL@@QEAA@XZ.c)
 */

__int64 __fastcall ATL::CComPtr<IMMDeviceEnumerator>::~CComPtr<IMMDeviceEnumerator>(_QWORD *a1)
{
  __int64 result; // rax

  if ( *a1 )
    return (*(__int64 (__fastcall **)(_QWORD))(*(_QWORD *)*a1 + 16LL))(*a1);
  return result;
}
